import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class askimemnu extends StatefulWidget {
  const askimemnu({Key? key}) : super(key: key);

  @override
  State<askimemnu> createState() => _askimemnuState();
}

class _askimemnuState extends State<askimemnu> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/aski memnu/page (1).png',
    'books/aski memnu/page (2).png',
    'books/aski memnu/page (3).png',
    'books/aski memnu/page (4).png',
    'books/aski memnu/page (5).png',
    'books/aski memnu/page (6).png',
    'books/aski memnu/page (7).png',
    'books/aski memnu/page (8).png',
    'books/aski memnu/page (9).png',
    'books/aski memnu/page (10).png',
    'books/aski memnu/page (11).png',
    'books/aski memnu/page (12).png',
    'books/aski memnu/page (13).png',
    'books/aski memnu/page (14).png',
    'books/aski memnu/page (15).png',
    'books/aski memnu/page (16).png',
    'books/aski memnu/page (17).png',
    'books/aski memnu/page (18).png',
    'books/aski memnu/page (19).png',
    'books/aski memnu/page (20).png',
    'books/aski memnu/page (21).png',
    'books/aski memnu/page (22).png',
    'books/aski memnu/page (23).png',
    'books/aski memnu/page (24).png',
    'books/aski memnu/page (25).png',
    'books/aski memnu/page (26).png',
    'books/aski memnu/page (27).png',
    'books/aski memnu/page (28).png',
    'books/aski memnu/page (29).png',
    'books/aski memnu/page (30).png',
    'books/aski memnu/page (31).png',
    'books/aski memnu/page (32).png',
    'books/aski memnu/page (33).png',
    'books/aski memnu/page (34).png',
    'books/aski memnu/page (35).png',
    'books/aski memnu/page (36).png',
    'books/aski memnu/page (37).png',
    'books/aski memnu/page (38).png',
    'books/aski memnu/page (39).png',
    'books/aski memnu/page (40).png',
    'books/aski memnu/page (41).png',
    'books/aski memnu/page (42).png',
    'books/aski memnu/page (43).png',
    'books/aski memnu/page (44).png',
    'books/aski memnu/page (45).png',
    'books/aski memnu/page (46).png',
    'books/aski memnu/page (47).png',
    'books/aski memnu/page (48).png',
    'books/aski memnu/page (49).png',
    'books/aski memnu/page (50).png',
    'books/aski memnu/page (51).png',
    'books/aski memnu/page (52).png',
    'books/aski memnu/page (53).png',
    'books/aski memnu/page (54).png',
    'books/aski memnu/page (55).png',
    'books/aski memnu/page (56).png',
    'books/aski memnu/page (57).png',
    'books/aski memnu/page (58).png',
    'books/aski memnu/page (59).png',
    'books/aski memnu/page (60).png',
    'books/aski memnu/page (61).png',
    'books/aski memnu/page (62).png',
    'books/aski memnu/page (63).png',
    'books/aski memnu/page (64).png',
    'books/aski memnu/page (65).png',
    'books/aski memnu/page (66).png',
    'books/aski memnu/page (67).png',
    'books/aski memnu/page (68).png',
    'books/aski memnu/page (69).png',
    'books/aski memnu/page (70).png',
    'books/aski memnu/page (71).png',
    'books/aski memnu/page (72).png',
    'books/aski memnu/page (73).png',
    'books/aski memnu/page (74).png',
    'books/aski memnu/page (75).png',
    'books/aski memnu/page (76).png',
    'books/aski memnu/page (77).png',
    'books/aski memnu/page (78).png',
    'books/aski memnu/page (79).png',
    'books/aski memnu/page (80).png',
    'books/aski memnu/page (81).png',
    'books/aski memnu/page (82).png',
    'books/aski memnu/page (83).png',
    'books/aski memnu/page (84).png',
    'books/aski memnu/page (85).png',
    'books/aski memnu/page (86).png',
    'books/aski memnu/page (87).png',
    'books/aski memnu/page (88).png',
    'books/aski memnu/page (89).png',
    'books/aski memnu/page (90).png',
    'books/aski memnu/page (91).png',
    'books/aski memnu/page (92).png',
    'books/aski memnu/page (93).png',
    'books/aski memnu/page (94).png',
    'books/aski memnu/page (95).png',
    'books/aski memnu/page (96).png',
    'books/aski memnu/page (97).png',
    'books/aski memnu/page (98).png',
    'books/aski memnu/page (99).png',
    'books/aski memnu/page (100).png',
    'books/aski memnu/page (101).png',
    'books/aski memnu/page (102).png',
    'books/aski memnu/page (103).png',
    'books/aski memnu/page (104).png',
    'books/aski memnu/page (105).png',
    'books/aski memnu/page (106).png',
    'books/aski memnu/page (107).png',
    'books/aski memnu/page (108).png',
    'books/aski memnu/page (109).png',
    'books/aski memnu/page (110).png',
    'books/aski memnu/page (111).png',
    'books/aski memnu/page (112).png',
    'books/aski memnu/page (113).png',
    'books/aski memnu/page (114).png',
    'books/aski memnu/page (115).png',
    'books/aski memnu/page (116).png',
    'books/aski memnu/page (117).png',
    'books/aski memnu/page (118).png',
    'books/aski memnu/page (119).png',
    'books/aski memnu/page (120).png',
    'books/aski memnu/page (121).png',
    'books/aski memnu/page (122).png',
    'books/aski memnu/page (123).png',
    'books/aski memnu/page (124).png',
    'books/aski memnu/page (125).png',
    'books/aski memnu/page (126).png',
    'books/aski memnu/page (127).png',
    'books/aski memnu/page (128).png',
    'books/aski memnu/page (129).png',
    'books/aski memnu/page (130).png',
    'books/aski memnu/page (131).png',
    'books/aski memnu/page (132).png',
    'books/aski memnu/page (133).png',
    'books/aski memnu/page (134).png',
    'books/aski memnu/page (135).png',
    'books/aski memnu/page (136).png',
    'books/aski memnu/page (137).png',
    'books/aski memnu/page (138).png',
    'books/aski memnu/page (139).png',
    'books/aski memnu/page (140).png',
    'books/aski memnu/page (141).png',
    'books/aski memnu/page (142).png',
    'books/aski memnu/page (143).png',
    'books/aski memnu/page (144).png',
    'books/aski memnu/page (145).png',
    'books/aski memnu/page (146).png',
    'books/aski memnu/page (147).png',
    'books/aski memnu/page (148).png',
    'books/aski memnu/page (149).png',
    'books/aski memnu/page (150).png',
    'books/aski memnu/page (151).png',
    'books/aski memnu/page (152).png',
    'books/aski memnu/page (153).png',
    'books/aski memnu/page (154).png',
    'books/aski memnu/page (155).png',
    'books/aski memnu/page (156).png',
    'books/aski memnu/page (157).png',
    'books/aski memnu/page (158).png',
    'books/aski memnu/page (159).png',
    'books/aski memnu/page (160).png',
    'books/aski memnu/page (161).png',
    'books/aski memnu/page (162).png',
    'books/aski memnu/page (163).png',
    'books/aski memnu/page (164).png',
    'books/aski memnu/page (165).png',
    'books/aski memnu/page (166).png',
    'books/aski memnu/page (167).png',
    'books/aski memnu/page (168).png',
    'books/aski memnu/page (169).png',
    'books/aski memnu/page (170).png',
    'books/aski memnu/page (171).png',
    'books/aski memnu/page (172).png',
    'books/aski memnu/page (173).png',
    'books/aski memnu/page (174).png',
    'books/aski memnu/page (175).png',
    'books/aski memnu/page (176).png',
    'books/aski memnu/page (177).png',
    'books/aski memnu/page (178).png',
    'books/aski memnu/page (179).png',
    'books/aski memnu/page (180).png',
    'books/aski memnu/page (181).png',
    'books/aski memnu/page (182).png',
    'books/aski memnu/page (183).png',
    'books/aski memnu/page (184).png',
    'books/aski memnu/page (185).png',
    'books/aski memnu/page (186).png',
    'books/aski memnu/page (187).png',
    'books/aski memnu/page (188).png',
    'books/aski memnu/page (189).png',
    'books/aski memnu/page (190).png',
    'books/aski memnu/page (191).png',
    'books/aski memnu/page (192).png',
    'books/aski memnu/page (193).png',
    'books/aski memnu/page (194).png',
    'books/aski memnu/page (195).png',
    'books/aski memnu/page (196).png',
    'books/aski memnu/page (197).png',
    'books/aski memnu/page (198).png',
    'books/aski memnu/page (199).png',
    'books/aski memnu/page (200).png',
    'books/aski memnu/page (201).png',
    'books/aski memnu/page (202).png',
    'books/aski memnu/page (203).png',
    'books/aski memnu/page (204).png',
    'books/aski memnu/page (205).png',
    'books/aski memnu/page (206).png',
    'books/aski memnu/page (207).png',
    'books/aski memnu/page (208).png',
    'books/aski memnu/page (209).png',
    'books/aski memnu/page (210).png',
    'books/aski memnu/page (211).png',
    'books/aski memnu/page (212).png',
    'books/aski memnu/page (213).png',
    'books/aski memnu/page (214).png',
    'books/aski memnu/page (215).png',
    'books/aski memnu/page (216).png',
    'books/aski memnu/page (217).png',
    'books/aski memnu/page (218).png',
    'books/aski memnu/page (219).png',
    'books/aski memnu/page (220).png',
    'books/aski memnu/page (221).png',
    'books/aski memnu/page (222).png',
    'books/aski memnu/page (223).png',
    'books/aski memnu/page (224).png',
    'books/aski memnu/page (225).png',
    'books/aski memnu/page (226).png',
    'books/aski memnu/page (227).png',
    'books/aski memnu/page (228).png',
    'books/aski memnu/page (229).png',
    'books/aski memnu/page (230).png',
    'books/aski memnu/page (231).png',
    'books/aski memnu/page (232).png',
    'books/aski memnu/page (233).png',
    'books/aski memnu/page (234).png',
    'books/aski memnu/page (235).png',
    'books/aski memnu/page (236).png',
    'books/aski memnu/page (237).png',
    'books/aski memnu/page (238).png',
    'books/aski memnu/page (239).png',
    'books/aski memnu/page (240).png',
    'books/aski memnu/page (241).png',
    'books/aski memnu/page (242).png',
    'books/aski memnu/page (243).png',
    'books/aski memnu/page (244).png',
    'books/aski memnu/page (245).png',
    'books/aski memnu/page (246).png',
    'books/aski memnu/page (247).png',
    'books/aski memnu/page (248).png',
    'books/aski memnu/page (249).png',
    'books/aski memnu/page (250).png',
    'books/aski memnu/page (251).png',
    'books/aski memnu/page (252).png',
    'books/aski memnu/page (253).png',
    'books/aski memnu/page (254).png',
    'books/aski memnu/page (255).png',
    'books/aski memnu/page (256).png',
    'books/aski memnu/page (257).png',
    'books/aski memnu/page (258).png',
    'books/aski memnu/page (259).png',
    'books/aski memnu/page (260).png',
    'books/aski memnu/page (261).png',
    'books/aski memnu/page (262).png',
    'books/aski memnu/page (263).png',
    'books/aski memnu/page (264).png',
    'books/aski memnu/page (265).png',
    'books/aski memnu/page (266).png',
    'books/aski memnu/page (267).png',
    'books/aski memnu/page (268).png',
    'books/aski memnu/page (269).png',
    'books/aski memnu/page (270).png',
    'books/aski memnu/page (271).png',
    'books/aski memnu/page (272).png',
    'books/aski memnu/page (273).png',
    'books/aski memnu/page (274).png',
    'books/aski memnu/page (275).png',
    'books/aski memnu/page (276).png',
    'books/aski memnu/page (277).png',
    'books/aski memnu/page (278).png',
    'books/aski memnu/page (279).png',
    'books/aski memnu/page (280).png',
    'books/aski memnu/page (281).png',
    'books/aski memnu/page (282).png',
    'books/aski memnu/page (283).png',
    'books/aski memnu/page (284).png',
    'books/aski memnu/page (285).png',
    'books/aski memnu/page (286).png',
    'books/aski memnu/page (287).png',
    'books/aski memnu/page (288).png',
    'books/aski memnu/page (289).png',
    'books/aski memnu/page (290).png',
    'books/aski memnu/page (291).png',
    'books/aski memnu/page (292).png',
    'books/aski memnu/page (293).png',
    'books/aski memnu/page (294).png',
    'books/aski memnu/page (295).png',
    'books/aski memnu/page (296).png',
    'books/aski memnu/page (297).png',
    'books/aski memnu/page (298).png',
    'books/aski memnu/page (299).png',
    'books/aski memnu/page (300).png',
    'books/aski memnu/page (301).png',
    'books/aski memnu/page (302).png',
    'books/aski memnu/page (303).png',
    'books/aski memnu/page (304).png',
    'books/aski memnu/page (305).png',
    'books/aski memnu/page (306).png',
    'books/aski memnu/page (307).png',
    'books/aski memnu/page (308).png',
    'books/aski memnu/page (309).png',
    'books/aski memnu/page (310).png',
    'books/aski memnu/page (311).png',
    'books/aski memnu/page (312).png',
    'books/aski memnu/page (313).png',
    'books/aski memnu/page (314).png',
    'books/aski memnu/page (315).png',
    'books/aski memnu/page (316).png',
    'books/aski memnu/page (317).png',
    'books/aski memnu/page (318).png',
    'books/aski memnu/page (319).png',
    'books/aski memnu/page (320).png',
    'books/aski memnu/page (321).png',
    'books/aski memnu/page (322).png',
    'books/aski memnu/page (323).png',
    'books/aski memnu/page (324).png',
    'books/aski memnu/page (325).png',
    'books/aski memnu/page (326).png',
    'books/aski memnu/page (327).png',
    'books/aski memnu/page (328).png',
    'books/aski memnu/page (329).png',
    'books/aski memnu/page (330).png',
    'books/aski memnu/page (331).png',
    'books/aski memnu/page (332).png',
    'books/aski memnu/page (333).png',
    'books/aski memnu/page (334).png',
    'books/aski memnu/page (335).png',
    'books/aski memnu/page (336).png',
    'books/aski memnu/page (337).png',
    'books/aski memnu/page (338).png',
    'books/aski memnu/page (339).png',
    'books/aski memnu/page (340).png',
    'books/aski memnu/page (341).png',
    'books/aski memnu/page (342).png',
    'books/aski memnu/page (343).png',
    'books/aski memnu/page (344).png',
    'books/aski memnu/page (345).png',
    'books/aski memnu/page (346).png',
    'books/aski memnu/page (347).png',
    'books/aski memnu/page (348).png',
    'books/aski memnu/page (349).png',
    'books/aski memnu/page (350).png',
    'books/aski memnu/page (351).png',
    'books/aski memnu/page (352).png',
    'books/aski memnu/page (353).png',
    'books/aski memnu/page (354).png',
    'books/aski memnu/page (355).png',
    'books/aski memnu/page (356).png',
    'books/aski memnu/page (357).png',
    'books/aski memnu/page (358).png',
    'books/aski memnu/page (359).png',
    'books/aski memnu/page (360).png',
    'books/aski memnu/page (361).png',
    'books/aski memnu/page (362).png',
    'books/aski memnu/page (363).png',
    'books/aski memnu/page (364).png',
    'books/aski memnu/page (365).png',
    'books/aski memnu/page (366).png',
    'books/aski memnu/page (367).png',
    'books/aski memnu/page (368).png',
    'books/aski memnu/page (369).png',
    'books/aski memnu/page (370).png',
    'books/aski memnu/page (371).png',
    'books/aski memnu/page (372).png',
    'books/aski memnu/page (373).png',
    'books/aski memnu/page (374).png',
    'books/aski memnu/page (375).png',
    'books/aski memnu/page (376).png',
    'books/aski memnu/page (377).png',
    'books/aski memnu/page (378).png',
    'books/aski memnu/page (379).png',
    'books/aski memnu/page (380).png',
    'books/aski memnu/page (381).png',
    'books/aski memnu/page (382).png',
    'books/aski memnu/page (383).png',
    'books/aski memnu/page (384).png',
    'books/aski memnu/page (385).png',
    'books/aski memnu/page (386).png',
    'books/aski memnu/page (387).png',
    'books/aski memnu/page (388).png',
    'books/aski memnu/page (389).png',
    'books/aski memnu/page (390).png',
    'books/aski memnu/page (391).png',
    'books/aski memnu/page (392).png',
    'books/aski memnu/page (393).png',
    'books/aski memnu/page (394).png',
    'books/aski memnu/page (395).png',
    'books/aski memnu/page (396).png',
    'books/aski memnu/page (397).png',
    'books/aski memnu/page (398).png',
    'books/aski memnu/page (399).png',
    'books/aski memnu/page (400).png',
    'books/aski memnu/page (401).png',
    'books/aski memnu/page (402).png',
    'books/aski memnu/page (403).png',
    'books/aski memnu/page (404).png',
    'books/aski memnu/page (405).png',
    'books/aski memnu/page (406).png',
    'books/aski memnu/page (407).png',
    'books/aski memnu/page (408).png',
    'books/aski memnu/page (409).png',
    'books/aski memnu/page (410).png',
    'books/aski memnu/page (411).png',
    'books/aski memnu/page (412).png',
    'books/aski memnu/page (413).png',
    'books/aski memnu/page (414).png',
    'books/aski memnu/page (415).png',
    'books/aski memnu/page (416).png',
    'books/aski memnu/page (417).png',
    'books/aski memnu/page (418).png',
    'books/aski memnu/page (419).png',
    'books/aski memnu/page (420).png',
    'books/aski memnu/page (421).png',
    'books/aski memnu/page (422).png',
    'books/aski memnu/page (423).png',
    'books/aski memnu/page (424).png',
    'books/aski memnu/page (425).png',
    'books/aski memnu/page (426).png',
    'books/aski memnu/page (427).png',
    'books/aski memnu/page (428).png',
    'books/aski memnu/page (429).png',
    'books/aski memnu/page (430).png',
    'books/aski memnu/page (431).png',
    'books/aski memnu/page (432).png',
    'books/aski memnu/page (433).png',
    'books/aski memnu/page (434).png',
    'books/aski memnu/page (435).png',
    'books/aski memnu/page (436).png',
    'books/aski memnu/page (437).png',
    'books/aski memnu/page (438).png',
    'books/aski memnu/page (439).png',
    'books/aski memnu/page (440).png',
    'books/aski memnu/page (441).png',
    'books/aski memnu/page (442).png',
    'books/aski memnu/page (443).png',
    'books/aski memnu/page (444).png',
    'books/aski memnu/page (445).png',
    'books/aski memnu/page (446).png',
    'books/aski memnu/page (447).png',
    'books/aski memnu/page (448).png',
    'books/aski memnu/page (449).png',
    'books/aski memnu/page (450).png',
    'books/aski memnu/page (451).png',
    'books/aski memnu/page (452).png',
    'books/aski memnu/page (453).png',
    'books/aski memnu/page (454).png',
    'books/aski memnu/page (455).png',
    'books/aski memnu/page (456).png',
    'books/aski memnu/page (457).png',
    'books/aski memnu/page (458).png',
    'books/aski memnu/page (459).png',
    'books/aski memnu/page (460).png',
    'books/aski memnu/page (461).png',
    'books/aski memnu/page (462).png',
    'books/aski memnu/page (463).png',
    'books/aski memnu/page (464).png',
    'books/aski memnu/page (465).png',
    'books/aski memnu/page (466).png',
    'books/aski memnu/page (467).png',
    'books/aski memnu/page (468).png',
    'books/aski memnu/page (469).png',
    'books/aski memnu/page (470).png',
    'books/aski memnu/page (471).png',
    'books/aski memnu/page (472).png',
    'books/aski memnu/page (473).png',
    'books/aski memnu/page (474).png',
    'books/aski memnu/page (475).png',
    'books/aski memnu/page (476).png',
    'books/aski memnu/page (477).png',
    'books/aski memnu/page (478).png',
    'books/aski memnu/page (479).png',
    'books/aski memnu/page (480).png',
    'books/aski memnu/page (481).png',
    'books/aski memnu/page (482).png',
    'books/aski memnu/page (483).png',
    'books/aski memnu/page (484).png',
    'books/aski memnu/page (485).png',
    'books/aski memnu/page (486).png',
    'books/aski memnu/page (487).png',
    'books/aski memnu/page (488).png',
    'books/aski memnu/page (489).png',
    'books/aski memnu/page (490).png',
    'books/aski memnu/page (491).png',
    'books/aski memnu/page (492).png',
    'books/aski memnu/page (493).png',
    'books/aski memnu/page (494).png',
    'books/aski memnu/page (495).png',
    'books/aski memnu/page (496).png',
    'books/aski memnu/page (497).png',
    'books/aski memnu/page (498).png',
    'books/aski memnu/page (499).png',
    'books/aski memnu/page (500).png',
    'books/aski memnu/page (501).png',
    'books/aski memnu/page (502).png',
    'books/aski memnu/page (503).png',
    'books/aski memnu/page (504).png',
    'books/aski memnu/page (505).png',
    'books/aski memnu/page (506).png',
    'books/aski memnu/page (507).png',
    'books/aski memnu/page (508).png',
    'books/aski memnu/page (509).png',
    'books/aski memnu/page (510).png',
    'books/aski memnu/page (511).png',
    'books/aski memnu/page (512).png',
    'books/aski memnu/page (513).png',
    'books/aski memnu/page (514).png',
    'books/aski memnu/page (515).png',
    'books/aski memnu/page (516).png',
    'books/aski memnu/page (517).png',
    'books/aski memnu/page (518).png',
    'books/aski memnu/page (519).png',
    'books/aski memnu/page (520).png',
    'books/aski memnu/page (521).png',
    'books/aski memnu/page (522).png',
    'books/aski memnu/page (523).png',
    'books/aski memnu/page (524).png',
    'books/aski memnu/page (525).png',
    'books/aski memnu/page (526).png',
    'books/aski memnu/page (527).png',
    'books/aski memnu/page (528).png',
    'books/aski memnu/page (529).png',
    'books/aski memnu/page (530).png',
    'books/aski memnu/page (531).png',
    'books/aski memnu/page (532).png',
    'books/aski memnu/page (533).png',
    'books/aski memnu/page (534).png',
    'books/aski memnu/page (535).png',
    'books/aski memnu/page (536).png',
    'books/aski memnu/page (537).png',
    'books/aski memnu/page (538).png',
    'books/aski memnu/page (539).png',
    'books/aski memnu/page (540).png',
    'books/aski memnu/page (541).png',
    'books/aski memnu/page (542).png',
    'books/aski memnu/page (543).png',
    'books/aski memnu/page (544).png',
    'books/aski memnu/page (545).png',
    'books/aski memnu/page (546).png',
    'books/aski memnu/page (547).png',
    'books/aski memnu/page (548).png',
    'books/aski memnu/page (549).png',
    'books/aski memnu/page (550).png',
    'books/aski memnu/page (551).png',
    'books/aski memnu/page (552).png',
    'books/aski memnu/page (553).png',
    'books/aski memnu/page (554).png',
    'books/aski memnu/page (555).png',
    'books/aski memnu/page (556).png',
    'books/aski memnu/page (557).png',
    'books/aski memnu/page (558).png',
    'books/aski memnu/page (559).png',
    'books/aski memnu/page (560).png',
    'books/aski memnu/page (561).png',
    'books/aski memnu/page (562).png',
    'books/aski memnu/page (563).png',
    'books/aski memnu/page (564).png',
    'books/aski memnu/page (565).png',
    'books/aski memnu/page (566).png',
    'books/aski memnu/page (567).png',
    'books/aski memnu/page (568).png',
    'books/aski memnu/page (569).png',
    'books/aski memnu/page (570).png',
    'books/aski memnu/page (571).png',
    'books/aski memnu/page (572).png',
    'books/aski memnu/page (573).png',
    'books/aski memnu/page (574).png',
    'books/aski memnu/page (575).png',
    'books/aski memnu/page (576).png',
    'books/aski memnu/page (577).png',
    'books/aski memnu/page (578).png',
    'books/aski memnu/page (579).png',
    'books/aski memnu/page (580).png',
    'books/aski memnu/page (581).png',
    'books/aski memnu/page (582).png',
    'books/aski memnu/page (583).png',
    'books/aski memnu/page (584).png',
    'books/aski memnu/page (585).png',
    'books/aski memnu/page (586).png',
    'books/aski memnu/page (587).png',
    'books/aski memnu/page (588).png',
    'books/aski memnu/page (589).png',
    'books/aski memnu/page (590).png',
    'books/aski memnu/page (591).png',
    'books/aski memnu/page (592).png',
    'books/aski memnu/page (593).png',
    'books/aski memnu/page (594).png',
    'books/aski memnu/page (595).png',
    'books/aski memnu/page (596).png',
    'books/aski memnu/page (597).png',
    'books/aski memnu/page (598).png',
    'books/aski memnu/page (599).png',
    'books/aski memnu/page (600).png',
    'books/aski memnu/page (601).png',
    'books/aski memnu/page (602).png',
    'books/aski memnu/page (603).png',
    'books/aski memnu/page (604).png',
    'books/aski memnu/page (605).png',
    'books/aski memnu/page (606).png',
    'books/aski memnu/page (607).png',
    'books/aski memnu/page (608).png',
    'books/aski memnu/page (609).png',
    'books/aski memnu/page (610).png',
    'books/aski memnu/page (611).png',
    'books/aski memnu/page (612).png',
    'books/aski memnu/page (613).png',
    'books/aski memnu/page (614).png',
    'books/aski memnu/page (615).png',
    'books/aski memnu/page (616).png',
    'books/aski memnu/page (617).png',
    'books/aski memnu/page (618).png',
    'books/aski memnu/page (619).png',
    'books/aski memnu/page (620).png',
    'books/aski memnu/page (621).png',
    'books/aski memnu/page (622).png',
    'books/aski memnu/page (623).png',
    'books/aski memnu/page (624).png',
    'books/aski memnu/page (625).png',
    'books/aski memnu/page (626).png',
    'books/aski memnu/page (627).png',
    'books/aski memnu/page (628).png',
    'books/aski memnu/page (629).png',
    'books/aski memnu/page (630).png',
    'books/aski memnu/page (631).png',
    'books/aski memnu/page (632).png',
    'books/aski memnu/page (633).png',
    'books/aski memnu/page (634).png',
    'books/aski memnu/page (635).png',
    'books/aski memnu/page (636).png',
    'books/aski memnu/page (637).png',
    'books/aski memnu/page (638).png',
    'books/aski memnu/page (639).png',
    'books/aski memnu/page (640).png',
    'books/aski memnu/page (641).png',
    'books/aski memnu/page (642).png',
    'books/aski memnu/page (643).png',
    'books/aski memnu/page (644).png',
    'books/aski memnu/page (645).png',
    'books/aski memnu/page (646).png',
    'books/aski memnu/page (647).png',
    'books/aski memnu/page (648).png',
    'books/aski memnu/page (649).png',
    'books/aski memnu/page (650).png',
    'books/aski memnu/page (651).png',
    'books/aski memnu/page (652).png',
    'books/aski memnu/page (653).png',
    'books/aski memnu/page (654).png',
    'books/aski memnu/page (655).png',
    'books/aski memnu/page (656).png',
    'books/aski memnu/page (657).png',
    'books/aski memnu/page (658).png',
    'books/aski memnu/page (659).png',
    'books/aski memnu/page (660).png',
    'books/aski memnu/page (661).png',
    'books/aski memnu/page (662).png',
    'books/aski memnu/page (663).png',
    'books/aski memnu/page (664).png',
    'books/aski memnu/page (665).png',
    'books/aski memnu/page (666).png',
    'books/aski memnu/page (667).png',
    'books/aski memnu/page (668).png',
    'books/aski memnu/page (669).png',
    'books/aski memnu/page (670).png',
    'books/aski memnu/page (671).png',
    'books/aski memnu/page (672).png',
    'books/aski memnu/page (673).png',
    'books/aski memnu/page (674).png',
    'books/aski memnu/page (675).png',
    'books/aski memnu/page (676).png',
    'books/aski memnu/page (677).png',
    'books/aski memnu/page (678).png',
    'books/aski memnu/page (679).png',
    'books/aski memnu/page (680).png',
    'books/aski memnu/page (681).png',
    'books/aski memnu/page (682).png',
    'books/aski memnu/page (683).png',
    'books/aski memnu/page (684).png',
    'books/aski memnu/page (685).png',
    'books/aski memnu/page (686).png',
    'books/aski memnu/page (687).png',
    'books/aski memnu/page (688).png',
    'books/aski memnu/page (689).png',
    'books/aski memnu/page (690).png',
    'books/aski memnu/page (691).png',
    'books/aski memnu/page (692).png',
    'books/aski memnu/page (693).png',
    'books/aski memnu/page (694).png',
    'books/aski memnu/page (695).png',
    'books/aski memnu/page (696).png',
    'books/aski memnu/page (697).png',
    'books/aski memnu/page (698).png',
    'books/aski memnu/page (699).png',
    'books/aski memnu/page (700).png',
    'books/aski memnu/page (701).png',
    'books/aski memnu/page (702).png',
    'books/aski memnu/page (703).png',
    'books/aski memnu/page (704).png',
    'books/aski memnu/page (705).png',
    'books/aski memnu/page (706).png',
    'books/aski memnu/page (707).png',
    'books/aski memnu/page (708).png',
    'books/aski memnu/page (709).png',
    'books/aski memnu/page (710).png',
    'books/aski memnu/page (711).png',
    'books/aski memnu/page (712).png',
    'books/aski memnu/page (713).png',
    'books/aski memnu/page (714).png',
    'books/aski memnu/page (715).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
