import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class barnabyrudge extends StatefulWidget {
  const barnabyrudge({Key? key}) : super(key: key);

  @override
  State<barnabyrudge> createState() => _barnabyrudgeState();
}

class _barnabyrudgeState extends State<barnabyrudge> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/Barnaby Rudge/page (1).png',
    'books/Barnaby Rudge/page (2).png',
    'books/Barnaby Rudge/page (3).png',
    'books/Barnaby Rudge/page (4).png',
    'books/Barnaby Rudge/page (5).png',
    'books/Barnaby Rudge/page (6).png',
    'books/Barnaby Rudge/page (7).png',
    'books/Barnaby Rudge/page (8).png',
    'books/Barnaby Rudge/page (9).png',
    'books/Barnaby Rudge/page (10).png',
    'books/Barnaby Rudge/page (11).png',
    'books/Barnaby Rudge/page (12).png',
    'books/Barnaby Rudge/page (13).png',
    'books/Barnaby Rudge/page (14).png',
    'books/Barnaby Rudge/page (15).png',
    'books/Barnaby Rudge/page (16).png',
    'books/Barnaby Rudge/page (17).png',
    'books/Barnaby Rudge/page (18).png',
    'books/Barnaby Rudge/page (19).png',
    'books/Barnaby Rudge/page (20).png',
    'books/Barnaby Rudge/page (21).png',
    'books/Barnaby Rudge/page (22).png',
    'books/Barnaby Rudge/page (23).png',
    'books/Barnaby Rudge/page (24).png',
    'books/Barnaby Rudge/page (25).png',
    'books/Barnaby Rudge/page (26).png',
    'books/Barnaby Rudge/page (27).png',
    'books/Barnaby Rudge/page (28).png',
    'books/Barnaby Rudge/page (29).png',
    'books/Barnaby Rudge/page (30).png',
    'books/Barnaby Rudge/page (31).png',
    'books/Barnaby Rudge/page (32).png',
    'books/Barnaby Rudge/page (33).png',
    'books/Barnaby Rudge/page (34).png',
    'books/Barnaby Rudge/page (35).png',
    'books/Barnaby Rudge/page (36).png',
    'books/Barnaby Rudge/page (37).png',
    'books/Barnaby Rudge/page (38).png',
    'books/Barnaby Rudge/page (39).png',
    'books/Barnaby Rudge/page (40).png',
    'books/Barnaby Rudge/page (41).png',
    'books/Barnaby Rudge/page (42).png',
    'books/Barnaby Rudge/page (43).png',
    'books/Barnaby Rudge/page (44).png',
    'books/Barnaby Rudge/page (45).png',
    'books/Barnaby Rudge/page (46).png',
    'books/Barnaby Rudge/page (47).png',
    'books/Barnaby Rudge/page (48).png',
    'books/Barnaby Rudge/page (49).png',
    'books/Barnaby Rudge/page (50).png',
    'books/Barnaby Rudge/page (51).png',
    'books/Barnaby Rudge/page (52).png',
    'books/Barnaby Rudge/page (53).png',
    'books/Barnaby Rudge/page (54).png',
    'books/Barnaby Rudge/page (55).png',
    'books/Barnaby Rudge/page (56).png',
    'books/Barnaby Rudge/page (57).png',
    'books/Barnaby Rudge/page (58).png',
    'books/Barnaby Rudge/page (59).png',
    'books/Barnaby Rudge/page (60).png',
    'books/Barnaby Rudge/page (61).png',
    'books/Barnaby Rudge/page (62).png',
    'books/Barnaby Rudge/page (63).png',
    'books/Barnaby Rudge/page (64).png',
    'books/Barnaby Rudge/page (65).png',
    'books/Barnaby Rudge/page (66).png',
    'books/Barnaby Rudge/page (67).png',
    'books/Barnaby Rudge/page (68).png',
    'books/Barnaby Rudge/page (69).png',
    'books/Barnaby Rudge/page (70).png',
    'books/Barnaby Rudge/page (71).png',
    'books/Barnaby Rudge/page (72).png',
    'books/Barnaby Rudge/page (73).png',
    'books/Barnaby Rudge/page (74).png',
    'books/Barnaby Rudge/page (75).png',
    'books/Barnaby Rudge/page (76).png',
    'books/Barnaby Rudge/page (77).png',
    'books/Barnaby Rudge/page (78).png',
    'books/Barnaby Rudge/page (79).png',
    'books/Barnaby Rudge/page (80).png',
    'books/Barnaby Rudge/page (81).png',
    'books/Barnaby Rudge/page (82).png',
    'books/Barnaby Rudge/page (83).png',
    'books/Barnaby Rudge/page (84).png',
    'books/Barnaby Rudge/page (85).png',
    'books/Barnaby Rudge/page (86).png',
    'books/Barnaby Rudge/page (87).png',
    'books/Barnaby Rudge/page (88).png',
    'books/Barnaby Rudge/page (89).png',
    'books/Barnaby Rudge/page (90).png',
    'books/Barnaby Rudge/page (91).png',
    'books/Barnaby Rudge/page (92).png',
    'books/Barnaby Rudge/page (93).png',
    'books/Barnaby Rudge/page (94).png',
    'books/Barnaby Rudge/page (95).png',
    'books/Barnaby Rudge/page (96).png',
    'books/Barnaby Rudge/page (97).png',
    'books/Barnaby Rudge/page (98).png',
    'books/Barnaby Rudge/page (99).png',
    'books/Barnaby Rudge/page (100).png',
    'books/Barnaby Rudge/page (101).png',
    'books/Barnaby Rudge/page (102).png',
    'books/Barnaby Rudge/page (103).png',
    'books/Barnaby Rudge/page (104).png',
    'books/Barnaby Rudge/page (105).png',
    'books/Barnaby Rudge/page (106).png',
    'books/Barnaby Rudge/page (107).png',
    'books/Barnaby Rudge/page (108).png',
    'books/Barnaby Rudge/page (109).png',
    'books/Barnaby Rudge/page (110).png',
    'books/Barnaby Rudge/page (111).png',
    'books/Barnaby Rudge/page (112).png',
    'books/Barnaby Rudge/page (113).png',
    'books/Barnaby Rudge/page (114).png',
    'books/Barnaby Rudge/page (115).png',
    'books/Barnaby Rudge/page (116).png',
    'books/Barnaby Rudge/page (117).png',
    'books/Barnaby Rudge/page (118).png',
    'books/Barnaby Rudge/page (119).png',
    'books/Barnaby Rudge/page (120).png',
    'books/Barnaby Rudge/page (121).png',
    'books/Barnaby Rudge/page (122).png',
    'books/Barnaby Rudge/page (123).png',
    'books/Barnaby Rudge/page (124).png',
    'books/Barnaby Rudge/page (125).png',
    'books/Barnaby Rudge/page (126).png',
    'books/Barnaby Rudge/page (127).png',
    'books/Barnaby Rudge/page (128).png',
    'books/Barnaby Rudge/page (129).png',
    'books/Barnaby Rudge/page (130).png',
    'books/Barnaby Rudge/page (131).png',
    'books/Barnaby Rudge/page (132).png',
    'books/Barnaby Rudge/page (133).png',
    'books/Barnaby Rudge/page (134).png',
    'books/Barnaby Rudge/page (135).png',
    'books/Barnaby Rudge/page (136).png',
    'books/Barnaby Rudge/page (137).png',
    'books/Barnaby Rudge/page (138).png',
    'books/Barnaby Rudge/page (139).png',
    'books/Barnaby Rudge/page (140).png',
    'books/Barnaby Rudge/page (141).png',
    'books/Barnaby Rudge/page (142).png',
    'books/Barnaby Rudge/page (143).png',
    'books/Barnaby Rudge/page (144).png',
    'books/Barnaby Rudge/page (145).png',
    'books/Barnaby Rudge/page (146).png',
    'books/Barnaby Rudge/page (147).png',
    'books/Barnaby Rudge/page (148).png',
    'books/Barnaby Rudge/page (149).png',
    'books/Barnaby Rudge/page (150).png',
    'books/Barnaby Rudge/page (151).png',
    'books/Barnaby Rudge/page (152).png',
    'books/Barnaby Rudge/page (153).png',
    'books/Barnaby Rudge/page (154).png',
    'books/Barnaby Rudge/page (155).png',
    'books/Barnaby Rudge/page (156).png',
    'books/Barnaby Rudge/page (157).png',
    'books/Barnaby Rudge/page (158).png',
    'books/Barnaby Rudge/page (159).png',
    'books/Barnaby Rudge/page (160).png',
    'books/Barnaby Rudge/page (161).png',
    'books/Barnaby Rudge/page (162).png',
    'books/Barnaby Rudge/page (163).png',
    'books/Barnaby Rudge/page (164).png',
    'books/Barnaby Rudge/page (165).png',
    'books/Barnaby Rudge/page (166).png',
    'books/Barnaby Rudge/page (167).png',
    'books/Barnaby Rudge/page (168).png',
    'books/Barnaby Rudge/page (169).png',
    'books/Barnaby Rudge/page (170).png',
    'books/Barnaby Rudge/page (171).png',
    'books/Barnaby Rudge/page (172).png',
    'books/Barnaby Rudge/page (173).png',
    'books/Barnaby Rudge/page (174).png',
    'books/Barnaby Rudge/page (175).png',
    'books/Barnaby Rudge/page (176).png',
    'books/Barnaby Rudge/page (177).png',
    'books/Barnaby Rudge/page (178).png',
    'books/Barnaby Rudge/page (179).png',
    'books/Barnaby Rudge/page (180).png',
    'books/Barnaby Rudge/page (181).png',
    'books/Barnaby Rudge/page (182).png',
    'books/Barnaby Rudge/page (183).png',
    'books/Barnaby Rudge/page (184).png',
    'books/Barnaby Rudge/page (185).png',
    'books/Barnaby Rudge/page (186).png',
    'books/Barnaby Rudge/page (187).png',
    'books/Barnaby Rudge/page (188).png',
    'books/Barnaby Rudge/page (189).png',
    'books/Barnaby Rudge/page (190).png',
    'books/Barnaby Rudge/page (191).png',
    'books/Barnaby Rudge/page (192).png',
    'books/Barnaby Rudge/page (193).png',
    'books/Barnaby Rudge/page (194).png',
    'books/Barnaby Rudge/page (195).png',
    'books/Barnaby Rudge/page (196).png',
    'books/Barnaby Rudge/page (197).png',
    'books/Barnaby Rudge/page (198).png',
    'books/Barnaby Rudge/page (199).png',
    'books/Barnaby Rudge/page (200).png',
    'books/Barnaby Rudge/page (201).png',
    'books/Barnaby Rudge/page (202).png',
    'books/Barnaby Rudge/page (203).png',
    'books/Barnaby Rudge/page (204).png',
    'books/Barnaby Rudge/page (205).png',
    'books/Barnaby Rudge/page (206).png',
    'books/Barnaby Rudge/page (207).png',
    'books/Barnaby Rudge/page (208).png',
    'books/Barnaby Rudge/page (209).png',
    'books/Barnaby Rudge/page (210).png',
    'books/Barnaby Rudge/page (211).png',
    'books/Barnaby Rudge/page (212).png',
    'books/Barnaby Rudge/page (213).png',
    'books/Barnaby Rudge/page (214).png',
    'books/Barnaby Rudge/page (215).png',
    'books/Barnaby Rudge/page (216).png',
    'books/Barnaby Rudge/page (217).png',
    'books/Barnaby Rudge/page (218).png',
    'books/Barnaby Rudge/page (219).png',
    'books/Barnaby Rudge/page (220).png',
    'books/Barnaby Rudge/page (221).png',
    'books/Barnaby Rudge/page (222).png',
    'books/Barnaby Rudge/page (223).png',
    'books/Barnaby Rudge/page (224).png',
    'books/Barnaby Rudge/page (225).png',
    'books/Barnaby Rudge/page (226).png',
    'books/Barnaby Rudge/page (227).png',
    'books/Barnaby Rudge/page (228).png',
    'books/Barnaby Rudge/page (229).png',
    'books/Barnaby Rudge/page (230).png',
    'books/Barnaby Rudge/page (231).png',
    'books/Barnaby Rudge/page (232).png',
    'books/Barnaby Rudge/page (233).png',
    'books/Barnaby Rudge/page (234).png',
    'books/Barnaby Rudge/page (235).png',
    'books/Barnaby Rudge/page (236).png',
    'books/Barnaby Rudge/page (237).png',
    'books/Barnaby Rudge/page (238).png',
    'books/Barnaby Rudge/page (239).png',
    'books/Barnaby Rudge/page (240).png',
    'books/Barnaby Rudge/page (241).png',
    'books/Barnaby Rudge/page (242).png',
    'books/Barnaby Rudge/page (243).png',
    'books/Barnaby Rudge/page (244).png',
    'books/Barnaby Rudge/page (245).png',
    'books/Barnaby Rudge/page (246).png',
    'books/Barnaby Rudge/page (247).png',
    'books/Barnaby Rudge/page (248).png',
    'books/Barnaby Rudge/page (249).png',
    'books/Barnaby Rudge/page (250).png',
    'books/Barnaby Rudge/page (251).png',
    'books/Barnaby Rudge/page (252).png',
    'books/Barnaby Rudge/page (253).png',
    'books/Barnaby Rudge/page (254).png',
    'books/Barnaby Rudge/page (255).png',
    'books/Barnaby Rudge/page (256).png',
    'books/Barnaby Rudge/page (257).png',
    'books/Barnaby Rudge/page (258).png',
    'books/Barnaby Rudge/page (259).png',
    'books/Barnaby Rudge/page (260).png',
    'books/Barnaby Rudge/page (261).png',
    'books/Barnaby Rudge/page (262).png',
    'books/Barnaby Rudge/page (263).png',
    'books/Barnaby Rudge/page (264).png',
    'books/Barnaby Rudge/page (265).png',
    'books/Barnaby Rudge/page (266).png',
    'books/Barnaby Rudge/page (267).png',
    'books/Barnaby Rudge/page (268).png',
    'books/Barnaby Rudge/page (269).png',
    'books/Barnaby Rudge/page (270).png',
    'books/Barnaby Rudge/page (271).png',
    'books/Barnaby Rudge/page (272).png',
    'books/Barnaby Rudge/page (273).png',
    'books/Barnaby Rudge/page (274).png',
    'books/Barnaby Rudge/page (275).png',
    'books/Barnaby Rudge/page (276).png',
    'books/Barnaby Rudge/page (277).png',
    'books/Barnaby Rudge/page (278).png',
    'books/Barnaby Rudge/page (279).png',
    'books/Barnaby Rudge/page (280).png',
    'books/Barnaby Rudge/page (281).png',
    'books/Barnaby Rudge/page (282).png',
    'books/Barnaby Rudge/page (283).png',
    'books/Barnaby Rudge/page (284).png',
    'books/Barnaby Rudge/page (285).png',
    'books/Barnaby Rudge/page (286).png',
    'books/Barnaby Rudge/page (287).png',
    'books/Barnaby Rudge/page (288).png',
    'books/Barnaby Rudge/page (289).png',
    'books/Barnaby Rudge/page (290).png',
    'books/Barnaby Rudge/page (291).png',
    'books/Barnaby Rudge/page (292).png',
    'books/Barnaby Rudge/page (293).png',
    'books/Barnaby Rudge/page (294).png',
    'books/Barnaby Rudge/page (295).png',
    'books/Barnaby Rudge/page (296).png',
    'books/Barnaby Rudge/page (297).png',
    'books/Barnaby Rudge/page (298).png',
    'books/Barnaby Rudge/page (299).png',
    'books/Barnaby Rudge/page (300).png',
    'books/Barnaby Rudge/page (301).png',
    'books/Barnaby Rudge/page (302).png',
    'books/Barnaby Rudge/page (303).png',
    'books/Barnaby Rudge/page (304).png',
    'books/Barnaby Rudge/page (305).png',
    'books/Barnaby Rudge/page (306).png',
    'books/Barnaby Rudge/page (307).png',
    'books/Barnaby Rudge/page (308).png',
    'books/Barnaby Rudge/page (309).png',
    'books/Barnaby Rudge/page (310).png',
    'books/Barnaby Rudge/page (311).png',
    'books/Barnaby Rudge/page (312).png',
    'books/Barnaby Rudge/page (313).png',
    'books/Barnaby Rudge/page (314).png',
    'books/Barnaby Rudge/page (315).png',
    'books/Barnaby Rudge/page (316).png',
    'books/Barnaby Rudge/page (317).png',
    'books/Barnaby Rudge/page (318).png',
    'books/Barnaby Rudge/page (319).png',
    'books/Barnaby Rudge/page (320).png',
    'books/Barnaby Rudge/page (321).png',
    'books/Barnaby Rudge/page (322).png',
    'books/Barnaby Rudge/page (323).png',
    'books/Barnaby Rudge/page (324).png',
    'books/Barnaby Rudge/page (325).png',
    'books/Barnaby Rudge/page (326).png',
    'books/Barnaby Rudge/page (327).png',
    'books/Barnaby Rudge/page (328).png',
    'books/Barnaby Rudge/page (329).png',
    'books/Barnaby Rudge/page (330).png',
    'books/Barnaby Rudge/page (331).png',
    'books/Barnaby Rudge/page (332).png',
    'books/Barnaby Rudge/page (333).png',
    'books/Barnaby Rudge/page (334).png',
    'books/Barnaby Rudge/page (335).png',
    'books/Barnaby Rudge/page (336).png',
    'books/Barnaby Rudge/page (337).png',
    'books/Barnaby Rudge/page (338).png',
    'books/Barnaby Rudge/page (339).png',
    'books/Barnaby Rudge/page (340).png',
    'books/Barnaby Rudge/page (341).png',
    'books/Barnaby Rudge/page (342).png',
    'books/Barnaby Rudge/page (343).png',
    'books/Barnaby Rudge/page (344).png',
    'books/Barnaby Rudge/page (345).png',
    'books/Barnaby Rudge/page (346).png',
    'books/Barnaby Rudge/page (347).png',
    'books/Barnaby Rudge/page (348).png',
    'books/Barnaby Rudge/page (349).png',
    'books/Barnaby Rudge/page (350).png',
    'books/Barnaby Rudge/page (351).png',
    'books/Barnaby Rudge/page (352).png',
    'books/Barnaby Rudge/page (353).png',
    'books/Barnaby Rudge/page (354).png',
    'books/Barnaby Rudge/page (355).png',
    'books/Barnaby Rudge/page (356).png',
    'books/Barnaby Rudge/page (357).png',
    'books/Barnaby Rudge/page (358).png',
    'books/Barnaby Rudge/page (359).png',
    'books/Barnaby Rudge/page (360).png',
    'books/Barnaby Rudge/page (361).png',
    'books/Barnaby Rudge/page (362).png',
    'books/Barnaby Rudge/page (363).png',
    'books/Barnaby Rudge/page (364).png',
    'books/Barnaby Rudge/page (365).png',
    'books/Barnaby Rudge/page (366).png',
    'books/Barnaby Rudge/page (367).png',
    'books/Barnaby Rudge/page (368).png',
    'books/Barnaby Rudge/page (369).png',
    'books/Barnaby Rudge/page (370).png',
    'books/Barnaby Rudge/page (371).png',
    'books/Barnaby Rudge/page (372).png',
    'books/Barnaby Rudge/page (373).png',
    'books/Barnaby Rudge/page (374).png',
    'books/Barnaby Rudge/page (375).png',
    'books/Barnaby Rudge/page (376).png',
    'books/Barnaby Rudge/page (377).png',
    'books/Barnaby Rudge/page (378).png',
    'books/Barnaby Rudge/page (379).png',
    'books/Barnaby Rudge/page (380).png',
    'books/Barnaby Rudge/page (381).png',
    'books/Barnaby Rudge/page (382).png',
    'books/Barnaby Rudge/page (383).png',
    'books/Barnaby Rudge/page (384).png',
    'books/Barnaby Rudge/page (385).png',
    'books/Barnaby Rudge/page (386).png',
    'books/Barnaby Rudge/page (387).png',
    'books/Barnaby Rudge/page (388).png',
    'books/Barnaby Rudge/page (389).png',
    'books/Barnaby Rudge/page (390).png',
    'books/Barnaby Rudge/page (391).png',
    'books/Barnaby Rudge/page (392).png',
    'books/Barnaby Rudge/page (393).png',
    'books/Barnaby Rudge/page (394).png',
    'books/Barnaby Rudge/page (395).png',
    'books/Barnaby Rudge/page (396).png',
    'books/Barnaby Rudge/page (397).png',
    'books/Barnaby Rudge/page (398).png',
    'books/Barnaby Rudge/page (399).png',
    'books/Barnaby Rudge/page (400).png',
    'books/Barnaby Rudge/page (401).png',
    'books/Barnaby Rudge/page (402).png',
    'books/Barnaby Rudge/page (403).png',
    'books/Barnaby Rudge/page (404).png',
    'books/Barnaby Rudge/page (405).png',
    'books/Barnaby Rudge/page (406).png',
    'books/Barnaby Rudge/page (407).png',
    'books/Barnaby Rudge/page (408).png',
    'books/Barnaby Rudge/page (409).png',
    'books/Barnaby Rudge/page (410).png',
    'books/Barnaby Rudge/page (411).png',
    'books/Barnaby Rudge/page (412).png',
    'books/Barnaby Rudge/page (413).png',
    'books/Barnaby Rudge/page (414).png',
    'books/Barnaby Rudge/page (415).png',
    'books/Barnaby Rudge/page (416).png',
    'books/Barnaby Rudge/page (417).png',
    'books/Barnaby Rudge/page (418).png',
    'books/Barnaby Rudge/page (419).png',
    'books/Barnaby Rudge/page (420).png',
    'books/Barnaby Rudge/page (421).png',
    'books/Barnaby Rudge/page (422).png',
    'books/Barnaby Rudge/page (423).png',
    'books/Barnaby Rudge/page (424).png',
    'books/Barnaby Rudge/page (425).png',
    'books/Barnaby Rudge/page (426).png',
    'books/Barnaby Rudge/page (427).png',
    'books/Barnaby Rudge/page (428).png',
    'books/Barnaby Rudge/page (429).png',
    'books/Barnaby Rudge/page (430).png',
    'books/Barnaby Rudge/page (431).png',
    'books/Barnaby Rudge/page (432).png',
    'books/Barnaby Rudge/page (433).png',
    'books/Barnaby Rudge/page (434).png',
    'books/Barnaby Rudge/page (435).png',
    'books/Barnaby Rudge/page (436).png',
    'books/Barnaby Rudge/page (437).png',
    'books/Barnaby Rudge/page (438).png',
    'books/Barnaby Rudge/page (439).png',
    'books/Barnaby Rudge/page (440).png',
    'books/Barnaby Rudge/page (441).png',
    'books/Barnaby Rudge/page (442).png',
    'books/Barnaby Rudge/page (443).png',
    'books/Barnaby Rudge/page (444).png',
    'books/Barnaby Rudge/page (445).png',
    'books/Barnaby Rudge/page (446).png',
    'books/Barnaby Rudge/page (447).png',
    'books/Barnaby Rudge/page (448).png',
    'books/Barnaby Rudge/page (449).png',
    'books/Barnaby Rudge/page (450).png',
    'books/Barnaby Rudge/page (451).png',
    'books/Barnaby Rudge/page (452).png',
    'books/Barnaby Rudge/page (453).png',
    'books/Barnaby Rudge/page (454).png',
    'books/Barnaby Rudge/page (455).png',
    'books/Barnaby Rudge/page (456).png',
    'books/Barnaby Rudge/page (457).png',
    'books/Barnaby Rudge/page (458).png',
    'books/Barnaby Rudge/page (459).png',
    'books/Barnaby Rudge/page (460).png',
    'books/Barnaby Rudge/page (461).png',
    'books/Barnaby Rudge/page (462).png',
    'books/Barnaby Rudge/page (463).png',
    'books/Barnaby Rudge/page (464).png',
    'books/Barnaby Rudge/page (465).png',
    'books/Barnaby Rudge/page (466).png',
    'books/Barnaby Rudge/page (467).png',
    'books/Barnaby Rudge/page (468).png',
    'books/Barnaby Rudge/page (469).png',
    'books/Barnaby Rudge/page (470).png',
    'books/Barnaby Rudge/page (471).png',
    'books/Barnaby Rudge/page (472).png',
    'books/Barnaby Rudge/page (473).png',
    'books/Barnaby Rudge/page (474).png',
    'books/Barnaby Rudge/page (475).png',
    'books/Barnaby Rudge/page (476).png',
    'books/Barnaby Rudge/page (477).png',
    'books/Barnaby Rudge/page (478).png',
    'books/Barnaby Rudge/page (479).png',
    'books/Barnaby Rudge/page (480).png',
    'books/Barnaby Rudge/page (481).png',
    'books/Barnaby Rudge/page (482).png',
    'books/Barnaby Rudge/page (483).png',
    'books/Barnaby Rudge/page (484).png',
    'books/Barnaby Rudge/page (485).png',
    'books/Barnaby Rudge/page (486).png',
    'books/Barnaby Rudge/page (487).png',
    'books/Barnaby Rudge/page (488).png',
    'books/Barnaby Rudge/page (489).png',
    'books/Barnaby Rudge/page (490).png',
    'books/Barnaby Rudge/page (491).png',
    'books/Barnaby Rudge/page (492).png',
    'books/Barnaby Rudge/page (493).png',
    'books/Barnaby Rudge/page (494).png',
    'books/Barnaby Rudge/page (495).png',
    'books/Barnaby Rudge/page (496).png',
    'books/Barnaby Rudge/page (497).png',
    'books/Barnaby Rudge/page (498).png',
    'books/Barnaby Rudge/page (499).png',
    'books/Barnaby Rudge/page (500).png',
    'books/Barnaby Rudge/page (501).png',
    'books/Barnaby Rudge/page (502).png',
    'books/Barnaby Rudge/page (503).png',
    'books/Barnaby Rudge/page (504).png',
    'books/Barnaby Rudge/page (505).png',
    'books/Barnaby Rudge/page (506).png',
    'books/Barnaby Rudge/page (507).png',
    'books/Barnaby Rudge/page (508).png',
    'books/Barnaby Rudge/page (509).png',
    'books/Barnaby Rudge/page (510).png',
    'books/Barnaby Rudge/page (511).png',
    'books/Barnaby Rudge/page (512).png',
    'books/Barnaby Rudge/page (513).png',
    'books/Barnaby Rudge/page (514).png',
    'books/Barnaby Rudge/page (515).png',
    'books/Barnaby Rudge/page (516).png',
    'books/Barnaby Rudge/page (517).png',
    'books/Barnaby Rudge/page (518).png',
    'books/Barnaby Rudge/page (519).png',
    'books/Barnaby Rudge/page (520).png',
    'books/Barnaby Rudge/page (521).png',
    'books/Barnaby Rudge/page (522).png',
    'books/Barnaby Rudge/page (523).png',
    'books/Barnaby Rudge/page (524).png',
    'books/Barnaby Rudge/page (525).png',
    'books/Barnaby Rudge/page (526).png',
    'books/Barnaby Rudge/page (527).png',
    'books/Barnaby Rudge/page (528).png',
    'books/Barnaby Rudge/page (529).png',
    'books/Barnaby Rudge/page (530).png',
    'books/Barnaby Rudge/page (531).png',
    'books/Barnaby Rudge/page (532).png',
    'books/Barnaby Rudge/page (533).png',
    'books/Barnaby Rudge/page (534).png',
    'books/Barnaby Rudge/page (535).png',
    'books/Barnaby Rudge/page (536).png',
    'books/Barnaby Rudge/page (537).png',
    'books/Barnaby Rudge/page (538).png',
    'books/Barnaby Rudge/page (539).png',
    'books/Barnaby Rudge/page (540).png',
    'books/Barnaby Rudge/page (541).png',
    'books/Barnaby Rudge/page (542).png',
    'books/Barnaby Rudge/page (543).png',
    'books/Barnaby Rudge/page (544).png',
    'books/Barnaby Rudge/page (545).png',
    'books/Barnaby Rudge/page (546).png',
    'books/Barnaby Rudge/page (547).png',
    'books/Barnaby Rudge/page (548).png',
    'books/Barnaby Rudge/page (549).png',
    'books/Barnaby Rudge/page (550).png',
    'books/Barnaby Rudge/page (551).png',
    'books/Barnaby Rudge/page (552).png',
    'books/Barnaby Rudge/page (553).png',
    'books/Barnaby Rudge/page (554).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
