import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class bleakhouse extends StatefulWidget {
  const bleakhouse({Key? key}) : super(key: key);

  @override
  State<bleakhouse> createState() => _bleakhouseState();
}

class _bleakhouseState extends State<bleakhouse> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/bleak house/page (1).png',
    'books/bleak house/page (2).png',
    'books/bleak house/page (3).png',
    'books/bleak house/page (4).png',
    'books/bleak house/page (5).png',
    'books/bleak house/page (6).png',
    'books/bleak house/page (7).png',
    'books/bleak house/page (8).png',
    'books/bleak house/page (9).png',
    'books/bleak house/page (10).png',
    'books/bleak house/page (11).png',
    'books/bleak house/page (12).png',
    'books/bleak house/page (13).png',
    'books/bleak house/page (14).png',
    'books/bleak house/page (15).png',
    'books/bleak house/page (16).png',
    'books/bleak house/page (17).png',
    'books/bleak house/page (18).png',
    'books/bleak house/page (19).png',
    'books/bleak house/page (20).png',
    'books/bleak house/page (21).png',
    'books/bleak house/page (22).png',
    'books/bleak house/page (23).png',
    'books/bleak house/page (24).png',
    'books/bleak house/page (25).png',
    'books/bleak house/page (26).png',
    'books/bleak house/page (27).png',
    'books/bleak house/page (28).png',
    'books/bleak house/page (29).png',
    'books/bleak house/page (30).png',
    'books/bleak house/page (31).png',
    'books/bleak house/page (32).png',
    'books/bleak house/page (33).png',
    'books/bleak house/page (34).png',
    'books/bleak house/page (35).png',
    'books/bleak house/page (36).png',
    'books/bleak house/page (37).png',
    'books/bleak house/page (38).png',
    'books/bleak house/page (39).png',
    'books/bleak house/page (40).png',
    'books/bleak house/page (41).png',
    'books/bleak house/page (42).png',
    'books/bleak house/page (43).png',
    'books/bleak house/page (44).png',
    'books/bleak house/page (45).png',
    'books/bleak house/page (46).png',
    'books/bleak house/page (47).png',
    'books/bleak house/page (48).png',
    'books/bleak house/page (49).png',
    'books/bleak house/page (50).png',
    'books/bleak house/page (51).png',
    'books/bleak house/page (52).png',
    'books/bleak house/page (53).png',
    'books/bleak house/page (54).png',
    'books/bleak house/page (55).png',
    'books/bleak house/page (56).png',
    'books/bleak house/page (57).png',
    'books/bleak house/page (58).png',
    'books/bleak house/page (59).png',
    'books/bleak house/page (60).png',
    'books/bleak house/page (61).png',
    'books/bleak house/page (62).png',
    'books/bleak house/page (63).png',
    'books/bleak house/page (64).png',
    'books/bleak house/page (65).png',
    'books/bleak house/page (66).png',
    'books/bleak house/page (67).png',
    'books/bleak house/page (68).png',
    'books/bleak house/page (69).png',
    'books/bleak house/page (70).png',
    'books/bleak house/page (71).png',
    'books/bleak house/page (72).png',
    'books/bleak house/page (73).png',
    'books/bleak house/page (74).png',
    'books/bleak house/page (75).png',
    'books/bleak house/page (76).png',
    'books/bleak house/page (77).png',
    'books/bleak house/page (78).png',
    'books/bleak house/page (79).png',
    'books/bleak house/page (80).png',
    'books/bleak house/page (81).png',
    'books/bleak house/page (82).png',
    'books/bleak house/page (83).png',
    'books/bleak house/page (84).png',
    'books/bleak house/page (85).png',
    'books/bleak house/page (86).png',
    'books/bleak house/page (87).png',
    'books/bleak house/page (88).png',
    'books/bleak house/page (89).png',
    'books/bleak house/page (90).png',
    'books/bleak house/page (91).png',
    'books/bleak house/page (92).png',
    'books/bleak house/page (93).png',
    'books/bleak house/page (94).png',
    'books/bleak house/page (95).png',
    'books/bleak house/page (96).png',
    'books/bleak house/page (97).png',
    'books/bleak house/page (98).png',
    'books/bleak house/page (99).png',
    'books/bleak house/page (100).png',
    'books/bleak house/page (101).png',
    'books/bleak house/page (102).png',
    'books/bleak house/page (103).png',
    'books/bleak house/page (104).png',
    'books/bleak house/page (105).png',
    'books/bleak house/page (106).png',
    'books/bleak house/page (107).png',
    'books/bleak house/page (108).png',
    'books/bleak house/page (109).png',
    'books/bleak house/page (110).png',
    'books/bleak house/page (111).png',
    'books/bleak house/page (112).png',
    'books/bleak house/page (113).png',
    'books/bleak house/page (114).png',
    'books/bleak house/page (115).png',
    'books/bleak house/page (116).png',
    'books/bleak house/page (117).png',
    'books/bleak house/page (118).png',
    'books/bleak house/page (119).png',
    'books/bleak house/page (120).png',
    'books/bleak house/page (121).png',
    'books/bleak house/page (122).png',
    'books/bleak house/page (123).png',
    'books/bleak house/page (124).png',
    'books/bleak house/page (125).png',
    'books/bleak house/page (126).png',
    'books/bleak house/page (127).png',
    'books/bleak house/page (128).png',
    'books/bleak house/page (129).png',
    'books/bleak house/page (130).png',
    'books/bleak house/page (131).png',
    'books/bleak house/page (132).png',
    'books/bleak house/page (133).png',
    'books/bleak house/page (134).png',
    'books/bleak house/page (135).png',
    'books/bleak house/page (136).png',
    'books/bleak house/page (137).png',
    'books/bleak house/page (138).png',
    'books/bleak house/page (139).png',
    'books/bleak house/page (140).png',
    'books/bleak house/page (141).png',
    'books/bleak house/page (142).png',
    'books/bleak house/page (143).png',
    'books/bleak house/page (144).png',
    'books/bleak house/page (145).png',
    'books/bleak house/page (146).png',
    'books/bleak house/page (147).png',
    'books/bleak house/page (148).png',
    'books/bleak house/page (149).png',
    'books/bleak house/page (150).png',
    'books/bleak house/page (151).png',
    'books/bleak house/page (152).png',
    'books/bleak house/page (153).png',
    'books/bleak house/page (154).png',
    'books/bleak house/page (155).png',
    'books/bleak house/page (156).png',
    'books/bleak house/page (157).png',
    'books/bleak house/page (158).png',
    'books/bleak house/page (159).png',
    'books/bleak house/page (160).png',
    'books/bleak house/page (161).png',
    'books/bleak house/page (162).png',
    'books/bleak house/page (163).png',
    'books/bleak house/page (164).png',
    'books/bleak house/page (165).png',
    'books/bleak house/page (166).png',
    'books/bleak house/page (167).png',
    'books/bleak house/page (168).png',
    'books/bleak house/page (169).png',
    'books/bleak house/page (170).png',
    'books/bleak house/page (171).png',
    'books/bleak house/page (172).png',
    'books/bleak house/page (173).png',
    'books/bleak house/page (174).png',
    'books/bleak house/page (175).png',
    'books/bleak house/page (176).png',
    'books/bleak house/page (177).png',
    'books/bleak house/page (178).png',
    'books/bleak house/page (179).png',
    'books/bleak house/page (180).png',
    'books/bleak house/page (181).png',
    'books/bleak house/page (182).png',
    'books/bleak house/page (183).png',
    'books/bleak house/page (184).png',
    'books/bleak house/page (185).png',
    'books/bleak house/page (186).png',
    'books/bleak house/page (187).png',
    'books/bleak house/page (188).png',
    'books/bleak house/page (189).png',
    'books/bleak house/page (190).png',
    'books/bleak house/page (191).png',
    'books/bleak house/page (192).png',
    'books/bleak house/page (193).png',
    'books/bleak house/page (194).png',
    'books/bleak house/page (195).png',
    'books/bleak house/page (196).png',
    'books/bleak house/page (197).png',
    'books/bleak house/page (198).png',
    'books/bleak house/page (199).png',
    'books/bleak house/page (200).png',
    'books/bleak house/page (201).png',
    'books/bleak house/page (202).png',
    'books/bleak house/page (203).png',
    'books/bleak house/page (204).png',
    'books/bleak house/page (205).png',
    'books/bleak house/page (206).png',
    'books/bleak house/page (207).png',
    'books/bleak house/page (208).png',
    'books/bleak house/page (209).png',
    'books/bleak house/page (210).png',
    'books/bleak house/page (211).png',
    'books/bleak house/page (212).png',
    'books/bleak house/page (213).png',
    'books/bleak house/page (214).png',
    'books/bleak house/page (215).png',
    'books/bleak house/page (216).png',
    'books/bleak house/page (217).png',
    'books/bleak house/page (218).png',
    'books/bleak house/page (219).png',
    'books/bleak house/page (220).png',
    'books/bleak house/page (221).png',
    'books/bleak house/page (222).png',
    'books/bleak house/page (223).png',
    'books/bleak house/page (224).png',
    'books/bleak house/page (225).png',
    'books/bleak house/page (226).png',
    'books/bleak house/page (227).png',
    'books/bleak house/page (228).png',
    'books/bleak house/page (229).png',
    'books/bleak house/page (230).png',
    'books/bleak house/page (231).png',
    'books/bleak house/page (232).png',
    'books/bleak house/page (233).png',
    'books/bleak house/page (234).png',
    'books/bleak house/page (235).png',
    'books/bleak house/page (236).png',
    'books/bleak house/page (237).png',
    'books/bleak house/page (238).png',
    'books/bleak house/page (239).png',
    'books/bleak house/page (240).png',
    'books/bleak house/page (241).png',
    'books/bleak house/page (242).png',
    'books/bleak house/page (243).png',
    'books/bleak house/page (244).png',
    'books/bleak house/page (245).png',
    'books/bleak house/page (246).png',
    'books/bleak house/page (247).png',
    'books/bleak house/page (248).png',
    'books/bleak house/page (249).png',
    'books/bleak house/page (250).png',
    'books/bleak house/page (251).png',
    'books/bleak house/page (252).png',
    'books/bleak house/page (253).png',
    'books/bleak house/page (254).png',
    'books/bleak house/page (255).png',
    'books/bleak house/page (256).png',
    'books/bleak house/page (257).png',
    'books/bleak house/page (258).png',
    'books/bleak house/page (259).png',
    'books/bleak house/page (260).png',
    'books/bleak house/page (261).png',
    'books/bleak house/page (262).png',
    'books/bleak house/page (263).png',
    'books/bleak house/page (264).png',
    'books/bleak house/page (265).png',
    'books/bleak house/page (266).png',
    'books/bleak house/page (267).png',
    'books/bleak house/page (268).png',
    'books/bleak house/page (269).png',
    'books/bleak house/page (270).png',
    'books/bleak house/page (271).png',
    'books/bleak house/page (272).png',
    'books/bleak house/page (273).png',
    'books/bleak house/page (274).png',
    'books/bleak house/page (275).png',
    'books/bleak house/page (276).png',
    'books/bleak house/page (277).png',
    'books/bleak house/page (278).png',
    'books/bleak house/page (279).png',
    'books/bleak house/page (280).png',
    'books/bleak house/page (281).png',
    'books/bleak house/page (282).png',
    'books/bleak house/page (283).png',
    'books/bleak house/page (284).png',
    'books/bleak house/page (285).png',
    'books/bleak house/page (286).png',
    'books/bleak house/page (287).png',
    'books/bleak house/page (288).png',
    'books/bleak house/page (289).png',
    'books/bleak house/page (290).png',
    'books/bleak house/page (291).png',
    'books/bleak house/page (292).png',
    'books/bleak house/page (293).png',
    'books/bleak house/page (294).png',
    'books/bleak house/page (295).png',
    'books/bleak house/page (296).png',
    'books/bleak house/page (297).png',
    'books/bleak house/page (298).png',
    'books/bleak house/page (299).png',
    'books/bleak house/page (300).png',
    'books/bleak house/page (301).png',
    'books/bleak house/page (302).png',
    'books/bleak house/page (303).png',
    'books/bleak house/page (304).png',
    'books/bleak house/page (305).png',
    'books/bleak house/page (306).png',
    'books/bleak house/page (307).png',
    'books/bleak house/page (308).png',
    'books/bleak house/page (309).png',
    'books/bleak house/page (310).png',
    'books/bleak house/page (311).png',
    'books/bleak house/page (312).png',
    'books/bleak house/page (313).png',
    'books/bleak house/page (314).png',
    'books/bleak house/page (315).png',
    'books/bleak house/page (316).png',
    'books/bleak house/page (317).png',
    'books/bleak house/page (318).png',
    'books/bleak house/page (319).png',
    'books/bleak house/page (320).png',
    'books/bleak house/page (321).png',
    'books/bleak house/page (322).png',
    'books/bleak house/page (323).png',
    'books/bleak house/page (324).png',
    'books/bleak house/page (325).png',
    'books/bleak house/page (326).png',
    'books/bleak house/page (327).png',
    'books/bleak house/page (328).png',
    'books/bleak house/page (329).png',
    'books/bleak house/page (330).png',
    'books/bleak house/page (331).png',
    'books/bleak house/page (332).png',
    'books/bleak house/page (333).png',
    'books/bleak house/page (334).png',
    'books/bleak house/page (335).png',
    'books/bleak house/page (336).png',
    'books/bleak house/page (337).png',
    'books/bleak house/page (338).png',
    'books/bleak house/page (339).png',
    'books/bleak house/page (340).png',
    'books/bleak house/page (341).png',
    'books/bleak house/page (342).png',
    'books/bleak house/page (343).png',
    'books/bleak house/page (344).png',
    'books/bleak house/page (345).png',
    'books/bleak house/page (346).png',
    'books/bleak house/page (347).png',
    'books/bleak house/page (348).png',
    'books/bleak house/page (349).png',
    'books/bleak house/page (350).png',
    'books/bleak house/page (351).png',
    'books/bleak house/page (352).png',
    'books/bleak house/page (353).png',
    'books/bleak house/page (354).png',
    'books/bleak house/page (355).png',
    'books/bleak house/page (356).png',
    'books/bleak house/page (357).png',
    'books/bleak house/page (358).png',
    'books/bleak house/page (359).png',
    'books/bleak house/page (360).png',
    'books/bleak house/page (361).png',
    'books/bleak house/page (362).png',
    'books/bleak house/page (363).png',
    'books/bleak house/page (364).png',
    'books/bleak house/page (365).png',
    'books/bleak house/page (366).png',
    'books/bleak house/page (367).png',
    'books/bleak house/page (368).png',
    'books/bleak house/page (369).png',
    'books/bleak house/page (370).png',
    'books/bleak house/page (371).png',
    'books/bleak house/page (372).png',
    'books/bleak house/page (373).png',
    'books/bleak house/page (374).png',
    'books/bleak house/page (375).png',
    'books/bleak house/page (376).png',
    'books/bleak house/page (377).png',
    'books/bleak house/page (378).png',
    'books/bleak house/page (379).png',
    'books/bleak house/page (380).png',
    'books/bleak house/page (381).png',
    'books/bleak house/page (382).png',
    'books/bleak house/page (383).png',
    'books/bleak house/page (384).png',
    'books/bleak house/page (385).png',
    'books/bleak house/page (386).png',
    'books/bleak house/page (387).png',
    'books/bleak house/page (388).png',
    'books/bleak house/page (389).png',
    'books/bleak house/page (390).png',
    'books/bleak house/page (391).png',
    'books/bleak house/page (392).png',
    'books/bleak house/page (393).png',
    'books/bleak house/page (394).png',
    'books/bleak house/page (395).png',
    'books/bleak house/page (396).png',
    'books/bleak house/page (397).png',
    'books/bleak house/page (398).png',
    'books/bleak house/page (399).png',
    'books/bleak house/page (400).png',
    'books/bleak house/page (401).png',
    'books/bleak house/page (402).png',
    'books/bleak house/page (403).png',
    'books/bleak house/page (404).png',
    'books/bleak house/page (405).png',
    'books/bleak house/page (406).png',
    'books/bleak house/page (407).png',
    'books/bleak house/page (408).png',
    'books/bleak house/page (409).png',
    'books/bleak house/page (410).png',
    'books/bleak house/page (411).png',
    'books/bleak house/page (412).png',
    'books/bleak house/page (413).png',
    'books/bleak house/page (414).png',
    'books/bleak house/page (415).png',
    'books/bleak house/page (416).png',
    'books/bleak house/page (417).png',
    'books/bleak house/page (418).png',
    'books/bleak house/page (419).png',
    'books/bleak house/page (420).png',
    'books/bleak house/page (421).png',
    'books/bleak house/page (422).png',
    'books/bleak house/page (423).png',
    'books/bleak house/page (424).png',
    'books/bleak house/page (425).png',
    'books/bleak house/page (426).png',
    'books/bleak house/page (427).png',
    'books/bleak house/page (428).png',
    'books/bleak house/page (429).png',
    'books/bleak house/page (430).png',
    'books/bleak house/page (431).png',
    'books/bleak house/page (432).png',
    'books/bleak house/page (433).png',
    'books/bleak house/page (434).png',
    'books/bleak house/page (435).png',
    'books/bleak house/page (436).png',
    'books/bleak house/page (437).png',
    'books/bleak house/page (438).png',
    'books/bleak house/page (439).png',
    'books/bleak house/page (440).png',
    'books/bleak house/page (441).png',
    'books/bleak house/page (442).png',
    'books/bleak house/page (443).png',
    'books/bleak house/page (444).png',
    'books/bleak house/page (445).png',
    'books/bleak house/page (446).png',
    'books/bleak house/page (447).png',
    'books/bleak house/page (448).png',
    'books/bleak house/page (449).png',
    'books/bleak house/page (450).png',
    'books/bleak house/page (451).png',
    'books/bleak house/page (452).png',
    'books/bleak house/page (453).png',
    'books/bleak house/page (454).png',
    'books/bleak house/page (455).png',
    'books/bleak house/page (456).png',
    'books/bleak house/page (457).png',
    'books/bleak house/page (458).png',
    'books/bleak house/page (459).png',
    'books/bleak house/page (460).png',
    'books/bleak house/page (461).png',
    'books/bleak house/page (462).png',
    'books/bleak house/page (463).png',
    'books/bleak house/page (464).png',
    'books/bleak house/page (465).png',
    'books/bleak house/page (466).png',
    'books/bleak house/page (467).png',
    'books/bleak house/page (468).png',
    'books/bleak house/page (469).png',
    'books/bleak house/page (470).png',
    'books/bleak house/page (471).png',
    'books/bleak house/page (472).png',
    'books/bleak house/page (473).png',
    'books/bleak house/page (474).png',
    'books/bleak house/page (475).png',
    'books/bleak house/page (476).png',
    'books/bleak house/page (477).png',
    'books/bleak house/page (478).png',
    'books/bleak house/page (479).png',
    'books/bleak house/page (480).png',
    'books/bleak house/page (481).png',
    'books/bleak house/page (482).png',
    'books/bleak house/page (483).png',
    'books/bleak house/page (484).png',
    'books/bleak house/page (485).png',
    'books/bleak house/page (486).png',
    'books/bleak house/page (487).png',
    'books/bleak house/page (488).png',
    'books/bleak house/page (489).png',
    'books/bleak house/page (490).png',
    'books/bleak house/page (491).png',
    'books/bleak house/page (492).png',
    'books/bleak house/page (493).png',
    'books/bleak house/page (494).png',
    'books/bleak house/page (495).png',
    'books/bleak house/page (496).png',
    'books/bleak house/page (497).png',
    'books/bleak house/page (498).png',
    'books/bleak house/page (499).png',
    'books/bleak house/page (500).png',
    'books/bleak house/page (501).png',
    'books/bleak house/page (502).png',
    'books/bleak house/page (503).png',
    'books/bleak house/page (504).png',
    'books/bleak house/page (505).png',
    'books/bleak house/page (506).png',
    'books/bleak house/page (507).png',
    'books/bleak house/page (508).png',
    'books/bleak house/page (509).png',
    'books/bleak house/page (510).png',
    'books/bleak house/page (511).png',
    'books/bleak house/page (512).png',
    'books/bleak house/page (513).png',
    'books/bleak house/page (514).png',
    'books/bleak house/page (515).png',
    'books/bleak house/page (516).png',
    'books/bleak house/page (517).png',
    'books/bleak house/page (518).png',
    'books/bleak house/page (519).png',
    'books/bleak house/page (520).png',
    'books/bleak house/page (521).png',
    'books/bleak house/page (522).png',
    'books/bleak house/page (523).png',
    'books/bleak house/page (524).png',
    'books/bleak house/page (525).png',
    'books/bleak house/page (526).png',
    'books/bleak house/page (527).png',
    'books/bleak house/page (528).png',
    'books/bleak house/page (529).png',
    'books/bleak house/page (530).png',
    'books/bleak house/page (531).png',
    'books/bleak house/page (532).png',
    'books/bleak house/page (533).png',
    'books/bleak house/page (534).png',
    'books/bleak house/page (535).png',
    'books/bleak house/page (536).png',
    'books/bleak house/page (537).png',
    'books/bleak house/page (538).png',
    'books/bleak house/page (539).png',
    'books/bleak house/page (540).png',
    'books/bleak house/page (541).png',
    'books/bleak house/page (542).png',
    'books/bleak house/page (543).png',
    'books/bleak house/page (544).png',
    'books/bleak house/page (545).png',
    'books/bleak house/page (546).png',
    'books/bleak house/page (547).png',
    'books/bleak house/page (548).png',
    'books/bleak house/page (549).png',
    'books/bleak house/page (550).png',
    'books/bleak house/page (551).png',
    'books/bleak house/page (552).png',
    'books/bleak house/page (553).png',
    'books/bleak house/page (554).png',
    'books/bleak house/page (555).png',
    'books/bleak house/page (556).png',
    'books/bleak house/page (557).png',
    'books/bleak house/page (558).png',
    'books/bleak house/page (559).png',
    'books/bleak house/page (560).png',
    'books/bleak house/page (561).png',
    'books/bleak house/page (562).png',
    'books/bleak house/page (563).png',
    'books/bleak house/page (564).png',
    'books/bleak house/page (565).png',
    'books/bleak house/page (566).png',
    'books/bleak house/page (567).png',
    'books/bleak house/page (568).png',
    'books/bleak house/page (569).png',
    'books/bleak house/page (570).png',
    'books/bleak house/page (571).png',
    'books/bleak house/page (572).png',
    'books/bleak house/page (573).png',
    'books/bleak house/page (574).png',
    'books/bleak house/page (575).png',
    'books/bleak house/page (576).png',
    'books/bleak house/page (577).png',
    'books/bleak house/page (578).png',
    'books/bleak house/page (579).png',
    'books/bleak house/page (580).png',
    'books/bleak house/page (581).png',
    'books/bleak house/page (582).png',
    'books/bleak house/page (583).png',
    'books/bleak house/page (584).png',
    'books/bleak house/page (585).png',
    'books/bleak house/page (586).png',
    'books/bleak house/page (587).png',
    'books/bleak house/page (588).png',
    'books/bleak house/page (589).png',
    'books/bleak house/page (590).png',
    'books/bleak house/page (591).png',
    'books/bleak house/page (592).png',
    'books/bleak house/page (593).png',
    'books/bleak house/page (594).png',
    'books/bleak house/page (595).png',
    'books/bleak house/page (596).png',
    'books/bleak house/page (597).png',
    'books/bleak house/page (598).png',
    'books/bleak house/page (599).png',
    'books/bleak house/page (600).png',
    'books/bleak house/page (601).png',
    'books/bleak house/page (602).png',
    'books/bleak house/page (603).png',
    'books/bleak house/page (604).png',
    'books/bleak house/page (605).png',
    'books/bleak house/page (606).png',
    'books/bleak house/page (607).png',
    'books/bleak house/page (608).png',
    'books/bleak house/page (609).png',
    'books/bleak house/page (610).png',
    'books/bleak house/page (611).png',
    'books/bleak house/page (612).png',
    'books/bleak house/page (613).png',
    'books/bleak house/page (614).png',
    'books/bleak house/page (615).png',
    'books/bleak house/page (616).png',
    'books/bleak house/page (617).png',
    'books/bleak house/page (618).png',
    'books/bleak house/page (619).png',
    'books/bleak house/page (620).png',
    'books/bleak house/page (621).png',
    'books/bleak house/page (622).png',
    'books/bleak house/page (623).png',
    'books/bleak house/page (624).png',
    'books/bleak house/page (625).png',
    'books/bleak house/page (626).png',
    'books/bleak house/page (627).png',
    'books/bleak house/page (628).png',
    'books/bleak house/page (629).png',
    'books/bleak house/page (630).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
