import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class brotherskaramazov extends StatefulWidget {
  const brotherskaramazov({Key? key}) : super(key: key);

  @override
  State<brotherskaramazov> createState() => _brotherskaramazovState();
}

class _brotherskaramazovState extends State<brotherskaramazov> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/brother karamazov/page (1).png',
    'books/brother karamazov/page (2).png',
    'books/brother karamazov/page (3).png',
    'books/brother karamazov/page (4).png',
    'books/brother karamazov/page (5).png',
    'books/brother karamazov/page (6).png',
    'books/brother karamazov/page (7).png',
    'books/brother karamazov/page (8).png',
    'books/brother karamazov/page (9).png',
    'books/brother karamazov/page (10).png',
    'books/brother karamazov/page (11).png',
    'books/brother karamazov/page (12).png',
    'books/brother karamazov/page (13).png',
    'books/brother karamazov/page (14).png',
    'books/brother karamazov/page (15).png',
    'books/brother karamazov/page (16).png',
    'books/brother karamazov/page (17).png',
    'books/brother karamazov/page (18).png',
    'books/brother karamazov/page (19).png',
    'books/brother karamazov/page (20).png',
    'books/brother karamazov/page (21).png',
    'books/brother karamazov/page (22).png',
    'books/brother karamazov/page (23).png',
    'books/brother karamazov/page (24).png',
    'books/brother karamazov/page (25).png',
    'books/brother karamazov/page (26).png',
    'books/brother karamazov/page (27).png',
    'books/brother karamazov/page (28).png',
    'books/brother karamazov/page (29).png',
    'books/brother karamazov/page (30).png',
    'books/brother karamazov/page (31).png',
    'books/brother karamazov/page (32).png',
    'books/brother karamazov/page (33).png',
    'books/brother karamazov/page (34).png',
    'books/brother karamazov/page (35).png',
    'books/brother karamazov/page (36).png',
    'books/brother karamazov/page (37).png',
    'books/brother karamazov/page (38).png',
    'books/brother karamazov/page (39).png',
    'books/brother karamazov/page (40).png',
    'books/brother karamazov/page (41).png',
    'books/brother karamazov/page (42).png',
    'books/brother karamazov/page (43).png',
    'books/brother karamazov/page (44).png',
    'books/brother karamazov/page (45).png',
    'books/brother karamazov/page (46).png',
    'books/brother karamazov/page (47).png',
    'books/brother karamazov/page (48).png',
    'books/brother karamazov/page (49).png',
    'books/brother karamazov/page (50).png',
    'books/brother karamazov/page (51).png',
    'books/brother karamazov/page (52).png',
    'books/brother karamazov/page (53).png',
    'books/brother karamazov/page (54).png',
    'books/brother karamazov/page (55).png',
    'books/brother karamazov/page (56).png',
    'books/brother karamazov/page (57).png',
    'books/brother karamazov/page (58).png',
    'books/brother karamazov/page (59).png',
    'books/brother karamazov/page (60).png',
    'books/brother karamazov/page (61).png',
    'books/brother karamazov/page (62).png',
    'books/brother karamazov/page (63).png',
    'books/brother karamazov/page (64).png',
    'books/brother karamazov/page (65).png',
    'books/brother karamazov/page (66).png',
    'books/brother karamazov/page (67).png',
    'books/brother karamazov/page (68).png',
    'books/brother karamazov/page (69).png',
    'books/brother karamazov/page (70).png',
    'books/brother karamazov/page (71).png',
    'books/brother karamazov/page (72).png',
    'books/brother karamazov/page (73).png',
    'books/brother karamazov/page (74).png',
    'books/brother karamazov/page (75).png',
    'books/brother karamazov/page (76).png',
    'books/brother karamazov/page (77).png',
    'books/brother karamazov/page (78).png',
    'books/brother karamazov/page (79).png',
    'books/brother karamazov/page (80).png',
    'books/brother karamazov/page (81).png',
    'books/brother karamazov/page (82).png',
    'books/brother karamazov/page (83).png',
    'books/brother karamazov/page (84).png',
    'books/brother karamazov/page (85).png',
    'books/brother karamazov/page (86).png',
    'books/brother karamazov/page (87).png',
    'books/brother karamazov/page (88).png',
    'books/brother karamazov/page (89).png',
    'books/brother karamazov/page (90).png',
    'books/brother karamazov/page (91).png',
    'books/brother karamazov/page (92).png',
    'books/brother karamazov/page (93).png',
    'books/brother karamazov/page (94).png',
    'books/brother karamazov/page (95).png',
    'books/brother karamazov/page (96).png',
    'books/brother karamazov/page (97).png',
    'books/brother karamazov/page (98).png',
    'books/brother karamazov/page (99).png',
    'books/brother karamazov/page (100).png',
    'books/brother karamazov/page (101).png',
    'books/brother karamazov/page (102).png',
    'books/brother karamazov/page (103).png',
    'books/brother karamazov/page (104).png',
    'books/brother karamazov/page (105).png',
    'books/brother karamazov/page (106).png',
    'books/brother karamazov/page (107).png',
    'books/brother karamazov/page (108).png',
    'books/brother karamazov/page (109).png',
    'books/brother karamazov/page (110).png',
    'books/brother karamazov/page (111).png',
    'books/brother karamazov/page (112).png',
    'books/brother karamazov/page (113).png',
    'books/brother karamazov/page (114).png',
    'books/brother karamazov/page (115).png',
    'books/brother karamazov/page (116).png',
    'books/brother karamazov/page (117).png',
    'books/brother karamazov/page (118).png',
    'books/brother karamazov/page (119).png',
    'books/brother karamazov/page (120).png',
    'books/brother karamazov/page (121).png',
    'books/brother karamazov/page (122).png',
    'books/brother karamazov/page (123).png',
    'books/brother karamazov/page (124).png',
    'books/brother karamazov/page (125).png',
    'books/brother karamazov/page (126).png',
    'books/brother karamazov/page (127).png',
    'books/brother karamazov/page (128).png',
    'books/brother karamazov/page (129).png',
    'books/brother karamazov/page (130).png',
    'books/brother karamazov/page (131).png',
    'books/brother karamazov/page (132).png',
    'books/brother karamazov/page (133).png',
    'books/brother karamazov/page (134).png',
    'books/brother karamazov/page (135).png',
    'books/brother karamazov/page (136).png',
    'books/brother karamazov/page (137).png',
    'books/brother karamazov/page (138).png',
    'books/brother karamazov/page (139).png',
    'books/brother karamazov/page (140).png',
    'books/brother karamazov/page (141).png',
    'books/brother karamazov/page (142).png',
    'books/brother karamazov/page (143).png',
    'books/brother karamazov/page (144).png',
    'books/brother karamazov/page (145).png',
    'books/brother karamazov/page (146).png',
    'books/brother karamazov/page (147).png',
    'books/brother karamazov/page (148).png',
    'books/brother karamazov/page (149).png',
    'books/brother karamazov/page (150).png',
    'books/brother karamazov/page (151).png',
    'books/brother karamazov/page (152).png',
    'books/brother karamazov/page (153).png',
    'books/brother karamazov/page (154).png',
    'books/brother karamazov/page (155).png',
    'books/brother karamazov/page (156).png',
    'books/brother karamazov/page (157).png',
    'books/brother karamazov/page (158).png',
    'books/brother karamazov/page (159).png',
    'books/brother karamazov/page (160).png',
    'books/brother karamazov/page (161).png',
    'books/brother karamazov/page (162).png',
    'books/brother karamazov/page (163).png',
    'books/brother karamazov/page (164).png',
    'books/brother karamazov/page (165).png',
    'books/brother karamazov/page (166).png',
    'books/brother karamazov/page (167).png',
    'books/brother karamazov/page (168).png',
    'books/brother karamazov/page (169).png',
    'books/brother karamazov/page (170).png',
    'books/brother karamazov/page (171).png',
    'books/brother karamazov/page (172).png',
    'books/brother karamazov/page (173).png',
    'books/brother karamazov/page (174).png',
    'books/brother karamazov/page (175).png',
    'books/brother karamazov/page (176).png',
    'books/brother karamazov/page (177).png',
    'books/brother karamazov/page (178).png',
    'books/brother karamazov/page (179).png',
    'books/brother karamazov/page (180).png',
    'books/brother karamazov/page (181).png',
    'books/brother karamazov/page (182).png',
    'books/brother karamazov/page (183).png',
    'books/brother karamazov/page (184).png',
    'books/brother karamazov/page (185).png',
    'books/brother karamazov/page (186).png',
    'books/brother karamazov/page (187).png',
    'books/brother karamazov/page (188).png',
    'books/brother karamazov/page (189).png',
    'books/brother karamazov/page (190).png',
    'books/brother karamazov/page (191).png',
    'books/brother karamazov/page (192).png',
    'books/brother karamazov/page (193).png',
    'books/brother karamazov/page (194).png',
    'books/brother karamazov/page (195).png',
    'books/brother karamazov/page (196).png',
    'books/brother karamazov/page (197).png',
    'books/brother karamazov/page (198).png',
    'books/brother karamazov/page (199).png',
    'books/brother karamazov/page (200).png',
    'books/brother karamazov/page (201).png',
    'books/brother karamazov/page (202).png',
    'books/brother karamazov/page (203).png',
    'books/brother karamazov/page (204).png',
    'books/brother karamazov/page (205).png',
    'books/brother karamazov/page (206).png',
    'books/brother karamazov/page (207).png',
    'books/brother karamazov/page (208).png',
    'books/brother karamazov/page (209).png',
    'books/brother karamazov/page (210).png',
    'books/brother karamazov/page (211).png',
    'books/brother karamazov/page (212).png',
    'books/brother karamazov/page (213).png',
    'books/brother karamazov/page (214).png',
    'books/brother karamazov/page (215).png',
    'books/brother karamazov/page (216).png',
    'books/brother karamazov/page (217).png',
    'books/brother karamazov/page (218).png',
    'books/brother karamazov/page (219).png',
    'books/brother karamazov/page (220).png',
    'books/brother karamazov/page (221).png',
    'books/brother karamazov/page (222).png',
    'books/brother karamazov/page (223).png',
    'books/brother karamazov/page (224).png',
    'books/brother karamazov/page (225).png',
    'books/brother karamazov/page (226).png',
    'books/brother karamazov/page (227).png',
    'books/brother karamazov/page (228).png',
    'books/brother karamazov/page (229).png',
    'books/brother karamazov/page (230).png',
    'books/brother karamazov/page (231).png',
    'books/brother karamazov/page (232).png',
    'books/brother karamazov/page (233).png',
    'books/brother karamazov/page (234).png',
    'books/brother karamazov/page (235).png',
    'books/brother karamazov/page (236).png',
    'books/brother karamazov/page (237).png',
    'books/brother karamazov/page (238).png',
    'books/brother karamazov/page (239).png',
    'books/brother karamazov/page (240).png',
    'books/brother karamazov/page (241).png',
    'books/brother karamazov/page (242).png',
    'books/brother karamazov/page (243).png',
    'books/brother karamazov/page (244).png',
    'books/brother karamazov/page (245).png',
    'books/brother karamazov/page (246).png',
    'books/brother karamazov/page (247).png',
    'books/brother karamazov/page (248).png',
    'books/brother karamazov/page (249).png',
    'books/brother karamazov/page (250).png',
    'books/brother karamazov/page (251).png',
    'books/brother karamazov/page (252).png',
    'books/brother karamazov/page (253).png',
    'books/brother karamazov/page (254).png',
    'books/brother karamazov/page (255).png',
    'books/brother karamazov/page (256).png',
    'books/brother karamazov/page (257).png',
    'books/brother karamazov/page (258).png',
    'books/brother karamazov/page (259).png',
    'books/brother karamazov/page (260).png',
    'books/brother karamazov/page (261).png',
    'books/brother karamazov/page (262).png',
    'books/brother karamazov/page (263).png',
    'books/brother karamazov/page (264).png',
    'books/brother karamazov/page (265).png',
    'books/brother karamazov/page (266).png',
    'books/brother karamazov/page (267).png',
    'books/brother karamazov/page (268).png',
    'books/brother karamazov/page (269).png',
    'books/brother karamazov/page (270).png',
    'books/brother karamazov/page (271).png',
    'books/brother karamazov/page (272).png',
    'books/brother karamazov/page (273).png',
    'books/brother karamazov/page (274).png',
    'books/brother karamazov/page (275).png',
    'books/brother karamazov/page (276).png',
    'books/brother karamazov/page (277).png',
    'books/brother karamazov/page (278).png',
    'books/brother karamazov/page (279).png',
    'books/brother karamazov/page (280).png',
    'books/brother karamazov/page (281).png',
    'books/brother karamazov/page (282).png',
    'books/brother karamazov/page (283).png',
    'books/brother karamazov/page (284).png',
    'books/brother karamazov/page (285).png',
    'books/brother karamazov/page (286).png',
    'books/brother karamazov/page (287).png',
    'books/brother karamazov/page (288).png',
    'books/brother karamazov/page (289).png',
    'books/brother karamazov/page (290).png',
    'books/brother karamazov/page (291).png',
    'books/brother karamazov/page (292).png',
    'books/brother karamazov/page (293).png',
    'books/brother karamazov/page (294).png',
    'books/brother karamazov/page (295).png',
    'books/brother karamazov/page (296).png',
    'books/brother karamazov/page (297).png',
    'books/brother karamazov/page (298).png',
    'books/brother karamazov/page (299).png',
    'books/brother karamazov/page (300).png',
    'books/brother karamazov/page (301).png',
    'books/brother karamazov/page (302).png',
    'books/brother karamazov/page (303).png',
    'books/brother karamazov/page (304).png',
    'books/brother karamazov/page (305).png',
    'books/brother karamazov/page (306).png',
    'books/brother karamazov/page (307).png',
    'books/brother karamazov/page (308).png',
    'books/brother karamazov/page (309).png',
    'books/brother karamazov/page (310).png',
    'books/brother karamazov/page (311).png',
    'books/brother karamazov/page (312).png',
    'books/brother karamazov/page (313).png',
    'books/brother karamazov/page (314).png',
    'books/brother karamazov/page (315).png',
    'books/brother karamazov/page (316).png',
    'books/brother karamazov/page (317).png',
    'books/brother karamazov/page (318).png',
    'books/brother karamazov/page (319).png',
    'books/brother karamazov/page (320).png',
    'books/brother karamazov/page (321).png',
    'books/brother karamazov/page (322).png',
    'books/brother karamazov/page (323).png',
    'books/brother karamazov/page (324).png',
    'books/brother karamazov/page (325).png',
    'books/brother karamazov/page (326).png',
    'books/brother karamazov/page (327).png',
    'books/brother karamazov/page (328).png',
    'books/brother karamazov/page (329).png',
    'books/brother karamazov/page (330).png',
    'books/brother karamazov/page (331).png',
    'books/brother karamazov/page (332).png',
    'books/brother karamazov/page (333).png',
    'books/brother karamazov/page (334).png',
    'books/brother karamazov/page (335).png',
    'books/brother karamazov/page (336).png',
    'books/brother karamazov/page (337).png',
    'books/brother karamazov/page (338).png',
    'books/brother karamazov/page (339).png',
    'books/brother karamazov/page (340).png',
    'books/brother karamazov/page (341).png',
    'books/brother karamazov/page (342).png',
    'books/brother karamazov/page (343).png',
    'books/brother karamazov/page (344).png',
    'books/brother karamazov/page (345).png',
    'books/brother karamazov/page (346).png',
    'books/brother karamazov/page (347).png',
    'books/brother karamazov/page (348).png',
    'books/brother karamazov/page (349).png',
    'books/brother karamazov/page (350).png',
    'books/brother karamazov/page (351).png',
    'books/brother karamazov/page (352).png',
    'books/brother karamazov/page (353).png',
    'books/brother karamazov/page (354).png',
    'books/brother karamazov/page (355).png',
    'books/brother karamazov/page (356).png',
    'books/brother karamazov/page (357).png',
    'books/brother karamazov/page (358).png',
    'books/brother karamazov/page (359).png',
    'books/brother karamazov/page (360).png',
    'books/brother karamazov/page (361).png',
    'books/brother karamazov/page (362).png',
    'books/brother karamazov/page (363).png',
    'books/brother karamazov/page (364).png',
    'books/brother karamazov/page (365).png',
    'books/brother karamazov/page (366).png',
    'books/brother karamazov/page (367).png',
    'books/brother karamazov/page (368).png',
    'books/brother karamazov/page (369).png',
    'books/brother karamazov/page (370).png',
    'books/brother karamazov/page (371).png',
    'books/brother karamazov/page (372).png',
    'books/brother karamazov/page (373).png',
    'books/brother karamazov/page (374).png',
    'books/brother karamazov/page (375).png',
    'books/brother karamazov/page (376).png',
    'books/brother karamazov/page (377).png',
    'books/brother karamazov/page (378).png',
    'books/brother karamazov/page (379).png',
    'books/brother karamazov/page (380).png',
    'books/brother karamazov/page (381).png',
    'books/brother karamazov/page (382).png',
    'books/brother karamazov/page (383).png',
    'books/brother karamazov/page (384).png',
    'books/brother karamazov/page (385).png',
    'books/brother karamazov/page (386).png',
    'books/brother karamazov/page (387).png',
    'books/brother karamazov/page (388).png',
    'books/brother karamazov/page (389).png',
    'books/brother karamazov/page (390).png',
    'books/brother karamazov/page (391).png',
    'books/brother karamazov/page (392).png',
    'books/brother karamazov/page (393).png',
    'books/brother karamazov/page (394).png',
    'books/brother karamazov/page (395).png',
    'books/brother karamazov/page (396).png',
    'books/brother karamazov/page (397).png',
    'books/brother karamazov/page (398).png',
    'books/brother karamazov/page (399).png',
    'books/brother karamazov/page (400).png',
    'books/brother karamazov/page (401).png',
    'books/brother karamazov/page (402).png',
    'books/brother karamazov/page (403).png',
    'books/brother karamazov/page (404).png',
    'books/brother karamazov/page (405).png',
    'books/brother karamazov/page (406).png',
    'books/brother karamazov/page (407).png',
    'books/brother karamazov/page (408).png',
    'books/brother karamazov/page (409).png',
    'books/brother karamazov/page (410).png',
    'books/brother karamazov/page (411).png',
    'books/brother karamazov/page (412).png',
    'books/brother karamazov/page (413).png',
    'books/brother karamazov/page (414).png',
    'books/brother karamazov/page (415).png',
    'books/brother karamazov/page (416).png',
    'books/brother karamazov/page (417).png',
    'books/brother karamazov/page (418).png',
    'books/brother karamazov/page (419).png',
    'books/brother karamazov/page (420).png',
    'books/brother karamazov/page (421).png',
    'books/brother karamazov/page (422).png',
    'books/brother karamazov/page (423).png',
    'books/brother karamazov/page (424).png',
    'books/brother karamazov/page (425).png',
    'books/brother karamazov/page (426).png',
    'books/brother karamazov/page (427).png',
    'books/brother karamazov/page (428).png',
    'books/brother karamazov/page (429).png',
    'books/brother karamazov/page (430).png',
    'books/brother karamazov/page (431).png',
    'books/brother karamazov/page (432).png',
    'books/brother karamazov/page (433).png',
    'books/brother karamazov/page (434).png',
    'books/brother karamazov/page (435).png',
    'books/brother karamazov/page (436).png',
    'books/brother karamazov/page (437).png',
    'books/brother karamazov/page (438).png',
    'books/brother karamazov/page (439).png',
    'books/brother karamazov/page (440).png',
    'books/brother karamazov/page (441).png',
    'books/brother karamazov/page (442).png',
    'books/brother karamazov/page (443).png',
    'books/brother karamazov/page (444).png',
    'books/brother karamazov/page (445).png',
    'books/brother karamazov/page (446).png',
    'books/brother karamazov/page (447).png',
    'books/brother karamazov/page (448).png',
    'books/brother karamazov/page (449).png',
    'books/brother karamazov/page (450).png',
    'books/brother karamazov/page (451).png',
    'books/brother karamazov/page (452).png',
    'books/brother karamazov/page (453).png',
    'books/brother karamazov/page (454).png',
    'books/brother karamazov/page (455).png',
    'books/brother karamazov/page (456).png',
    'books/brother karamazov/page (457).png',
    'books/brother karamazov/page (458).png',
    'books/brother karamazov/page (459).png',
    'books/brother karamazov/page (460).png',
    'books/brother karamazov/page (461).png',
    'books/brother karamazov/page (462).png',
    'books/brother karamazov/page (463).png',
    'books/brother karamazov/page (464).png',
    'books/brother karamazov/page (465).png',
    'books/brother karamazov/page (466).png',
    'books/brother karamazov/page (467).png',
    'books/brother karamazov/page (468).png',
    'books/brother karamazov/page (469).png',
    'books/brother karamazov/page (470).png',
    'books/brother karamazov/page (471).png',
    'books/brother karamazov/page (472).png',
    'books/brother karamazov/page (473).png',
    'books/brother karamazov/page (474).png',
    'books/brother karamazov/page (475).png',
    'books/brother karamazov/page (476).png',
    'books/brother karamazov/page (477).png',
    'books/brother karamazov/page (478).png',
    'books/brother karamazov/page (479).png',
    'books/brother karamazov/page (480).png',
    'books/brother karamazov/page (481).png',
    'books/brother karamazov/page (482).png',
    'books/brother karamazov/page (483).png',
    'books/brother karamazov/page (484).png',
    'books/brother karamazov/page (485).png',
    'books/brother karamazov/page (486).png',
    'books/brother karamazov/page (487).png',
    'books/brother karamazov/page (488).png',
    'books/brother karamazov/page (489).png',
    'books/brother karamazov/page (490).png',
    'books/brother karamazov/page (491).png',
    'books/brother karamazov/page (492).png',
    'books/brother karamazov/page (493).png',
    'books/brother karamazov/page (494).png',
    'books/brother karamazov/page (495).png',
    'books/brother karamazov/page (496).png',
    'books/brother karamazov/page (497).png',
    'books/brother karamazov/page (498).png',
    'books/brother karamazov/page (499).png',
    'books/brother karamazov/page (500).png',
    'books/brother karamazov/page (501).png',
    'books/brother karamazov/page (502).png',
    'books/brother karamazov/page (503).png',
    'books/brother karamazov/page (504).png',
    'books/brother karamazov/page (505).png',
    'books/brother karamazov/page (506).png',
    'books/brother karamazov/page (507).png',
    'books/brother karamazov/page (508).png',
    'books/brother karamazov/page (509).png',
    'books/brother karamazov/page (510).png',
    'books/brother karamazov/page (511).png',
    'books/brother karamazov/page (512).png',
    'books/brother karamazov/page (513).png',
    'books/brother karamazov/page (514).png',
    'books/brother karamazov/page (515).png',
    'books/brother karamazov/page (516).png',
    'books/brother karamazov/page (517).png',
    'books/brother karamazov/page (518).png',
    'books/brother karamazov/page (519).png',
    'books/brother karamazov/page (520).png',
    'books/brother karamazov/page (521).png',
    'books/brother karamazov/page (522).png',
    'books/brother karamazov/page (523).png',
    'books/brother karamazov/page (524).png',
    'books/brother karamazov/page (525).png',
    'books/brother karamazov/page (526).png',
    'books/brother karamazov/page (527).png',
    'books/brother karamazov/page (528).png',
    'books/brother karamazov/page (529).png',
    'books/brother karamazov/page (530).png',
    'books/brother karamazov/page (531).png',
    'books/brother karamazov/page (532).png',
    'books/brother karamazov/page (533).png',
    'books/brother karamazov/page (534).png',
    'books/brother karamazov/page (535).png',
    'books/brother karamazov/page (536).png',
    'books/brother karamazov/page (537).png',
    'books/brother karamazov/page (538).png',
    'books/brother karamazov/page (539).png',
    'books/brother karamazov/page (540).png',
    'books/brother karamazov/page (541).png',
    'books/brother karamazov/page (542).png',
    'books/brother karamazov/page (543).png',
    'books/brother karamazov/page (544).png',
    'books/brother karamazov/page (545).png',
    'books/brother karamazov/page (546).png',
    'books/brother karamazov/page (547).png',
    'books/brother karamazov/page (548).png',
    'books/brother karamazov/page (549).png',
    'books/brother karamazov/page (550).png',
    'books/brother karamazov/page (551).png',
    'books/brother karamazov/page (552).png',
    'books/brother karamazov/page (553).png',
    'books/brother karamazov/page (554).png',
    'books/brother karamazov/page (555).png',
    'books/brother karamazov/page (556).png',
    'books/brother karamazov/page (557).png',
    'books/brother karamazov/page (558).png',
    'books/brother karamazov/page (559).png',
    'books/brother karamazov/page (560).png',
    'books/brother karamazov/page (561).png',
    'books/brother karamazov/page (562).png',
    'books/brother karamazov/page (563).png',
    'books/brother karamazov/page (564).png',
    'books/brother karamazov/page (565).png',
    'books/brother karamazov/page (566).png',
    'books/brother karamazov/page (567).png',
    'books/brother karamazov/page (568).png',
    'books/brother karamazov/page (569).png',
    'books/brother karamazov/page (570).png',
    'books/brother karamazov/page (571).png',
    'books/brother karamazov/page (572).png',
    'books/brother karamazov/page (573).png',
    'books/brother karamazov/page (574).png',
    'books/brother karamazov/page (575).png',
    'books/brother karamazov/page (576).png',
    'books/brother karamazov/page (577).png',
    'books/brother karamazov/page (578).png',
    'books/brother karamazov/page (579).png',
    'books/brother karamazov/page (580).png',
    'books/brother karamazov/page (581).png',
    'books/brother karamazov/page (582).png',
    'books/brother karamazov/page (583).png',
    'books/brother karamazov/page (584).png',
    'books/brother karamazov/page (585).png',
    'books/brother karamazov/page (586).png',
    'books/brother karamazov/page (587).png',
    'books/brother karamazov/page (588).png',
    'books/brother karamazov/page (589).png',
    'books/brother karamazov/page (590).png',
    'books/brother karamazov/page (591).png',
    'books/brother karamazov/page (592).png',
    'books/brother karamazov/page (593).png',
    'books/brother karamazov/page (594).png',
    'books/brother karamazov/page (595).png',
    'books/brother karamazov/page (596).png',
    'books/brother karamazov/page (597).png',
    'books/brother karamazov/page (598).png',
    'books/brother karamazov/page (599).png',
    'books/brother karamazov/page (600).png',
    'books/brother karamazov/page (601).png',
    'books/brother karamazov/page (602).png',
    'books/brother karamazov/page (603).png',
    'books/brother karamazov/page (604).png',
    'books/brother karamazov/page (605).png',
    'books/brother karamazov/page (606).png',
    'books/brother karamazov/page (607).png',
    'books/brother karamazov/page (608).png',
    'books/brother karamazov/page (609).png',
    'books/brother karamazov/page (610).png',
    'books/brother karamazov/page (611).png',
    'books/brother karamazov/page (612).png',
    'books/brother karamazov/page (613).png',
    'books/brother karamazov/page (614).png',
    'books/brother karamazov/page (615).png',
    'books/brother karamazov/page (616).png',
    'books/brother karamazov/page (617).png',
    'books/brother karamazov/page (618).png',
    'books/brother karamazov/page (619).png',
    'books/brother karamazov/page (620).png',
    'books/brother karamazov/page (621).png',
    'books/brother karamazov/page (622).png',
    'books/brother karamazov/page (623).png',
    'books/brother karamazov/page (624).png',
    'books/brother karamazov/page (625).png',
    'books/brother karamazov/page (626).png',
    'books/brother karamazov/page (627).png',
    'books/brother karamazov/page (628).png',
    'books/brother karamazov/page (629).png',
    'books/brother karamazov/page (630).png',
    'books/brother karamazov/page (631).png',
    'books/brother karamazov/page (632).png',
    'books/brother karamazov/page (633).png',
    'books/brother karamazov/page (634).png',
    'books/brother karamazov/page (635).png',
    'books/brother karamazov/page (636).png',
    'books/brother karamazov/page (637).png',
    'books/brother karamazov/page (638).png',
    'books/brother karamazov/page (639).png',
    'books/brother karamazov/page (640).png',
    'books/brother karamazov/page (641).png',
    'books/brother karamazov/page (642).png',
    'books/brother karamazov/page (643).png',
    'books/brother karamazov/page (644).png',
    'books/brother karamazov/page (645).png',
    'books/brother karamazov/page (646).png',
    'books/brother karamazov/page (647).png',
    'books/brother karamazov/page (648).png',
    'books/brother karamazov/page (649).png',
    'books/brother karamazov/page (650).png',
    'books/brother karamazov/page (651).png',
    'books/brother karamazov/page (652).png',
    'books/brother karamazov/page (653).png',
    'books/brother karamazov/page (654).png',
    'books/brother karamazov/page (655).png',
    'books/brother karamazov/page (656).png',
    'books/brother karamazov/page (657).png',
    'books/brother karamazov/page (658).png',
    'books/brother karamazov/page (659).png',
    'books/brother karamazov/page (660).png',
    'books/brother karamazov/page (661).png',
    'books/brother karamazov/page (662).png',
    'books/brother karamazov/page (663).png',
    'books/brother karamazov/page (664).png',
    'books/brother karamazov/page (665).png',
    'books/brother karamazov/page (666).png',
    'books/brother karamazov/page (667).png',
    'books/brother karamazov/page (668).png',
    'books/brother karamazov/page (669).png',
    'books/brother karamazov/page (670).png',
    'books/brother karamazov/page (671).png',
    'books/brother karamazov/page (672).png',
    'books/brother karamazov/page (673).png',
    'books/brother karamazov/page (674).png',
    'books/brother karamazov/page (675).png',
    'books/brother karamazov/page (676).png',
    'books/brother karamazov/page (677).png',
    'books/brother karamazov/page (678).png',
    'books/brother karamazov/page (679).png',
    'books/brother karamazov/page (680).png',
    'books/brother karamazov/page (681).png',
    'books/brother karamazov/page (682).png',
    'books/brother karamazov/page (683).png',
    'books/brother karamazov/page (684).png',
    'books/brother karamazov/page (685).png',
    'books/brother karamazov/page (686).png',
    'books/brother karamazov/page (687).png',
    'books/brother karamazov/page (688).png',
    'books/brother karamazov/page (689).png',
    'books/brother karamazov/page (690).png',
    'books/brother karamazov/page (691).png',
    'books/brother karamazov/page (692).png',
    'books/brother karamazov/page (693).png',
    'books/brother karamazov/page (694).png',
    'books/brother karamazov/page (695).png',
    'books/brother karamazov/page (696).png',
    'books/brother karamazov/page (697).png',
    'books/brother karamazov/page (698).png',
    'books/brother karamazov/page (699).png',
    'books/brother karamazov/page (700).png',
    'books/brother karamazov/page (701).png',
    'books/brother karamazov/page (702).png',
    'books/brother karamazov/page (703).png',
    'books/brother karamazov/page (704).png',
    'books/brother karamazov/page (705).png',
    'books/brother karamazov/page (706).png',
    'books/brother karamazov/page (707).png',
    'books/brother karamazov/page (708).png',
    'books/brother karamazov/page (709).png',
    'books/brother karamazov/page (710).png',
    'books/brother karamazov/page (711).png',
    'books/brother karamazov/page (712).png',
    'books/brother karamazov/page (713).png',
    'books/brother karamazov/page (714).png',
    'books/brother karamazov/page (715).png',
    'books/brother karamazov/page (716).png',
    'books/brother karamazov/page (717).png',
    'books/brother karamazov/page (718).png',
    'books/brother karamazov/page (719).png',
    'books/brother karamazov/page (720).png',
    'books/brother karamazov/page (721).png',
    'books/brother karamazov/page (722).png',
    'books/brother karamazov/page (723).png',
    'books/brother karamazov/page (724).png',
    'books/brother karamazov/page (725).png',
    'books/brother karamazov/page (726).png',
    'books/brother karamazov/page (727).png',
    'books/brother karamazov/page (728).png',
    'books/brother karamazov/page (729).png',
    'books/brother karamazov/page (730).png',
    'books/brother karamazov/page (731).png',
    'books/brother karamazov/page (732).png',
    'books/brother karamazov/page (733).png',
    'books/brother karamazov/page (734).png',
    'books/brother karamazov/page (735).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
