import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class chartreuseparma extends StatefulWidget {
  const chartreuseparma({Key? key}) : super(key: key);

  @override
  State<chartreuseparma> createState() => _chartreuseparmaState();
}

class _chartreuseparmaState extends State<chartreuseparma> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/chartreuse parma/page (1).png',
    'books/chartreuse parma/page (2).png',
    'books/chartreuse parma/page (3).png',
    'books/chartreuse parma/page (4).png',
    'books/chartreuse parma/page (5).png',
    'books/chartreuse parma/page (6).png',
    'books/chartreuse parma/page (7).png',
    'books/chartreuse parma/page (8).png',
    'books/chartreuse parma/page (9).png',
    'books/chartreuse parma/page (10).png',
    'books/chartreuse parma/page (11).png',
    'books/chartreuse parma/page (12).png',
    'books/chartreuse parma/page (13).png',
    'books/chartreuse parma/page (14).png',
    'books/chartreuse parma/page (15).png',
    'books/chartreuse parma/page (16).png',
    'books/chartreuse parma/page (17).png',
    'books/chartreuse parma/page (18).png',
    'books/chartreuse parma/page (19).png',
    'books/chartreuse parma/page (20).png',
    'books/chartreuse parma/page (21).png',
    'books/chartreuse parma/page (22).png',
    'books/chartreuse parma/page (23).png',
    'books/chartreuse parma/page (24).png',
    'books/chartreuse parma/page (25).png',
    'books/chartreuse parma/page (26).png',
    'books/chartreuse parma/page (27).png',
    'books/chartreuse parma/page (28).png',
    'books/chartreuse parma/page (29).png',
    'books/chartreuse parma/page (30).png',
    'books/chartreuse parma/page (31).png',
    'books/chartreuse parma/page (32).png',
    'books/chartreuse parma/page (33).png',
    'books/chartreuse parma/page (34).png',
    'books/chartreuse parma/page (35).png',
    'books/chartreuse parma/page (36).png',
    'books/chartreuse parma/page (37).png',
    'books/chartreuse parma/page (38).png',
    'books/chartreuse parma/page (39).png',
    'books/chartreuse parma/page (40).png',
    'books/chartreuse parma/page (41).png',
    'books/chartreuse parma/page (42).png',
    'books/chartreuse parma/page (43).png',
    'books/chartreuse parma/page (44).png',
    'books/chartreuse parma/page (45).png',
    'books/chartreuse parma/page (46).png',
    'books/chartreuse parma/page (47).png',
    'books/chartreuse parma/page (48).png',
    'books/chartreuse parma/page (49).png',
    'books/chartreuse parma/page (50).png',
    'books/chartreuse parma/page (51).png',
    'books/chartreuse parma/page (52).png',
    'books/chartreuse parma/page (53).png',
    'books/chartreuse parma/page (54).png',
    'books/chartreuse parma/page (55).png',
    'books/chartreuse parma/page (56).png',
    'books/chartreuse parma/page (57).png',
    'books/chartreuse parma/page (58).png',
    'books/chartreuse parma/page (59).png',
    'books/chartreuse parma/page (60).png',
    'books/chartreuse parma/page (61).png',
    'books/chartreuse parma/page (62).png',
    'books/chartreuse parma/page (63).png',
    'books/chartreuse parma/page (64).png',
    'books/chartreuse parma/page (65).png',
    'books/chartreuse parma/page (66).png',
    'books/chartreuse parma/page (67).png',
    'books/chartreuse parma/page (68).png',
    'books/chartreuse parma/page (69).png',
    'books/chartreuse parma/page (70).png',
    'books/chartreuse parma/page (71).png',
    'books/chartreuse parma/page (72).png',
    'books/chartreuse parma/page (73).png',
    'books/chartreuse parma/page (74).png',
    'books/chartreuse parma/page (75).png',
    'books/chartreuse parma/page (76).png',
    'books/chartreuse parma/page (77).png',
    'books/chartreuse parma/page (78).png',
    'books/chartreuse parma/page (79).png',
    'books/chartreuse parma/page (80).png',
    'books/chartreuse parma/page (81).png',
    'books/chartreuse parma/page (82).png',
    'books/chartreuse parma/page (83).png',
    'books/chartreuse parma/page (84).png',
    'books/chartreuse parma/page (85).png',
    'books/chartreuse parma/page (86).png',
    'books/chartreuse parma/page (87).png',
    'books/chartreuse parma/page (88).png',
    'books/chartreuse parma/page (89).png',
    'books/chartreuse parma/page (90).png',
    'books/chartreuse parma/page (91).png',
    'books/chartreuse parma/page (92).png',
    'books/chartreuse parma/page (93).png',
    'books/chartreuse parma/page (94).png',
    'books/chartreuse parma/page (95).png',
    'books/chartreuse parma/page (96).png',
    'books/chartreuse parma/page (97).png',
    'books/chartreuse parma/page (98).png',
    'books/chartreuse parma/page (99).png',
    'books/chartreuse parma/page (100).png',
    'books/chartreuse parma/page (101).png',
    'books/chartreuse parma/page (102).png',
    'books/chartreuse parma/page (103).png',
    'books/chartreuse parma/page (104).png',
    'books/chartreuse parma/page (105).png',
    'books/chartreuse parma/page (106).png',
    'books/chartreuse parma/page (107).png',
    'books/chartreuse parma/page (108).png',
    'books/chartreuse parma/page (109).png',
    'books/chartreuse parma/page (110).png',
    'books/chartreuse parma/page (111).png',
    'books/chartreuse parma/page (112).png',
    'books/chartreuse parma/page (113).png',
    'books/chartreuse parma/page (114).png',
    'books/chartreuse parma/page (115).png',
    'books/chartreuse parma/page (116).png',
    'books/chartreuse parma/page (117).png',
    'books/chartreuse parma/page (118).png',
    'books/chartreuse parma/page (119).png',
    'books/chartreuse parma/page (120).png',
    'books/chartreuse parma/page (121).png',
    'books/chartreuse parma/page (122).png',
    'books/chartreuse parma/page (123).png',
    'books/chartreuse parma/page (124).png',
    'books/chartreuse parma/page (125).png',
    'books/chartreuse parma/page (126).png',
    'books/chartreuse parma/page (127).png',
    'books/chartreuse parma/page (128).png',
    'books/chartreuse parma/page (129).png',
    'books/chartreuse parma/page (130).png',
    'books/chartreuse parma/page (131).png',
    'books/chartreuse parma/page (132).png',
    'books/chartreuse parma/page (133).png',
    'books/chartreuse parma/page (134).png',
    'books/chartreuse parma/page (135).png',
    'books/chartreuse parma/page (136).png',
    'books/chartreuse parma/page (137).png',
    'books/chartreuse parma/page (138).png',
    'books/chartreuse parma/page (139).png',
    'books/chartreuse parma/page (140).png',
    'books/chartreuse parma/page (141).png',
    'books/chartreuse parma/page (142).png',
    'books/chartreuse parma/page (143).png',
    'books/chartreuse parma/page (144).png',
    'books/chartreuse parma/page (145).png',
    'books/chartreuse parma/page (146).png',
    'books/chartreuse parma/page (147).png',
    'books/chartreuse parma/page (148).png',
    'books/chartreuse parma/page (149).png',
    'books/chartreuse parma/page (150).png',
    'books/chartreuse parma/page (151).png',
    'books/chartreuse parma/page (152).png',
    'books/chartreuse parma/page (153).png',
    'books/chartreuse parma/page (154).png',
    'books/chartreuse parma/page (155).png',
    'books/chartreuse parma/page (156).png',
    'books/chartreuse parma/page (157).png',
    'books/chartreuse parma/page (158).png',
    'books/chartreuse parma/page (159).png',
    'books/chartreuse parma/page (160).png',
    'books/chartreuse parma/page (161).png',
    'books/chartreuse parma/page (162).png',
    'books/chartreuse parma/page (163).png',
    'books/chartreuse parma/page (164).png',
    'books/chartreuse parma/page (165).png',
    'books/chartreuse parma/page (166).png',
    'books/chartreuse parma/page (167).png',
    'books/chartreuse parma/page (168).png',
    'books/chartreuse parma/page (169).png',
    'books/chartreuse parma/page (170).png',
    'books/chartreuse parma/page (171).png',
    'books/chartreuse parma/page (172).png',
    'books/chartreuse parma/page (173).png',
    'books/chartreuse parma/page (174).png',
    'books/chartreuse parma/page (175).png',
    'books/chartreuse parma/page (176).png',
    'books/chartreuse parma/page (177).png',
    'books/chartreuse parma/page (178).png',
    'books/chartreuse parma/page (179).png',
    'books/chartreuse parma/page (180).png',
    'books/chartreuse parma/page (181).png',
    'books/chartreuse parma/page (182).png',
    'books/chartreuse parma/page (183).png',
    'books/chartreuse parma/page (184).png',
    'books/chartreuse parma/page (185).png',
    'books/chartreuse parma/page (186).png',
    'books/chartreuse parma/page (187).png',
    'books/chartreuse parma/page (188).png',
    'books/chartreuse parma/page (189).png',
    'books/chartreuse parma/page (190).png',
    'books/chartreuse parma/page (191).png',
    'books/chartreuse parma/page (192).png',
    'books/chartreuse parma/page (193).png',
    'books/chartreuse parma/page (194).png',
    'books/chartreuse parma/page (195).png',
    'books/chartreuse parma/page (196).png',
    'books/chartreuse parma/page (197).png',
    'books/chartreuse parma/page (198).png',
    'books/chartreuse parma/page (199).png',
    'books/chartreuse parma/page (200).png',
    'books/chartreuse parma/page (201).png',
    'books/chartreuse parma/page (202).png',
    'books/chartreuse parma/page (203).png',
    'books/chartreuse parma/page (204).png',
    'books/chartreuse parma/page (205).png',
    'books/chartreuse parma/page (206).png',
    'books/chartreuse parma/page (207).png',
    'books/chartreuse parma/page (208).png',
    'books/chartreuse parma/page (209).png',
    'books/chartreuse parma/page (210).png',
    'books/chartreuse parma/page (211).png',
    'books/chartreuse parma/page (212).png',
    'books/chartreuse parma/page (213).png',
    'books/chartreuse parma/page (214).png',
    'books/chartreuse parma/page (215).png',
    'books/chartreuse parma/page (216).png',
    'books/chartreuse parma/page (217).png',
    'books/chartreuse parma/page (218).png',
    'books/chartreuse parma/page (219).png',
    'books/chartreuse parma/page (220).png',
    'books/chartreuse parma/page (221).png',
    'books/chartreuse parma/page (222).png',
    'books/chartreuse parma/page (223).png',
    'books/chartreuse parma/page (224).png',
    'books/chartreuse parma/page (225).png',
    'books/chartreuse parma/page (226).png',
    'books/chartreuse parma/page (227).png',
    'books/chartreuse parma/page (228).png',
    'books/chartreuse parma/page (229).png',
    'books/chartreuse parma/page (230).png',
    'books/chartreuse parma/page (231).png',
    'books/chartreuse parma/page (232).png',
    'books/chartreuse parma/page (233).png',
    'books/chartreuse parma/page (234).png',
    'books/chartreuse parma/page (235).png',
    'books/chartreuse parma/page (236).png',
    'books/chartreuse parma/page (237).png',
    'books/chartreuse parma/page (238).png',
    'books/chartreuse parma/page (239).png',
    'books/chartreuse parma/page (240).png',
    'books/chartreuse parma/page (241).png',
    'books/chartreuse parma/page (242).png',
    'books/chartreuse parma/page (243).png',
    'books/chartreuse parma/page (244).png',
    'books/chartreuse parma/page (245).png',
    'books/chartreuse parma/page (246).png',
    'books/chartreuse parma/page (247).png',
    'books/chartreuse parma/page (248).png',
    'books/chartreuse parma/page (249).png',
    'books/chartreuse parma/page (250).png',
    'books/chartreuse parma/page (251).png',
    'books/chartreuse parma/page (252).png',
    'books/chartreuse parma/page (253).png',
    'books/chartreuse parma/page (254).png',
    'books/chartreuse parma/page (255).png',
    'books/chartreuse parma/page (256).png',
    'books/chartreuse parma/page (257).png',
    'books/chartreuse parma/page (258).png',
    'books/chartreuse parma/page (259).png',
    'books/chartreuse parma/page (260).png',
    'books/chartreuse parma/page (261).png',
    'books/chartreuse parma/page (262).png',
    'books/chartreuse parma/page (263).png',
    'books/chartreuse parma/page (264).png',
    'books/chartreuse parma/page (265).png',
    'books/chartreuse parma/page (266).png',
    'books/chartreuse parma/page (267).png',
    'books/chartreuse parma/page (268).png',
    'books/chartreuse parma/page (269).png',
    'books/chartreuse parma/page (270).png',
    'books/chartreuse parma/page (271).png',
    'books/chartreuse parma/page (272).png',
    'books/chartreuse parma/page (273).png',
    'books/chartreuse parma/page (274).png',
    'books/chartreuse parma/page (275).png',
    'books/chartreuse parma/page (276).png',
    'books/chartreuse parma/page (277).png',
    'books/chartreuse parma/page (278).png',
    'books/chartreuse parma/page (279).png',
    'books/chartreuse parma/page (280).png',
    'books/chartreuse parma/page (281).png',
    'books/chartreuse parma/page (282).png',
    'books/chartreuse parma/page (283).png',
    'books/chartreuse parma/page (284).png',
    'books/chartreuse parma/page (285).png',
    'books/chartreuse parma/page (286).png',
    'books/chartreuse parma/page (287).png',
    'books/chartreuse parma/page (288).png',
    'books/chartreuse parma/page (289).png',
    'books/chartreuse parma/page (290).png',
    'books/chartreuse parma/page (291).png',
    'books/chartreuse parma/page (292).png',
    'books/chartreuse parma/page (293).png',
    'books/chartreuse parma/page (294).png',
    'books/chartreuse parma/page (295).png',
    'books/chartreuse parma/page (296).png',
    'books/chartreuse parma/page (297).png',
    'books/chartreuse parma/page (298).png',
    'books/chartreuse parma/page (299).png',
    'books/chartreuse parma/page (300).png',
    'books/chartreuse parma/page (301).png',
    'books/chartreuse parma/page (302).png',
    'books/chartreuse parma/page (303).png',
    'books/chartreuse parma/page (304).png',
    'books/chartreuse parma/page (305).png',
    'books/chartreuse parma/page (306).png',
    'books/chartreuse parma/page (307).png',
    'books/chartreuse parma/page (308).png',
    'books/chartreuse parma/page (309).png',
    'books/chartreuse parma/page (310).png',
    'books/chartreuse parma/page (311).png',
    'books/chartreuse parma/page (312).png',
    'books/chartreuse parma/page (313).png',
    'books/chartreuse parma/page (314).png',
    'books/chartreuse parma/page (315).png',
    'books/chartreuse parma/page (316).png',
    'books/chartreuse parma/page (317).png',
    'books/chartreuse parma/page (318).png',
    'books/chartreuse parma/page (319).png',
    'books/chartreuse parma/page (320).png',
    'books/chartreuse parma/page (321).png',
    'books/chartreuse parma/page (322).png',
    'books/chartreuse parma/page (323).png',
    'books/chartreuse parma/page (324).png',
    'books/chartreuse parma/page (325).png',
    'books/chartreuse parma/page (326).png',
    'books/chartreuse parma/page (327).png',
    'books/chartreuse parma/page (328).png',
    'books/chartreuse parma/page (329).png',
    'books/chartreuse parma/page (330).png',
    'books/chartreuse parma/page (331).png',
    'books/chartreuse parma/page (332).png',
    'books/chartreuse parma/page (333).png',
    'books/chartreuse parma/page (334).png',
    'books/chartreuse parma/page (335).png',
    'books/chartreuse parma/page (336).png',
    'books/chartreuse parma/page (337).png',
    'books/chartreuse parma/page (338).png',
    'books/chartreuse parma/page (339).png',
    'books/chartreuse parma/page (340).png',
    'books/chartreuse parma/page (341).png',
    'books/chartreuse parma/page (342).png',
    'books/chartreuse parma/page (343).png',
    'books/chartreuse parma/page (344).png',
    'books/chartreuse parma/page (345).png',
    'books/chartreuse parma/page (346).png',
    'books/chartreuse parma/page (347).png',
    'books/chartreuse parma/page (348).png',
    'books/chartreuse parma/page (349).png',
    'books/chartreuse parma/page (350).png',
    'books/chartreuse parma/page (351).png',
    'books/chartreuse parma/page (352).png',
    'books/chartreuse parma/page (353).png',
    'books/chartreuse parma/page (354).png',
    'books/chartreuse parma/page (355).png',
    'books/chartreuse parma/page (356).png',
    'books/chartreuse parma/page (357).png',
    'books/chartreuse parma/page (358).png',
    'books/chartreuse parma/page (359).png',
    'books/chartreuse parma/page (360).png',
    'books/chartreuse parma/page (361).png',
    'books/chartreuse parma/page (362).png',
    'books/chartreuse parma/page (363).png',
    'books/chartreuse parma/page (364).png',
    'books/chartreuse parma/page (365).png',
    'books/chartreuse parma/page (366).png',
    'books/chartreuse parma/page (367).png',
    'books/chartreuse parma/page (368).png',
    'books/chartreuse parma/page (369).png',
    'books/chartreuse parma/page (370).png',
    'books/chartreuse parma/page (371).png',
    'books/chartreuse parma/page (372).png',
    'books/chartreuse parma/page (373).png',
    'books/chartreuse parma/page (374).png',
    'books/chartreuse parma/page (375).png',
    'books/chartreuse parma/page (376).png',
    'books/chartreuse parma/page (377).png',
    'books/chartreuse parma/page (378).png',
    'books/chartreuse parma/page (379).png',
    'books/chartreuse parma/page (380).png',
    'books/chartreuse parma/page (381).png',
    'books/chartreuse parma/page (382).png',
    'books/chartreuse parma/page (383).png',
    'books/chartreuse parma/page (384).png',
    'books/chartreuse parma/page (385).png',
    'books/chartreuse parma/page (386).png',
    'books/chartreuse parma/page (387).png',
    'books/chartreuse parma/page (388).png',
    'books/chartreuse parma/page (389).png',
    'books/chartreuse parma/page (390).png',
    'books/chartreuse parma/page (391).png',
    'books/chartreuse parma/page (392).png',
    'books/chartreuse parma/page (393).png',
    'books/chartreuse parma/page (394).png',
    'books/chartreuse parma/page (395).png',
    'books/chartreuse parma/page (396).png',
    'books/chartreuse parma/page (397).png',
    'books/chartreuse parma/page (398).png',
    'books/chartreuse parma/page (399).png',
    'books/chartreuse parma/page (400).png',
    'books/chartreuse parma/page (401).png',
    'books/chartreuse parma/page (402).png',
    'books/chartreuse parma/page (403).png',
    'books/chartreuse parma/page (404).png',
    'books/chartreuse parma/page (405).png',
    'books/chartreuse parma/page (406).png',
    'books/chartreuse parma/page (407).png',
    'books/chartreuse parma/page (408).png',
    'books/chartreuse parma/page (409).png',
    'books/chartreuse parma/page (410).png',
    'books/chartreuse parma/page (411).png',
    'books/chartreuse parma/page (412).png',
    'books/chartreuse parma/page (413).png',
    'books/chartreuse parma/page (414).png',
    'books/chartreuse parma/page (415).png',
    'books/chartreuse parma/page (416).png',
    'books/chartreuse parma/page (417).png',
    'books/chartreuse parma/page (418).png',
    'books/chartreuse parma/page (419).png',
    'books/chartreuse parma/page (420).png',
    'books/chartreuse parma/page (421).png',
    'books/chartreuse parma/page (422).png',
    'books/chartreuse parma/page (423).png',
    'books/chartreuse parma/page (424).png',
    'books/chartreuse parma/page (425).png',
    'books/chartreuse parma/page (426).png',
    'books/chartreuse parma/page (427).png',
    'books/chartreuse parma/page (428).png',
    'books/chartreuse parma/page (429).png',
    'books/chartreuse parma/page (430).png',
    'books/chartreuse parma/page (431).png',
    'books/chartreuse parma/page (432).png',
    'books/chartreuse parma/page (433).png',
    'books/chartreuse parma/page (434).png',
    'books/chartreuse parma/page (435).png',
    'books/chartreuse parma/page (436).png',
    'books/chartreuse parma/page (437).png',
    'books/chartreuse parma/page (438).png',
    'books/chartreuse parma/page (439).png',
    'books/chartreuse parma/page (440).png',
    'books/chartreuse parma/page (441).png',
    'books/chartreuse parma/page (442).png',
    'books/chartreuse parma/page (443).png',
    'books/chartreuse parma/page (444).png',
    'books/chartreuse parma/page (445).png',
    'books/chartreuse parma/page (446).png',
    'books/chartreuse parma/page (447).png',
    'books/chartreuse parma/page (448).png',
    'books/chartreuse parma/page (449).png',
    'books/chartreuse parma/page (450).png',
    'books/chartreuse parma/page (451).png',
    'books/chartreuse parma/page (452).png',
    'books/chartreuse parma/page (453).png',
    'books/chartreuse parma/page (454).png',
    'books/chartreuse parma/page (455).png',
    'books/chartreuse parma/page (456).png',
    'books/chartreuse parma/page (457).png',
    'books/chartreuse parma/page (458).png',
    'books/chartreuse parma/page (459).png',
    'books/chartreuse parma/page (460).png',
    'books/chartreuse parma/page (461).png',
    'books/chartreuse parma/page (462).png',
    'books/chartreuse parma/page (463).png',
    'books/chartreuse parma/page (464).png',
    'books/chartreuse parma/page (465).png',
    'books/chartreuse parma/page (466).png',
    'books/chartreuse parma/page (467).png',
    'books/chartreuse parma/page (468).png',
    'books/chartreuse parma/page (469).png',
    'books/chartreuse parma/page (470).png',
    'books/chartreuse parma/page (471).png',
    'books/chartreuse parma/page (472).png',
    'books/chartreuse parma/page (473).png',
    'books/chartreuse parma/page (474).png',
    'books/chartreuse parma/page (475).png',
    'books/chartreuse parma/page (476).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
