import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class danielderonda extends StatefulWidget {
  const danielderonda({Key? key}) : super(key: key);

  @override
  State<danielderonda> createState() => _danielderondaState();
}

class _danielderondaState extends State<danielderonda> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/Daniel Deronda/page (1).png',
    'books/Daniel Deronda/page (2).png',
    'books/Daniel Deronda/page (3).png',
    'books/Daniel Deronda/page (4).png',
    'books/Daniel Deronda/page (5).png',
    'books/Daniel Deronda/page (6).png',
    'books/Daniel Deronda/page (7).png',
    'books/Daniel Deronda/page (8).png',
    'books/Daniel Deronda/page (9).png',
    'books/Daniel Deronda/page (10).png',
    'books/Daniel Deronda/page (11).png',
    'books/Daniel Deronda/page (12).png',
    'books/Daniel Deronda/page (13).png',
    'books/Daniel Deronda/page (14).png',
    'books/Daniel Deronda/page (15).png',
    'books/Daniel Deronda/page (16).png',
    'books/Daniel Deronda/page (17).png',
    'books/Daniel Deronda/page (18).png',
    'books/Daniel Deronda/page (19).png',
    'books/Daniel Deronda/page (20).png',
    'books/Daniel Deronda/page (21).png',
    'books/Daniel Deronda/page (22).png',
    'books/Daniel Deronda/page (23).png',
    'books/Daniel Deronda/page (24).png',
    'books/Daniel Deronda/page (25).png',
    'books/Daniel Deronda/page (26).png',
    'books/Daniel Deronda/page (27).png',
    'books/Daniel Deronda/page (28).png',
    'books/Daniel Deronda/page (29).png',
    'books/Daniel Deronda/page (30).png',
    'books/Daniel Deronda/page (31).png',
    'books/Daniel Deronda/page (32).png',
    'books/Daniel Deronda/page (33).png',
    'books/Daniel Deronda/page (34).png',
    'books/Daniel Deronda/page (35).png',
    'books/Daniel Deronda/page (36).png',
    'books/Daniel Deronda/page (37).png',
    'books/Daniel Deronda/page (38).png',
    'books/Daniel Deronda/page (39).png',
    'books/Daniel Deronda/page (40).png',
    'books/Daniel Deronda/page (41).png',
    'books/Daniel Deronda/page (42).png',
    'books/Daniel Deronda/page (43).png',
    'books/Daniel Deronda/page (44).png',
    'books/Daniel Deronda/page (45).png',
    'books/Daniel Deronda/page (46).png',
    'books/Daniel Deronda/page (47).png',
    'books/Daniel Deronda/page (48).png',
    'books/Daniel Deronda/page (49).png',
    'books/Daniel Deronda/page (50).png',
    'books/Daniel Deronda/page (51).png',
    'books/Daniel Deronda/page (52).png',
    'books/Daniel Deronda/page (53).png',
    'books/Daniel Deronda/page (54).png',
    'books/Daniel Deronda/page (55).png',
    'books/Daniel Deronda/page (56).png',
    'books/Daniel Deronda/page (57).png',
    'books/Daniel Deronda/page (58).png',
    'books/Daniel Deronda/page (59).png',
    'books/Daniel Deronda/page (60).png',
    'books/Daniel Deronda/page (61).png',
    'books/Daniel Deronda/page (62).png',
    'books/Daniel Deronda/page (63).png',
    'books/Daniel Deronda/page (64).png',
    'books/Daniel Deronda/page (65).png',
    'books/Daniel Deronda/page (66).png',
    'books/Daniel Deronda/page (67).png',
    'books/Daniel Deronda/page (68).png',
    'books/Daniel Deronda/page (69).png',
    'books/Daniel Deronda/page (70).png',
    'books/Daniel Deronda/page (71).png',
    'books/Daniel Deronda/page (72).png',
    'books/Daniel Deronda/page (73).png',
    'books/Daniel Deronda/page (74).png',
    'books/Daniel Deronda/page (75).png',
    'books/Daniel Deronda/page (76).png',
    'books/Daniel Deronda/page (77).png',
    'books/Daniel Deronda/page (78).png',
    'books/Daniel Deronda/page (79).png',
    'books/Daniel Deronda/page (80).png',
    'books/Daniel Deronda/page (81).png',
    'books/Daniel Deronda/page (82).png',
    'books/Daniel Deronda/page (83).png',
    'books/Daniel Deronda/page (84).png',
    'books/Daniel Deronda/page (85).png',
    'books/Daniel Deronda/page (86).png',
    'books/Daniel Deronda/page (87).png',
    'books/Daniel Deronda/page (88).png',
    'books/Daniel Deronda/page (89).png',
    'books/Daniel Deronda/page (90).png',
    'books/Daniel Deronda/page (91).png',
    'books/Daniel Deronda/page (92).png',
    'books/Daniel Deronda/page (93).png',
    'books/Daniel Deronda/page (94).png',
    'books/Daniel Deronda/page (95).png',
    'books/Daniel Deronda/page (96).png',
    'books/Daniel Deronda/page (97).png',
    'books/Daniel Deronda/page (98).png',
    'books/Daniel Deronda/page (99).png',
    'books/Daniel Deronda/page (100).png',
    'books/Daniel Deronda/page (101).png',
    'books/Daniel Deronda/page (102).png',
    'books/Daniel Deronda/page (103).png',
    'books/Daniel Deronda/page (104).png',
    'books/Daniel Deronda/page (105).png',
    'books/Daniel Deronda/page (106).png',
    'books/Daniel Deronda/page (107).png',
    'books/Daniel Deronda/page (108).png',
    'books/Daniel Deronda/page (109).png',
    'books/Daniel Deronda/page (110).png',
    'books/Daniel Deronda/page (111).png',
    'books/Daniel Deronda/page (112).png',
    'books/Daniel Deronda/page (113).png',
    'books/Daniel Deronda/page (114).png',
    'books/Daniel Deronda/page (115).png',
    'books/Daniel Deronda/page (116).png',
    'books/Daniel Deronda/page (117).png',
    'books/Daniel Deronda/page (118).png',
    'books/Daniel Deronda/page (119).png',
    'books/Daniel Deronda/page (120).png',
    'books/Daniel Deronda/page (121).png',
    'books/Daniel Deronda/page (122).png',
    'books/Daniel Deronda/page (123).png',
    'books/Daniel Deronda/page (124).png',
    'books/Daniel Deronda/page (125).png',
    'books/Daniel Deronda/page (126).png',
    'books/Daniel Deronda/page (127).png',
    'books/Daniel Deronda/page (128).png',
    'books/Daniel Deronda/page (129).png',
    'books/Daniel Deronda/page (130).png',
    'books/Daniel Deronda/page (131).png',
    'books/Daniel Deronda/page (132).png',
    'books/Daniel Deronda/page (133).png',
    'books/Daniel Deronda/page (134).png',
    'books/Daniel Deronda/page (135).png',
    'books/Daniel Deronda/page (136).png',
    'books/Daniel Deronda/page (137).png',
    'books/Daniel Deronda/page (138).png',
    'books/Daniel Deronda/page (139).png',
    'books/Daniel Deronda/page (140).png',
    'books/Daniel Deronda/page (141).png',
    'books/Daniel Deronda/page (142).png',
    'books/Daniel Deronda/page (143).png',
    'books/Daniel Deronda/page (144).png',
    'books/Daniel Deronda/page (145).png',
    'books/Daniel Deronda/page (146).png',
    'books/Daniel Deronda/page (147).png',
    'books/Daniel Deronda/page (148).png',
    'books/Daniel Deronda/page (149).png',
    'books/Daniel Deronda/page (150).png',
    'books/Daniel Deronda/page (151).png',
    'books/Daniel Deronda/page (152).png',
    'books/Daniel Deronda/page (153).png',
    'books/Daniel Deronda/page (154).png',
    'books/Daniel Deronda/page (155).png',
    'books/Daniel Deronda/page (156).png',
    'books/Daniel Deronda/page (157).png',
    'books/Daniel Deronda/page (158).png',
    'books/Daniel Deronda/page (159).png',
    'books/Daniel Deronda/page (160).png',
    'books/Daniel Deronda/page (161).png',
    'books/Daniel Deronda/page (162).png',
    'books/Daniel Deronda/page (163).png',
    'books/Daniel Deronda/page (164).png',
    'books/Daniel Deronda/page (165).png',
    'books/Daniel Deronda/page (166).png',
    'books/Daniel Deronda/page (167).png',
    'books/Daniel Deronda/page (168).png',
    'books/Daniel Deronda/page (169).png',
    'books/Daniel Deronda/page (170).png',
    'books/Daniel Deronda/page (171).png',
    'books/Daniel Deronda/page (172).png',
    'books/Daniel Deronda/page (173).png',
    'books/Daniel Deronda/page (174).png',
    'books/Daniel Deronda/page (175).png',
    'books/Daniel Deronda/page (176).png',
    'books/Daniel Deronda/page (177).png',
    'books/Daniel Deronda/page (178).png',
    'books/Daniel Deronda/page (179).png',
    'books/Daniel Deronda/page (180).png',
    'books/Daniel Deronda/page (181).png',
    'books/Daniel Deronda/page (182).png',
    'books/Daniel Deronda/page (183).png',
    'books/Daniel Deronda/page (184).png',
    'books/Daniel Deronda/page (185).png',
    'books/Daniel Deronda/page (186).png',
    'books/Daniel Deronda/page (187).png',
    'books/Daniel Deronda/page (188).png',
    'books/Daniel Deronda/page (189).png',
    'books/Daniel Deronda/page (190).png',
    'books/Daniel Deronda/page (191).png',
    'books/Daniel Deronda/page (192).png',
    'books/Daniel Deronda/page (193).png',
    'books/Daniel Deronda/page (194).png',
    'books/Daniel Deronda/page (195).png',
    'books/Daniel Deronda/page (196).png',
    'books/Daniel Deronda/page (197).png',
    'books/Daniel Deronda/page (198).png',
    'books/Daniel Deronda/page (199).png',
    'books/Daniel Deronda/page (200).png',
    'books/Daniel Deronda/page (201).png',
    'books/Daniel Deronda/page (202).png',
    'books/Daniel Deronda/page (203).png',
    'books/Daniel Deronda/page (204).png',
    'books/Daniel Deronda/page (205).png',
    'books/Daniel Deronda/page (206).png',
    'books/Daniel Deronda/page (207).png',
    'books/Daniel Deronda/page (208).png',
    'books/Daniel Deronda/page (209).png',
    'books/Daniel Deronda/page (210).png',
    'books/Daniel Deronda/page (211).png',
    'books/Daniel Deronda/page (212).png',
    'books/Daniel Deronda/page (213).png',
    'books/Daniel Deronda/page (214).png',
    'books/Daniel Deronda/page (215).png',
    'books/Daniel Deronda/page (216).png',
    'books/Daniel Deronda/page (217).png',
    'books/Daniel Deronda/page (218).png',
    'books/Daniel Deronda/page (219).png',
    'books/Daniel Deronda/page (220).png',
    'books/Daniel Deronda/page (221).png',
    'books/Daniel Deronda/page (222).png',
    'books/Daniel Deronda/page (223).png',
    'books/Daniel Deronda/page (224).png',
    'books/Daniel Deronda/page (225).png',
    'books/Daniel Deronda/page (226).png',
    'books/Daniel Deronda/page (227).png',
    'books/Daniel Deronda/page (228).png',
    'books/Daniel Deronda/page (229).png',
    'books/Daniel Deronda/page (230).png',
    'books/Daniel Deronda/page (231).png',
    'books/Daniel Deronda/page (232).png',
    'books/Daniel Deronda/page (233).png',
    'books/Daniel Deronda/page (234).png',
    'books/Daniel Deronda/page (235).png',
    'books/Daniel Deronda/page (236).png',
    'books/Daniel Deronda/page (237).png',
    'books/Daniel Deronda/page (238).png',
    'books/Daniel Deronda/page (239).png',
    'books/Daniel Deronda/page (240).png',
    'books/Daniel Deronda/page (241).png',
    'books/Daniel Deronda/page (242).png',
    'books/Daniel Deronda/page (243).png',
    'books/Daniel Deronda/page (244).png',
    'books/Daniel Deronda/page (245).png',
    'books/Daniel Deronda/page (246).png',
    'books/Daniel Deronda/page (247).png',
    'books/Daniel Deronda/page (248).png',
    'books/Daniel Deronda/page (249).png',
    'books/Daniel Deronda/page (250).png',
    'books/Daniel Deronda/page (251).png',
    'books/Daniel Deronda/page (252).png',
    'books/Daniel Deronda/page (253).png',
    'books/Daniel Deronda/page (254).png',
    'books/Daniel Deronda/page (255).png',
    'books/Daniel Deronda/page (256).png',
    'books/Daniel Deronda/page (257).png',
    'books/Daniel Deronda/page (258).png',
    'books/Daniel Deronda/page (259).png',
    'books/Daniel Deronda/page (260).png',
    'books/Daniel Deronda/page (261).png',
    'books/Daniel Deronda/page (262).png',
    'books/Daniel Deronda/page (263).png',
    'books/Daniel Deronda/page (264).png',
    'books/Daniel Deronda/page (265).png',
    'books/Daniel Deronda/page (266).png',
    'books/Daniel Deronda/page (267).png',
    'books/Daniel Deronda/page (268).png',
    'books/Daniel Deronda/page (269).png',
    'books/Daniel Deronda/page (270).png',
    'books/Daniel Deronda/page (271).png',
    'books/Daniel Deronda/page (272).png',
    'books/Daniel Deronda/page (273).png',
    'books/Daniel Deronda/page (274).png',
    'books/Daniel Deronda/page (275).png',
    'books/Daniel Deronda/page (276).png',
    'books/Daniel Deronda/page (277).png',
    'books/Daniel Deronda/page (278).png',
    'books/Daniel Deronda/page (279).png',
    'books/Daniel Deronda/page (280).png',
    'books/Daniel Deronda/page (281).png',
    'books/Daniel Deronda/page (282).png',
    'books/Daniel Deronda/page (283).png',
    'books/Daniel Deronda/page (284).png',
    'books/Daniel Deronda/page (285).png',
    'books/Daniel Deronda/page (286).png',
    'books/Daniel Deronda/page (287).png',
    'books/Daniel Deronda/page (288).png',
    'books/Daniel Deronda/page (289).png',
    'books/Daniel Deronda/page (290).png',
    'books/Daniel Deronda/page (291).png',
    'books/Daniel Deronda/page (292).png',
    'books/Daniel Deronda/page (293).png',
    'books/Daniel Deronda/page (294).png',
    'books/Daniel Deronda/page (295).png',
    'books/Daniel Deronda/page (296).png',
    'books/Daniel Deronda/page (297).png',
    'books/Daniel Deronda/page (298).png',
    'books/Daniel Deronda/page (299).png',
    'books/Daniel Deronda/page (300).png',
    'books/Daniel Deronda/page (301).png',
    'books/Daniel Deronda/page (302).png',
    'books/Daniel Deronda/page (303).png',
    'books/Daniel Deronda/page (304).png',
    'books/Daniel Deronda/page (305).png',
    'books/Daniel Deronda/page (306).png',
    'books/Daniel Deronda/page (307).png',
    'books/Daniel Deronda/page (308).png',
    'books/Daniel Deronda/page (309).png',
    'books/Daniel Deronda/page (310).png',
    'books/Daniel Deronda/page (311).png',
    'books/Daniel Deronda/page (312).png',
    'books/Daniel Deronda/page (313).png',
    'books/Daniel Deronda/page (314).png',
    'books/Daniel Deronda/page (315).png',
    'books/Daniel Deronda/page (316).png',
    'books/Daniel Deronda/page (317).png',
    'books/Daniel Deronda/page (318).png',
    'books/Daniel Deronda/page (319).png',
    'books/Daniel Deronda/page (320).png',
    'books/Daniel Deronda/page (321).png',
    'books/Daniel Deronda/page (322).png',
    'books/Daniel Deronda/page (323).png',
    'books/Daniel Deronda/page (324).png',
    'books/Daniel Deronda/page (325).png',
    'books/Daniel Deronda/page (326).png',
    'books/Daniel Deronda/page (327).png',
    'books/Daniel Deronda/page (328).png',
    'books/Daniel Deronda/page (329).png',
    'books/Daniel Deronda/page (330).png',
    'books/Daniel Deronda/page (331).png',
    'books/Daniel Deronda/page (332).png',
    'books/Daniel Deronda/page (333).png',
    'books/Daniel Deronda/page (334).png',
    'books/Daniel Deronda/page (335).png',
    'books/Daniel Deronda/page (336).png',
    'books/Daniel Deronda/page (337).png',
    'books/Daniel Deronda/page (338).png',
    'books/Daniel Deronda/page (339).png',
    'books/Daniel Deronda/page (340).png',
    'books/Daniel Deronda/page (341).png',
    'books/Daniel Deronda/page (342).png',
    'books/Daniel Deronda/page (343).png',
    'books/Daniel Deronda/page (344).png',
    'books/Daniel Deronda/page (345).png',
    'books/Daniel Deronda/page (346).png',
    'books/Daniel Deronda/page (347).png',
    'books/Daniel Deronda/page (348).png',
    'books/Daniel Deronda/page (349).png',
    'books/Daniel Deronda/page (350).png',
    'books/Daniel Deronda/page (351).png',
    'books/Daniel Deronda/page (352).png',
    'books/Daniel Deronda/page (353).png',
    'books/Daniel Deronda/page (354).png',
    'books/Daniel Deronda/page (355).png',
    'books/Daniel Deronda/page (356).png',
    'books/Daniel Deronda/page (357).png',
    'books/Daniel Deronda/page (358).png',
    'books/Daniel Deronda/page (359).png',
    'books/Daniel Deronda/page (360).png',
    'books/Daniel Deronda/page (361).png',
    'books/Daniel Deronda/page (362).png',
    'books/Daniel Deronda/page (363).png',
    'books/Daniel Deronda/page (364).png',
    'books/Daniel Deronda/page (365).png',
    'books/Daniel Deronda/page (366).png',
    'books/Daniel Deronda/page (367).png',
    'books/Daniel Deronda/page (368).png',
    'books/Daniel Deronda/page (369).png',
    'books/Daniel Deronda/page (370).png',
    'books/Daniel Deronda/page (371).png',
    'books/Daniel Deronda/page (372).png',
    'books/Daniel Deronda/page (373).png',
    'books/Daniel Deronda/page (374).png',
    'books/Daniel Deronda/page (375).png',
    'books/Daniel Deronda/page (376).png',
    'books/Daniel Deronda/page (377).png',
    'books/Daniel Deronda/page (378).png',
    'books/Daniel Deronda/page (379).png',
    'books/Daniel Deronda/page (380).png',
    'books/Daniel Deronda/page (381).png',
    'books/Daniel Deronda/page (382).png',
    'books/Daniel Deronda/page (383).png',
    'books/Daniel Deronda/page (384).png',
    'books/Daniel Deronda/page (385).png',
    'books/Daniel Deronda/page (386).png',
    'books/Daniel Deronda/page (387).png',
    'books/Daniel Deronda/page (388).png',
    'books/Daniel Deronda/page (389).png',
    'books/Daniel Deronda/page (390).png',
    'books/Daniel Deronda/page (391).png',
    'books/Daniel Deronda/page (392).png',
    'books/Daniel Deronda/page (393).png',
    'books/Daniel Deronda/page (394).png',
    'books/Daniel Deronda/page (395).png',
    'books/Daniel Deronda/page (396).png',
    'books/Daniel Deronda/page (397).png',
    'books/Daniel Deronda/page (398).png',
    'books/Daniel Deronda/page (399).png',
    'books/Daniel Deronda/page (400).png',
    'books/Daniel Deronda/page (401).png',
    'books/Daniel Deronda/page (402).png',
    'books/Daniel Deronda/page (403).png',
    'books/Daniel Deronda/page (404).png',
    'books/Daniel Deronda/page (405).png',
    'books/Daniel Deronda/page (406).png',
    'books/Daniel Deronda/page (407).png',
    'books/Daniel Deronda/page (408).png',
    'books/Daniel Deronda/page (409).png',
    'books/Daniel Deronda/page (410).png',
    'books/Daniel Deronda/page (411).png',
    'books/Daniel Deronda/page (412).png',
    'books/Daniel Deronda/page (413).png',
    'books/Daniel Deronda/page (414).png',
    'books/Daniel Deronda/page (415).png',
    'books/Daniel Deronda/page (416).png',
    'books/Daniel Deronda/page (417).png',
    'books/Daniel Deronda/page (418).png',
    'books/Daniel Deronda/page (419).png',
    'books/Daniel Deronda/page (420).png',
    'books/Daniel Deronda/page (421).png',
    'books/Daniel Deronda/page (422).png',
    'books/Daniel Deronda/page (423).png',
    'books/Daniel Deronda/page (424).png',
    'books/Daniel Deronda/page (425).png',
    'books/Daniel Deronda/page (426).png',
    'books/Daniel Deronda/page (427).png',
    'books/Daniel Deronda/page (428).png',
    'books/Daniel Deronda/page (429).png',
    'books/Daniel Deronda/page (430).png',
    'books/Daniel Deronda/page (431).png',
    'books/Daniel Deronda/page (432).png',
    'books/Daniel Deronda/page (433).png',
    'books/Daniel Deronda/page (434).png',
    'books/Daniel Deronda/page (435).png',
    'books/Daniel Deronda/page (436).png',
    'books/Daniel Deronda/page (437).png',
    'books/Daniel Deronda/page (438).png',
    'books/Daniel Deronda/page (439).png',
    'books/Daniel Deronda/page (440).png',
    'books/Daniel Deronda/page (441).png',
    'books/Daniel Deronda/page (442).png',
    'books/Daniel Deronda/page (443).png',
    'books/Daniel Deronda/page (444).png',
    'books/Daniel Deronda/page (445).png',
    'books/Daniel Deronda/page (446).png',
    'books/Daniel Deronda/page (447).png',
    'books/Daniel Deronda/page (448).png',
    'books/Daniel Deronda/page (449).png',
    'books/Daniel Deronda/page (450).png',
    'books/Daniel Deronda/page (451).png',
    'books/Daniel Deronda/page (452).png',
    'books/Daniel Deronda/page (453).png',
    'books/Daniel Deronda/page (454).png',
    'books/Daniel Deronda/page (455).png',
    'books/Daniel Deronda/page (456).png',
    'books/Daniel Deronda/page (457).png',
    'books/Daniel Deronda/page (458).png',
    'books/Daniel Deronda/page (459).png',
    'books/Daniel Deronda/page (460).png',
    'books/Daniel Deronda/page (461).png',
    'books/Daniel Deronda/page (462).png',
    'books/Daniel Deronda/page (463).png',
    'books/Daniel Deronda/page (464).png',
    'books/Daniel Deronda/page (465).png',
    'books/Daniel Deronda/page (466).png',
    'books/Daniel Deronda/page (467).png',
    'books/Daniel Deronda/page (468).png',
    'books/Daniel Deronda/page (469).png',
    'books/Daniel Deronda/page (470).png',
    'books/Daniel Deronda/page (471).png',
    'books/Daniel Deronda/page (472).png',
    'books/Daniel Deronda/page (473).png',
    'books/Daniel Deronda/page (474).png',
    'books/Daniel Deronda/page (475).png',
    'books/Daniel Deronda/page (476).png',
    'books/Daniel Deronda/page (477).png',
    'books/Daniel Deronda/page (478).png',
    'books/Daniel Deronda/page (479).png',
    'books/Daniel Deronda/page (480).png',
    'books/Daniel Deronda/page (481).png',
    'books/Daniel Deronda/page (482).png',
    'books/Daniel Deronda/page (483).png',
    'books/Daniel Deronda/page (484).png',
    'books/Daniel Deronda/page (485).png',
    'books/Daniel Deronda/page (486).png',
    'books/Daniel Deronda/page (487).png',
    'books/Daniel Deronda/page (488).png',
    'books/Daniel Deronda/page (489).png',
    'books/Daniel Deronda/page (490).png',
    'books/Daniel Deronda/page (491).png',
    'books/Daniel Deronda/page (492).png',
    'books/Daniel Deronda/page (493).png',
    'books/Daniel Deronda/page (494).png',
    'books/Daniel Deronda/page (495).png',
    'books/Daniel Deronda/page (496).png',
    'books/Daniel Deronda/page (497).png',
    'books/Daniel Deronda/page (498).png',
    'books/Daniel Deronda/page (499).png',
    'books/Daniel Deronda/page (500).png',
    'books/Daniel Deronda/page (501).png',
    'books/Daniel Deronda/page (502).png',
    'books/Daniel Deronda/page (503).png',
    'books/Daniel Deronda/page (504).png',
    'books/Daniel Deronda/page (505).png',
    'books/Daniel Deronda/page (506).png',
    'books/Daniel Deronda/page (507).png',
    'books/Daniel Deronda/page (508).png',
    'books/Daniel Deronda/page (509).png',
    'books/Daniel Deronda/page (510).png',
    'books/Daniel Deronda/page (511).png',
    'books/Daniel Deronda/page (512).png',
    'books/Daniel Deronda/page (513).png',
    'books/Daniel Deronda/page (514).png',
    'books/Daniel Deronda/page (515).png',
    'books/Daniel Deronda/page (516).png',
    'books/Daniel Deronda/page (517).png',
    'books/Daniel Deronda/page (518).png',
    'books/Daniel Deronda/page (519).png',
    'books/Daniel Deronda/page (520).png',
    'books/Daniel Deronda/page (521).png',
    'books/Daniel Deronda/page (522).png',
    'books/Daniel Deronda/page (523).png',
    'books/Daniel Deronda/page (524).png',
    'books/Daniel Deronda/page (525).png',
    'books/Daniel Deronda/page (526).png',
    'books/Daniel Deronda/page (527).png',
    'books/Daniel Deronda/page (528).png',
    'books/Daniel Deronda/page (529).png',
    'books/Daniel Deronda/page (530).png',
    'books/Daniel Deronda/page (531).png',
    'books/Daniel Deronda/page (532).png',
    'books/Daniel Deronda/page (533).png',
    'books/Daniel Deronda/page (534).png',
    'books/Daniel Deronda/page (535).png',
    'books/Daniel Deronda/page (536).png',
    'books/Daniel Deronda/page (537).png',
    'books/Daniel Deronda/page (538).png',
    'books/Daniel Deronda/page (539).png',
    'books/Daniel Deronda/page (540).png',
    'books/Daniel Deronda/page (541).png',
    'books/Daniel Deronda/page (542).png',
    'books/Daniel Deronda/page (543).png',
    'books/Daniel Deronda/page (544).png',
    'books/Daniel Deronda/page (545).png',
    'books/Daniel Deronda/page (546).png',
    'books/Daniel Deronda/page (547).png',
    'books/Daniel Deronda/page (548).png',
    'books/Daniel Deronda/page (549).png',
    'books/Daniel Deronda/page (550).png',
    'books/Daniel Deronda/page (551).png',
    'books/Daniel Deronda/page (552).png',
    'books/Daniel Deronda/page (553).png',
    'books/Daniel Deronda/page (554).png',
    'books/Daniel Deronda/page (555).png',
    'books/Daniel Deronda/page (556).png',
    'books/Daniel Deronda/page (557).png',
    'books/Daniel Deronda/page (558).png',
    'books/Daniel Deronda/page (559).png',
    'books/Daniel Deronda/page (560).png',
    'books/Daniel Deronda/page (561).png',
    'books/Daniel Deronda/page (562).png',
    'books/Daniel Deronda/page (563).png',
    'books/Daniel Deronda/page (564).png',
    'books/Daniel Deronda/page (565).png',
    'books/Daniel Deronda/page (566).png',
    'books/Daniel Deronda/page (567).png',
    'books/Daniel Deronda/page (568).png',
    'books/Daniel Deronda/page (569).png',
    'books/Daniel Deronda/page (570).png',
    'books/Daniel Deronda/page (571).png',
    'books/Daniel Deronda/page (572).png',
    'books/Daniel Deronda/page (573).png',
    'books/Daniel Deronda/page (574).png',
    'books/Daniel Deronda/page (575).png',
    'books/Daniel Deronda/page (576).png',
    'books/Daniel Deronda/page (577).png',
    'books/Daniel Deronda/page (578).png',
    'books/Daniel Deronda/page (579).png',
    'books/Daniel Deronda/page (580).png',
    'books/Daniel Deronda/page (581).png',
    'books/Daniel Deronda/page (582).png',
    'books/Daniel Deronda/page (583).png',
    'books/Daniel Deronda/page (584).png',
    'books/Daniel Deronda/page (585).png',
    'books/Daniel Deronda/page (586).png',
    'books/Daniel Deronda/page (587).png',
    'books/Daniel Deronda/page (588).png',
    'books/Daniel Deronda/page (589).png',
    'books/Daniel Deronda/page (590).png',
    'books/Daniel Deronda/page (591).png',
    'books/Daniel Deronda/page (592).png',
    'books/Daniel Deronda/page (593).png',
    'books/Daniel Deronda/page (594).png',
    'books/Daniel Deronda/page (595).png',
    'books/Daniel Deronda/page (596).png',
    'books/Daniel Deronda/page (597).png',
    'books/Daniel Deronda/page (598).png',
    'books/Daniel Deronda/page (599).png',
    'books/Daniel Deronda/page (600).png',
    'books/Daniel Deronda/page (601).png',
    'books/Daniel Deronda/page (602).png',
    'books/Daniel Deronda/page (603).png',
    'books/Daniel Deronda/page (604).png',
    'books/Daniel Deronda/page (605).png',
    'books/Daniel Deronda/page (606).png',
    'books/Daniel Deronda/page (607).png',
    'books/Daniel Deronda/page (608).png',
    'books/Daniel Deronda/page (609).png',
    'books/Daniel Deronda/page (610).png',
    'books/Daniel Deronda/page (611).png',
    'books/Daniel Deronda/page (612).png',
    'books/Daniel Deronda/page (613).png',
    'books/Daniel Deronda/page (614).png',
    'books/Daniel Deronda/page (615).png',
    'books/Daniel Deronda/page (616).png',
    'books/Daniel Deronda/page (617).png',
    'books/Daniel Deronda/page (618).png',
    'books/Daniel Deronda/page (619).png',
    'books/Daniel Deronda/page (620).png',
    'books/Daniel Deronda/page (621).png',
    'books/Daniel Deronda/page (622).png',
    'books/Daniel Deronda/page (623).png',
    'books/Daniel Deronda/page (624).png',
    'books/Daniel Deronda/page (625).png',
    'books/Daniel Deronda/page (626).png',
    'books/Daniel Deronda/page (627).png',
    'books/Daniel Deronda/page (628).png',
    'books/Daniel Deronda/page (629).png',
    'books/Daniel Deronda/page (630).png',
    'books/Daniel Deronda/page (631).png',
    'books/Daniel Deronda/page (632).png',
    'books/Daniel Deronda/page (633).png',
    'books/Daniel Deronda/page (634).png',
    'books/Daniel Deronda/page (635).png',
    'books/Daniel Deronda/page (636).png',
    'books/Daniel Deronda/page (637).png',
    'books/Daniel Deronda/page (638).png',
    'books/Daniel Deronda/page (639).png',
    'books/Daniel Deronda/page (640).png',
    'books/Daniel Deronda/page (641).png',
    'books/Daniel Deronda/page (642).png',
    'books/Daniel Deronda/page (643).png',
    'books/Daniel Deronda/page (644).png',
    'books/Daniel Deronda/page (645).png',
    'books/Daniel Deronda/page (646).png',
    'books/Daniel Deronda/page (647).png',
    'books/Daniel Deronda/page (648).png',
    'books/Daniel Deronda/page (649).png',
    'books/Daniel Deronda/page (650).png',
    'books/Daniel Deronda/page (651).png',
    'books/Daniel Deronda/page (652).png',
    'books/Daniel Deronda/page (653).png',
    'books/Daniel Deronda/page (654).png',
    'books/Daniel Deronda/page (655).png',
    'books/Daniel Deronda/page (656).png',
    'books/Daniel Deronda/page (657).png',
    'books/Daniel Deronda/page (658).png',
    'books/Daniel Deronda/page (659).png',
    'books/Daniel Deronda/page (660).png',
    'books/Daniel Deronda/page (661).png',
    'books/Daniel Deronda/page (662).png',
    'books/Daniel Deronda/page (663).png',
    'books/Daniel Deronda/page (664).png',
    'books/Daniel Deronda/page (665).png',
    'books/Daniel Deronda/page (666).png',
    'books/Daniel Deronda/page (667).png',
    'books/Daniel Deronda/page (668).png',
    'books/Daniel Deronda/page (669).png',
    'books/Daniel Deronda/page (670).png',
    'books/Daniel Deronda/page (671).png',
    'books/Daniel Deronda/page (672).png',
    'books/Daniel Deronda/page (673).png',
    'books/Daniel Deronda/page (674).png',
    'books/Daniel Deronda/page (675).png',
    'books/Daniel Deronda/page (676).png',
    'books/Daniel Deronda/page (677).png',
    'books/Daniel Deronda/page (678).png',
    'books/Daniel Deronda/page (679).png',
    'books/Daniel Deronda/page (680).png',
    'books/Daniel Deronda/page (681).png',
    'books/Daniel Deronda/page (682).png',
    'books/Daniel Deronda/page (683).png',
    'books/Daniel Deronda/page (684).png',
    'books/Daniel Deronda/page (685).png',
    'books/Daniel Deronda/page (686).png',
    'books/Daniel Deronda/page (687).png',
    'books/Daniel Deronda/page (688).png',
    'books/Daniel Deronda/page (689).png',
    'books/Daniel Deronda/page (690).png',
    'books/Daniel Deronda/page (691).png',
    'books/Daniel Deronda/page (692).png',
    'books/Daniel Deronda/page (693).png',
    'books/Daniel Deronda/page (694).png',
    'books/Daniel Deronda/page (695).png',
    'books/Daniel Deronda/page (696).png',
    'books/Daniel Deronda/page (697).png',
    'books/Daniel Deronda/page (698).png',
    'books/Daniel Deronda/page (699).png',
    'books/Daniel Deronda/page (700).png',
    'books/Daniel Deronda/page (701).png',
    'books/Daniel Deronda/page (702).png',
    'books/Daniel Deronda/page (703).png',
    'books/Daniel Deronda/page (704).png',
    'books/Daniel Deronda/page (705).png',
    'books/Daniel Deronda/page (706).png',
    'books/Daniel Deronda/page (707).png',
    'books/Daniel Deronda/page (708).png',
    'books/Daniel Deronda/page (709).png',
    'books/Daniel Deronda/page (710).png',
    'books/Daniel Deronda/page (711).png',
    'books/Daniel Deronda/page (712).png',
    'books/Daniel Deronda/page (713).png',
    'books/Daniel Deronda/page (714).png',
    'books/Daniel Deronda/page (715).png',
    'books/Daniel Deronda/page (716).png',
    'books/Daniel Deronda/page (717).png',
    'books/Daniel Deronda/page (718).png',
    'books/Daniel Deronda/page (719).png',
    'books/Daniel Deronda/page (720).png',
    'books/Daniel Deronda/page (721).png',
    'books/Daniel Deronda/page (722).png',
    'books/Daniel Deronda/page (723).png',
    'books/Daniel Deronda/page (724).png',
    'books/Daniel Deronda/page (725).png',
    'books/Daniel Deronda/page (726).png',
    'books/Daniel Deronda/page (727).png',
    'books/Daniel Deronda/page (728).png',
    'books/Daniel Deronda/page (729).png',
    'books/Daniel Deronda/page (730).png',
    'books/Daniel Deronda/page (731).png',
    'books/Daniel Deronda/page (732).png',
    'books/Daniel Deronda/page (733).png',
    'books/Daniel Deronda/page (734).png',
    'books/Daniel Deronda/page (735).png',
    'books/Daniel Deronda/page (736).png',
    'books/Daniel Deronda/page (737).png',
    'books/Daniel Deronda/page (738).png',
    'books/Daniel Deronda/page (739).png',
    'books/Daniel Deronda/page (740).png',
    'books/Daniel Deronda/page (741).png',
    'books/Daniel Deronda/page (742).png',
    'books/Daniel Deronda/page (743).png',
    'books/Daniel Deronda/page (744).png',
    'books/Daniel Deronda/page (745).png',
    'books/Daniel Deronda/page (746).png',
    'books/Daniel Deronda/page (747).png',
    'books/Daniel Deronda/page (748).png',
    'books/Daniel Deronda/page (749).png',
    'books/Daniel Deronda/page (750).png',
    'books/Daniel Deronda/page (751).png',
    'books/Daniel Deronda/page (752).png',
    'books/Daniel Deronda/page (753).png',
    'books/Daniel Deronda/page (754).png',
    'books/Daniel Deronda/page (755).png',
    'books/Daniel Deronda/page (756).png',
    'books/Daniel Deronda/page (757).png',
    'books/Daniel Deronda/page (758).png',
    'books/Daniel Deronda/page (759).png',
    'books/Daniel Deronda/page (760).png',
    'books/Daniel Deronda/page (761).png',
    'books/Daniel Deronda/page (762).png',
    'books/Daniel Deronda/page (763).png',
    'books/Daniel Deronda/page (764).png',
    'books/Daniel Deronda/page (765).png',
    'books/Daniel Deronda/page (766).png',
    'books/Daniel Deronda/page (767).png',
    'books/Daniel Deronda/page (768).png',
    'books/Daniel Deronda/page (769).png',
    'books/Daniel Deronda/page (770).png',
    'books/Daniel Deronda/page (771).png',
    'books/Daniel Deronda/page (772).png',
    'books/Daniel Deronda/page (773).png',
    'books/Daniel Deronda/page (774).png',
    'books/Daniel Deronda/page (775).png',
    'books/Daniel Deronda/page (776).png',
    'books/Daniel Deronda/page (777).png',
    'books/Daniel Deronda/page (778).png',
    'books/Daniel Deronda/page (779).png',
    'books/Daniel Deronda/page (780).png',
    'books/Daniel Deronda/page (781).png',
    'books/Daniel Deronda/page (782).png',
    'books/Daniel Deronda/page (783).png',
    'books/Daniel Deronda/page (784).png',
    'books/Daniel Deronda/page (785).png',
    'books/Daniel Deronda/page (786).png',
    'books/Daniel Deronda/page (787).png',
    'books/Daniel Deronda/page (788).png',
    'books/Daniel Deronda/page (789).png',
    'books/Daniel Deronda/page (790).png',
    'books/Daniel Deronda/page (791).png',
    'books/Daniel Deronda/page (792).png',
    'books/Daniel Deronda/page (793).png',
    'books/Daniel Deronda/page (794).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
