import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class davidcopperfield extends StatefulWidget {
  const davidcopperfield({Key? key}) : super(key: key);

  @override
  State<davidcopperfield> createState() => _davidcopperfieldState();
}

class _davidcopperfieldState extends State<davidcopperfield> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/David Copperfield/page (1).png',
    'books/David Copperfield/page (2).png',
    'books/David Copperfield/page (3).png',
    'books/David Copperfield/page (4).png',
    'books/David Copperfield/page (5).png',
    'books/David Copperfield/page (6).png',
    'books/David Copperfield/page (7).png',
    'books/David Copperfield/page (8).png',
    'books/David Copperfield/page (9).png',
    'books/David Copperfield/page (10).png',
    'books/David Copperfield/page (11).png',
    'books/David Copperfield/page (12).png',
    'books/David Copperfield/page (13).png',
    'books/David Copperfield/page (14).png',
    'books/David Copperfield/page (15).png',
    'books/David Copperfield/page (16).png',
    'books/David Copperfield/page (17).png',
    'books/David Copperfield/page (18).png',
    'books/David Copperfield/page (19).png',
    'books/David Copperfield/page (20).png',
    'books/David Copperfield/page (21).png',
    'books/David Copperfield/page (22).png',
    'books/David Copperfield/page (23).png',
    'books/David Copperfield/page (24).png',
    'books/David Copperfield/page (25).png',
    'books/David Copperfield/page (26).png',
    'books/David Copperfield/page (27).png',
    'books/David Copperfield/page (28).png',
    'books/David Copperfield/page (29).png',
    'books/David Copperfield/page (30).png',
    'books/David Copperfield/page (31).png',
    'books/David Copperfield/page (32).png',
    'books/David Copperfield/page (33).png',
    'books/David Copperfield/page (34).png',
    'books/David Copperfield/page (35).png',
    'books/David Copperfield/page (36).png',
    'books/David Copperfield/page (37).png',
    'books/David Copperfield/page (38).png',
    'books/David Copperfield/page (39).png',
    'books/David Copperfield/page (40).png',
    'books/David Copperfield/page (41).png',
    'books/David Copperfield/page (42).png',
    'books/David Copperfield/page (43).png',
    'books/David Copperfield/page (44).png',
    'books/David Copperfield/page (45).png',
    'books/David Copperfield/page (46).png',
    'books/David Copperfield/page (47).png',
    'books/David Copperfield/page (48).png',
    'books/David Copperfield/page (49).png',
    'books/David Copperfield/page (50).png',
    'books/David Copperfield/page (51).png',
    'books/David Copperfield/page (52).png',
    'books/David Copperfield/page (53).png',
    'books/David Copperfield/page (54).png',
    'books/David Copperfield/page (55).png',
    'books/David Copperfield/page (56).png',
    'books/David Copperfield/page (57).png',
    'books/David Copperfield/page (58).png',
    'books/David Copperfield/page (59).png',
    'books/David Copperfield/page (60).png',
    'books/David Copperfield/page (61).png',
    'books/David Copperfield/page (62).png',
    'books/David Copperfield/page (63).png',
    'books/David Copperfield/page (64).png',
    'books/David Copperfield/page (65).png',
    'books/David Copperfield/page (66).png',
    'books/David Copperfield/page (67).png',
    'books/David Copperfield/page (68).png',
    'books/David Copperfield/page (69).png',
    'books/David Copperfield/page (70).png',
    'books/David Copperfield/page (71).png',
    'books/David Copperfield/page (72).png',
    'books/David Copperfield/page (73).png',
    'books/David Copperfield/page (74).png',
    'books/David Copperfield/page (75).png',
    'books/David Copperfield/page (76).png',
    'books/David Copperfield/page (77).png',
    'books/David Copperfield/page (78).png',
    'books/David Copperfield/page (79).png',
    'books/David Copperfield/page (80).png',
    'books/David Copperfield/page (81).png',
    'books/David Copperfield/page (82).png',
    'books/David Copperfield/page (83).png',
    'books/David Copperfield/page (84).png',
    'books/David Copperfield/page (85).png',
    'books/David Copperfield/page (86).png',
    'books/David Copperfield/page (87).png',
    'books/David Copperfield/page (88).png',
    'books/David Copperfield/page (89).png',
    'books/David Copperfield/page (90).png',
    'books/David Copperfield/page (91).png',
    'books/David Copperfield/page (92).png',
    'books/David Copperfield/page (93).png',
    'books/David Copperfield/page (94).png',
    'books/David Copperfield/page (95).png',
    'books/David Copperfield/page (96).png',
    'books/David Copperfield/page (97).png',
    'books/David Copperfield/page (98).png',
    'books/David Copperfield/page (99).png',
    'books/David Copperfield/page (100).png',
    'books/David Copperfield/page (101).png',
    'books/David Copperfield/page (102).png',
    'books/David Copperfield/page (103).png',
    'books/David Copperfield/page (104).png',
    'books/David Copperfield/page (105).png',
    'books/David Copperfield/page (106).png',
    'books/David Copperfield/page (107).png',
    'books/David Copperfield/page (108).png',
    'books/David Copperfield/page (109).png',
    'books/David Copperfield/page (110).png',
    'books/David Copperfield/page (111).png',
    'books/David Copperfield/page (112).png',
    'books/David Copperfield/page (113).png',
    'books/David Copperfield/page (114).png',
    'books/David Copperfield/page (115).png',
    'books/David Copperfield/page (116).png',
    'books/David Copperfield/page (117).png',
    'books/David Copperfield/page (118).png',
    'books/David Copperfield/page (119).png',
    'books/David Copperfield/page (120).png',
    'books/David Copperfield/page (121).png',
    'books/David Copperfield/page (122).png',
    'books/David Copperfield/page (123).png',
    'books/David Copperfield/page (124).png',
    'books/David Copperfield/page (125).png',
    'books/David Copperfield/page (126).png',
    'books/David Copperfield/page (127).png',
    'books/David Copperfield/page (128).png',
    'books/David Copperfield/page (129).png',
    'books/David Copperfield/page (130).png',
    'books/David Copperfield/page (131).png',
    'books/David Copperfield/page (132).png',
    'books/David Copperfield/page (133).png',
    'books/David Copperfield/page (134).png',
    'books/David Copperfield/page (135).png',
    'books/David Copperfield/page (136).png',
    'books/David Copperfield/page (137).png',
    'books/David Copperfield/page (138).png',
    'books/David Copperfield/page (139).png',
    'books/David Copperfield/page (140).png',
    'books/David Copperfield/page (141).png',
    'books/David Copperfield/page (142).png',
    'books/David Copperfield/page (143).png',
    'books/David Copperfield/page (144).png',
    'books/David Copperfield/page (145).png',
    'books/David Copperfield/page (146).png',
    'books/David Copperfield/page (147).png',
    'books/David Copperfield/page (148).png',
    'books/David Copperfield/page (149).png',
    'books/David Copperfield/page (150).png',
    'books/David Copperfield/page (151).png',
    'books/David Copperfield/page (152).png',
    'books/David Copperfield/page (153).png',
    'books/David Copperfield/page (154).png',
    'books/David Copperfield/page (155).png',
    'books/David Copperfield/page (156).png',
    'books/David Copperfield/page (157).png',
    'books/David Copperfield/page (158).png',
    'books/David Copperfield/page (159).png',
    'books/David Copperfield/page (160).png',
    'books/David Copperfield/page (161).png',
    'books/David Copperfield/page (162).png',
    'books/David Copperfield/page (163).png',
    'books/David Copperfield/page (164).png',
    'books/David Copperfield/page (165).png',
    'books/David Copperfield/page (166).png',
    'books/David Copperfield/page (167).png',
    'books/David Copperfield/page (168).png',
    'books/David Copperfield/page (169).png',
    'books/David Copperfield/page (170).png',
    'books/David Copperfield/page (171).png',
    'books/David Copperfield/page (172).png',
    'books/David Copperfield/page (173).png',
    'books/David Copperfield/page (174).png',
    'books/David Copperfield/page (175).png',
    'books/David Copperfield/page (176).png',
    'books/David Copperfield/page (177).png',
    'books/David Copperfield/page (178).png',
    'books/David Copperfield/page (179).png',
    'books/David Copperfield/page (180).png',
    'books/David Copperfield/page (181).png',
    'books/David Copperfield/page (182).png',
    'books/David Copperfield/page (183).png',
    'books/David Copperfield/page (184).png',
    'books/David Copperfield/page (185).png',
    'books/David Copperfield/page (186).png',
    'books/David Copperfield/page (187).png',
    'books/David Copperfield/page (188).png',
    'books/David Copperfield/page (189).png',
    'books/David Copperfield/page (190).png',
    'books/David Copperfield/page (191).png',
    'books/David Copperfield/page (192).png',
    'books/David Copperfield/page (193).png',
    'books/David Copperfield/page (194).png',
    'books/David Copperfield/page (195).png',
    'books/David Copperfield/page (196).png',
    'books/David Copperfield/page (197).png',
    'books/David Copperfield/page (198).png',
    'books/David Copperfield/page (199).png',
    'books/David Copperfield/page (200).png',
    'books/David Copperfield/page (201).png',
    'books/David Copperfield/page (202).png',
    'books/David Copperfield/page (203).png',
    'books/David Copperfield/page (204).png',
    'books/David Copperfield/page (205).png',
    'books/David Copperfield/page (206).png',
    'books/David Copperfield/page (207).png',
    'books/David Copperfield/page (208).png',
    'books/David Copperfield/page (209).png',
    'books/David Copperfield/page (210).png',
    'books/David Copperfield/page (211).png',
    'books/David Copperfield/page (212).png',
    'books/David Copperfield/page (213).png',
    'books/David Copperfield/page (214).png',
    'books/David Copperfield/page (215).png',
    'books/David Copperfield/page (216).png',
    'books/David Copperfield/page (217).png',
    'books/David Copperfield/page (218).png',
    'books/David Copperfield/page (219).png',
    'books/David Copperfield/page (220).png',
    'books/David Copperfield/page (221).png',
    'books/David Copperfield/page (222).png',
    'books/David Copperfield/page (223).png',
    'books/David Copperfield/page (224).png',
    'books/David Copperfield/page (225).png',
    'books/David Copperfield/page (226).png',
    'books/David Copperfield/page (227).png',
    'books/David Copperfield/page (228).png',
    'books/David Copperfield/page (229).png',
    'books/David Copperfield/page (230).png',
    'books/David Copperfield/page (231).png',
    'books/David Copperfield/page (232).png',
    'books/David Copperfield/page (233).png',
    'books/David Copperfield/page (234).png',
    'books/David Copperfield/page (235).png',
    'books/David Copperfield/page (236).png',
    'books/David Copperfield/page (237).png',
    'books/David Copperfield/page (238).png',
    'books/David Copperfield/page (239).png',
    'books/David Copperfield/page (240).png',
    'books/David Copperfield/page (241).png',
    'books/David Copperfield/page (242).png',
    'books/David Copperfield/page (243).png',
    'books/David Copperfield/page (244).png',
    'books/David Copperfield/page (245).png',
    'books/David Copperfield/page (246).png',
    'books/David Copperfield/page (247).png',
    'books/David Copperfield/page (248).png',
    'books/David Copperfield/page (249).png',
    'books/David Copperfield/page (250).png',
    'books/David Copperfield/page (251).png',
    'books/David Copperfield/page (252).png',
    'books/David Copperfield/page (253).png',
    'books/David Copperfield/page (254).png',
    'books/David Copperfield/page (255).png',
    'books/David Copperfield/page (256).png',
    'books/David Copperfield/page (257).png',
    'books/David Copperfield/page (258).png',
    'books/David Copperfield/page (259).png',
    'books/David Copperfield/page (260).png',
    'books/David Copperfield/page (261).png',
    'books/David Copperfield/page (262).png',
    'books/David Copperfield/page (263).png',
    'books/David Copperfield/page (264).png',
    'books/David Copperfield/page (265).png',
    'books/David Copperfield/page (266).png',
    'books/David Copperfield/page (267).png',
    'books/David Copperfield/page (268).png',
    'books/David Copperfield/page (269).png',
    'books/David Copperfield/page (270).png',
    'books/David Copperfield/page (271).png',
    'books/David Copperfield/page (272).png',
    'books/David Copperfield/page (273).png',
    'books/David Copperfield/page (274).png',
    'books/David Copperfield/page (275).png',
    'books/David Copperfield/page (276).png',
    'books/David Copperfield/page (277).png',
    'books/David Copperfield/page (278).png',
    'books/David Copperfield/page (279).png',
    'books/David Copperfield/page (280).png',
    'books/David Copperfield/page (281).png',
    'books/David Copperfield/page (282).png',
    'books/David Copperfield/page (283).png',
    'books/David Copperfield/page (284).png',
    'books/David Copperfield/page (285).png',
    'books/David Copperfield/page (286).png',
    'books/David Copperfield/page (287).png',
    'books/David Copperfield/page (288).png',
    'books/David Copperfield/page (289).png',
    'books/David Copperfield/page (290).png',
    'books/David Copperfield/page (291).png',
    'books/David Copperfield/page (292).png',
    'books/David Copperfield/page (293).png',
    'books/David Copperfield/page (294).png',
    'books/David Copperfield/page (295).png',
    'books/David Copperfield/page (296).png',
    'books/David Copperfield/page (297).png',
    'books/David Copperfield/page (298).png',
    'books/David Copperfield/page (299).png',
    'books/David Copperfield/page (300).png',
    'books/David Copperfield/page (301).png',
    'books/David Copperfield/page (302).png',
    'books/David Copperfield/page (303).png',
    'books/David Copperfield/page (304).png',
    'books/David Copperfield/page (305).png',
    'books/David Copperfield/page (306).png',
    'books/David Copperfield/page (307).png',
    'books/David Copperfield/page (308).png',
    'books/David Copperfield/page (309).png',
    'books/David Copperfield/page (310).png',
    'books/David Copperfield/page (311).png',
    'books/David Copperfield/page (312).png',
    'books/David Copperfield/page (313).png',
    'books/David Copperfield/page (314).png',
    'books/David Copperfield/page (315).png',
    'books/David Copperfield/page (316).png',
    'books/David Copperfield/page (317).png',
    'books/David Copperfield/page (318).png',
    'books/David Copperfield/page (319).png',
    'books/David Copperfield/page (320).png',
    'books/David Copperfield/page (321).png',
    'books/David Copperfield/page (322).png',
    'books/David Copperfield/page (323).png',
    'books/David Copperfield/page (324).png',
    'books/David Copperfield/page (325).png',
    'books/David Copperfield/page (326).png',
    'books/David Copperfield/page (327).png',
    'books/David Copperfield/page (328).png',
    'books/David Copperfield/page (329).png',
    'books/David Copperfield/page (330).png',
    'books/David Copperfield/page (331).png',
    'books/David Copperfield/page (332).png',
    'books/David Copperfield/page (333).png',
    'books/David Copperfield/page (334).png',
    'books/David Copperfield/page (335).png',
    'books/David Copperfield/page (336).png',
    'books/David Copperfield/page (337).png',
    'books/David Copperfield/page (338).png',
    'books/David Copperfield/page (339).png',
    'books/David Copperfield/page (340).png',
    'books/David Copperfield/page (341).png',
    'books/David Copperfield/page (342).png',
    'books/David Copperfield/page (343).png',
    'books/David Copperfield/page (344).png',
    'books/David Copperfield/page (345).png',
    'books/David Copperfield/page (346).png',
    'books/David Copperfield/page (347).png',
    'books/David Copperfield/page (348).png',
    'books/David Copperfield/page (349).png',
    'books/David Copperfield/page (350).png',
    'books/David Copperfield/page (351).png',
    'books/David Copperfield/page (352).png',
    'books/David Copperfield/page (353).png',
    'books/David Copperfield/page (354).png',
    'books/David Copperfield/page (355).png',
    'books/David Copperfield/page (356).png',
    'books/David Copperfield/page (357).png',
    'books/David Copperfield/page (358).png',
    'books/David Copperfield/page (359).png',
    'books/David Copperfield/page (360).png',
    'books/David Copperfield/page (361).png',
    'books/David Copperfield/page (362).png',
    'books/David Copperfield/page (363).png',
    'books/David Copperfield/page (364).png',
    'books/David Copperfield/page (365).png',
    'books/David Copperfield/page (366).png',
    'books/David Copperfield/page (367).png',
    'books/David Copperfield/page (368).png',
    'books/David Copperfield/page (369).png',
    'books/David Copperfield/page (370).png',
    'books/David Copperfield/page (371).png',
    'books/David Copperfield/page (372).png',
    'books/David Copperfield/page (373).png',
    'books/David Copperfield/page (374).png',
    'books/David Copperfield/page (375).png',
    'books/David Copperfield/page (376).png',
    'books/David Copperfield/page (377).png',
    'books/David Copperfield/page (378).png',
    'books/David Copperfield/page (379).png',
    'books/David Copperfield/page (380).png',
    'books/David Copperfield/page (381).png',
    'books/David Copperfield/page (382).png',
    'books/David Copperfield/page (383).png',
    'books/David Copperfield/page (384).png',
    'books/David Copperfield/page (385).png',
    'books/David Copperfield/page (386).png',
    'books/David Copperfield/page (387).png',
    'books/David Copperfield/page (388).png',
    'books/David Copperfield/page (389).png',
    'books/David Copperfield/page (390).png',
    'books/David Copperfield/page (391).png',
    'books/David Copperfield/page (392).png',
    'books/David Copperfield/page (393).png',
    'books/David Copperfield/page (394).png',
    'books/David Copperfield/page (395).png',
    'books/David Copperfield/page (396).png',
    'books/David Copperfield/page (397).png',
    'books/David Copperfield/page (398).png',
    'books/David Copperfield/page (399).png',
    'books/David Copperfield/page (400).png',
    'books/David Copperfield/page (401).png',
    'books/David Copperfield/page (402).png',
    'books/David Copperfield/page (403).png',
    'books/David Copperfield/page (404).png',
    'books/David Copperfield/page (405).png',
    'books/David Copperfield/page (406).png',
    'books/David Copperfield/page (407).png',
    'books/David Copperfield/page (408).png',
    'books/David Copperfield/page (409).png',
    'books/David Copperfield/page (410).png',
    'books/David Copperfield/page (411).png',
    'books/David Copperfield/page (412).png',
    'books/David Copperfield/page (413).png',
    'books/David Copperfield/page (414).png',
    'books/David Copperfield/page (415).png',
    'books/David Copperfield/page (416).png',
    'books/David Copperfield/page (417).png',
    'books/David Copperfield/page (418).png',
    'books/David Copperfield/page (419).png',
    'books/David Copperfield/page (420).png',
    'books/David Copperfield/page (421).png',
    'books/David Copperfield/page (422).png',
    'books/David Copperfield/page (423).png',
    'books/David Copperfield/page (424).png',
    'books/David Copperfield/page (425).png',
    'books/David Copperfield/page (426).png',
    'books/David Copperfield/page (427).png',
    'books/David Copperfield/page (428).png',
    'books/David Copperfield/page (429).png',
    'books/David Copperfield/page (430).png',
    'books/David Copperfield/page (431).png',
    'books/David Copperfield/page (432).png',
    'books/David Copperfield/page (433).png',
    'books/David Copperfield/page (434).png',
    'books/David Copperfield/page (435).png',
    'books/David Copperfield/page (436).png',
    'books/David Copperfield/page (437).png',
    'books/David Copperfield/page (438).png',
    'books/David Copperfield/page (439).png',
    'books/David Copperfield/page (440).png',
    'books/David Copperfield/page (441).png',
    'books/David Copperfield/page (442).png',
    'books/David Copperfield/page (443).png',
    'books/David Copperfield/page (444).png',
    'books/David Copperfield/page (445).png',
    'books/David Copperfield/page (446).png',
    'books/David Copperfield/page (447).png',
    'books/David Copperfield/page (448).png',
    'books/David Copperfield/page (449).png',
    'books/David Copperfield/page (450).png',
    'books/David Copperfield/page (451).png',
    'books/David Copperfield/page (452).png',
    'books/David Copperfield/page (453).png',
    'books/David Copperfield/page (454).png',
    'books/David Copperfield/page (455).png',
    'books/David Copperfield/page (456).png',
    'books/David Copperfield/page (457).png',
    'books/David Copperfield/page (458).png',
    'books/David Copperfield/page (459).png',
    'books/David Copperfield/page (460).png',
    'books/David Copperfield/page (461).png',
    'books/David Copperfield/page (462).png',
    'books/David Copperfield/page (463).png',
    'books/David Copperfield/page (464).png',
    'books/David Copperfield/page (465).png',
    'books/David Copperfield/page (466).png',
    'books/David Copperfield/page (467).png',
    'books/David Copperfield/page (468).png',
    'books/David Copperfield/page (469).png',
    'books/David Copperfield/page (470).png',
    'books/David Copperfield/page (471).png',
    'books/David Copperfield/page (472).png',
    'books/David Copperfield/page (473).png',
    'books/David Copperfield/page (474).png',
    'books/David Copperfield/page (475).png',
    'books/David Copperfield/page (476).png',
    'books/David Copperfield/page (477).png',
    'books/David Copperfield/page (478).png',
    'books/David Copperfield/page (479).png',
    'books/David Copperfield/page (480).png',
    'books/David Copperfield/page (481).png',
    'books/David Copperfield/page (482).png',
    'books/David Copperfield/page (483).png',
    'books/David Copperfield/page (484).png',
    'books/David Copperfield/page (485).png',
    'books/David Copperfield/page (486).png',
    'books/David Copperfield/page (487).png',
    'books/David Copperfield/page (488).png',
    'books/David Copperfield/page (489).png',
    'books/David Copperfield/page (490).png',
    'books/David Copperfield/page (491).png',
    'books/David Copperfield/page (492).png',
    'books/David Copperfield/page (493).png',
    'books/David Copperfield/page (494).png',
    'books/David Copperfield/page (495).png',
    'books/David Copperfield/page (496).png',
    'books/David Copperfield/page (497).png',
    'books/David Copperfield/page (498).png',
    'books/David Copperfield/page (499).png',
    'books/David Copperfield/page (500).png',
    'books/David Copperfield/page (501).png',
    'books/David Copperfield/page (502).png',
    'books/David Copperfield/page (503).png',
    'books/David Copperfield/page (504).png',
    'books/David Copperfield/page (505).png',
    'books/David Copperfield/page (506).png',
    'books/David Copperfield/page (507).png',
    'books/David Copperfield/page (508).png',
    'books/David Copperfield/page (509).png',
    'books/David Copperfield/page (510).png',
    'books/David Copperfield/page (511).png',
    'books/David Copperfield/page (512).png',
    'books/David Copperfield/page (513).png',
    'books/David Copperfield/page (514).png',
    'books/David Copperfield/page (515).png',
    'books/David Copperfield/page (516).png',
    'books/David Copperfield/page (517).png',
    'books/David Copperfield/page (518).png',
    'books/David Copperfield/page (519).png',
    'books/David Copperfield/page (520).png',
    'books/David Copperfield/page (521).png',
    'books/David Copperfield/page (522).png',
    'books/David Copperfield/page (523).png',
    'books/David Copperfield/page (524).png',
    'books/David Copperfield/page (525).png',
    'books/David Copperfield/page (526).png',
    'books/David Copperfield/page (527).png',
    'books/David Copperfield/page (528).png',
    'books/David Copperfield/page (529).png',
    'books/David Copperfield/page (530).png',
    'books/David Copperfield/page (531).png',
    'books/David Copperfield/page (532).png',
    'books/David Copperfield/page (533).png',
    'books/David Copperfield/page (534).png',
    'books/David Copperfield/page (535).png',
    'books/David Copperfield/page (536).png',
    'books/David Copperfield/page (537).png',
    'books/David Copperfield/page (538).png',
    'books/David Copperfield/page (539).png',
    'books/David Copperfield/page (540).png',
    'books/David Copperfield/page (541).png',
    'books/David Copperfield/page (542).png',
    'books/David Copperfield/page (543).png',
    'books/David Copperfield/page (544).png',
    'books/David Copperfield/page (545).png',
    'books/David Copperfield/page (546).png',
    'books/David Copperfield/page (547).png',
    'books/David Copperfield/page (548).png',
    'books/David Copperfield/page (549).png',
    'books/David Copperfield/page (550).png',
    'books/David Copperfield/page (551).png',
    'books/David Copperfield/page (552).png',
    'books/David Copperfield/page (553).png',
    'books/David Copperfield/page (554).png',
    'books/David Copperfield/page (555).png',
    'books/David Copperfield/page (556).png',
    'books/David Copperfield/page (557).png',
    'books/David Copperfield/page (558).png',
    'books/David Copperfield/page (559).png',
    'books/David Copperfield/page (560).png',
    'books/David Copperfield/page (561).png',
    'books/David Copperfield/page (562).png',
    'books/David Copperfield/page (563).png',
    'books/David Copperfield/page (564).png',
    'books/David Copperfield/page (565).png',
    'books/David Copperfield/page (566).png',
    'books/David Copperfield/page (567).png',
    'books/David Copperfield/page (568).png',
    'books/David Copperfield/page (569).png',
    'books/David Copperfield/page (570).png',
    'books/David Copperfield/page (571).png',
    'books/David Copperfield/page (572).png',
    'books/David Copperfield/page (573).png',
    'books/David Copperfield/page (574).png',
    'books/David Copperfield/page (575).png',
    'books/David Copperfield/page (576).png',
    'books/David Copperfield/page (577).png',
    'books/David Copperfield/page (578).png',
    'books/David Copperfield/page (579).png',
    'books/David Copperfield/page (580).png',
    'books/David Copperfield/page (581).png',
    'books/David Copperfield/page (582).png',
    'books/David Copperfield/page (583).png',
    'books/David Copperfield/page (584).png',
    'books/David Copperfield/page (585).png',
    'books/David Copperfield/page (586).png',
    'books/David Copperfield/page (587).png',
    'books/David Copperfield/page (588).png',
    'books/David Copperfield/page (589).png',
    'books/David Copperfield/page (590).png',
    'books/David Copperfield/page (591).png',
    'books/David Copperfield/page (592).png',
    'books/David Copperfield/page (593).png',
    'books/David Copperfield/page (594).png',
    'books/David Copperfield/page (595).png',
    'books/David Copperfield/page (596).png',
    'books/David Copperfield/page (597).png',
    'books/David Copperfield/page (598).png',
    'books/David Copperfield/page (599).png',
    'books/David Copperfield/page (600).png',
    'books/David Copperfield/page (601).png',
    'books/David Copperfield/page (602).png',
    'books/David Copperfield/page (603).png',
    'books/David Copperfield/page (604).png',
    'books/David Copperfield/page (605).png',
    'books/David Copperfield/page (606).png',
    'books/David Copperfield/page (607).png',
    'books/David Copperfield/page (608).png',
    'books/David Copperfield/page (609).png',
    'books/David Copperfield/page (610).png',
    'books/David Copperfield/page (611).png',
    'books/David Copperfield/page (612).png',
    'books/David Copperfield/page (613).png',
    'books/David Copperfield/page (614).png',
    'books/David Copperfield/page (615).png',
    'books/David Copperfield/page (616).png',
    'books/David Copperfield/page (617).png',
    'books/David Copperfield/page (618).png',
    'books/David Copperfield/page (619).png',
    'books/David Copperfield/page (620).png',
    'books/David Copperfield/page (621).png',
    'books/David Copperfield/page (622).png',
    'books/David Copperfield/page (623).png',
    'books/David Copperfield/page (624).png',
    'books/David Copperfield/page (625).png',
    'books/David Copperfield/page (626).png',
    'books/David Copperfield/page (627).png',
    'books/David Copperfield/page (628).png',
    'books/David Copperfield/page (629).png',
    'books/David Copperfield/page (630).png',
    'books/David Copperfield/page (631).png',
    'books/David Copperfield/page (632).png',
    'books/David Copperfield/page (633).png',
    'books/David Copperfield/page (634).png',
    'books/David Copperfield/page (635).png',
    'books/David Copperfield/page (636).png',
    'books/David Copperfield/page (637).png',
    'books/David Copperfield/page (638).png',
    'books/David Copperfield/page (639).png',
    'books/David Copperfield/page (640).png',
    'books/David Copperfield/page (641).png',
    'books/David Copperfield/page (642).png',
    'books/David Copperfield/page (643).png',
    'books/David Copperfield/page (644).png',
    'books/David Copperfield/page (645).png',
    'books/David Copperfield/page (646).png',
    'books/David Copperfield/page (647).png',
    'books/David Copperfield/page (648).png',
    'books/David Copperfield/page (649).png',
    'books/David Copperfield/page (650).png',
    'books/David Copperfield/page (651).png',
    'books/David Copperfield/page (652).png',
    'books/David Copperfield/page (653).png',
    'books/David Copperfield/page (654).png',
    'books/David Copperfield/page (655).png',
    'books/David Copperfield/page (656).png',
    'books/David Copperfield/page (657).png',
    'books/David Copperfield/page (658).png',
    'books/David Copperfield/page (659).png',
    'books/David Copperfield/page (660).png',
    'books/David Copperfield/page (661).png',
    'books/David Copperfield/page (662).png',
    'books/David Copperfield/page (663).png',
    'books/David Copperfield/page (664).png',
    'books/David Copperfield/page (665).png',
    'books/David Copperfield/page (666).png',
    'books/David Copperfield/page (667).png',
    'books/David Copperfield/page (668).png',
    'books/David Copperfield/page (669).png',
    'books/David Copperfield/page (670).png',
    'books/David Copperfield/page (671).png',
    'books/David Copperfield/page (672).png',
    'books/David Copperfield/page (673).png',
    'books/David Copperfield/page (674).png',
    'books/David Copperfield/page (675).png',
    'books/David Copperfield/page (676).png',
    'books/David Copperfield/page (677).png',
    'books/David Copperfield/page (678).png',
    'books/David Copperfield/page (679).png',
    'books/David Copperfield/page (680).png',
    'books/David Copperfield/page (681).png',
    'books/David Copperfield/page (682).png',
    'books/David Copperfield/page (683).png',
    'books/David Copperfield/page (684).png',
    'books/David Copperfield/page (685).png',
    'books/David Copperfield/page (686).png',
    'books/David Copperfield/page (687).png',
    'books/David Copperfield/page (688).png',
    'books/David Copperfield/page (689).png',
    'books/David Copperfield/page (690).png',
    'books/David Copperfield/page (691).png',
    'books/David Copperfield/page (692).png',
    'books/David Copperfield/page (693).png',
    'books/David Copperfield/page (694).png',
    'books/David Copperfield/page (695).png',
    'books/David Copperfield/page (696).png',
    'books/David Copperfield/page (697).png',
    'books/David Copperfield/page (698).png',
    'books/David Copperfield/page (699).png',
    'books/David Copperfield/page (700).png',
    'books/David Copperfield/page (701).png',
    'books/David Copperfield/page (702).png',
    'books/David Copperfield/page (703).png',
    'books/David Copperfield/page (704).png',
    'books/David Copperfield/page (705).png',
    'books/David Copperfield/page (706).png',
    'books/David Copperfield/page (707).png',
    'books/David Copperfield/page (708).png',
    'books/David Copperfield/page (709).png',
    'books/David Copperfield/page (710).png',
    'books/David Copperfield/page (711).png',
    'books/David Copperfield/page (712).png',
    'books/David Copperfield/page (713).png',
    'books/David Copperfield/page (714).png',
    'books/David Copperfield/page (715).png',
    'books/David Copperfield/page (716).png',
    'books/David Copperfield/page (717).png',
    'books/David Copperfield/page (718).png',
    'books/David Copperfield/page (719).png',
    'books/David Copperfield/page (720).png',
    'books/David Copperfield/page (721).png',
    'books/David Copperfield/page (722).png',
    'books/David Copperfield/page (723).png',
    'books/David Copperfield/page (724).png',
    'books/David Copperfield/page (725).png',
    'books/David Copperfield/page (726).png',
    'books/David Copperfield/page (727).png',
    'books/David Copperfield/page (728).png',
    'books/David Copperfield/page (729).png',
    'books/David Copperfield/page (730).png',
    'books/David Copperfield/page (731).png',
    'books/David Copperfield/page (732).png',
    'books/David Copperfield/page (733).png',
    'books/David Copperfield/page (734).png',
    'books/David Copperfield/page (735).png',
    'books/David Copperfield/page (736).png',
    'books/David Copperfield/page (737).png',
    'books/David Copperfield/page (738).png',
    'books/David Copperfield/page (739).png',
    'books/David Copperfield/page (740).png',
    'books/David Copperfield/page (741).png',
    'books/David Copperfield/page (742).png',
    'books/David Copperfield/page (743).png',
    'books/David Copperfield/page (744).png',
    'books/David Copperfield/page (745).png',
    'books/David Copperfield/page (746).png',
    'books/David Copperfield/page (747).png',
    'books/David Copperfield/page (748).png',
    'books/David Copperfield/page (749).png',
    'books/David Copperfield/page (750).png',
    'books/David Copperfield/page (751).png',
    'books/David Copperfield/page (752).png',
    'books/David Copperfield/page (753).png',
    'books/David Copperfield/page (754).png',
    'books/David Copperfield/page (755).png',
    'books/David Copperfield/page (756).png',
    'books/David Copperfield/page (757).png',
    'books/David Copperfield/page (758).png',
    'books/David Copperfield/page (759).png',
    'books/David Copperfield/page (760).png',
    'books/David Copperfield/page (761).png',
    'books/David Copperfield/page (762).png',
    'books/David Copperfield/page (763).png',
    'books/David Copperfield/page (764).png',
    'books/David Copperfield/page (765).png',
    'books/David Copperfield/page (766).png',
    'books/David Copperfield/page (767).png',
    'books/David Copperfield/page (768).png',
    'books/David Copperfield/page (769).png',
    'books/David Copperfield/page (770).png',
    'books/David Copperfield/page (771).png',
    'books/David Copperfield/page (772).png',
    'books/David Copperfield/page (773).png',
    'books/David Copperfield/page (774).png',
    'books/David Copperfield/page (775).png',
    'books/David Copperfield/page (776).png',
    'books/David Copperfield/page (777).png',
    'books/David Copperfield/page (778).png',
    'books/David Copperfield/page (779).png',
    'books/David Copperfield/page (780).png',
    'books/David Copperfield/page (781).png',
    'books/David Copperfield/page (782).png',
    'books/David Copperfield/page (783).png',
    'books/David Copperfield/page (784).png',
    'books/David Copperfield/page (785).png',
    'books/David Copperfield/page (786).png',
    'books/David Copperfield/page (787).png',
    'books/David Copperfield/page (788).png',
    'books/David Copperfield/page (789).png',
    'books/David Copperfield/page (790).png',
    'books/David Copperfield/page (791).png',
    'books/David Copperfield/page (792).png',
    'books/David Copperfield/page (793).png',
    'books/David Copperfield/page (794).png',
    'books/David Copperfield/page (795).png',
    'books/David Copperfield/page (796).png',
    'books/David Copperfield/page (797).png',
    'books/David Copperfield/page (798).png',
    'books/David Copperfield/page (799).png',
    'books/David Copperfield/page (800).png',
    'books/David Copperfield/page (801).png',
    'books/David Copperfield/page (802).png',
    'books/David Copperfield/page (803).png',
    'books/David Copperfield/page (804).png',
    'books/David Copperfield/page (805).png',
    'books/David Copperfield/page (806).png',
    'books/David Copperfield/page (807).png',
    'books/David Copperfield/page (808).png',
    'books/David Copperfield/page (809).png',
    'books/David Copperfield/page (810).png',
    'books/David Copperfield/page (811).png',
    'books/David Copperfield/page (812).png',
    'books/David Copperfield/page (813).png',
    'books/David Copperfield/page (814).png',
    'books/David Copperfield/page (815).png',
    'books/David Copperfield/page (816).png',
    'books/David Copperfield/page (817).png',
    'books/David Copperfield/page (818).png',
    'books/David Copperfield/page (819).png',
    'books/David Copperfield/page (820).png',
    'books/David Copperfield/page (821).png',
    'books/David Copperfield/page (822).png',
    'books/David Copperfield/page (823).png',
    'books/David Copperfield/page (824).png',
    'books/David Copperfield/page (825).png',
    'books/David Copperfield/page (826).png',
    'books/David Copperfield/page (827).png',
    'books/David Copperfield/page (828).png',
    'books/David Copperfield/page (829).png',
    'books/David Copperfield/page (830).png',
    'books/David Copperfield/page (831).png',
    'books/David Copperfield/page (832).png',
    'books/David Copperfield/page (833).png',
    'books/David Copperfield/page (834).png',
    'books/David Copperfield/page (835).png',
    'books/David Copperfield/page (836).png',
    'books/David Copperfield/page (837).png',
    'books/David Copperfield/page (838).png',
    'books/David Copperfield/page (839).png',
    'books/David Copperfield/page (840).png',
    'books/David Copperfield/page (841).png',
    'books/David Copperfield/page (842).png',
    'books/David Copperfield/page (843).png',
    'books/David Copperfield/page (844).png',
    'books/David Copperfield/page (845).png',
    'books/David Copperfield/page (846).png',
    'books/David Copperfield/page (847).png',
    'books/David Copperfield/page (848).png',
    'books/David Copperfield/page (849).png',
    'books/David Copperfield/page (850).png',
    'books/David Copperfield/page (851).png',
    'books/David Copperfield/page (852).png',
    'books/David Copperfield/page (853).png',
    'books/David Copperfield/page (854).png',
    'books/David Copperfield/page (855).png',
    'books/David Copperfield/page (856).png',
    'books/David Copperfield/page (857).png',
    'books/David Copperfield/page (858).png',
    'books/David Copperfield/page (859).png',
    'books/David Copperfield/page (860).png',
    'books/David Copperfield/page (861).png',
    'books/David Copperfield/page (862).png',
    'books/David Copperfield/page (863).png',
    'books/David Copperfield/page (864).png',
    'books/David Copperfield/page (865).png',
    'books/David Copperfield/page (866).png',
    'books/David Copperfield/page (867).png',
    'books/David Copperfield/page (868).png',
    'books/David Copperfield/page (869).png',
    'books/David Copperfield/page (870).png',
    'books/David Copperfield/page (871).png',
    'books/David Copperfield/page (872).png',
    'books/David Copperfield/page (873).png',
    'books/David Copperfield/page (874).png',
    'books/David Copperfield/page (875).png',
    'books/David Copperfield/page (876).png',
    'books/David Copperfield/page (877).png',
    'books/David Copperfield/page (878).png',
    'books/David Copperfield/page (879).png',
    'books/David Copperfield/page (880).png',
    'books/David Copperfield/page (881).png',
    'books/David Copperfield/page (882).png',
    'books/David Copperfield/page (883).png',
    'books/David Copperfield/page (884).png',
    'books/David Copperfield/page (885).png',
    'books/David Copperfield/page (886).png',
    'books/David Copperfield/page (887).png',
    'books/David Copperfield/page (888).png',
    'books/David Copperfield/page (889).png',
    'books/David Copperfield/page (890).png',
    'books/David Copperfield/page (891).png',
    'books/David Copperfield/page (892).png',
    'books/David Copperfield/page (893).png',
    'books/David Copperfield/page (894).png',
    'books/David Copperfield/page (895).png',
    'books/David Copperfield/page (896).png',
    'books/David Copperfield/page (897).png',
    'books/David Copperfield/page (898).png',
    'books/David Copperfield/page (899).png',
    'books/David Copperfield/page (900).png',
    'books/David Copperfield/page (901).png',
    'books/David Copperfield/page (902).png',
    'books/David Copperfield/page (903).png',
    'books/David Copperfield/page (904).png',
    'books/David Copperfield/page (905).png',
    'books/David Copperfield/page (906).png',
    'books/David Copperfield/page (907).png',
    'books/David Copperfield/page (908).png',
    'books/David Copperfield/page (909).png',
    'books/David Copperfield/page (910).png',
    'books/David Copperfield/page (911).png',
    'books/David Copperfield/page (912).png',
    'books/David Copperfield/page (913).png',
    'books/David Copperfield/page (914).png',
    'books/David Copperfield/page (915).png',
    'books/David Copperfield/page (916).png',
    'books/David Copperfield/page (917).png',
    'books/David Copperfield/page (918).png',
    'books/David Copperfield/page (919).png',
    'books/David Copperfield/page (920).png',
    'books/David Copperfield/page (921).png',
    'books/David Copperfield/page (922).png',
    'books/David Copperfield/page (923).png',
    'books/David Copperfield/page (924).png',
    'books/David Copperfield/page (925).png',
    'books/David Copperfield/page (926).png',
    'books/David Copperfield/page (927).png',
    'books/David Copperfield/page (928).png',
    'books/David Copperfield/page (929).png',
    'books/David Copperfield/page (930).png',
    'books/David Copperfield/page (931).png',
    'books/David Copperfield/page (932).png',
    'books/David Copperfield/page (933).png',
    'books/David Copperfield/page (934).png',
    'books/David Copperfield/page (935).png',
    'books/David Copperfield/page (936).png',
    'books/David Copperfield/page (937).png',
    'books/David Copperfield/page (938).png',
    'books/David Copperfield/page (939).png',
    'books/David Copperfield/page (940).png',
    'books/David Copperfield/page (941).png',
    'books/David Copperfield/page (942).png',
    'books/David Copperfield/page (943).png',
    'books/David Copperfield/page (944).png',
    'books/David Copperfield/page (945).png',
    'books/David Copperfield/page (946).png',
    'books/David Copperfield/page (947).png',
    'books/David Copperfield/page (948).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
