import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class derzuberberg extends StatefulWidget {
  const derzuberberg({Key? key}) : super(key: key);

  @override
  State<derzuberberg> createState() => _derzuberbergState();
}

class _derzuberbergState extends State<derzuberberg> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/Der Zuberberg/page (1).png',
    'books/Der Zuberberg/page (2).png',
    'books/Der Zuberberg/page (3).png',
    'books/Der Zuberberg/page (4).png',
    'books/Der Zuberberg/page (5).png',
    'books/Der Zuberberg/page (6).png',
    'books/Der Zuberberg/page (7).png',
    'books/Der Zuberberg/page (8).png',
    'books/Der Zuberberg/page (9).png',
    'books/Der Zuberberg/page (10).png',
    'books/Der Zuberberg/page (11).png',
    'books/Der Zuberberg/page (12).png',
    'books/Der Zuberberg/page (13).png',
    'books/Der Zuberberg/page (14).png',
    'books/Der Zuberberg/page (15).png',
    'books/Der Zuberberg/page (16).png',
    'books/Der Zuberberg/page (17).png',
    'books/Der Zuberberg/page (18).png',
    'books/Der Zuberberg/page (19).png',
    'books/Der Zuberberg/page (20).png',
    'books/Der Zuberberg/page (21).png',
    'books/Der Zuberberg/page (22).png',
    'books/Der Zuberberg/page (23).png',
    'books/Der Zuberberg/page (24).png',
    'books/Der Zuberberg/page (25).png',
    'books/Der Zuberberg/page (26).png',
    'books/Der Zuberberg/page (27).png',
    'books/Der Zuberberg/page (28).png',
    'books/Der Zuberberg/page (29).png',
    'books/Der Zuberberg/page (30).png',
    'books/Der Zuberberg/page (31).png',
    'books/Der Zuberberg/page (32).png',
    'books/Der Zuberberg/page (33).png',
    'books/Der Zuberberg/page (34).png',
    'books/Der Zuberberg/page (35).png',
    'books/Der Zuberberg/page (36).png',
    'books/Der Zuberberg/page (37).png',
    'books/Der Zuberberg/page (38).png',
    'books/Der Zuberberg/page (39).png',
    'books/Der Zuberberg/page (40).png',
    'books/Der Zuberberg/page (41).png',
    'books/Der Zuberberg/page (42).png',
    'books/Der Zuberberg/page (43).png',
    'books/Der Zuberberg/page (44).png',
    'books/Der Zuberberg/page (45).png',
    'books/Der Zuberberg/page (46).png',
    'books/Der Zuberberg/page (47).png',
    'books/Der Zuberberg/page (48).png',
    'books/Der Zuberberg/page (49).png',
    'books/Der Zuberberg/page (50).png',
    'books/Der Zuberberg/page (51).png',
    'books/Der Zuberberg/page (52).png',
    'books/Der Zuberberg/page (53).png',
    'books/Der Zuberberg/page (54).png',
    'books/Der Zuberberg/page (55).png',
    'books/Der Zuberberg/page (56).png',
    'books/Der Zuberberg/page (57).png',
    'books/Der Zuberberg/page (58).png',
    'books/Der Zuberberg/page (59).png',
    'books/Der Zuberberg/page (60).png',
    'books/Der Zuberberg/page (61).png',
    'books/Der Zuberberg/page (62).png',
    'books/Der Zuberberg/page (63).png',
    'books/Der Zuberberg/page (64).png',
    'books/Der Zuberberg/page (65).png',
    'books/Der Zuberberg/page (66).png',
    'books/Der Zuberberg/page (67).png',
    'books/Der Zuberberg/page (68).png',
    'books/Der Zuberberg/page (69).png',
    'books/Der Zuberberg/page (70).png',
    'books/Der Zuberberg/page (71).png',
    'books/Der Zuberberg/page (72).png',
    'books/Der Zuberberg/page (73).png',
    'books/Der Zuberberg/page (74).png',
    'books/Der Zuberberg/page (75).png',
    'books/Der Zuberberg/page (76).png',
    'books/Der Zuberberg/page (77).png',
    'books/Der Zuberberg/page (78).png',
    'books/Der Zuberberg/page (79).png',
    'books/Der Zuberberg/page (80).png',
    'books/Der Zuberberg/page (81).png',
    'books/Der Zuberberg/page (82).png',
    'books/Der Zuberberg/page (83).png',
    'books/Der Zuberberg/page (84).png',
    'books/Der Zuberberg/page (85).png',
    'books/Der Zuberberg/page (86).png',
    'books/Der Zuberberg/page (87).png',
    'books/Der Zuberberg/page (88).png',
    'books/Der Zuberberg/page (89).png',
    'books/Der Zuberberg/page (90).png',
    'books/Der Zuberberg/page (91).png',
    'books/Der Zuberberg/page (92).png',
    'books/Der Zuberberg/page (93).png',
    'books/Der Zuberberg/page (94).png',
    'books/Der Zuberberg/page (95).png',
    'books/Der Zuberberg/page (96).png',
    'books/Der Zuberberg/page (97).png',
    'books/Der Zuberberg/page (98).png',
    'books/Der Zuberberg/page (99).png',
    'books/Der Zuberberg/page (100).png',
    'books/Der Zuberberg/page (101).png',
    'books/Der Zuberberg/page (102).png',
    'books/Der Zuberberg/page (103).png',
    'books/Der Zuberberg/page (104).png',
    'books/Der Zuberberg/page (105).png',
    'books/Der Zuberberg/page (106).png',
    'books/Der Zuberberg/page (107).png',
    'books/Der Zuberberg/page (108).png',
    'books/Der Zuberberg/page (109).png',
    'books/Der Zuberberg/page (110).png',
    'books/Der Zuberberg/page (111).png',
    'books/Der Zuberberg/page (112).png',
    'books/Der Zuberberg/page (113).png',
    'books/Der Zuberberg/page (114).png',
    'books/Der Zuberberg/page (115).png',
    'books/Der Zuberberg/page (116).png',
    'books/Der Zuberberg/page (117).png',
    'books/Der Zuberberg/page (118).png',
    'books/Der Zuberberg/page (119).png',
    'books/Der Zuberberg/page (120).png',
    'books/Der Zuberberg/page (121).png',
    'books/Der Zuberberg/page (122).png',
    'books/Der Zuberberg/page (123).png',
    'books/Der Zuberberg/page (124).png',
    'books/Der Zuberberg/page (125).png',
    'books/Der Zuberberg/page (126).png',
    'books/Der Zuberberg/page (127).png',
    'books/Der Zuberberg/page (128).png',
    'books/Der Zuberberg/page (129).png',
    'books/Der Zuberberg/page (130).png',
    'books/Der Zuberberg/page (131).png',
    'books/Der Zuberberg/page (132).png',
    'books/Der Zuberberg/page (133).png',
    'books/Der Zuberberg/page (134).png',
    'books/Der Zuberberg/page (135).png',
    'books/Der Zuberberg/page (136).png',
    'books/Der Zuberberg/page (137).png',
    'books/Der Zuberberg/page (138).png',
    'books/Der Zuberberg/page (139).png',
    'books/Der Zuberberg/page (140).png',
    'books/Der Zuberberg/page (141).png',
    'books/Der Zuberberg/page (142).png',
    'books/Der Zuberberg/page (143).png',
    'books/Der Zuberberg/page (144).png',
    'books/Der Zuberberg/page (145).png',
    'books/Der Zuberberg/page (146).png',
    'books/Der Zuberberg/page (147).png',
    'books/Der Zuberberg/page (148).png',
    'books/Der Zuberberg/page (149).png',
    'books/Der Zuberberg/page (150).png',
    'books/Der Zuberberg/page (151).png',
    'books/Der Zuberberg/page (152).png',
    'books/Der Zuberberg/page (153).png',
    'books/Der Zuberberg/page (154).png',
    'books/Der Zuberberg/page (155).png',
    'books/Der Zuberberg/page (156).png',
    'books/Der Zuberberg/page (157).png',
    'books/Der Zuberberg/page (158).png',
    'books/Der Zuberberg/page (159).png',
    'books/Der Zuberberg/page (160).png',
    'books/Der Zuberberg/page (161).png',
    'books/Der Zuberberg/page (162).png',
    'books/Der Zuberberg/page (163).png',
    'books/Der Zuberberg/page (164).png',
    'books/Der Zuberberg/page (165).png',
    'books/Der Zuberberg/page (166).png',
    'books/Der Zuberberg/page (167).png',
    'books/Der Zuberberg/page (168).png',
    'books/Der Zuberberg/page (169).png',
    'books/Der Zuberberg/page (170).png',
    'books/Der Zuberberg/page (171).png',
    'books/Der Zuberberg/page (172).png',
    'books/Der Zuberberg/page (173).png',
    'books/Der Zuberberg/page (174).png',
    'books/Der Zuberberg/page (175).png',
    'books/Der Zuberberg/page (176).png',
    'books/Der Zuberberg/page (177).png',
    'books/Der Zuberberg/page (178).png',
    'books/Der Zuberberg/page (179).png',
    'books/Der Zuberberg/page (180).png',
    'books/Der Zuberberg/page (181).png',
    'books/Der Zuberberg/page (182).png',
    'books/Der Zuberberg/page (183).png',
    'books/Der Zuberberg/page (184).png',
    'books/Der Zuberberg/page (185).png',
    'books/Der Zuberberg/page (186).png',
    'books/Der Zuberberg/page (187).png',
    'books/Der Zuberberg/page (188).png',
    'books/Der Zuberberg/page (189).png',
    'books/Der Zuberberg/page (190).png',
    'books/Der Zuberberg/page (191).png',
    'books/Der Zuberberg/page (192).png',
    'books/Der Zuberberg/page (193).png',
    'books/Der Zuberberg/page (194).png',
    'books/Der Zuberberg/page (195).png',
    'books/Der Zuberberg/page (196).png',
    'books/Der Zuberberg/page (197).png',
    'books/Der Zuberberg/page (198).png',
    'books/Der Zuberberg/page (199).png',
    'books/Der Zuberberg/page (200).png',
    'books/Der Zuberberg/page (201).png',
    'books/Der Zuberberg/page (202).png',
    'books/Der Zuberberg/page (203).png',
    'books/Der Zuberberg/page (204).png',
    'books/Der Zuberberg/page (205).png',
    'books/Der Zuberberg/page (206).png',
    'books/Der Zuberberg/page (207).png',
    'books/Der Zuberberg/page (208).png',
    'books/Der Zuberberg/page (209).png',
    'books/Der Zuberberg/page (210).png',
    'books/Der Zuberberg/page (211).png',
    'books/Der Zuberberg/page (212).png',
    'books/Der Zuberberg/page (213).png',
    'books/Der Zuberberg/page (214).png',
    'books/Der Zuberberg/page (215).png',
    'books/Der Zuberberg/page (216).png',
    'books/Der Zuberberg/page (217).png',
    'books/Der Zuberberg/page (218).png',
    'books/Der Zuberberg/page (219).png',
    'books/Der Zuberberg/page (220).png',
    'books/Der Zuberberg/page (221).png',
    'books/Der Zuberberg/page (222).png',
    'books/Der Zuberberg/page (223).png',
    'books/Der Zuberberg/page (224).png',
    'books/Der Zuberberg/page (225).png',
    'books/Der Zuberberg/page (226).png',
    'books/Der Zuberberg/page (227).png',
    'books/Der Zuberberg/page (228).png',
    'books/Der Zuberberg/page (229).png',
    'books/Der Zuberberg/page (230).png',
    'books/Der Zuberberg/page (231).png',
    'books/Der Zuberberg/page (232).png',
    'books/Der Zuberberg/page (233).png',
    'books/Der Zuberberg/page (234).png',
    'books/Der Zuberberg/page (235).png',
    'books/Der Zuberberg/page (236).png',
    'books/Der Zuberberg/page (237).png',
    'books/Der Zuberberg/page (238).png',
    'books/Der Zuberberg/page (239).png',
    'books/Der Zuberberg/page (240).png',
    'books/Der Zuberberg/page (241).png',
    'books/Der Zuberberg/page (242).png',
    'books/Der Zuberberg/page (243).png',
    'books/Der Zuberberg/page (244).png',
    'books/Der Zuberberg/page (245).png',
    'books/Der Zuberberg/page (246).png',
    'books/Der Zuberberg/page (247).png',
    'books/Der Zuberberg/page (248).png',
    'books/Der Zuberberg/page (249).png',
    'books/Der Zuberberg/page (250).png',
    'books/Der Zuberberg/page (251).png',
    'books/Der Zuberberg/page (252).png',
    'books/Der Zuberberg/page (253).png',
    'books/Der Zuberberg/page (254).png',
    'books/Der Zuberberg/page (255).png',
    'books/Der Zuberberg/page (256).png',
    'books/Der Zuberberg/page (257).png',
    'books/Der Zuberberg/page (258).png',
    'books/Der Zuberberg/page (259).png',
    'books/Der Zuberberg/page (260).png',
    'books/Der Zuberberg/page (261).png',
    'books/Der Zuberberg/page (262).png',
    'books/Der Zuberberg/page (263).png',
    'books/Der Zuberberg/page (264).png',
    'books/Der Zuberberg/page (265).png',
    'books/Der Zuberberg/page (266).png',
    'books/Der Zuberberg/page (267).png',
    'books/Der Zuberberg/page (268).png',
    'books/Der Zuberberg/page (269).png',
    'books/Der Zuberberg/page (270).png',
    'books/Der Zuberberg/page (271).png',
    'books/Der Zuberberg/page (272).png',
    'books/Der Zuberberg/page (273).png',
    'books/Der Zuberberg/page (274).png',
    'books/Der Zuberberg/page (275).png',
    'books/Der Zuberberg/page (276).png',
    'books/Der Zuberberg/page (277).png',
    'books/Der Zuberberg/page (278).png',
    'books/Der Zuberberg/page (279).png',
    'books/Der Zuberberg/page (280).png',
    'books/Der Zuberberg/page (281).png',
    'books/Der Zuberberg/page (282).png',
    'books/Der Zuberberg/page (283).png',
    'books/Der Zuberberg/page (284).png',
    'books/Der Zuberberg/page (285).png',
    'books/Der Zuberberg/page (286).png',
    'books/Der Zuberberg/page (287).png',
    'books/Der Zuberberg/page (288).png',
    'books/Der Zuberberg/page (289).png',
    'books/Der Zuberberg/page (290).png',
    'books/Der Zuberberg/page (291).png',
    'books/Der Zuberberg/page (292).png',
    'books/Der Zuberberg/page (293).png',
    'books/Der Zuberberg/page (294).png',
    'books/Der Zuberberg/page (295).png',
    'books/Der Zuberberg/page (296).png',
    'books/Der Zuberberg/page (297).png',
    'books/Der Zuberberg/page (298).png',
    'books/Der Zuberberg/page (299).png',
    'books/Der Zuberberg/page (300).png',
    'books/Der Zuberberg/page (301).png',
    'books/Der Zuberberg/page (302).png',
    'books/Der Zuberberg/page (303).png',
    'books/Der Zuberberg/page (304).png',
    'books/Der Zuberberg/page (305).png',
    'books/Der Zuberberg/page (306).png',
    'books/Der Zuberberg/page (307).png',
    'books/Der Zuberberg/page (308).png',
    'books/Der Zuberberg/page (309).png',
    'books/Der Zuberberg/page (310).png',
    'books/Der Zuberberg/page (311).png',
    'books/Der Zuberberg/page (312).png',
    'books/Der Zuberberg/page (313).png',
    'books/Der Zuberberg/page (314).png',
    'books/Der Zuberberg/page (315).png',
    'books/Der Zuberberg/page (316).png',
    'books/Der Zuberberg/page (317).png',
    'books/Der Zuberberg/page (318).png',
    'books/Der Zuberberg/page (319).png',
    'books/Der Zuberberg/page (320).png',
    'books/Der Zuberberg/page (321).png',
    'books/Der Zuberberg/page (322).png',
    'books/Der Zuberberg/page (323).png',
    'books/Der Zuberberg/page (324).png',
    'books/Der Zuberberg/page (325).png',
    'books/Der Zuberberg/page (326).png',
    'books/Der Zuberberg/page (327).png',
    'books/Der Zuberberg/page (328).png',
    'books/Der Zuberberg/page (329).png',
    'books/Der Zuberberg/page (330).png',
    'books/Der Zuberberg/page (331).png',
    'books/Der Zuberberg/page (332).png',
    'books/Der Zuberberg/page (333).png',
    'books/Der Zuberberg/page (334).png',
    'books/Der Zuberberg/page (335).png',
    'books/Der Zuberberg/page (336).png',
    'books/Der Zuberberg/page (337).png',
    'books/Der Zuberberg/page (338).png',
    'books/Der Zuberberg/page (339).png',
    'books/Der Zuberberg/page (340).png',
    'books/Der Zuberberg/page (341).png',
    'books/Der Zuberberg/page (342).png',
    'books/Der Zuberberg/page (343).png',
    'books/Der Zuberberg/page (344).png',
    'books/Der Zuberberg/page (345).png',
    'books/Der Zuberberg/page (346).png',
    'books/Der Zuberberg/page (347).png',
    'books/Der Zuberberg/page (348).png',
    'books/Der Zuberberg/page (349).png',
    'books/Der Zuberberg/page (350).png',
    'books/Der Zuberberg/page (351).png',
    'books/Der Zuberberg/page (352).png',
    'books/Der Zuberberg/page (353).png',
    'books/Der Zuberberg/page (354).png',
    'books/Der Zuberberg/page (355).png',
    'books/Der Zuberberg/page (356).png',
    'books/Der Zuberberg/page (357).png',
    'books/Der Zuberberg/page (358).png',
    'books/Der Zuberberg/page (359).png',
    'books/Der Zuberberg/page (360).png',
    'books/Der Zuberberg/page (361).png',
    'books/Der Zuberberg/page (362).png',
    'books/Der Zuberberg/page (363).png',
    'books/Der Zuberberg/page (364).png',
    'books/Der Zuberberg/page (365).png',
    'books/Der Zuberberg/page (366).png',
    'books/Der Zuberberg/page (367).png',
    'books/Der Zuberberg/page (368).png',
    'books/Der Zuberberg/page (369).png',
    'books/Der Zuberberg/page (370).png',
    'books/Der Zuberberg/page (371).png',
    'books/Der Zuberberg/page (372).png',
    'books/Der Zuberberg/page (373).png',
    'books/Der Zuberberg/page (374).png',
    'books/Der Zuberberg/page (375).png',
    'books/Der Zuberberg/page (376).png',
    'books/Der Zuberberg/page (377).png',
    'books/Der Zuberberg/page (378).png',
    'books/Der Zuberberg/page (379).png',
    'books/Der Zuberberg/page (380).png',
    'books/Der Zuberberg/page (381).png',
    'books/Der Zuberberg/page (382).png',
    'books/Der Zuberberg/page (383).png',
    'books/Der Zuberberg/page (384).png',
    'books/Der Zuberberg/page (385).png',
    'books/Der Zuberberg/page (386).png',
    'books/Der Zuberberg/page (387).png',
    'books/Der Zuberberg/page (388).png',
    'books/Der Zuberberg/page (389).png',
    'books/Der Zuberberg/page (390).png',
    'books/Der Zuberberg/page (391).png',
    'books/Der Zuberberg/page (392).png',
    'books/Der Zuberberg/page (393).png',
    'books/Der Zuberberg/page (394).png',
    'books/Der Zuberberg/page (395).png',
    'books/Der Zuberberg/page (396).png',
    'books/Der Zuberberg/page (397).png',
    'books/Der Zuberberg/page (398).png',
    'books/Der Zuberberg/page (399).png',
    'books/Der Zuberberg/page (400).png',
    'books/Der Zuberberg/page (401).png',
    'books/Der Zuberberg/page (402).png',
    'books/Der Zuberberg/page (403).png',
    'books/Der Zuberberg/page (404).png',
    'books/Der Zuberberg/page (405).png',
    'books/Der Zuberberg/page (406).png',
    'books/Der Zuberberg/page (407).png',
    'books/Der Zuberberg/page (408).png',
    'books/Der Zuberberg/page (409).png',
    'books/Der Zuberberg/page (410).png',
    'books/Der Zuberberg/page (411).png',
    'books/Der Zuberberg/page (412).png',
    'books/Der Zuberberg/page (413).png',
    'books/Der Zuberberg/page (414).png',
    'books/Der Zuberberg/page (415).png',
    'books/Der Zuberberg/page (416).png',
    'books/Der Zuberberg/page (417).png',
    'books/Der Zuberberg/page (418).png',
    'books/Der Zuberberg/page (419).png',
    'books/Der Zuberberg/page (420).png',
    'books/Der Zuberberg/page (421).png',
    'books/Der Zuberberg/page (422).png',
    'books/Der Zuberberg/page (423).png',
    'books/Der Zuberberg/page (424).png',
    'books/Der Zuberberg/page (425).png',
    'books/Der Zuberberg/page (426).png',
    'books/Der Zuberberg/page (427).png',
    'books/Der Zuberberg/page (428).png',
    'books/Der Zuberberg/page (429).png',
    'books/Der Zuberberg/page (430).png',
    'books/Der Zuberberg/page (431).png',
    'books/Der Zuberberg/page (432).png',
    'books/Der Zuberberg/page (433).png',
    'books/Der Zuberberg/page (434).png',
    'books/Der Zuberberg/page (435).png',
    'books/Der Zuberberg/page (436).png',
    'books/Der Zuberberg/page (437).png',
    'books/Der Zuberberg/page (438).png',
    'books/Der Zuberberg/page (439).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
