import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class divinecomedy extends StatefulWidget {
  const divinecomedy({Key? key}) : super(key: key);

  @override
  State<divinecomedy> createState() => _divinecomedyState();
}

class _divinecomedyState extends State<divinecomedy> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/divine comedy/page (1).png',
    'books/divine comedy/page (2).png',
    'books/divine comedy/page (3).png',
    'books/divine comedy/page (4).png',
    'books/divine comedy/page (5).png',
    'books/divine comedy/page (6).png',
    'books/divine comedy/page (7).png',
    'books/divine comedy/page (8).png',
    'books/divine comedy/page (9).png',
    'books/divine comedy/page (10).png',
    'books/divine comedy/page (11).png',
    'books/divine comedy/page (12).png',
    'books/divine comedy/page (13).png',
    'books/divine comedy/page (14).png',
    'books/divine comedy/page (15).png',
    'books/divine comedy/page (16).png',
    'books/divine comedy/page (17).png',
    'books/divine comedy/page (18).png',
    'books/divine comedy/page (19).png',
    'books/divine comedy/page (20).png',
    'books/divine comedy/page (21).png',
    'books/divine comedy/page (22).png',
    'books/divine comedy/page (23).png',
    'books/divine comedy/page (24).png',
    'books/divine comedy/page (25).png',
    'books/divine comedy/page (26).png',
    'books/divine comedy/page (27).png',
    'books/divine comedy/page (28).png',
    'books/divine comedy/page (29).png',
    'books/divine comedy/page (30).png',
    'books/divine comedy/page (31).png',
    'books/divine comedy/page (32).png',
    'books/divine comedy/page (33).png',
    'books/divine comedy/page (34).png',
    'books/divine comedy/page (35).png',
    'books/divine comedy/page (36).png',
    'books/divine comedy/page (37).png',
    'books/divine comedy/page (38).png',
    'books/divine comedy/page (39).png',
    'books/divine comedy/page (40).png',
    'books/divine comedy/page (41).png',
    'books/divine comedy/page (42).png',
    'books/divine comedy/page (43).png',
    'books/divine comedy/page (44).png',
    'books/divine comedy/page (45).png',
    'books/divine comedy/page (46).png',
    'books/divine comedy/page (47).png',
    'books/divine comedy/page (48).png',
    'books/divine comedy/page (49).png',
    'books/divine comedy/page (50).png',
    'books/divine comedy/page (51).png',
    'books/divine comedy/page (52).png',
    'books/divine comedy/page (53).png',
    'books/divine comedy/page (54).png',
    'books/divine comedy/page (55).png',
    'books/divine comedy/page (56).png',
    'books/divine comedy/page (57).png',
    'books/divine comedy/page (58).png',
    'books/divine comedy/page (59).png',
    'books/divine comedy/page (60).png',
    'books/divine comedy/page (61).png',
    'books/divine comedy/page (62).png',
    'books/divine comedy/page (63).png',
    'books/divine comedy/page (64).png',
    'books/divine comedy/page (65).png',
    'books/divine comedy/page (66).png',
    'books/divine comedy/page (67).png',
    'books/divine comedy/page (68).png',
    'books/divine comedy/page (69).png',
    'books/divine comedy/page (70).png',
    'books/divine comedy/page (71).png',
    'books/divine comedy/page (72).png',
    'books/divine comedy/page (73).png',
    'books/divine comedy/page (74).png',
    'books/divine comedy/page (75).png',
    'books/divine comedy/page (76).png',
    'books/divine comedy/page (77).png',
    'books/divine comedy/page (78).png',
    'books/divine comedy/page (79).png',
    'books/divine comedy/page (80).png',
    'books/divine comedy/page (81).png',
    'books/divine comedy/page (82).png',
    'books/divine comedy/page (83).png',
    'books/divine comedy/page (84).png',
    'books/divine comedy/page (85).png',
    'books/divine comedy/page (86).png',
    'books/divine comedy/page (87).png',
    'books/divine comedy/page (88).png',
    'books/divine comedy/page (89).png',
    'books/divine comedy/page (90).png',
    'books/divine comedy/page (91).png',
    'books/divine comedy/page (92).png',
    'books/divine comedy/page (93).png',
    'books/divine comedy/page (94).png',
    'books/divine comedy/page (95).png',
    'books/divine comedy/page (96).png',
    'books/divine comedy/page (97).png',
    'books/divine comedy/page (98).png',
    'books/divine comedy/page (99).png',
    'books/divine comedy/page (100).png',
    'books/divine comedy/page (101).png',
    'books/divine comedy/page (102).png',
    'books/divine comedy/page (103).png',
    'books/divine comedy/page (104).png',
    'books/divine comedy/page (105).png',
    'books/divine comedy/page (106).png',
    'books/divine comedy/page (107).png',
    'books/divine comedy/page (108).png',
    'books/divine comedy/page (109).png',
    'books/divine comedy/page (110).png',
    'books/divine comedy/page (111).png',
    'books/divine comedy/page (112).png',
    'books/divine comedy/page (113).png',
    'books/divine comedy/page (114).png',
    'books/divine comedy/page (115).png',
    'books/divine comedy/page (116).png',
    'books/divine comedy/page (117).png',
    'books/divine comedy/page (118).png',
    'books/divine comedy/page (119).png',
    'books/divine comedy/page (120).png',
    'books/divine comedy/page (121).png',
    'books/divine comedy/page (122).png',
    'books/divine comedy/page (123).png',
    'books/divine comedy/page (124).png',
    'books/divine comedy/page (125).png',
    'books/divine comedy/page (126).png',
    'books/divine comedy/page (127).png',
    'books/divine comedy/page (128).png',
    'books/divine comedy/page (129).png',
    'books/divine comedy/page (130).png',
    'books/divine comedy/page (131).png',
    'books/divine comedy/page (132).png',
    'books/divine comedy/page (133).png',
    'books/divine comedy/page (134).png',
    'books/divine comedy/page (135).png',
    'books/divine comedy/page (136).png',
    'books/divine comedy/page (137).png',
    'books/divine comedy/page (138).png',
    'books/divine comedy/page (139).png',
    'books/divine comedy/page (140).png',
    'books/divine comedy/page (141).png',
    'books/divine comedy/page (142).png',
    'books/divine comedy/page (143).png',
    'books/divine comedy/page (144).png',
    'books/divine comedy/page (145).png',
    'books/divine comedy/page (146).png',
    'books/divine comedy/page (147).png',
    'books/divine comedy/page (148).png',
    'books/divine comedy/page (149).png',
    'books/divine comedy/page (150).png',
    'books/divine comedy/page (151).png',
    'books/divine comedy/page (152).png',
    'books/divine comedy/page (153).png',
    'books/divine comedy/page (154).png',
    'books/divine comedy/page (155).png',
    'books/divine comedy/page (156).png',
    'books/divine comedy/page (157).png',
    'books/divine comedy/page (158).png',
    'books/divine comedy/page (159).png',
    'books/divine comedy/page (160).png',
    'books/divine comedy/page (161).png',
    'books/divine comedy/page (162).png',
    'books/divine comedy/page (163).png',
    'books/divine comedy/page (164).png',
    'books/divine comedy/page (165).png',
    'books/divine comedy/page (166).png',
    'books/divine comedy/page (167).png',
    'books/divine comedy/page (168).png',
    'books/divine comedy/page (169).png',
    'books/divine comedy/page (170).png',
    'books/divine comedy/page (171).png',
    'books/divine comedy/page (172).png',
    'books/divine comedy/page (173).png',
    'books/divine comedy/page (174).png',
    'books/divine comedy/page (175).png',
    'books/divine comedy/page (176).png',
    'books/divine comedy/page (177).png',
    'books/divine comedy/page (178).png',
    'books/divine comedy/page (179).png',
    'books/divine comedy/page (180).png',
    'books/divine comedy/page (181).png',
    'books/divine comedy/page (182).png',
    'books/divine comedy/page (183).png',
    'books/divine comedy/page (184).png',
    'books/divine comedy/page (185).png',
    'books/divine comedy/page (186).png',
    'books/divine comedy/page (187).png',
    'books/divine comedy/page (188).png',
    'books/divine comedy/page (189).png',
    'books/divine comedy/page (190).png',
    'books/divine comedy/page (191).png',
    'books/divine comedy/page (192).png',
    'books/divine comedy/page (193).png',
    'books/divine comedy/page (194).png',
    'books/divine comedy/page (195).png',
    'books/divine comedy/page (196).png',
    'books/divine comedy/page (197).png',
    'books/divine comedy/page (198).png',
    'books/divine comedy/page (199).png',
    'books/divine comedy/page (200).png',
    'books/divine comedy/page (201).png',
    'books/divine comedy/page (202).png',
    'books/divine comedy/page (203).png',
    'books/divine comedy/page (204).png',
    'books/divine comedy/page (205).png',
    'books/divine comedy/page (206).png',
    'books/divine comedy/page (207).png',
    'books/divine comedy/page (208).png',
    'books/divine comedy/page (209).png',
    'books/divine comedy/page (210).png',
    'books/divine comedy/page (211).png',
    'books/divine comedy/page (212).png',
    'books/divine comedy/page (213).png',
    'books/divine comedy/page (214).png',
    'books/divine comedy/page (215).png',
    'books/divine comedy/page (216).png',
    'books/divine comedy/page (217).png',
    'books/divine comedy/page (218).png',
    'books/divine comedy/page (219).png',
    'books/divine comedy/page (220).png',
    'books/divine comedy/page (221).png',
    'books/divine comedy/page (222).png',
    'books/divine comedy/page (223).png',
    'books/divine comedy/page (224).png',
    'books/divine comedy/page (225).png',
    'books/divine comedy/page (226).png',
    'books/divine comedy/page (227).png',
    'books/divine comedy/page (228).png',
    'books/divine comedy/page (229).png',
    'books/divine comedy/page (230).png',
    'books/divine comedy/page (231).png',
    'books/divine comedy/page (232).png',
    'books/divine comedy/page (233).png',
    'books/divine comedy/page (234).png',
    'books/divine comedy/page (235).png',
    'books/divine comedy/page (236).png',
    'books/divine comedy/page (237).png',
    'books/divine comedy/page (238).png',
    'books/divine comedy/page (239).png',
    'books/divine comedy/page (240).png',
    'books/divine comedy/page (241).png',
    'books/divine comedy/page (242).png',
    'books/divine comedy/page (243).png',
    'books/divine comedy/page (244).png',
    'books/divine comedy/page (245).png',
    'books/divine comedy/page (246).png',
    'books/divine comedy/page (247).png',
    'books/divine comedy/page (248).png',
    'books/divine comedy/page (249).png',
    'books/divine comedy/page (250).png',
    'books/divine comedy/page (251).png',
    'books/divine comedy/page (252).png',
    'books/divine comedy/page (253).png',
    'books/divine comedy/page (254).png',
    'books/divine comedy/page (255).png',
    'books/divine comedy/page (256).png',
    'books/divine comedy/page (257).png',
    'books/divine comedy/page (258).png',
    'books/divine comedy/page (259).png',
    'books/divine comedy/page (260).png',
    'books/divine comedy/page (261).png',
    'books/divine comedy/page (262).png',
    'books/divine comedy/page (263).png',
    'books/divine comedy/page (264).png',
    'books/divine comedy/page (265).png',
    'books/divine comedy/page (266).png',
    'books/divine comedy/page (267).png',
    'books/divine comedy/page (268).png',
    'books/divine comedy/page (269).png',
    'books/divine comedy/page (270).png',
    'books/divine comedy/page (271).png',
    'books/divine comedy/page (272).png',
    'books/divine comedy/page (273).png',
    'books/divine comedy/page (274).png',
    'books/divine comedy/page (275).png',
    'books/divine comedy/page (276).png',
    'books/divine comedy/page (277).png',
    'books/divine comedy/page (278).png',
    'books/divine comedy/page (279).png',
    'books/divine comedy/page (280).png',
    'books/divine comedy/page (281).png',
    'books/divine comedy/page (282).png',
    'books/divine comedy/page (283).png',
    'books/divine comedy/page (284).png',
    'books/divine comedy/page (285).png',
    'books/divine comedy/page (286).png',
    'books/divine comedy/page (287).png',
    'books/divine comedy/page (288).png',
    'books/divine comedy/page (289).png',
    'books/divine comedy/page (290).png',
    'books/divine comedy/page (291).png',
    'books/divine comedy/page (292).png',
    'books/divine comedy/page (293).png',
    'books/divine comedy/page (294).png',
    'books/divine comedy/page (295).png',
    'books/divine comedy/page (296).png',
    'books/divine comedy/page (297).png',
    'books/divine comedy/page (298).png',
    'books/divine comedy/page (299).png',
    'books/divine comedy/page (300).png',
    'books/divine comedy/page (301).png',
    'books/divine comedy/page (302).png',
    'books/divine comedy/page (303).png',
    'books/divine comedy/page (304).png',
    'books/divine comedy/page (305).png',
    'books/divine comedy/page (306).png',
    'books/divine comedy/page (307).png',
    'books/divine comedy/page (308).png',
    'books/divine comedy/page (309).png',
    'books/divine comedy/page (310).png',
    'books/divine comedy/page (311).png',
    'books/divine comedy/page (312).png',
    'books/divine comedy/page (313).png',
    'books/divine comedy/page (314).png',
    'books/divine comedy/page (315).png',
    'books/divine comedy/page (316).png',
    'books/divine comedy/page (317).png',
    'books/divine comedy/page (318).png',
    'books/divine comedy/page (319).png',
    'books/divine comedy/page (320).png',
    'books/divine comedy/page (321).png',
    'books/divine comedy/page (322).png',
    'books/divine comedy/page (323).png',
    'books/divine comedy/page (324).png',
    'books/divine comedy/page (325).png',
    'books/divine comedy/page (326).png',
    'books/divine comedy/page (327).png',
    'books/divine comedy/page (328).png',
    'books/divine comedy/page (329).png',
    'books/divine comedy/page (330).png',
    'books/divine comedy/page (331).png',
    'books/divine comedy/page (332).png',
    'books/divine comedy/page (333).png',
    'books/divine comedy/page (334).png',
    'books/divine comedy/page (335).png',
    'books/divine comedy/page (336).png',
    'books/divine comedy/page (337).png',
    'books/divine comedy/page (338).png',
    'books/divine comedy/page (339).png',
    'books/divine comedy/page (340).png',
    'books/divine comedy/page (341).png',
    'books/divine comedy/page (342).png',
    'books/divine comedy/page (343).png',
    'books/divine comedy/page (344).png',
    'books/divine comedy/page (345).png',
    'books/divine comedy/page (346).png',
    'books/divine comedy/page (347).png',
    'books/divine comedy/page (348).png',
    'books/divine comedy/page (349).png',
    'books/divine comedy/page (350).png',
    'books/divine comedy/page (351).png',
    'books/divine comedy/page (352).png',
    'books/divine comedy/page (353).png',
    'books/divine comedy/page (354).png',
    'books/divine comedy/page (355).png',
    'books/divine comedy/page (356).png',
    'books/divine comedy/page (357).png',
    'books/divine comedy/page (358).png',
    'books/divine comedy/page (359).png',
    'books/divine comedy/page (360).png',
    'books/divine comedy/page (361).png',
    'books/divine comedy/page (362).png',
    'books/divine comedy/page (363).png',
    'books/divine comedy/page (364).png',
    'books/divine comedy/page (365).png',
    'books/divine comedy/page (366).png',
    'books/divine comedy/page (367).png',
    'books/divine comedy/page (368).png',
    'books/divine comedy/page (369).png',
    'books/divine comedy/page (370).png',
    'books/divine comedy/page (371).png',
    'books/divine comedy/page (372).png',
    'books/divine comedy/page (373).png',
    'books/divine comedy/page (374).png',
    'books/divine comedy/page (375).png',
    'books/divine comedy/page (376).png',
    'books/divine comedy/page (377).png',
    'books/divine comedy/page (378).png',
    'books/divine comedy/page (379).png',
    'books/divine comedy/page (380).png',
    'books/divine comedy/page (381).png',
    'books/divine comedy/page (382).png',
    'books/divine comedy/page (383).png',
    'books/divine comedy/page (384).png',
    'books/divine comedy/page (385).png',
    'books/divine comedy/page (386).png',
    'books/divine comedy/page (387).png',
    'books/divine comedy/page (388).png',
    'books/divine comedy/page (389).png',
    'books/divine comedy/page (390).png',
    'books/divine comedy/page (391).png',
    'books/divine comedy/page (392).png',
    'books/divine comedy/page (393).png',
    'books/divine comedy/page (394).png',
    'books/divine comedy/page (395).png',
    'books/divine comedy/page (396).png',
    'books/divine comedy/page (397).png',
    'books/divine comedy/page (398).png',
    'books/divine comedy/page (399).png',
    'books/divine comedy/page (400).png',
    'books/divine comedy/page (401).png',
    'books/divine comedy/page (402).png',
    'books/divine comedy/page (403).png',
    'books/divine comedy/page (404).png',
    'books/divine comedy/page (405).png',
    'books/divine comedy/page (406).png',
    'books/divine comedy/page (407).png',
    'books/divine comedy/page (408).png',
    'books/divine comedy/page (409).png',
    'books/divine comedy/page (410).png',
    'books/divine comedy/page (411).png',
    'books/divine comedy/page (412).png',
    'books/divine comedy/page (413).png',
    'books/divine comedy/page (414).png',
    'books/divine comedy/page (415).png',
    'books/divine comedy/page (416).png',
    'books/divine comedy/page (417).png',
    'books/divine comedy/page (418).png',
    'books/divine comedy/page (419).png',
    'books/divine comedy/page (420).png',
    'books/divine comedy/page (421).png',
    'books/divine comedy/page (422).png',
    'books/divine comedy/page (423).png',
    'books/divine comedy/page (424).png',
    'books/divine comedy/page (425).png',
    'books/divine comedy/page (426).png',
    'books/divine comedy/page (427).png',
    'books/divine comedy/page (428).png',
    'books/divine comedy/page (429).png',
    'books/divine comedy/page (430).png',
    'books/divine comedy/page (431).png',
    'books/divine comedy/page (432).png',
    'books/divine comedy/page (433).png',
    'books/divine comedy/page (434).png',
    'books/divine comedy/page (435).png',
    'books/divine comedy/page (436).png',
    'books/divine comedy/page (437).png',
    'books/divine comedy/page (438).png',
    'books/divine comedy/page (439).png',
    'books/divine comedy/page (440).png',
    'books/divine comedy/page (441).png',
    'books/divine comedy/page (442).png',
    'books/divine comedy/page (443).png',
    'books/divine comedy/page (444).png',
    'books/divine comedy/page (445).png',
    'books/divine comedy/page (446).png',
    'books/divine comedy/page (447).png',
    'books/divine comedy/page (448).png',
    'books/divine comedy/page (449).png',
    'books/divine comedy/page (450).png',
    'books/divine comedy/page (451).png',
    'books/divine comedy/page (452).png',
    'books/divine comedy/page (453).png',
    'books/divine comedy/page (454).png',
    'books/divine comedy/page (455).png',
    'books/divine comedy/page (456).png',
    'books/divine comedy/page (457).png',
    'books/divine comedy/page (458).png',
    'books/divine comedy/page (459).png',
    'books/divine comedy/page (460).png',
    'books/divine comedy/page (461).png',
    'books/divine comedy/page (462).png',
    'books/divine comedy/page (463).png',
    'books/divine comedy/page (464).png',
    'books/divine comedy/page (465).png',
    'books/divine comedy/page (466).png',
    'books/divine comedy/page (467).png',
    'books/divine comedy/page (468).png',
    'books/divine comedy/page (469).png',
    'books/divine comedy/page (470).png',
    'books/divine comedy/page (471).png',
    'books/divine comedy/page (472).png',
    'books/divine comedy/page (473).png',
    'books/divine comedy/page (474).png',
    'books/divine comedy/page (475).png',
    'books/divine comedy/page (476).png',
    'books/divine comedy/page (477).png',
    'books/divine comedy/page (478).png',
    'books/divine comedy/page (479).png',
    'books/divine comedy/page (480).png',
    'books/divine comedy/page (481).png',
    'books/divine comedy/page (482).png',
    'books/divine comedy/page (483).png',
    'books/divine comedy/page (484).png',
    'books/divine comedy/page (485).png',
    'books/divine comedy/page (486).png',
    'books/divine comedy/page (487).png',
    'books/divine comedy/page (488).png',
    'books/divine comedy/page (489).png',
    'books/divine comedy/page (490).png',
    'books/divine comedy/page (491).png',
    'books/divine comedy/page (492).png',
    'books/divine comedy/page (493).png',
    'books/divine comedy/page (494).png',
    'books/divine comedy/page (495).png',
    'books/divine comedy/page (496).png',
    'books/divine comedy/page (497).png',
    'books/divine comedy/page (498).png',
    'books/divine comedy/page (499).png',
    'books/divine comedy/page (500).png',
    'books/divine comedy/page (501).png',
    'books/divine comedy/page (502).png',
    'books/divine comedy/page (503).png',
    'books/divine comedy/page (504).png',
    'books/divine comedy/page (505).png',
    'books/divine comedy/page (506).png',
    'books/divine comedy/page (507).png',
    'books/divine comedy/page (508).png',
    'books/divine comedy/page (509).png',
    'books/divine comedy/page (510).png',
    'books/divine comedy/page (511).png',
    'books/divine comedy/page (512).png',
    'books/divine comedy/page (513).png',
    'books/divine comedy/page (514).png',
    'books/divine comedy/page (515).png',
    'books/divine comedy/page (516).png',
    'books/divine comedy/page (517).png',
    'books/divine comedy/page (518).png',
    'books/divine comedy/page (519).png',
    'books/divine comedy/page (520).png',
    'books/divine comedy/page (521).png',
    'books/divine comedy/page (522).png',
    'books/divine comedy/page (523).png',
    'books/divine comedy/page (524).png',
    'books/divine comedy/page (525).png',
    'books/divine comedy/page (526).png',
    'books/divine comedy/page (527).png',
    'books/divine comedy/page (528).png',
    'books/divine comedy/page (529).png',
    'books/divine comedy/page (530).png',
    'books/divine comedy/page (531).png',
    'books/divine comedy/page (532).png',
    'books/divine comedy/page (533).png',
    'books/divine comedy/page (534).png',
    'books/divine comedy/page (535).png',
    'books/divine comedy/page (536).png',
    'books/divine comedy/page (537).png',
    'books/divine comedy/page (538).png',
    'books/divine comedy/page (539).png',
    'books/divine comedy/page (540).png',
    'books/divine comedy/page (541).png',
    'books/divine comedy/page (542).png',
    'books/divine comedy/page (543).png',
    'books/divine comedy/page (544).png',
    'books/divine comedy/page (545).png',
    'books/divine comedy/page (546).png',
    'books/divine comedy/page (547).png',
    'books/divine comedy/page (548).png',
    'books/divine comedy/page (549).png',
    'books/divine comedy/page (550).png',
    'books/divine comedy/page (551).png',
    'books/divine comedy/page (552).png',
    'books/divine comedy/page (553).png',
    'books/divine comedy/page (554).png',
    'books/divine comedy/page (555).png',
    'books/divine comedy/page (556).png',
    'books/divine comedy/page (557).png',
    'books/divine comedy/page (558).png',
    'books/divine comedy/page (559).png',
    'books/divine comedy/page (560).png',
    'books/divine comedy/page (561).png',
    'books/divine comedy/page (562).png',
    'books/divine comedy/page (563).png',
    'books/divine comedy/page (564).png',
    'books/divine comedy/page (565).png',
    'books/divine comedy/page (566).png',
    'books/divine comedy/page (567).png',
    'books/divine comedy/page (568).png',
    'books/divine comedy/page (569).png',
    'books/divine comedy/page (570).png',
    'books/divine comedy/page (571).png',
    'books/divine comedy/page (572).png',
    'books/divine comedy/page (573).png',
    'books/divine comedy/page (574).png',
    'books/divine comedy/page (575).png',
    'books/divine comedy/page (576).png',
    'books/divine comedy/page (577).png',
    'books/divine comedy/page (578).png',
    'books/divine comedy/page (579).png',
    'books/divine comedy/page (580).png',
    'books/divine comedy/page (581).png',
    'books/divine comedy/page (582).png',
    'books/divine comedy/page (583).png',
    'books/divine comedy/page (584).png',
    'books/divine comedy/page (585).png',
    'books/divine comedy/page (586).png',
    'books/divine comedy/page (587).png',
    'books/divine comedy/page (588).png',
    'books/divine comedy/page (589).png',
    'books/divine comedy/page (590).png',
    'books/divine comedy/page (591).png',
    'books/divine comedy/page (592).png',
    'books/divine comedy/page (593).png',
    'books/divine comedy/page (594).png',
    'books/divine comedy/page (595).png',
    'books/divine comedy/page (596).png',
    'books/divine comedy/page (597).png',
    'books/divine comedy/page (598).png',
    'books/divine comedy/page (599).png',
    'books/divine comedy/page (600).png',
    'books/divine comedy/page (601).png',
    'books/divine comedy/page (602).png',
    'books/divine comedy/page (603).png',
    'books/divine comedy/page (604).png',
    'books/divine comedy/page (605).png',
    'books/divine comedy/page (606).png',
    'books/divine comedy/page (607).png',
    'books/divine comedy/page (608).png',
    'books/divine comedy/page (609).png',
    'books/divine comedy/page (610).png',
    'books/divine comedy/page (611).png',
    'books/divine comedy/page (612).png',
    'books/divine comedy/page (613).png',
    'books/divine comedy/page (614).png',
    'books/divine comedy/page (615).png',
    'books/divine comedy/page (616).png',
    'books/divine comedy/page (617).png',
    'books/divine comedy/page (618).png',
    'books/divine comedy/page (619).png',
    'books/divine comedy/page (620).png',
    'books/divine comedy/page (621).png',
    'books/divine comedy/page (622).png',
    'books/divine comedy/page (623).png',
    'books/divine comedy/page (624).png',
    'books/divine comedy/page (625).png',
    'books/divine comedy/page (626).png',
    'books/divine comedy/page (627).png',
    'books/divine comedy/page (628).png',
    'books/divine comedy/page (629).png',
    'books/divine comedy/page (630).png',
    'books/divine comedy/page (631).png',
    'books/divine comedy/page (632).png',
    'books/divine comedy/page (633).png',
    'books/divine comedy/page (634).png',
    'books/divine comedy/page (635).png',
    'books/divine comedy/page (636).png',
    'books/divine comedy/page (637).png',
    'books/divine comedy/page (638).png',
    'books/divine comedy/page (639).png',
    'books/divine comedy/page (640).png',
    'books/divine comedy/page (641).png',
    'books/divine comedy/page (642).png',
    'books/divine comedy/page (643).png',
    'books/divine comedy/page (644).png',
    'books/divine comedy/page (645).png',
    'books/divine comedy/page (646).png',
    'books/divine comedy/page (647).png',
    'books/divine comedy/page (648).png',
    'books/divine comedy/page (649).png',
    'books/divine comedy/page (650).png',
    'books/divine comedy/page (651).png',
    'books/divine comedy/page (652).png',
    'books/divine comedy/page (653).png',
    'books/divine comedy/page (654).png',
    'books/divine comedy/page (655).png',
    'books/divine comedy/page (656).png',
    'books/divine comedy/page (657).png',
    'books/divine comedy/page (658).png',
    'books/divine comedy/page (659).png',
    'books/divine comedy/page (660).png',
    'books/divine comedy/page (661).png',
    'books/divine comedy/page (662).png',
    'books/divine comedy/page (663).png',
    'books/divine comedy/page (664).png',
    'books/divine comedy/page (665).png',
    'books/divine comedy/page (666).png',
    'books/divine comedy/page (667).png',
    'books/divine comedy/page (668).png',
    'books/divine comedy/page (669).png',
    'books/divine comedy/page (670).png',
    'books/divine comedy/page (671).png',
    'books/divine comedy/page (672).png',
    'books/divine comedy/page (673).png',
    'books/divine comedy/page (674).png',
    'books/divine comedy/page (675).png',
    'books/divine comedy/page (676).png',
    'books/divine comedy/page (677).png',
    'books/divine comedy/page (678).png',
    'books/divine comedy/page (679).png',
    'books/divine comedy/page (680).png',
    'books/divine comedy/page (681).png',
    'books/divine comedy/page (682).png',
    'books/divine comedy/page (683).png',
    'books/divine comedy/page (684).png',
    'books/divine comedy/page (685).png',
    'books/divine comedy/page (686).png',
    'books/divine comedy/page (687).png',
    'books/divine comedy/page (688).png',
    'books/divine comedy/page (689).png',
    'books/divine comedy/page (690).png',
    'books/divine comedy/page (691).png',
    'books/divine comedy/page (692).png',
    'books/divine comedy/page (693).png',
    'books/divine comedy/page (694).png',
    'books/divine comedy/page (695).png',
    'books/divine comedy/page (696).png',
    'books/divine comedy/page (697).png',
    'books/divine comedy/page (698).png',
    'books/divine comedy/page (699).png',
    'books/divine comedy/page (700).png',
    'books/divine comedy/page (701).png',
    'books/divine comedy/page (702).png',
    'books/divine comedy/page (703).png',
    'books/divine comedy/page (704).png',
    'books/divine comedy/page (705).png',
    'books/divine comedy/page (706).png',
    'books/divine comedy/page (707).png',
    'books/divine comedy/page (708).png',
    'books/divine comedy/page (709).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
