import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class dombeyandson extends StatefulWidget {
  const dombeyandson({Key? key}) : super(key: key);

  @override
  State<dombeyandson> createState() => _dombeyandsonState();
}

class _dombeyandsonState extends State<dombeyandson> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/Dombey and Son/page (1).png',
    'books/Dombey and Son/page (2).png',
    'books/Dombey and Son/page (3).png',
    'books/Dombey and Son/page (4).png',
    'books/Dombey and Son/page (5).png',
    'books/Dombey and Son/page (6).png',
    'books/Dombey and Son/page (7).png',
    'books/Dombey and Son/page (8).png',
    'books/Dombey and Son/page (9).png',
    'books/Dombey and Son/page (10).png',
    'books/Dombey and Son/page (11).png',
    'books/Dombey and Son/page (12).png',
    'books/Dombey and Son/page (13).png',
    'books/Dombey and Son/page (14).png',
    'books/Dombey and Son/page (15).png',
    'books/Dombey and Son/page (16).png',
    'books/Dombey and Son/page (17).png',
    'books/Dombey and Son/page (18).png',
    'books/Dombey and Son/page (19).png',
    'books/Dombey and Son/page (20).png',
    'books/Dombey and Son/page (21).png',
    'books/Dombey and Son/page (22).png',
    'books/Dombey and Son/page (23).png',
    'books/Dombey and Son/page (24).png',
    'books/Dombey and Son/page (25).png',
    'books/Dombey and Son/page (26).png',
    'books/Dombey and Son/page (27).png',
    'books/Dombey and Son/page (28).png',
    'books/Dombey and Son/page (29).png',
    'books/Dombey and Son/page (30).png',
    'books/Dombey and Son/page (31).png',
    'books/Dombey and Son/page (32).png',
    'books/Dombey and Son/page (33).png',
    'books/Dombey and Son/page (34).png',
    'books/Dombey and Son/page (35).png',
    'books/Dombey and Son/page (36).png',
    'books/Dombey and Son/page (37).png',
    'books/Dombey and Son/page (38).png',
    'books/Dombey and Son/page (39).png',
    'books/Dombey and Son/page (40).png',
    'books/Dombey and Son/page (41).png',
    'books/Dombey and Son/page (42).png',
    'books/Dombey and Son/page (43).png',
    'books/Dombey and Son/page (44).png',
    'books/Dombey and Son/page (45).png',
    'books/Dombey and Son/page (46).png',
    'books/Dombey and Son/page (47).png',
    'books/Dombey and Son/page (48).png',
    'books/Dombey and Son/page (49).png',
    'books/Dombey and Son/page (50).png',
    'books/Dombey and Son/page (51).png',
    'books/Dombey and Son/page (52).png',
    'books/Dombey and Son/page (53).png',
    'books/Dombey and Son/page (54).png',
    'books/Dombey and Son/page (55).png',
    'books/Dombey and Son/page (56).png',
    'books/Dombey and Son/page (57).png',
    'books/Dombey and Son/page (58).png',
    'books/Dombey and Son/page (59).png',
    'books/Dombey and Son/page (60).png',
    'books/Dombey and Son/page (61).png',
    'books/Dombey and Son/page (62).png',
    'books/Dombey and Son/page (63).png',
    'books/Dombey and Son/page (64).png',
    'books/Dombey and Son/page (65).png',
    'books/Dombey and Son/page (66).png',
    'books/Dombey and Son/page (67).png',
    'books/Dombey and Son/page (68).png',
    'books/Dombey and Son/page (69).png',
    'books/Dombey and Son/page (70).png',
    'books/Dombey and Son/page (71).png',
    'books/Dombey and Son/page (72).png',
    'books/Dombey and Son/page (73).png',
    'books/Dombey and Son/page (74).png',
    'books/Dombey and Son/page (75).png',
    'books/Dombey and Son/page (76).png',
    'books/Dombey and Son/page (77).png',
    'books/Dombey and Son/page (78).png',
    'books/Dombey and Son/page (79).png',
    'books/Dombey and Son/page (80).png',
    'books/Dombey and Son/page (81).png',
    'books/Dombey and Son/page (82).png',
    'books/Dombey and Son/page (83).png',
    'books/Dombey and Son/page (84).png',
    'books/Dombey and Son/page (85).png',
    'books/Dombey and Son/page (86).png',
    'books/Dombey and Son/page (87).png',
    'books/Dombey and Son/page (88).png',
    'books/Dombey and Son/page (89).png',
    'books/Dombey and Son/page (90).png',
    'books/Dombey and Son/page (91).png',
    'books/Dombey and Son/page (92).png',
    'books/Dombey and Son/page (93).png',
    'books/Dombey and Son/page (94).png',
    'books/Dombey and Son/page (95).png',
    'books/Dombey and Son/page (96).png',
    'books/Dombey and Son/page (97).png',
    'books/Dombey and Son/page (98).png',
    'books/Dombey and Son/page (99).png',
    'books/Dombey and Son/page (100).png',
    'books/Dombey and Son/page (101).png',
    'books/Dombey and Son/page (102).png',
    'books/Dombey and Son/page (103).png',
    'books/Dombey and Son/page (104).png',
    'books/Dombey and Son/page (105).png',
    'books/Dombey and Son/page (106).png',
    'books/Dombey and Son/page (107).png',
    'books/Dombey and Son/page (108).png',
    'books/Dombey and Son/page (109).png',
    'books/Dombey and Son/page (110).png',
    'books/Dombey and Son/page (111).png',
    'books/Dombey and Son/page (112).png',
    'books/Dombey and Son/page (113).png',
    'books/Dombey and Son/page (114).png',
    'books/Dombey and Son/page (115).png',
    'books/Dombey and Son/page (116).png',
    'books/Dombey and Son/page (117).png',
    'books/Dombey and Son/page (118).png',
    'books/Dombey and Son/page (119).png',
    'books/Dombey and Son/page (120).png',
    'books/Dombey and Son/page (121).png',
    'books/Dombey and Son/page (122).png',
    'books/Dombey and Son/page (123).png',
    'books/Dombey and Son/page (124).png',
    'books/Dombey and Son/page (125).png',
    'books/Dombey and Son/page (126).png',
    'books/Dombey and Son/page (127).png',
    'books/Dombey and Son/page (128).png',
    'books/Dombey and Son/page (129).png',
    'books/Dombey and Son/page (130).png',
    'books/Dombey and Son/page (131).png',
    'books/Dombey and Son/page (132).png',
    'books/Dombey and Son/page (133).png',
    'books/Dombey and Son/page (134).png',
    'books/Dombey and Son/page (135).png',
    'books/Dombey and Son/page (136).png',
    'books/Dombey and Son/page (137).png',
    'books/Dombey and Son/page (138).png',
    'books/Dombey and Son/page (139).png',
    'books/Dombey and Son/page (140).png',
    'books/Dombey and Son/page (141).png',
    'books/Dombey and Son/page (142).png',
    'books/Dombey and Son/page (143).png',
    'books/Dombey and Son/page (144).png',
    'books/Dombey and Son/page (145).png',
    'books/Dombey and Son/page (146).png',
    'books/Dombey and Son/page (147).png',
    'books/Dombey and Son/page (148).png',
    'books/Dombey and Son/page (149).png',
    'books/Dombey and Son/page (150).png',
    'books/Dombey and Son/page (151).png',
    'books/Dombey and Son/page (152).png',
    'books/Dombey and Son/page (153).png',
    'books/Dombey and Son/page (154).png',
    'books/Dombey and Son/page (155).png',
    'books/Dombey and Son/page (156).png',
    'books/Dombey and Son/page (157).png',
    'books/Dombey and Son/page (158).png',
    'books/Dombey and Son/page (159).png',
    'books/Dombey and Son/page (160).png',
    'books/Dombey and Son/page (161).png',
    'books/Dombey and Son/page (162).png',
    'books/Dombey and Son/page (163).png',
    'books/Dombey and Son/page (164).png',
    'books/Dombey and Son/page (165).png',
    'books/Dombey and Son/page (166).png',
    'books/Dombey and Son/page (167).png',
    'books/Dombey and Son/page (168).png',
    'books/Dombey and Son/page (169).png',
    'books/Dombey and Son/page (170).png',
    'books/Dombey and Son/page (171).png',
    'books/Dombey and Son/page (172).png',
    'books/Dombey and Son/page (173).png',
    'books/Dombey and Son/page (174).png',
    'books/Dombey and Son/page (175).png',
    'books/Dombey and Son/page (176).png',
    'books/Dombey and Son/page (177).png',
    'books/Dombey and Son/page (178).png',
    'books/Dombey and Son/page (179).png',
    'books/Dombey and Son/page (180).png',
    'books/Dombey and Son/page (181).png',
    'books/Dombey and Son/page (182).png',
    'books/Dombey and Son/page (183).png',
    'books/Dombey and Son/page (184).png',
    'books/Dombey and Son/page (185).png',
    'books/Dombey and Son/page (186).png',
    'books/Dombey and Son/page (187).png',
    'books/Dombey and Son/page (188).png',
    'books/Dombey and Son/page (189).png',
    'books/Dombey and Son/page (190).png',
    'books/Dombey and Son/page (191).png',
    'books/Dombey and Son/page (192).png',
    'books/Dombey and Son/page (193).png',
    'books/Dombey and Son/page (194).png',
    'books/Dombey and Son/page (195).png',
    'books/Dombey and Son/page (196).png',
    'books/Dombey and Son/page (197).png',
    'books/Dombey and Son/page (198).png',
    'books/Dombey and Son/page (199).png',
    'books/Dombey and Son/page (200).png',
    'books/Dombey and Son/page (201).png',
    'books/Dombey and Son/page (202).png',
    'books/Dombey and Son/page (203).png',
    'books/Dombey and Son/page (204).png',
    'books/Dombey and Son/page (205).png',
    'books/Dombey and Son/page (206).png',
    'books/Dombey and Son/page (207).png',
    'books/Dombey and Son/page (208).png',
    'books/Dombey and Son/page (209).png',
    'books/Dombey and Son/page (210).png',
    'books/Dombey and Son/page (211).png',
    'books/Dombey and Son/page (212).png',
    'books/Dombey and Son/page (213).png',
    'books/Dombey and Son/page (214).png',
    'books/Dombey and Son/page (215).png',
    'books/Dombey and Son/page (216).png',
    'books/Dombey and Son/page (217).png',
    'books/Dombey and Son/page (218).png',
    'books/Dombey and Son/page (219).png',
    'books/Dombey and Son/page (220).png',
    'books/Dombey and Son/page (221).png',
    'books/Dombey and Son/page (222).png',
    'books/Dombey and Son/page (223).png',
    'books/Dombey and Son/page (224).png',
    'books/Dombey and Son/page (225).png',
    'books/Dombey and Son/page (226).png',
    'books/Dombey and Son/page (227).png',
    'books/Dombey and Son/page (228).png',
    'books/Dombey and Son/page (229).png',
    'books/Dombey and Son/page (230).png',
    'books/Dombey and Son/page (231).png',
    'books/Dombey and Son/page (232).png',
    'books/Dombey and Son/page (233).png',
    'books/Dombey and Son/page (234).png',
    'books/Dombey and Son/page (235).png',
    'books/Dombey and Son/page (236).png',
    'books/Dombey and Son/page (237).png',
    'books/Dombey and Son/page (238).png',
    'books/Dombey and Son/page (239).png',
    'books/Dombey and Son/page (240).png',
    'books/Dombey and Son/page (241).png',
    'books/Dombey and Son/page (242).png',
    'books/Dombey and Son/page (243).png',
    'books/Dombey and Son/page (244).png',
    'books/Dombey and Son/page (245).png',
    'books/Dombey and Son/page (246).png',
    'books/Dombey and Son/page (247).png',
    'books/Dombey and Son/page (248).png',
    'books/Dombey and Son/page (249).png',
    'books/Dombey and Son/page (250).png',
    'books/Dombey and Son/page (251).png',
    'books/Dombey and Son/page (252).png',
    'books/Dombey and Son/page (253).png',
    'books/Dombey and Son/page (254).png',
    'books/Dombey and Son/page (255).png',
    'books/Dombey and Son/page (256).png',
    'books/Dombey and Son/page (257).png',
    'books/Dombey and Son/page (258).png',
    'books/Dombey and Son/page (259).png',
    'books/Dombey and Son/page (260).png',
    'books/Dombey and Son/page (261).png',
    'books/Dombey and Son/page (262).png',
    'books/Dombey and Son/page (263).png',
    'books/Dombey and Son/page (264).png',
    'books/Dombey and Son/page (265).png',
    'books/Dombey and Son/page (266).png',
    'books/Dombey and Son/page (267).png',
    'books/Dombey and Son/page (268).png',
    'books/Dombey and Son/page (269).png',
    'books/Dombey and Son/page (270).png',
    'books/Dombey and Son/page (271).png',
    'books/Dombey and Son/page (272).png',
    'books/Dombey and Son/page (273).png',
    'books/Dombey and Son/page (274).png',
    'books/Dombey and Son/page (275).png',
    'books/Dombey and Son/page (276).png',
    'books/Dombey and Son/page (277).png',
    'books/Dombey and Son/page (278).png',
    'books/Dombey and Son/page (279).png',
    'books/Dombey and Son/page (280).png',
    'books/Dombey and Son/page (281).png',
    'books/Dombey and Son/page (282).png',
    'books/Dombey and Son/page (283).png',
    'books/Dombey and Son/page (284).png',
    'books/Dombey and Son/page (285).png',
    'books/Dombey and Son/page (286).png',
    'books/Dombey and Son/page (287).png',
    'books/Dombey and Son/page (288).png',
    'books/Dombey and Son/page (289).png',
    'books/Dombey and Son/page (290).png',
    'books/Dombey and Son/page (291).png',
    'books/Dombey and Son/page (292).png',
    'books/Dombey and Son/page (293).png',
    'books/Dombey and Son/page (294).png',
    'books/Dombey and Son/page (295).png',
    'books/Dombey and Son/page (296).png',
    'books/Dombey and Son/page (297).png',
    'books/Dombey and Son/page (298).png',
    'books/Dombey and Son/page (299).png',
    'books/Dombey and Son/page (300).png',
    'books/Dombey and Son/page (301).png',
    'books/Dombey and Son/page (302).png',
    'books/Dombey and Son/page (303).png',
    'books/Dombey and Son/page (304).png',
    'books/Dombey and Son/page (305).png',
    'books/Dombey and Son/page (306).png',
    'books/Dombey and Son/page (307).png',
    'books/Dombey and Son/page (308).png',
    'books/Dombey and Son/page (309).png',
    'books/Dombey and Son/page (310).png',
    'books/Dombey and Son/page (311).png',
    'books/Dombey and Son/page (312).png',
    'books/Dombey and Son/page (313).png',
    'books/Dombey and Son/page (314).png',
    'books/Dombey and Son/page (315).png',
    'books/Dombey and Son/page (316).png',
    'books/Dombey and Son/page (317).png',
    'books/Dombey and Son/page (318).png',
    'books/Dombey and Son/page (319).png',
    'books/Dombey and Son/page (320).png',
    'books/Dombey and Son/page (321).png',
    'books/Dombey and Son/page (322).png',
    'books/Dombey and Son/page (323).png',
    'books/Dombey and Son/page (324).png',
    'books/Dombey and Son/page (325).png',
    'books/Dombey and Son/page (326).png',
    'books/Dombey and Son/page (327).png',
    'books/Dombey and Son/page (328).png',
    'books/Dombey and Son/page (329).png',
    'books/Dombey and Son/page (330).png',
    'books/Dombey and Son/page (331).png',
    'books/Dombey and Son/page (332).png',
    'books/Dombey and Son/page (333).png',
    'books/Dombey and Son/page (334).png',
    'books/Dombey and Son/page (335).png',
    'books/Dombey and Son/page (336).png',
    'books/Dombey and Son/page (337).png',
    'books/Dombey and Son/page (338).png',
    'books/Dombey and Son/page (339).png',
    'books/Dombey and Son/page (340).png',
    'books/Dombey and Son/page (341).png',
    'books/Dombey and Son/page (342).png',
    'books/Dombey and Son/page (343).png',
    'books/Dombey and Son/page (344).png',
    'books/Dombey and Son/page (345).png',
    'books/Dombey and Son/page (346).png',
    'books/Dombey and Son/page (347).png',
    'books/Dombey and Son/page (348).png',
    'books/Dombey and Son/page (349).png',
    'books/Dombey and Son/page (350).png',
    'books/Dombey and Son/page (351).png',
    'books/Dombey and Son/page (352).png',
    'books/Dombey and Son/page (353).png',
    'books/Dombey and Son/page (354).png',
    'books/Dombey and Son/page (355).png',
    'books/Dombey and Son/page (356).png',
    'books/Dombey and Son/page (357).png',
    'books/Dombey and Son/page (358).png',
    'books/Dombey and Son/page (359).png',
    'books/Dombey and Son/page (360).png',
    'books/Dombey and Son/page (361).png',
    'books/Dombey and Son/page (362).png',
    'books/Dombey and Son/page (363).png',
    'books/Dombey and Son/page (364).png',
    'books/Dombey and Son/page (365).png',
    'books/Dombey and Son/page (366).png',
    'books/Dombey and Son/page (367).png',
    'books/Dombey and Son/page (368).png',
    'books/Dombey and Son/page (369).png',
    'books/Dombey and Son/page (370).png',
    'books/Dombey and Son/page (371).png',
    'books/Dombey and Son/page (372).png',
    'books/Dombey and Son/page (373).png',
    'books/Dombey and Son/page (374).png',
    'books/Dombey and Son/page (375).png',
    'books/Dombey and Son/page (376).png',
    'books/Dombey and Son/page (377).png',
    'books/Dombey and Son/page (378).png',
    'books/Dombey and Son/page (379).png',
    'books/Dombey and Son/page (380).png',
    'books/Dombey and Son/page (381).png',
    'books/Dombey and Son/page (382).png',
    'books/Dombey and Son/page (383).png',
    'books/Dombey and Son/page (384).png',
    'books/Dombey and Son/page (385).png',
    'books/Dombey and Son/page (386).png',
    'books/Dombey and Son/page (387).png',
    'books/Dombey and Son/page (388).png',
    'books/Dombey and Son/page (389).png',
    'books/Dombey and Son/page (390).png',
    'books/Dombey and Son/page (391).png',
    'books/Dombey and Son/page (392).png',
    'books/Dombey and Son/page (393).png',
    'books/Dombey and Son/page (394).png',
    'books/Dombey and Son/page (395).png',
    'books/Dombey and Son/page (396).png',
    'books/Dombey and Son/page (397).png',
    'books/Dombey and Son/page (398).png',
    'books/Dombey and Son/page (399).png',
    'books/Dombey and Son/page (400).png',
    'books/Dombey and Son/page (401).png',
    'books/Dombey and Son/page (402).png',
    'books/Dombey and Son/page (403).png',
    'books/Dombey and Son/page (404).png',
    'books/Dombey and Son/page (405).png',
    'books/Dombey and Son/page (406).png',
    'books/Dombey and Son/page (407).png',
    'books/Dombey and Son/page (408).png',
    'books/Dombey and Son/page (409).png',
    'books/Dombey and Son/page (410).png',
    'books/Dombey and Son/page (411).png',
    'books/Dombey and Son/page (412).png',
    'books/Dombey and Son/page (413).png',
    'books/Dombey and Son/page (414).png',
    'books/Dombey and Son/page (415).png',
    'books/Dombey and Son/page (416).png',
    'books/Dombey and Son/page (417).png',
    'books/Dombey and Son/page (418).png',
    'books/Dombey and Son/page (419).png',
    'books/Dombey and Son/page (420).png',
    'books/Dombey and Son/page (421).png',
    'books/Dombey and Son/page (422).png',
    'books/Dombey and Son/page (423).png',
    'books/Dombey and Son/page (424).png',
    'books/Dombey and Son/page (425).png',
    'books/Dombey and Son/page (426).png',
    'books/Dombey and Son/page (427).png',
    'books/Dombey and Son/page (428).png',
    'books/Dombey and Son/page (429).png',
    'books/Dombey and Son/page (430).png',
    'books/Dombey and Son/page (431).png',
    'books/Dombey and Son/page (432).png',
    'books/Dombey and Son/page (433).png',
    'books/Dombey and Son/page (434).png',
    'books/Dombey and Son/page (435).png',
    'books/Dombey and Son/page (436).png',
    'books/Dombey and Son/page (437).png',
    'books/Dombey and Son/page (438).png',
    'books/Dombey and Son/page (439).png',
    'books/Dombey and Son/page (440).png',
    'books/Dombey and Son/page (441).png',
    'books/Dombey and Son/page (442).png',
    'books/Dombey and Son/page (443).png',
    'books/Dombey and Son/page (444).png',
    'books/Dombey and Son/page (445).png',
    'books/Dombey and Son/page (446).png',
    'books/Dombey and Son/page (447).png',
    'books/Dombey and Son/page (448).png',
    'books/Dombey and Son/page (449).png',
    'books/Dombey and Son/page (450).png',
    'books/Dombey and Son/page (451).png',
    'books/Dombey and Son/page (452).png',
    'books/Dombey and Son/page (453).png',
    'books/Dombey and Son/page (454).png',
    'books/Dombey and Son/page (455).png',
    'books/Dombey and Son/page (456).png',
    'books/Dombey and Son/page (457).png',
    'books/Dombey and Son/page (458).png',
    'books/Dombey and Son/page (459).png',
    'books/Dombey and Son/page (460).png',
    'books/Dombey and Son/page (461).png',
    'books/Dombey and Son/page (462).png',
    'books/Dombey and Son/page (463).png',
    'books/Dombey and Son/page (464).png',
    'books/Dombey and Son/page (465).png',
    'books/Dombey and Son/page (466).png',
    'books/Dombey and Son/page (467).png',
    'books/Dombey and Son/page (468).png',
    'books/Dombey and Son/page (469).png',
    'books/Dombey and Son/page (470).png',
    'books/Dombey and Son/page (471).png',
    'books/Dombey and Son/page (472).png',
    'books/Dombey and Son/page (473).png',
    'books/Dombey and Son/page (474).png',
    'books/Dombey and Son/page (475).png',
    'books/Dombey and Son/page (476).png',
    'books/Dombey and Son/page (477).png',
    'books/Dombey and Son/page (478).png',
    'books/Dombey and Son/page (479).png',
    'books/Dombey and Son/page (480).png',
    'books/Dombey and Son/page (481).png',
    'books/Dombey and Son/page (482).png',
    'books/Dombey and Son/page (483).png',
    'books/Dombey and Son/page (484).png',
    'books/Dombey and Son/page (485).png',
    'books/Dombey and Son/page (486).png',
    'books/Dombey and Son/page (487).png',
    'books/Dombey and Son/page (488).png',
    'books/Dombey and Son/page (489).png',
    'books/Dombey and Son/page (490).png',
    'books/Dombey and Son/page (491).png',
    'books/Dombey and Son/page (492).png',
    'books/Dombey and Son/page (493).png',
    'books/Dombey and Son/page (494).png',
    'books/Dombey and Son/page (495).png',
    'books/Dombey and Son/page (496).png',
    'books/Dombey and Son/page (497).png',
    'books/Dombey and Son/page (498).png',
    'books/Dombey and Son/page (499).png',
    'books/Dombey and Son/page (500).png',
    'books/Dombey and Son/page (501).png',
    'books/Dombey and Son/page (502).png',
    'books/Dombey and Son/page (503).png',
    'books/Dombey and Son/page (504).png',
    'books/Dombey and Son/page (505).png',
    'books/Dombey and Son/page (506).png',
    'books/Dombey and Son/page (507).png',
    'books/Dombey and Son/page (508).png',
    'books/Dombey and Son/page (509).png',
    'books/Dombey and Son/page (510).png',
    'books/Dombey and Son/page (511).png',
    'books/Dombey and Son/page (512).png',
    'books/Dombey and Son/page (513).png',
    'books/Dombey and Son/page (514).png',
    'books/Dombey and Son/page (515).png',
    'books/Dombey and Son/page (516).png',
    'books/Dombey and Son/page (517).png',
    'books/Dombey and Son/page (518).png',
    'books/Dombey and Son/page (519).png',
    'books/Dombey and Son/page (520).png',
    'books/Dombey and Son/page (521).png',
    'books/Dombey and Son/page (522).png',
    'books/Dombey and Son/page (523).png',
    'books/Dombey and Son/page (524).png',
    'books/Dombey and Son/page (525).png',
    'books/Dombey and Son/page (526).png',
    'books/Dombey and Son/page (527).png',
    'books/Dombey and Son/page (528).png',
    'books/Dombey and Son/page (529).png',
    'books/Dombey and Son/page (530).png',
    'books/Dombey and Son/page (531).png',
    'books/Dombey and Son/page (532).png',
    'books/Dombey and Son/page (533).png',
    'books/Dombey and Son/page (534).png',
    'books/Dombey and Son/page (535).png',
    'books/Dombey and Son/page (536).png',
    'books/Dombey and Son/page (537).png',
    'books/Dombey and Son/page (538).png',
    'books/Dombey and Son/page (539).png',
    'books/Dombey and Son/page (540).png',
    'books/Dombey and Son/page (541).png',
    'books/Dombey and Son/page (542).png',
    'books/Dombey and Son/page (543).png',
    'books/Dombey and Son/page (544).png',
    'books/Dombey and Son/page (545).png',
    'books/Dombey and Son/page (546).png',
    'books/Dombey and Son/page (547).png',
    'books/Dombey and Son/page (548).png',
    'books/Dombey and Son/page (549).png',
    'books/Dombey and Son/page (550).png',
    'books/Dombey and Son/page (551).png',
    'books/Dombey and Son/page (552).png',
    'books/Dombey and Son/page (553).png',
    'books/Dombey and Son/page (554).png',
    'books/Dombey and Son/page (555).png',
    'books/Dombey and Son/page (556).png',
    'books/Dombey and Son/page (557).png',
    'books/Dombey and Son/page (558).png',
    'books/Dombey and Son/page (559).png',
    'books/Dombey and Son/page (560).png',
    'books/Dombey and Son/page (561).png',
    'books/Dombey and Son/page (562).png',
    'books/Dombey and Son/page (563).png',
    'books/Dombey and Son/page (564).png',
    'books/Dombey and Son/page (565).png',
    'books/Dombey and Son/page (566).png',
    'books/Dombey and Son/page (567).png',
    'books/Dombey and Son/page (568).png',
    'books/Dombey and Son/page (569).png',
    'books/Dombey and Son/page (570).png',
    'books/Dombey and Son/page (571).png',
    'books/Dombey and Son/page (572).png',
    'books/Dombey and Son/page (573).png',
    'books/Dombey and Son/page (574).png',
    'books/Dombey and Son/page (575).png',
    'books/Dombey and Son/page (576).png',
    'books/Dombey and Son/page (577).png',
    'books/Dombey and Son/page (578).png',
    'books/Dombey and Son/page (579).png',
    'books/Dombey and Son/page (580).png',
    'books/Dombey and Son/page (581).png',
    'books/Dombey and Son/page (582).png',
    'books/Dombey and Son/page (583).png',
    'books/Dombey and Son/page (584).png',
    'books/Dombey and Son/page (585).png',
    'books/Dombey and Son/page (586).png',
    'books/Dombey and Son/page (587).png',
    'books/Dombey and Son/page (588).png',
    'books/Dombey and Son/page (589).png',
    'books/Dombey and Son/page (590).png',
    'books/Dombey and Son/page (591).png',
    'books/Dombey and Son/page (592).png',
    'books/Dombey and Son/page (593).png',
    'books/Dombey and Son/page (594).png',
    'books/Dombey and Son/page (595).png',
    'books/Dombey and Son/page (596).png',
    'books/Dombey and Son/page (597).png',
    'books/Dombey and Son/page (598).png',
    'books/Dombey and Son/page (599).png',
    'books/Dombey and Son/page (600).png',
    'books/Dombey and Son/page (601).png',
    'books/Dombey and Son/page (602).png',
    'books/Dombey and Son/page (603).png',
    'books/Dombey and Son/page (604).png',
    'books/Dombey and Son/page (605).png',
    'books/Dombey and Son/page (606).png',
    'books/Dombey and Son/page (607).png',
    'books/Dombey and Son/page (608).png',
    'books/Dombey and Son/page (609).png',
    'books/Dombey and Son/page (610).png',
    'books/Dombey and Son/page (611).png',
    'books/Dombey and Son/page (612).png',
    'books/Dombey and Son/page (613).png',
    'books/Dombey and Son/page (614).png',
    'books/Dombey and Son/page (615).png',
    'books/Dombey and Son/page (616).png',
    'books/Dombey and Son/page (617).png',
    'books/Dombey and Son/page (618).png',
    'books/Dombey and Son/page (619).png',
    'books/Dombey and Son/page (620).png',
    'books/Dombey and Son/page (621).png',
    'books/Dombey and Son/page (622).png',
    'books/Dombey and Son/page (623).png',
    'books/Dombey and Son/page (624).png',
    'books/Dombey and Son/page (625).png',
    'books/Dombey and Son/page (626).png',
    'books/Dombey and Son/page (627).png',
    'books/Dombey and Son/page (628).png',
    'books/Dombey and Son/page (629).png',
    'books/Dombey and Son/page (630).png',
    'books/Dombey and Son/page (631).png',
    'books/Dombey and Son/page (632).png',
    'books/Dombey and Son/page (633).png',
    'books/Dombey and Son/page (634).png',
    'books/Dombey and Son/page (635).png',
    'books/Dombey and Son/page (636).png',
    'books/Dombey and Son/page (637).png',
    'books/Dombey and Son/page (638).png',
    'books/Dombey and Son/page (639).png',
    'books/Dombey and Son/page (640).png',
    'books/Dombey and Son/page (641).png',
    'books/Dombey and Son/page (642).png',
    'books/Dombey and Son/page (643).png',
    'books/Dombey and Son/page (644).png',
    'books/Dombey and Son/page (645).png',
    'books/Dombey and Son/page (646).png',
    'books/Dombey and Son/page (647).png',
    'books/Dombey and Son/page (648).png',
    'books/Dombey and Son/page (649).png',
    'books/Dombey and Son/page (650).png',
    'books/Dombey and Son/page (651).png',
    'books/Dombey and Son/page (652).png',
    'books/Dombey and Son/page (653).png',
    'books/Dombey and Son/page (654).png',
    'books/Dombey and Son/page (655).png',
    'books/Dombey and Son/page (656).png',
    'books/Dombey and Son/page (657).png',
    'books/Dombey and Son/page (658).png',
    'books/Dombey and Son/page (659).png',
    'books/Dombey and Son/page (660).png',
    'books/Dombey and Son/page (661).png',
    'books/Dombey and Son/page (662).png',
    'books/Dombey and Son/page (663).png',
    'books/Dombey and Son/page (664).png',
    'books/Dombey and Son/page (665).png',
    'books/Dombey and Son/page (666).png',
    'books/Dombey and Son/page (667).png',
    'books/Dombey and Son/page (668).png',
    'books/Dombey and Son/page (669).png',
    'books/Dombey and Son/page (670).png',
    'books/Dombey and Son/page (671).png',
    'books/Dombey and Son/page (672).png',
    'books/Dombey and Son/page (673).png',
    'books/Dombey and Son/page (674).png',
    'books/Dombey and Son/page (675).png',
    'books/Dombey and Son/page (676).png',
    'books/Dombey and Son/page (677).png',
    'books/Dombey and Son/page (678).png',
    'books/Dombey and Son/page (679).png',
    'books/Dombey and Son/page (680).png',
    'books/Dombey and Son/page (681).png',
    'books/Dombey and Son/page (682).png',
    'books/Dombey and Son/page (683).png',
    'books/Dombey and Son/page (684).png',
    'books/Dombey and Son/page (685).png',
    'books/Dombey and Son/page (686).png',
    'books/Dombey and Son/page (687).png',
    'books/Dombey and Son/page (688).png',
    'books/Dombey and Son/page (689).png',
    'books/Dombey and Son/page (690).png',
    'books/Dombey and Son/page (691).png',
    'books/Dombey and Son/page (692).png',
    'books/Dombey and Son/page (693).png',
    'books/Dombey and Son/page (694).png',
    'books/Dombey and Son/page (695).png',
    'books/Dombey and Son/page (696).png',
    'books/Dombey and Son/page (697).png',
    'books/Dombey and Son/page (698).png',
    'books/Dombey and Son/page (699).png',
    'books/Dombey and Son/page (700).png',
    'books/Dombey and Son/page (701).png',
    'books/Dombey and Son/page (702).png',
    'books/Dombey and Son/page (703).png',
    'books/Dombey and Son/page (704).png',
    'books/Dombey and Son/page (705).png',
    'books/Dombey and Son/page (706).png',
    'books/Dombey and Son/page (707).png',
    'books/Dombey and Son/page (708).png',
    'books/Dombey and Son/page (709).png',
    'books/Dombey and Son/page (710).png',
    'books/Dombey and Son/page (711).png',
    'books/Dombey and Son/page (712).png',
    'books/Dombey and Son/page (713).png',
    'books/Dombey and Son/page (714).png',
    'books/Dombey and Son/page (715).png',
    'books/Dombey and Son/page (716).png',
    'books/Dombey and Son/page (717).png',
    'books/Dombey and Son/page (718).png',
    'books/Dombey and Son/page (719).png',
    'books/Dombey and Son/page (720).png',
    'books/Dombey and Son/page (721).png',
    'books/Dombey and Son/page (722).png',
    'books/Dombey and Son/page (723).png',
    'books/Dombey and Son/page (724).png',
    'books/Dombey and Son/page (725).png',
    'books/Dombey and Son/page (726).png',
    'books/Dombey and Son/page (727).png',
    'books/Dombey and Son/page (728).png',
    'books/Dombey and Son/page (729).png',
    'books/Dombey and Son/page (730).png',
    'books/Dombey and Son/page (731).png',
    'books/Dombey and Son/page (732).png',
    'books/Dombey and Son/page (733).png',
    'books/Dombey and Son/page (734).png',
    'books/Dombey and Son/page (735).png',
    'books/Dombey and Son/page (736).png',
    'books/Dombey and Son/page (737).png',
    'books/Dombey and Son/page (738).png',
    'books/Dombey and Son/page (739).png',
    'books/Dombey and Son/page (740).png',
    'books/Dombey and Son/page (741).png',
    'books/Dombey and Son/page (742).png',
    'books/Dombey and Son/page (743).png',
    'books/Dombey and Son/page (744).png',
    'books/Dombey and Son/page (745).png',
    'books/Dombey and Son/page (746).png',
    'books/Dombey and Son/page (747).png',
    'books/Dombey and Son/page (748).png',
    'books/Dombey and Son/page (749).png',
    'books/Dombey and Son/page (750).png',
    'books/Dombey and Son/page (751).png',
    'books/Dombey and Son/page (752).png',
    'books/Dombey and Son/page (753).png',
    'books/Dombey and Son/page (754).png',
    'books/Dombey and Son/page (755).png',
    'books/Dombey and Son/page (756).png',
    'books/Dombey and Son/page (757).png',
    'books/Dombey and Son/page (758).png',
    'books/Dombey and Son/page (759).png',
    'books/Dombey and Son/page (760).png',
    'books/Dombey and Son/page (761).png',
    'books/Dombey and Son/page (762).png',
    'books/Dombey and Son/page (763).png',
    'books/Dombey and Son/page (764).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
