import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class emma extends StatefulWidget {
  const emma({Key? key}) : super(key: key);

  @override
  State<emma> createState() => _emmaState();
}

class _emmaState extends State<emma> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/emma/page (1).png',
    'books/emma/page (2).png',
    'books/emma/page (3).png',
    'books/emma/page (4).png',
    'books/emma/page (5).png',
    'books/emma/page (6).png',
    'books/emma/page (7).png',
    'books/emma/page (8).png',
    'books/emma/page (9).png',
    'books/emma/page (10).png',
    'books/emma/page (11).png',
    'books/emma/page (12).png',
    'books/emma/page (13).png',
    'books/emma/page (14).png',
    'books/emma/page (15).png',
    'books/emma/page (16).png',
    'books/emma/page (17).png',
    'books/emma/page (18).png',
    'books/emma/page (19).png',
    'books/emma/page (20).png',
    'books/emma/page (21).png',
    'books/emma/page (22).png',
    'books/emma/page (23).png',
    'books/emma/page (24).png',
    'books/emma/page (25).png',
    'books/emma/page (26).png',
    'books/emma/page (27).png',
    'books/emma/page (28).png',
    'books/emma/page (29).png',
    'books/emma/page (30).png',
    'books/emma/page (31).png',
    'books/emma/page (32).png',
    'books/emma/page (33).png',
    'books/emma/page (34).png',
    'books/emma/page (35).png',
    'books/emma/page (36).png',
    'books/emma/page (37).png',
    'books/emma/page (38).png',
    'books/emma/page (39).png',
    'books/emma/page (40).png',
    'books/emma/page (41).png',
    'books/emma/page (42).png',
    'books/emma/page (43).png',
    'books/emma/page (44).png',
    'books/emma/page (45).png',
    'books/emma/page (46).png',
    'books/emma/page (47).png',
    'books/emma/page (48).png',
    'books/emma/page (49).png',
    'books/emma/page (50).png',
    'books/emma/page (51).png',
    'books/emma/page (52).png',
    'books/emma/page (53).png',
    'books/emma/page (54).png',
    'books/emma/page (55).png',
    'books/emma/page (56).png',
    'books/emma/page (57).png',
    'books/emma/page (58).png',
    'books/emma/page (59).png',
    'books/emma/page (60).png',
    'books/emma/page (61).png',
    'books/emma/page (62).png',
    'books/emma/page (63).png',
    'books/emma/page (64).png',
    'books/emma/page (65).png',
    'books/emma/page (66).png',
    'books/emma/page (67).png',
    'books/emma/page (68).png',
    'books/emma/page (69).png',
    'books/emma/page (70).png',
    'books/emma/page (71).png',
    'books/emma/page (72).png',
    'books/emma/page (73).png',
    'books/emma/page (74).png',
    'books/emma/page (75).png',
    'books/emma/page (76).png',
    'books/emma/page (77).png',
    'books/emma/page (78).png',
    'books/emma/page (79).png',
    'books/emma/page (80).png',
    'books/emma/page (81).png',
    'books/emma/page (82).png',
    'books/emma/page (83).png',
    'books/emma/page (84).png',
    'books/emma/page (85).png',
    'books/emma/page (86).png',
    'books/emma/page (87).png',
    'books/emma/page (88).png',
    'books/emma/page (89).png',
    'books/emma/page (90).png',
    'books/emma/page (91).png',
    'books/emma/page (92).png',
    'books/emma/page (93).png',
    'books/emma/page (94).png',
    'books/emma/page (95).png',
    'books/emma/page (96).png',
    'books/emma/page (97).png',
    'books/emma/page (98).png',
    'books/emma/page (99).png',
    'books/emma/page (100).png',
    'books/emma/page (101).png',
    'books/emma/page (102).png',
    'books/emma/page (103).png',
    'books/emma/page (104).png',
    'books/emma/page (105).png',
    'books/emma/page (106).png',
    'books/emma/page (107).png',
    'books/emma/page (108).png',
    'books/emma/page (109).png',
    'books/emma/page (110).png',
    'books/emma/page (111).png',
    'books/emma/page (112).png',
    'books/emma/page (113).png',
    'books/emma/page (114).png',
    'books/emma/page (115).png',
    'books/emma/page (116).png',
    'books/emma/page (117).png',
    'books/emma/page (118).png',
    'books/emma/page (119).png',
    'books/emma/page (120).png',
    'books/emma/page (121).png',
    'books/emma/page (122).png',
    'books/emma/page (123).png',
    'books/emma/page (124).png',
    'books/emma/page (125).png',
    'books/emma/page (126).png',
    'books/emma/page (127).png',
    'books/emma/page (128).png',
    'books/emma/page (129).png',
    'books/emma/page (130).png',
    'books/emma/page (131).png',
    'books/emma/page (132).png',
    'books/emma/page (133).png',
    'books/emma/page (134).png',
    'books/emma/page (135).png',
    'books/emma/page (136).png',
    'books/emma/page (137).png',
    'books/emma/page (138).png',
    'books/emma/page (139).png',
    'books/emma/page (140).png',
    'books/emma/page (141).png',
    'books/emma/page (142).png',
    'books/emma/page (143).png',
    'books/emma/page (144).png',
    'books/emma/page (145).png',
    'books/emma/page (146).png',
    'books/emma/page (147).png',
    'books/emma/page (148).png',
    'books/emma/page (149).png',
    'books/emma/page (150).png',
    'books/emma/page (151).png',
    'books/emma/page (152).png',
    'books/emma/page (153).png',
    'books/emma/page (154).png',
    'books/emma/page (155).png',
    'books/emma/page (156).png',
    'books/emma/page (157).png',
    'books/emma/page (158).png',
    'books/emma/page (159).png',
    'books/emma/page (160).png',
    'books/emma/page (161).png',
    'books/emma/page (162).png',
    'books/emma/page (163).png',
    'books/emma/page (164).png',
    'books/emma/page (165).png',
    'books/emma/page (166).png',
    'books/emma/page (167).png',
    'books/emma/page (168).png',
    'books/emma/page (169).png',
    'books/emma/page (170).png',
    'books/emma/page (171).png',
    'books/emma/page (172).png',
    'books/emma/page (173).png',
    'books/emma/page (174).png',
    'books/emma/page (175).png',
    'books/emma/page (176).png',
    'books/emma/page (177).png',
    'books/emma/page (178).png',
    'books/emma/page (179).png',
    'books/emma/page (180).png',
    'books/emma/page (181).png',
    'books/emma/page (182).png',
    'books/emma/page (183).png',
    'books/emma/page (184).png',
    'books/emma/page (185).png',
    'books/emma/page (186).png',
    'books/emma/page (187).png',
    'books/emma/page (188).png',
    'books/emma/page (189).png',
    'books/emma/page (190).png',
    'books/emma/page (191).png',
    'books/emma/page (192).png',
    'books/emma/page (193).png',
    'books/emma/page (194).png',
    'books/emma/page (195).png',
    'books/emma/page (196).png',
    'books/emma/page (197).png',
    'books/emma/page (198).png',
    'books/emma/page (199).png',
    'books/emma/page (200).png',
    'books/emma/page (201).png',
    'books/emma/page (202).png',
    'books/emma/page (203).png',
    'books/emma/page (204).png',
    'books/emma/page (205).png',
    'books/emma/page (206).png',
    'books/emma/page (207).png',
    'books/emma/page (208).png',
    'books/emma/page (209).png',
    'books/emma/page (210).png',
    'books/emma/page (211).png',
    'books/emma/page (212).png',
    'books/emma/page (213).png',
    'books/emma/page (214).png',
    'books/emma/page (215).png',
    'books/emma/page (216).png',
    'books/emma/page (217).png',
    'books/emma/page (218).png',
    'books/emma/page (219).png',
    'books/emma/page (220).png',
    'books/emma/page (221).png',
    'books/emma/page (222).png',
    'books/emma/page (223).png',
    'books/emma/page (224).png',
    'books/emma/page (225).png',
    'books/emma/page (226).png',
    'books/emma/page (227).png',
    'books/emma/page (228).png',
    'books/emma/page (229).png',
    'books/emma/page (230).png',
    'books/emma/page (231).png',
    'books/emma/page (232).png',
    'books/emma/page (233).png',
    'books/emma/page (234).png',
    'books/emma/page (235).png',
    'books/emma/page (236).png',
    'books/emma/page (237).png',
    'books/emma/page (238).png',
    'books/emma/page (239).png',
    'books/emma/page (240).png',
    'books/emma/page (241).png',
    'books/emma/page (242).png',
    'books/emma/page (243).png',
    'books/emma/page (244).png',
    'books/emma/page (245).png',
    'books/emma/page (246).png',
    'books/emma/page (247).png',
    'books/emma/page (248).png',
    'books/emma/page (249).png',
    'books/emma/page (250).png',
    'books/emma/page (251).png',
    'books/emma/page (252).png',
    'books/emma/page (253).png',
    'books/emma/page (254).png',
    'books/emma/page (255).png',
    'books/emma/page (256).png',
    'books/emma/page (257).png',
    'books/emma/page (258).png',
    'books/emma/page (259).png',
    'books/emma/page (260).png',
    'books/emma/page (261).png',
    'books/emma/page (262).png',
    'books/emma/page (263).png',
    'books/emma/page (264).png',
    'books/emma/page (265).png',
    'books/emma/page (266).png',
    'books/emma/page (267).png',
    'books/emma/page (268).png',
    'books/emma/page (269).png',
    'books/emma/page (270).png',
    'books/emma/page (271).png',
    'books/emma/page (272).png',
    'books/emma/page (273).png',
    'books/emma/page (274).png',
    'books/emma/page (275).png',
    'books/emma/page (276).png',
    'books/emma/page (277).png',
    'books/emma/page (278).png',
    'books/emma/page (279).png',
    'books/emma/page (280).png',
    'books/emma/page (281).png',
    'books/emma/page (282).png',
    'books/emma/page (283).png',
    'books/emma/page (284).png',
    'books/emma/page (285).png',
    'books/emma/page (286).png',
    'books/emma/page (287).png',
    'books/emma/page (288).png',
    'books/emma/page (289).png',
    'books/emma/page (290).png',
    'books/emma/page (291).png',
    'books/emma/page (292).png',
    'books/emma/page (293).png',
    'books/emma/page (294).png',
    'books/emma/page (295).png',
    'books/emma/page (296).png',
    'books/emma/page (297).png',
    'books/emma/page (298).png',
    'books/emma/page (299).png',
    'books/emma/page (300).png',
    'books/emma/page (301).png',
    'books/emma/page (302).png',
    'books/emma/page (303).png',
    'books/emma/page (304).png',
    'books/emma/page (305).png',
    'books/emma/page (306).png',
    'books/emma/page (307).png',
    'books/emma/page (308).png',
    'books/emma/page (309).png',
    'books/emma/page (310).png',
    'books/emma/page (311).png',
    'books/emma/page (312).png',
    'books/emma/page (313).png',
    'books/emma/page (314).png',
    'books/emma/page (315).png',
    'books/emma/page (316).png',
    'books/emma/page (317).png',
    'books/emma/page (318).png',
    'books/emma/page (319).png',
    'books/emma/page (320).png',
    'books/emma/page (321).png',
    'books/emma/page (322).png',
    'books/emma/page (323).png',
    'books/emma/page (324).png',
    'books/emma/page (325).png',
    'books/emma/page (326).png',
    'books/emma/page (327).png',
    'books/emma/page (328).png',
    'books/emma/page (329).png',
    'books/emma/page (330).png',
    'books/emma/page (331).png',
    'books/emma/page (332).png',
    'books/emma/page (333).png',
    'books/emma/page (334).png',
    'books/emma/page (335).png',
    'books/emma/page (336).png',
    'books/emma/page (337).png',
    'books/emma/page (338).png',
    'books/emma/page (339).png',
    'books/emma/page (340).png',
    'books/emma/page (341).png',
    'books/emma/page (342).png',
    'books/emma/page (343).png',
    'books/emma/page (344).png',
    'books/emma/page (345).png',
    'books/emma/page (346).png',
    'books/emma/page (347).png',
    'books/emma/page (348).png',
    'books/emma/page (349).png',
    'books/emma/page (350).png',
    'books/emma/page (351).png',
    'books/emma/page (352).png',
    'books/emma/page (353).png',
    'books/emma/page (354).png',
    'books/emma/page (355).png',
    'books/emma/page (356).png',
    'books/emma/page (357).png',
    'books/emma/page (358).png',
    'books/emma/page (359).png',
    'books/emma/page (360).png',
    'books/emma/page (361).png',
    'books/emma/page (362).png',
    'books/emma/page (363).png',
    'books/emma/page (364).png',
    'books/emma/page (365).png',
    'books/emma/page (366).png',
    'books/emma/page (367).png',
    'books/emma/page (368).png',
    'books/emma/page (369).png',
    'books/emma/page (370).png',
    'books/emma/page (371).png',
    'books/emma/page (372).png',
    'books/emma/page (373).png',
    'books/emma/page (374).png',
    'books/emma/page (375).png',
    'books/emma/page (376).png',
    'books/emma/page (377).png',
    'books/emma/page (378).png',
    'books/emma/page (379).png',
    'books/emma/page (380).png',
    'books/emma/page (381).png',
    'books/emma/page (382).png',
    'books/emma/page (383).png',
    'books/emma/page (384).png',
    'books/emma/page (385).png',
    'books/emma/page (386).png',
    'books/emma/page (387).png',
    'books/emma/page (388).png',
    'books/emma/page (389).png',
    'books/emma/page (390).png',
    'books/emma/page (391).png',
    'books/emma/page (392).png',
    'books/emma/page (393).png',
    'books/emma/page (394).png',
    'books/emma/page (395).png',
    'books/emma/page (396).png',
    'books/emma/page (397).png',
    'books/emma/page (398).png',
    'books/emma/page (399).png',
    'books/emma/page (400).png',
    'books/emma/page (401).png',
    'books/emma/page (402).png',
    'books/emma/page (403).png',
    'books/emma/page (404).png',
    'books/emma/page (405).png',
    'books/emma/page (406).png',
    'books/emma/page (407).png',
    'books/emma/page (408).png',
    'books/emma/page (409).png',
    'books/emma/page (410).png',
    'books/emma/page (411).png',
    'books/emma/page (412).png',
    'books/emma/page (413).png',
    'books/emma/page (414).png',
    'books/emma/page (415).png',
    'books/emma/page (416).png',
    'books/emma/page (417).png',
    'books/emma/page (418).png',
    'books/emma/page (419).png',
    'books/emma/page (420).png',
    'books/emma/page (421).png',
    'books/emma/page (422).png',
    'books/emma/page (423).png',
    'books/emma/page (424).png',
    'books/emma/page (425).png',
    'books/emma/page (426).png',
    'books/emma/page (427).png',
    'books/emma/page (428).png',
    'books/emma/page (429).png',
    'books/emma/page (430).png',
    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
