import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class exemplary extends StatefulWidget {
  const exemplary({Key? key}) : super(key: key);

  @override
  State<exemplary> createState() => _exemplaryState();
}

class _exemplaryState extends State<exemplary> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/exemplary/page (1).png',
    'books/exemplary/page (2).png',
    'books/exemplary/page (3).png',
    'books/exemplary/page (4).png',
    'books/exemplary/page (5).png',
    'books/exemplary/page (6).png',
    'books/exemplary/page (7).png',
    'books/exemplary/page (8).png',
    'books/exemplary/page (9).png',
    'books/exemplary/page (10).png',
    'books/exemplary/page (11).png',
    'books/exemplary/page (12).png',
    'books/exemplary/page (13).png',
    'books/exemplary/page (14).png',
    'books/exemplary/page (15).png',
    'books/exemplary/page (16).png',
    'books/exemplary/page (17).png',
    'books/exemplary/page (18).png',
    'books/exemplary/page (19).png',
    'books/exemplary/page (20).png',
    'books/exemplary/page (21).png',
    'books/exemplary/page (22).png',
    'books/exemplary/page (23).png',
    'books/exemplary/page (24).png',
    'books/exemplary/page (25).png',
    'books/exemplary/page (26).png',
    'books/exemplary/page (27).png',
    'books/exemplary/page (28).png',
    'books/exemplary/page (29).png',
    'books/exemplary/page (30).png',
    'books/exemplary/page (31).png',
    'books/exemplary/page (32).png',
    'books/exemplary/page (33).png',
    'books/exemplary/page (34).png',
    'books/exemplary/page (35).png',
    'books/exemplary/page (36).png',
    'books/exemplary/page (37).png',
    'books/exemplary/page (38).png',
    'books/exemplary/page (39).png',
    'books/exemplary/page (40).png',
    'books/exemplary/page (41).png',
    'books/exemplary/page (42).png',
    'books/exemplary/page (43).png',
    'books/exemplary/page (44).png',
    'books/exemplary/page (45).png',
    'books/exemplary/page (46).png',
    'books/exemplary/page (47).png',
    'books/exemplary/page (48).png',
    'books/exemplary/page (49).png',
    'books/exemplary/page (50).png',
    'books/exemplary/page (51).png',
    'books/exemplary/page (52).png',
    'books/exemplary/page (53).png',
    'books/exemplary/page (54).png',
    'books/exemplary/page (55).png',
    'books/exemplary/page (56).png',
    'books/exemplary/page (57).png',
    'books/exemplary/page (58).png',
    'books/exemplary/page (59).png',
    'books/exemplary/page (60).png',
    'books/exemplary/page (61).png',
    'books/exemplary/page (62).png',
    'books/exemplary/page (63).png',
    'books/exemplary/page (64).png',
    'books/exemplary/page (65).png',
    'books/exemplary/page (66).png',
    'books/exemplary/page (67).png',
    'books/exemplary/page (68).png',
    'books/exemplary/page (69).png',
    'books/exemplary/page (70).png',
    'books/exemplary/page (71).png',
    'books/exemplary/page (72).png',
    'books/exemplary/page (73).png',
    'books/exemplary/page (74).png',
    'books/exemplary/page (75).png',
    'books/exemplary/page (76).png',
    'books/exemplary/page (77).png',
    'books/exemplary/page (78).png',
    'books/exemplary/page (79).png',
    'books/exemplary/page (80).png',
    'books/exemplary/page (81).png',
    'books/exemplary/page (82).png',
    'books/exemplary/page (83).png',
    'books/exemplary/page (84).png',
    'books/exemplary/page (85).png',
    'books/exemplary/page (86).png',
    'books/exemplary/page (87).png',
    'books/exemplary/page (88).png',
    'books/exemplary/page (89).png',
    'books/exemplary/page (90).png',
    'books/exemplary/page (91).png',
    'books/exemplary/page (92).png',
    'books/exemplary/page (93).png',
    'books/exemplary/page (94).png',
    'books/exemplary/page (95).png',
    'books/exemplary/page (96).png',
    'books/exemplary/page (97).png',
    'books/exemplary/page (98).png',
    'books/exemplary/page (99).png',
    'books/exemplary/page (100).png',
    'books/exemplary/page (101).png',
    'books/exemplary/page (102).png',
    'books/exemplary/page (103).png',
    'books/exemplary/page (104).png',
    'books/exemplary/page (105).png',
    'books/exemplary/page (106).png',
    'books/exemplary/page (107).png',
    'books/exemplary/page (108).png',
    'books/exemplary/page (109).png',
    'books/exemplary/page (110).png',
    'books/exemplary/page (111).png',
    'books/exemplary/page (112).png',
    'books/exemplary/page (113).png',
    'books/exemplary/page (114).png',
    'books/exemplary/page (115).png',
    'books/exemplary/page (116).png',
    'books/exemplary/page (117).png',
    'books/exemplary/page (118).png',
    'books/exemplary/page (119).png',
    'books/exemplary/page (120).png',
    'books/exemplary/page (121).png',
    'books/exemplary/page (122).png',
    'books/exemplary/page (123).png',
    'books/exemplary/page (124).png',
    'books/exemplary/page (125).png',
    'books/exemplary/page (126).png',
    'books/exemplary/page (127).png',
    'books/exemplary/page (128).png',
    'books/exemplary/page (129).png',
    'books/exemplary/page (130).png',
    'books/exemplary/page (131).png',
    'books/exemplary/page (132).png',
    'books/exemplary/page (133).png',
    'books/exemplary/page (134).png',
    'books/exemplary/page (135).png',
    'books/exemplary/page (136).png',
    'books/exemplary/page (137).png',
    'books/exemplary/page (138).png',
    'books/exemplary/page (139).png',
    'books/exemplary/page (140).png',
    'books/exemplary/page (141).png',
    'books/exemplary/page (142).png',
    'books/exemplary/page (143).png',
    'books/exemplary/page (144).png',
    'books/exemplary/page (145).png',
    'books/exemplary/page (146).png',
    'books/exemplary/page (147).png',
    'books/exemplary/page (148).png',
    'books/exemplary/page (149).png',
    'books/exemplary/page (150).png',
    'books/exemplary/page (151).png',
    'books/exemplary/page (152).png',
    'books/exemplary/page (153).png',
    'books/exemplary/page (154).png',
    'books/exemplary/page (155).png',
    'books/exemplary/page (156).png',
    'books/exemplary/page (157).png',
    'books/exemplary/page (158).png',
    'books/exemplary/page (159).png',
    'books/exemplary/page (160).png',
    'books/exemplary/page (161).png',
    'books/exemplary/page (162).png',
    'books/exemplary/page (163).png',
    'books/exemplary/page (164).png',
    'books/exemplary/page (165).png',
    'books/exemplary/page (166).png',
    'books/exemplary/page (167).png',
    'books/exemplary/page (168).png',
    'books/exemplary/page (169).png',
    'books/exemplary/page (170).png',
    'books/exemplary/page (171).png',
    'books/exemplary/page (172).png',
    'books/exemplary/page (173).png',
    'books/exemplary/page (174).png',
    'books/exemplary/page (175).png',
    'books/exemplary/page (176).png',
    'books/exemplary/page (177).png',
    'books/exemplary/page (178).png',
    'books/exemplary/page (179).png',
    'books/exemplary/page (180).png',
    'books/exemplary/page (181).png',
    'books/exemplary/page (182).png',
    'books/exemplary/page (183).png',
    'books/exemplary/page (184).png',
    'books/exemplary/page (185).png',
    'books/exemplary/page (186).png',
    'books/exemplary/page (187).png',
    'books/exemplary/page (188).png',
    'books/exemplary/page (189).png',
    'books/exemplary/page (190).png',
    'books/exemplary/page (191).png',
    'books/exemplary/page (192).png',
    'books/exemplary/page (193).png',
    'books/exemplary/page (194).png',
    'books/exemplary/page (195).png',
    'books/exemplary/page (196).png',
    'books/exemplary/page (197).png',
    'books/exemplary/page (198).png',
    'books/exemplary/page (199).png',
    'books/exemplary/page (200).png',
    'books/exemplary/page (201).png',
    'books/exemplary/page (202).png',
    'books/exemplary/page (203).png',
    'books/exemplary/page (204).png',
    'books/exemplary/page (205).png',
    'books/exemplary/page (206).png',
    'books/exemplary/page (207).png',
    'books/exemplary/page (208).png',
    'books/exemplary/page (209).png',
    'books/exemplary/page (210).png',
    'books/exemplary/page (211).png',
    'books/exemplary/page (212).png',
    'books/exemplary/page (213).png',
    'books/exemplary/page (214).png',
    'books/exemplary/page (215).png',
    'books/exemplary/page (216).png',
    'books/exemplary/page (217).png',
    'books/exemplary/page (218).png',
    'books/exemplary/page (219).png',
    'books/exemplary/page (220).png',
    'books/exemplary/page (221).png',
    'books/exemplary/page (222).png',
    'books/exemplary/page (223).png',
    'books/exemplary/page (224).png',
    'books/exemplary/page (225).png',
    'books/exemplary/page (226).png',
    'books/exemplary/page (227).png',
    'books/exemplary/page (228).png',
    'books/exemplary/page (229).png',
    'books/exemplary/page (230).png',
    'books/exemplary/page (231).png',
    'books/exemplary/page (232).png',
    'books/exemplary/page (233).png',
    'books/exemplary/page (234).png',
    'books/exemplary/page (235).png',
    'books/exemplary/page (236).png',
    'books/exemplary/page (237).png',
    'books/exemplary/page (238).png',
    'books/exemplary/page (239).png',
    'books/exemplary/page (240).png',
    'books/exemplary/page (241).png',
    'books/exemplary/page (242).png',
    'books/exemplary/page (243).png',
    'books/exemplary/page (244).png',
    'books/exemplary/page (245).png',
    'books/exemplary/page (246).png',
    'books/exemplary/page (247).png',
    'books/exemplary/page (248).png',
    'books/exemplary/page (249).png',
    'books/exemplary/page (250).png',
    'books/exemplary/page (251).png',
    'books/exemplary/page (252).png',
    'books/exemplary/page (253).png',
    'books/exemplary/page (254).png',
    'books/exemplary/page (255).png',
    'books/exemplary/page (256).png',
    'books/exemplary/page (257).png',
    'books/exemplary/page (258).png',
    'books/exemplary/page (259).png',
    'books/exemplary/page (260).png',
    'books/exemplary/page (261).png',
    'books/exemplary/page (262).png',
    'books/exemplary/page (263).png',
    'books/exemplary/page (264).png',
    'books/exemplary/page (265).png',
    'books/exemplary/page (266).png',
    'books/exemplary/page (267).png',
    'books/exemplary/page (268).png',
    'books/exemplary/page (269).png',
    'books/exemplary/page (270).png',
    'books/exemplary/page (271).png',
    'books/exemplary/page (272).png',
    'books/exemplary/page (273).png',
    'books/exemplary/page (274).png',
    'books/exemplary/page (275).png',
    'books/exemplary/page (276).png',
    'books/exemplary/page (277).png',
    'books/exemplary/page (278).png',
    'books/exemplary/page (279).png',
    'books/exemplary/page (280).png',
    'books/exemplary/page (281).png',
    'books/exemplary/page (282).png',
    'books/exemplary/page (283).png',
    'books/exemplary/page (284).png',
    'books/exemplary/page (285).png',
    'books/exemplary/page (286).png',
    'books/exemplary/page (287).png',
    'books/exemplary/page (288).png',
    'books/exemplary/page (289).png',
    'books/exemplary/page (290).png',
    'books/exemplary/page (291).png',
    'books/exemplary/page (292).png',
    'books/exemplary/page (293).png',
    'books/exemplary/page (294).png',
    'books/exemplary/page (295).png',
    'books/exemplary/page (296).png',
    'books/exemplary/page (297).png',
    'books/exemplary/page (298).png',
    'books/exemplary/page (299).png',
    'books/exemplary/page (300).png',
    'books/exemplary/page (301).png',
    'books/exemplary/page (302).png',
    'books/exemplary/page (303).png',
    'books/exemplary/page (304).png',
    'books/exemplary/page (305).png',
    'books/exemplary/page (306).png',
    'books/exemplary/page (307).png',
    'books/exemplary/page (308).png',
    'books/exemplary/page (309).png',
    'books/exemplary/page (310).png',
    'books/exemplary/page (311).png',
    'books/exemplary/page (312).png',
    'books/exemplary/page (313).png',
    'books/exemplary/page (314).png',
    'books/exemplary/page (315).png',
    'books/exemplary/page (316).png',
    'books/exemplary/page (317).png',
    'books/exemplary/page (318).png',
    'books/exemplary/page (319).png',
    'books/exemplary/page (320).png',
    'books/exemplary/page (321).png',
    'books/exemplary/page (322).png',
    'books/exemplary/page (323).png',
    'books/exemplary/page (324).png',
    'books/exemplary/page (325).png',
    'books/exemplary/page (326).png',
    'books/exemplary/page (327).png',
    'books/exemplary/page (328).png',
    'books/exemplary/page (329).png',
    'books/exemplary/page (330).png',
    'books/exemplary/page (331).png',
    'books/exemplary/page (332).png',
    'books/exemplary/page (333).png',
    'books/exemplary/page (334).png',
    'books/exemplary/page (335).png',
    'books/exemplary/page (336).png',
    'books/exemplary/page (337).png',
    'books/exemplary/page (338).png',
    'books/exemplary/page (339).png',
    'books/exemplary/page (340).png',
    'books/exemplary/page (341).png',
    'books/exemplary/page (342).png',
    'books/exemplary/page (343).png',
    'books/exemplary/page (344).png',
    'books/exemplary/page (345).png',
    'books/exemplary/page (346).png',
    'books/exemplary/page (347).png',
    'books/exemplary/page (348).png',
    'books/exemplary/page (349).png',
    'books/exemplary/page (350).png',
    'books/exemplary/page (351).png',
    'books/exemplary/page (352).png',
    'books/exemplary/page (353).png',
    'books/exemplary/page (354).png',
    'books/exemplary/page (355).png',
    'books/exemplary/page (356).png',
    'books/exemplary/page (357).png',
    'books/exemplary/page (358).png',
    'books/exemplary/page (359).png',
    'books/exemplary/page (360).png',
    'books/exemplary/page (361).png',
    'books/exemplary/page (362).png',
    'books/exemplary/page (363).png',
    'books/exemplary/page (364).png',
    'books/exemplary/page (365).png',
    'books/exemplary/page (366).png',
    'books/exemplary/page (367).png',
    'books/exemplary/page (368).png',
    'books/exemplary/page (369).png',
    'books/exemplary/page (370).png',
    'books/exemplary/page (371).png',
    'books/exemplary/page (372).png',
    'books/exemplary/page (373).png',
    'books/exemplary/page (374).png',
    'books/exemplary/page (375).png',
    'books/exemplary/page (376).png',
    'books/exemplary/page (377).png',
    'books/exemplary/page (378).png',
    'books/exemplary/page (379).png',
    'books/exemplary/page (380).png',
    'books/exemplary/page (381).png',
    'books/exemplary/page (382).png',
    'books/exemplary/page (383).png',
    'books/exemplary/page (384).png',
    'books/exemplary/page (385).png',
    'books/exemplary/page (386).png',
    'books/exemplary/page (387).png',
    'books/exemplary/page (388).png',
    'books/exemplary/page (389).png',
    'books/exemplary/page (390).png',
    'books/exemplary/page (391).png',
    'books/exemplary/page (392).png',
    'books/exemplary/page (393).png',
    'books/exemplary/page (394).png',
    'books/exemplary/page (395).png',
    'books/exemplary/page (396).png',
    'books/exemplary/page (397).png',
    'books/exemplary/page (398).png',
    'books/exemplary/page (399).png',
    'books/exemplary/page (400).png',
    'books/exemplary/page (401).png',
    'books/exemplary/page (402).png',
    'books/exemplary/page (403).png',
    'books/exemplary/page (404).png',
    'books/exemplary/page (405).png',
    'books/exemplary/page (406).png',
    'books/exemplary/page (407).png',
    'books/exemplary/page (408).png',
    'books/exemplary/page (409).png',
    'books/exemplary/page (410).png',
    'books/exemplary/page (411).png',
    'books/exemplary/page (412).png',
    'books/exemplary/page (413).png',
    'books/exemplary/page (414).png',
    'books/exemplary/page (415).png',
    'books/exemplary/page (416).png',
    'books/exemplary/page (417).png',
    'books/exemplary/page (418).png',
    'books/exemplary/page (419).png',
    'books/exemplary/page (420).png',
    'books/exemplary/page (421).png',
    'books/exemplary/page (422).png',
    'books/exemplary/page (423).png',
    'books/exemplary/page (424).png',
    'books/exemplary/page (425).png',
    'books/exemplary/page (426).png',
    'books/exemplary/page (427).png',
    'books/exemplary/page (428).png',
    'books/exemplary/page (429).png',
    'books/exemplary/page (430).png',
    'books/exemplary/page (431).png',
    'books/exemplary/page (432).png',
    'books/exemplary/page (433).png',
    'books/exemplary/page (434).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
