import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class historyengland2 extends StatefulWidget {
  const historyengland2({Key? key}) : super(key: key);

  @override
  State<historyengland2> createState() => _historyengland2State();
}

class _historyengland2State extends State<historyengland2> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/history england 2/page (1).png',
    'books/history england 2/page (2).png',
    'books/history england 2/page (3).png',
    'books/history england 2/page (4).png',
    'books/history england 2/page (5).png',
    'books/history england 2/page (6).png',
    'books/history england 2/page (7).png',
    'books/history england 2/page (8).png',
    'books/history england 2/page (9).png',
    'books/history england 2/page (10).png',
    'books/history england 2/page (11).png',
    'books/history england 2/page (12).png',
    'books/history england 2/page (13).png',
    'books/history england 2/page (14).png',
    'books/history england 2/page (15).png',
    'books/history england 2/page (16).png',
    'books/history england 2/page (17).png',
    'books/history england 2/page (18).png',
    'books/history england 2/page (19).png',
    'books/history england 2/page (20).png',
    'books/history england 2/page (21).png',
    'books/history england 2/page (22).png',
    'books/history england 2/page (23).png',
    'books/history england 2/page (24).png',
    'books/history england 2/page (25).png',
    'books/history england 2/page (26).png',
    'books/history england 2/page (27).png',
    'books/history england 2/page (28).png',
    'books/history england 2/page (29).png',
    'books/history england 2/page (30).png',
    'books/history england 2/page (31).png',
    'books/history england 2/page (32).png',
    'books/history england 2/page (33).png',
    'books/history england 2/page (34).png',
    'books/history england 2/page (35).png',
    'books/history england 2/page (36).png',
    'books/history england 2/page (37).png',
    'books/history england 2/page (38).png',
    'books/history england 2/page (39).png',
    'books/history england 2/page (40).png',
    'books/history england 2/page (41).png',
    'books/history england 2/page (42).png',
    'books/history england 2/page (43).png',
    'books/history england 2/page (44).png',
    'books/history england 2/page (45).png',
    'books/history england 2/page (46).png',
    'books/history england 2/page (47).png',
    'books/history england 2/page (48).png',
    'books/history england 2/page (49).png',
    'books/history england 2/page (50).png',
    'books/history england 2/page (51).png',
    'books/history england 2/page (52).png',
    'books/history england 2/page (53).png',
    'books/history england 2/page (54).png',
    'books/history england 2/page (55).png',
    'books/history england 2/page (56).png',
    'books/history england 2/page (57).png',
    'books/history england 2/page (58).png',
    'books/history england 2/page (59).png',
    'books/history england 2/page (60).png',
    'books/history england 2/page (61).png',
    'books/history england 2/page (62).png',
    'books/history england 2/page (63).png',
    'books/history england 2/page (64).png',
    'books/history england 2/page (65).png',
    'books/history england 2/page (66).png',
    'books/history england 2/page (67).png',
    'books/history england 2/page (68).png',
    'books/history england 2/page (69).png',
    'books/history england 2/page (70).png',
    'books/history england 2/page (71).png',
    'books/history england 2/page (72).png',
    'books/history england 2/page (73).png',
    'books/history england 2/page (74).png',
    'books/history england 2/page (75).png',
    'books/history england 2/page (76).png',
    'books/history england 2/page (77).png',
    'books/history england 2/page (78).png',
    'books/history england 2/page (79).png',
    'books/history england 2/page (80).png',
    'books/history england 2/page (81).png',
    'books/history england 2/page (82).png',
    'books/history england 2/page (83).png',
    'books/history england 2/page (84).png',
    'books/history england 2/page (85).png',
    'books/history england 2/page (86).png',
    'books/history england 2/page (87).png',
    'books/history england 2/page (88).png',
    'books/history england 2/page (89).png',
    'books/history england 2/page (90).png',
    'books/history england 2/page (91).png',
    'books/history england 2/page (92).png',
    'books/history england 2/page (93).png',
    'books/history england 2/page (94).png',
    'books/history england 2/page (95).png',
    'books/history england 2/page (96).png',
    'books/history england 2/page (97).png',
    'books/history england 2/page (98).png',
    'books/history england 2/page (99).png',
    'books/history england 2/page (100).png',
    'books/history england 2/page (101).png',
    'books/history england 2/page (102).png',
    'books/history england 2/page (103).png',
    'books/history england 2/page (104).png',
    'books/history england 2/page (105).png',
    'books/history england 2/page (106).png',
    'books/history england 2/page (107).png',
    'books/history england 2/page (108).png',
    'books/history england 2/page (109).png',
    'books/history england 2/page (110).png',
    'books/history england 2/page (111).png',
    'books/history england 2/page (112).png',
    'books/history england 2/page (113).png',
    'books/history england 2/page (114).png',
    'books/history england 2/page (115).png',
    'books/history england 2/page (116).png',
    'books/history england 2/page (117).png',
    'books/history england 2/page (118).png',
    'books/history england 2/page (119).png',
    'books/history england 2/page (120).png',
    'books/history england 2/page (121).png',
    'books/history england 2/page (122).png',
    'books/history england 2/page (123).png',
    'books/history england 2/page (124).png',
    'books/history england 2/page (125).png',
    'books/history england 2/page (126).png',
    'books/history england 2/page (127).png',
    'books/history england 2/page (128).png',
    'books/history england 2/page (129).png',
    'books/history england 2/page (130).png',
    'books/history england 2/page (131).png',
    'books/history england 2/page (132).png',
    'books/history england 2/page (133).png',
    'books/history england 2/page (134).png',
    'books/history england 2/page (135).png',
    'books/history england 2/page (136).png',
    'books/history england 2/page (137).png',
    'books/history england 2/page (138).png',
    'books/history england 2/page (139).png',
    'books/history england 2/page (140).png',
    'books/history england 2/page (141).png',
    'books/history england 2/page (142).png',
    'books/history england 2/page (143).png',
    'books/history england 2/page (144).png',
    'books/history england 2/page (145).png',
    'books/history england 2/page (146).png',
    'books/history england 2/page (147).png',
    'books/history england 2/page (148).png',
    'books/history england 2/page (149).png',
    'books/history england 2/page (150).png',
    'books/history england 2/page (151).png',
    'books/history england 2/page (152).png',
    'books/history england 2/page (153).png',
    'books/history england 2/page (154).png',
    'books/history england 2/page (155).png',
    'books/history england 2/page (156).png',
    'books/history england 2/page (157).png',
    'books/history england 2/page (158).png',
    'books/history england 2/page (159).png',
    'books/history england 2/page (160).png',
    'books/history england 2/page (161).png',
    'books/history england 2/page (162).png',
    'books/history england 2/page (163).png',
    'books/history england 2/page (164).png',
    'books/history england 2/page (165).png',
    'books/history england 2/page (166).png',
    'books/history england 2/page (167).png',
    'books/history england 2/page (168).png',
    'books/history england 2/page (169).png',
    'books/history england 2/page (170).png',
    'books/history england 2/page (171).png',
    'books/history england 2/page (172).png',
    'books/history england 2/page (173).png',
    'books/history england 2/page (174).png',
    'books/history england 2/page (175).png',
    'books/history england 2/page (176).png',
    'books/history england 2/page (177).png',
    'books/history england 2/page (178).png',
    'books/history england 2/page (179).png',
    'books/history england 2/page (180).png',
    'books/history england 2/page (181).png',
    'books/history england 2/page (182).png',
    'books/history england 2/page (183).png',
    'books/history england 2/page (184).png',
    'books/history england 2/page (185).png',
    'books/history england 2/page (186).png',
    'books/history england 2/page (187).png',
    'books/history england 2/page (188).png',
    'books/history england 2/page (189).png',
    'books/history england 2/page (190).png',
    'books/history england 2/page (191).png',
    'books/history england 2/page (192).png',
    'books/history england 2/page (193).png',
    'books/history england 2/page (194).png',
    'books/history england 2/page (195).png',
    'books/history england 2/page (196).png',
    'books/history england 2/page (197).png',
    'books/history england 2/page (198).png',
    'books/history england 2/page (199).png',
    'books/history england 2/page (200).png',
    'books/history england 2/page (201).png',
    'books/history england 2/page (202).png',
    'books/history england 2/page (203).png',
    'books/history england 2/page (204).png',
    'books/history england 2/page (205).png',
    'books/history england 2/page (206).png',
    'books/history england 2/page (207).png',
    'books/history england 2/page (208).png',
    'books/history england 2/page (209).png',
    'books/history england 2/page (210).png',
    'books/history england 2/page (211).png',
    'books/history england 2/page (212).png',
    'books/history england 2/page (213).png',
    'books/history england 2/page (214).png',
    'books/history england 2/page (215).png',
    'books/history england 2/page (216).png',
    'books/history england 2/page (217).png',
    'books/history england 2/page (218).png',
    'books/history england 2/page (219).png',
    'books/history england 2/page (220).png',
    'books/history england 2/page (221).png',
    'books/history england 2/page (222).png',
    'books/history england 2/page (223).png',
    'books/history england 2/page (224).png',
    'books/history england 2/page (225).png',
    'books/history england 2/page (226).png',
    'books/history england 2/page (227).png',
    'books/history england 2/page (228).png',
    'books/history england 2/page (229).png',
    'books/history england 2/page (230).png',
    'books/history england 2/page (231).png',
    'books/history england 2/page (232).png',
    'books/history england 2/page (233).png',
    'books/history england 2/page (234).png',
    'books/history england 2/page (235).png',
    'books/history england 2/page (236).png',
    'books/history england 2/page (237).png',
    'books/history england 2/page (238).png',
    'books/history england 2/page (239).png',
    'books/history england 2/page (240).png',
    'books/history england 2/page (241).png',
    'books/history england 2/page (242).png',
    'books/history england 2/page (243).png',
    'books/history england 2/page (244).png',
    'books/history england 2/page (245).png',
    'books/history england 2/page (246).png',
    'books/history england 2/page (247).png',
    'books/history england 2/page (248).png',
    'books/history england 2/page (249).png',
    'books/history england 2/page (250).png',
    'books/history england 2/page (251).png',
    'books/history england 2/page (252).png',
    'books/history england 2/page (253).png',
    'books/history england 2/page (254).png',
    'books/history england 2/page (255).png',
    'books/history england 2/page (256).png',
    'books/history england 2/page (257).png',
    'books/history england 2/page (258).png',
    'books/history england 2/page (259).png',
    'books/history england 2/page (260).png',
    'books/history england 2/page (261).png',
    'books/history england 2/page (262).png',
    'books/history england 2/page (263).png',
    'books/history england 2/page (264).png',
    'books/history england 2/page (265).png',
    'books/history england 2/page (266).png',
    'books/history england 2/page (267).png',
    'books/history england 2/page (268).png',
    'books/history england 2/page (269).png',
    'books/history england 2/page (270).png',
    'books/history england 2/page (271).png',
    'books/history england 2/page (272).png',
    'books/history england 2/page (273).png',
    'books/history england 2/page (274).png',
    'books/history england 2/page (275).png',
    'books/history england 2/page (276).png',
    'books/history england 2/page (277).png',
    'books/history england 2/page (278).png',
    'books/history england 2/page (279).png',
    'books/history england 2/page (280).png',
    'books/history england 2/page (281).png',
    'books/history england 2/page (282).png',
    'books/history england 2/page (283).png',
    'books/history england 2/page (284).png',
    'books/history england 2/page (285).png',
    'books/history england 2/page (286).png',
    'books/history england 2/page (287).png',
    'books/history england 2/page (288).png',
    'books/history england 2/page (289).png',
    'books/history england 2/page (290).png',
    'books/history england 2/page (291).png',
    'books/history england 2/page (292).png',
    'books/history england 2/page (293).png',
    'books/history england 2/page (294).png',
    'books/history england 2/page (295).png',
    'books/history england 2/page (296).png',
    'books/history england 2/page (297).png',
    'books/history england 2/page (298).png',
    'books/history england 2/page (299).png',
    'books/history england 2/page (300).png',
    'books/history england 2/page (301).png',
    'books/history england 2/page (302).png',
    'books/history england 2/page (303).png',
    'books/history england 2/page (304).png',
    'books/history england 2/page (305).png',
    'books/history england 2/page (306).png',
    'books/history england 2/page (307).png',
    'books/history england 2/page (308).png',
    'books/history england 2/page (309).png',
    'books/history england 2/page (310).png',
    'books/history england 2/page (311).png',
    'books/history england 2/page (312).png',
    'books/history england 2/page (313).png',
    'books/history england 2/page (314).png',
    'books/history england 2/page (315).png',
    'books/history england 2/page (316).png',
    'books/history england 2/page (317).png',
    'books/history england 2/page (318).png',
    'books/history england 2/page (319).png',
    'books/history england 2/page (320).png',
    'books/history england 2/page (321).png',
    'books/history england 2/page (322).png',
    'books/history england 2/page (323).png',
    'books/history england 2/page (324).png',
    'books/history england 2/page (325).png',
    'books/history england 2/page (326).png',
    'books/history england 2/page (327).png',
    'books/history england 2/page (328).png',
    'books/history england 2/page (329).png',
    'books/history england 2/page (330).png',
    'books/history england 2/page (331).png',
    'books/history england 2/page (332).png',
    'books/history england 2/page (333).png',
    'books/history england 2/page (334).png',
    'books/history england 2/page (335).png',
    'books/history england 2/page (336).png',
    'books/history england 2/page (337).png',
    'books/history england 2/page (338).png',
    'books/history england 2/page (339).png',
    'books/history england 2/page (340).png',
    'books/history england 2/page (341).png',
    'books/history england 2/page (342).png',
    'books/history england 2/page (343).png',
    'books/history england 2/page (344).png',
    'books/history england 2/page (345).png',
    'books/history england 2/page (346).png',
    'books/history england 2/page (347).png',
    'books/history england 2/page (348).png',
    'books/history england 2/page (349).png',
    'books/history england 2/page (350).png',
    'books/history england 2/page (351).png',
    'books/history england 2/page (352).png',
    'books/history england 2/page (353).png',
    'books/history england 2/page (354).png',
    'books/history england 2/page (355).png',
    'books/history england 2/page (356).png',
    'books/history england 2/page (357).png',
    'books/history england 2/page (358).png',
    'books/history england 2/page (359).png',
    'books/history england 2/page (360).png',
    'books/history england 2/page (361).png',
    'books/history england 2/page (362).png',
    'books/history england 2/page (363).png',
    'books/history england 2/page (364).png',
    'books/history england 2/page (365).png',
    'books/history england 2/page (366).png',
    'books/history england 2/page (367).png',
    'books/history england 2/page (368).png',
    'books/history england 2/page (369).png',
    'books/history england 2/page (370).png',
    'books/history england 2/page (371).png',
    'books/history england 2/page (372).png',
    'books/history england 2/page (373).png',
    'books/history england 2/page (374).png',
    'books/history england 2/page (375).png',
    'books/history england 2/page (376).png',
    'books/history england 2/page (377).png',
    'books/history england 2/page (378).png',
    'books/history england 2/page (379).png',
    'books/history england 2/page (380).png',
    'books/history england 2/page (381).png',
    'books/history england 2/page (382).png',
    'books/history england 2/page (383).png',
    'books/history england 2/page (384).png',
    'books/history england 2/page (385).png',
    'books/history england 2/page (386).png',
    'books/history england 2/page (387).png',
    'books/history england 2/page (388).png',
    'books/history england 2/page (389).png',
    'books/history england 2/page (390).png',
    'books/history england 2/page (391).png',
    'books/history england 2/page (392).png',
    'books/history england 2/page (393).png',
    'books/history england 2/page (394).png',
    'books/history england 2/page (395).png',
    'books/history england 2/page (396).png',
    'books/history england 2/page (397).png',
    'books/history england 2/page (398).png',
    'books/history england 2/page (399).png',
    'books/history england 2/page (400).png',
    'books/history england 2/page (401).png',
    'books/history england 2/page (402).png',
    'books/history england 2/page (403).png',
    'books/history england 2/page (404).png',
    'books/history england 2/page (405).png',
    'books/history england 2/page (406).png',
    'books/history england 2/page (407).png',
    'books/history england 2/page (408).png',
    'books/history england 2/page (409).png',
    'books/history england 2/page (410).png',
    'books/history england 2/page (411).png',
    'books/history england 2/page (412).png',
    'books/history england 2/page (413).png',
    'books/history england 2/page (414).png',
    'books/history england 2/page (415).png',
    'books/history england 2/page (416).png',
    'books/history england 2/page (417).png',
    'books/history england 2/page (418).png',
    'books/history england 2/page (419).png',
    'books/history england 2/page (420).png',
    'books/history england 2/page (421).png',
    'books/history england 2/page (422).png',
    'books/history england 2/page (423).png',
    'books/history england 2/page (424).png',
    'books/history england 2/page (425).png',
    'books/history england 2/page (426).png',
    'books/history england 2/page (427).png',
    'books/history england 2/page (428).png',
    'books/history england 2/page (429).png',
    'books/history england 2/page (430).png',
    'books/history england 2/page (431).png',
    'books/history england 2/page (432).png',
    'books/history england 2/page (433).png',
    'books/history england 2/page (434).png',
    'books/history england 2/page (435).png',
    'books/history england 2/page (436).png',
    'books/history england 2/page (437).png',
    'books/history england 2/page (438).png',
    'books/history england 2/page (439).png',
    'books/history england 2/page (440).png',
    'books/history england 2/page (441).png',
    'books/history england 2/page (442).png',
    'books/history england 2/page (443).png',
    'books/history england 2/page (444).png',
    'books/history england 2/page (445).png',
    'books/history england 2/page (446).png',
    'books/history england 2/page (447).png',
    'books/history england 2/page (448).png',
    'books/history england 2/page (449).png',
    'books/history england 2/page (450).png',
    'books/history england 2/page (451).png',
    'books/history england 2/page (452).png',
    'books/history england 2/page (453).png',
    'books/history england 2/page (454).png',
    'books/history england 2/page (455).png',
    'books/history england 2/page (456).png',
    'books/history england 2/page (457).png',
    'books/history england 2/page (458).png',
    'books/history england 2/page (459).png',
    'books/history england 2/page (460).png',
    'books/history england 2/page (461).png',
    'books/history england 2/page (462).png',
    'books/history england 2/page (463).png',
    'books/history england 2/page (464).png',
    'books/history england 2/page (465).png',
    'books/history england 2/page (466).png',
    'books/history england 2/page (467).png',
    'books/history england 2/page (468).png',
    'books/history england 2/page (469).png',
    'books/history england 2/page (470).png',
    'books/history england 2/page (471).png',
    'books/history england 2/page (472).png',
    'books/history england 2/page (473).png',
    'books/history england 2/page (474).png',
    'books/history england 2/page (475).png',
    'books/history england 2/page (476).png',
    'books/history england 2/page (477).png',
    'books/history england 2/page (478).png',
    'books/history england 2/page (479).png',
    'books/history england 2/page (480).png',
    'books/history england 2/page (481).png',
    'books/history england 2/page (482).png',
    'books/history england 2/page (483).png',
    'books/history england 2/page (484).png',
    'books/history england 2/page (485).png',
    'books/history england 2/page (486).png',
    'books/history england 2/page (487).png',
    'books/history england 2/page (488).png',
    'books/history england 2/page (489).png',
    'books/history england 2/page (490).png',
    'books/history england 2/page (491).png',
    'books/history england 2/page (492).png',
    'books/history england 2/page (493).png',
    'books/history england 2/page (494).png',
    'books/history england 2/page (495).png',
    'books/history england 2/page (496).png',
    'books/history england 2/page (497).png',
    'books/history england 2/page (498).png',
    'books/history england 2/page (499).png',
    'books/history england 2/page (500).png',
    'books/history england 2/page (501).png',
    'books/history england 2/page (502).png',
    'books/history england 2/page (503).png',
    'books/history england 2/page (504).png',
    'books/history england 2/page (505).png',
    'books/history england 2/page (506).png',
    'books/history england 2/page (507).png',
    'books/history england 2/page (508).png',
    'books/history england 2/page (509).png',
    'books/history england 2/page (510).png',
    'books/history england 2/page (511).png',
    'books/history england 2/page (512).png',
    'books/history england 2/page (513).png',
    'books/history england 2/page (514).png',
    'books/history england 2/page (515).png',
    'books/history england 2/page (516).png',
    'books/history england 2/page (517).png',
    'books/history england 2/page (518).png',
    'books/history england 2/page (519).png',
    'books/history england 2/page (520).png',
    'books/history england 2/page (521).png',
    'books/history england 2/page (522).png',
    'books/history england 2/page (523).png',
    'books/history england 2/page (524).png',
    'books/history england 2/page (525).png',
    'books/history england 2/page (526).png',
    'books/history england 2/page (527).png',
    'books/history england 2/page (528).png',
    'books/history england 2/page (529).png',
    'books/history england 2/page (530).png',
    'books/history england 2/page (531).png',
    'books/history england 2/page (532).png',
    'books/history england 2/page (533).png',
    'books/history england 2/page (534).png',
    'books/history england 2/page (535).png',
    'books/history england 2/page (536).png',
    'books/history england 2/page (537).png',
    'books/history england 2/page (538).png',
    'books/history england 2/page (539).png',
    'books/history england 2/page (540).png',
    'books/history england 2/page (541).png',
    'books/history england 2/page (542).png',
    'books/history england 2/page (543).png',
    'books/history england 2/page (544).png',
    'books/history england 2/page (545).png',
    'books/history england 2/page (546).png',
    'books/history england 2/page (547).png',
    'books/history england 2/page (548).png',
    'books/history england 2/page (549).png',
    'books/history england 2/page (550).png',
    'books/history england 2/page (551).png',
    'books/history england 2/page (552).png',
    'books/history england 2/page (553).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
