import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class innocents extends StatefulWidget {
  const innocents({Key? key}) : super(key: key);

  @override
  State<innocents> createState() => _innocentsState();
}

class _innocentsState extends State<innocents> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/innocents abroad/page (1).png',
    'books/innocents abroad/page (2).png',
    'books/innocents abroad/page (3).png',
    'books/innocents abroad/page (4).png',
    'books/innocents abroad/page (5).png',
    'books/innocents abroad/page (6).png',
    'books/innocents abroad/page (7).png',
    'books/innocents abroad/page (8).png',
    'books/innocents abroad/page (9).png',
    'books/innocents abroad/page (10).png',
    'books/innocents abroad/page (11).png',
    'books/innocents abroad/page (12).png',
    'books/innocents abroad/page (13).png',
    'books/innocents abroad/page (14).png',
    'books/innocents abroad/page (15).png',
    'books/innocents abroad/page (16).png',
    'books/innocents abroad/page (17).png',
    'books/innocents abroad/page (18).png',
    'books/innocents abroad/page (19).png',
    'books/innocents abroad/page (20).png',
    'books/innocents abroad/page (21).png',
    'books/innocents abroad/page (22).png',
    'books/innocents abroad/page (23).png',
    'books/innocents abroad/page (24).png',
    'books/innocents abroad/page (25).png',
    'books/innocents abroad/page (26).png',
    'books/innocents abroad/page (27).png',
    'books/innocents abroad/page (28).png',
    'books/innocents abroad/page (29).png',
    'books/innocents abroad/page (30).png',
    'books/innocents abroad/page (31).png',
    'books/innocents abroad/page (32).png',
    'books/innocents abroad/page (33).png',
    'books/innocents abroad/page (34).png',
    'books/innocents abroad/page (35).png',
    'books/innocents abroad/page (36).png',
    'books/innocents abroad/page (37).png',
    'books/innocents abroad/page (38).png',
    'books/innocents abroad/page (39).png',
    'books/innocents abroad/page (40).png',
    'books/innocents abroad/page (41).png',
    'books/innocents abroad/page (42).png',
    'books/innocents abroad/page (43).png',
    'books/innocents abroad/page (44).png',
    'books/innocents abroad/page (45).png',
    'books/innocents abroad/page (46).png',
    'books/innocents abroad/page (47).png',
    'books/innocents abroad/page (48).png',
    'books/innocents abroad/page (49).png',
    'books/innocents abroad/page (50).png',
    'books/innocents abroad/page (51).png',
    'books/innocents abroad/page (52).png',
    'books/innocents abroad/page (53).png',
    'books/innocents abroad/page (54).png',
    'books/innocents abroad/page (55).png',
    'books/innocents abroad/page (56).png',
    'books/innocents abroad/page (57).png',
    'books/innocents abroad/page (58).png',
    'books/innocents abroad/page (59).png',
    'books/innocents abroad/page (60).png',
    'books/innocents abroad/page (61).png',
    'books/innocents abroad/page (62).png',
    'books/innocents abroad/page (63).png',
    'books/innocents abroad/page (64).png',
    'books/innocents abroad/page (65).png',
    'books/innocents abroad/page (66).png',
    'books/innocents abroad/page (67).png',
    'books/innocents abroad/page (68).png',
    'books/innocents abroad/page (69).png',
    'books/innocents abroad/page (70).png',
    'books/innocents abroad/page (71).png',
    'books/innocents abroad/page (72).png',
    'books/innocents abroad/page (73).png',
    'books/innocents abroad/page (74).png',
    'books/innocents abroad/page (75).png',
    'books/innocents abroad/page (76).png',
    'books/innocents abroad/page (77).png',
    'books/innocents abroad/page (78).png',
    'books/innocents abroad/page (79).png',
    'books/innocents abroad/page (80).png',
    'books/innocents abroad/page (81).png',
    'books/innocents abroad/page (82).png',
    'books/innocents abroad/page (83).png',
    'books/innocents abroad/page (84).png',
    'books/innocents abroad/page (85).png',
    'books/innocents abroad/page (86).png',
    'books/innocents abroad/page (87).png',
    'books/innocents abroad/page (88).png',
    'books/innocents abroad/page (89).png',
    'books/innocents abroad/page (90).png',
    'books/innocents abroad/page (91).png',
    'books/innocents abroad/page (92).png',
    'books/innocents abroad/page (93).png',
    'books/innocents abroad/page (94).png',
    'books/innocents abroad/page (95).png',
    'books/innocents abroad/page (96).png',
    'books/innocents abroad/page (97).png',
    'books/innocents abroad/page (98).png',
    'books/innocents abroad/page (99).png',
    'books/innocents abroad/page (100).png',
    'books/innocents abroad/page (101).png',
    'books/innocents abroad/page (102).png',
    'books/innocents abroad/page (103).png',
    'books/innocents abroad/page (104).png',
    'books/innocents abroad/page (105).png',
    'books/innocents abroad/page (106).png',
    'books/innocents abroad/page (107).png',
    'books/innocents abroad/page (108).png',
    'books/innocents abroad/page (109).png',
    'books/innocents abroad/page (110).png',
    'books/innocents abroad/page (111).png',
    'books/innocents abroad/page (112).png',
    'books/innocents abroad/page (113).png',
    'books/innocents abroad/page (114).png',
    'books/innocents abroad/page (115).png',
    'books/innocents abroad/page (116).png',
    'books/innocents abroad/page (117).png',
    'books/innocents abroad/page (118).png',
    'books/innocents abroad/page (119).png',
    'books/innocents abroad/page (120).png',
    'books/innocents abroad/page (121).png',
    'books/innocents abroad/page (122).png',
    'books/innocents abroad/page (123).png',
    'books/innocents abroad/page (124).png',
    'books/innocents abroad/page (125).png',
    'books/innocents abroad/page (126).png',
    'books/innocents abroad/page (127).png',
    'books/innocents abroad/page (128).png',
    'books/innocents abroad/page (129).png',
    'books/innocents abroad/page (130).png',
    'books/innocents abroad/page (131).png',
    'books/innocents abroad/page (132).png',
    'books/innocents abroad/page (133).png',
    'books/innocents abroad/page (134).png',
    'books/innocents abroad/page (135).png',
    'books/innocents abroad/page (136).png',
    'books/innocents abroad/page (137).png',
    'books/innocents abroad/page (138).png',
    'books/innocents abroad/page (139).png',
    'books/innocents abroad/page (140).png',
    'books/innocents abroad/page (141).png',
    'books/innocents abroad/page (142).png',
    'books/innocents abroad/page (143).png',
    'books/innocents abroad/page (144).png',
    'books/innocents abroad/page (145).png',
    'books/innocents abroad/page (146).png',
    'books/innocents abroad/page (147).png',
    'books/innocents abroad/page (148).png',
    'books/innocents abroad/page (149).png',
    'books/innocents abroad/page (150).png',
    'books/innocents abroad/page (151).png',
    'books/innocents abroad/page (152).png',
    'books/innocents abroad/page (153).png',
    'books/innocents abroad/page (154).png',
    'books/innocents abroad/page (155).png',
    'books/innocents abroad/page (156).png',
    'books/innocents abroad/page (157).png',
    'books/innocents abroad/page (158).png',
    'books/innocents abroad/page (159).png',
    'books/innocents abroad/page (160).png',
    'books/innocents abroad/page (161).png',
    'books/innocents abroad/page (162).png',
    'books/innocents abroad/page (163).png',
    'books/innocents abroad/page (164).png',
    'books/innocents abroad/page (165).png',
    'books/innocents abroad/page (166).png',
    'books/innocents abroad/page (167).png',
    'books/innocents abroad/page (168).png',
    'books/innocents abroad/page (169).png',
    'books/innocents abroad/page (170).png',
    'books/innocents abroad/page (171).png',
    'books/innocents abroad/page (172).png',
    'books/innocents abroad/page (173).png',
    'books/innocents abroad/page (174).png',
    'books/innocents abroad/page (175).png',
    'books/innocents abroad/page (176).png',
    'books/innocents abroad/page (177).png',
    'books/innocents abroad/page (178).png',
    'books/innocents abroad/page (179).png',
    'books/innocents abroad/page (180).png',
    'books/innocents abroad/page (181).png',
    'books/innocents abroad/page (182).png',
    'books/innocents abroad/page (183).png',
    'books/innocents abroad/page (184).png',
    'books/innocents abroad/page (185).png',
    'books/innocents abroad/page (186).png',
    'books/innocents abroad/page (187).png',
    'books/innocents abroad/page (188).png',
    'books/innocents abroad/page (189).png',
    'books/innocents abroad/page (190).png',
    'books/innocents abroad/page (191).png',
    'books/innocents abroad/page (192).png',
    'books/innocents abroad/page (193).png',
    'books/innocents abroad/page (194).png',
    'books/innocents abroad/page (195).png',
    'books/innocents abroad/page (196).png',
    'books/innocents abroad/page (197).png',
    'books/innocents abroad/page (198).png',
    'books/innocents abroad/page (199).png',
    'books/innocents abroad/page (200).png',
    'books/innocents abroad/page (201).png',
    'books/innocents abroad/page (202).png',
    'books/innocents abroad/page (203).png',
    'books/innocents abroad/page (204).png',
    'books/innocents abroad/page (205).png',
    'books/innocents abroad/page (206).png',
    'books/innocents abroad/page (207).png',
    'books/innocents abroad/page (208).png',
    'books/innocents abroad/page (209).png',
    'books/innocents abroad/page (210).png',
    'books/innocents abroad/page (211).png',
    'books/innocents abroad/page (212).png',
    'books/innocents abroad/page (213).png',
    'books/innocents abroad/page (214).png',
    'books/innocents abroad/page (215).png',
    'books/innocents abroad/page (216).png',
    'books/innocents abroad/page (217).png',
    'books/innocents abroad/page (218).png',
    'books/innocents abroad/page (219).png',
    'books/innocents abroad/page (220).png',
    'books/innocents abroad/page (221).png',
    'books/innocents abroad/page (222).png',
    'books/innocents abroad/page (223).png',
    'books/innocents abroad/page (224).png',
    'books/innocents abroad/page (225).png',
    'books/innocents abroad/page (226).png',
    'books/innocents abroad/page (227).png',
    'books/innocents abroad/page (228).png',
    'books/innocents abroad/page (229).png',
    'books/innocents abroad/page (230).png',
    'books/innocents abroad/page (231).png',
    'books/innocents abroad/page (232).png',
    'books/innocents abroad/page (233).png',
    'books/innocents abroad/page (234).png',
    'books/innocents abroad/page (235).png',
    'books/innocents abroad/page (236).png',
    'books/innocents abroad/page (237).png',
    'books/innocents abroad/page (238).png',
    'books/innocents abroad/page (239).png',
    'books/innocents abroad/page (240).png',
    'books/innocents abroad/page (241).png',
    'books/innocents abroad/page (242).png',
    'books/innocents abroad/page (243).png',
    'books/innocents abroad/page (244).png',
    'books/innocents abroad/page (245).png',
    'books/innocents abroad/page (246).png',
    'books/innocents abroad/page (247).png',
    'books/innocents abroad/page (248).png',
    'books/innocents abroad/page (249).png',
    'books/innocents abroad/page (250).png',
    'books/innocents abroad/page (251).png',
    'books/innocents abroad/page (252).png',
    'books/innocents abroad/page (253).png',
    'books/innocents abroad/page (254).png',
    'books/innocents abroad/page (255).png',
    'books/innocents abroad/page (256).png',
    'books/innocents abroad/page (257).png',
    'books/innocents abroad/page (258).png',
    'books/innocents abroad/page (259).png',
    'books/innocents abroad/page (260).png',
    'books/innocents abroad/page (261).png',
    'books/innocents abroad/page (262).png',
    'books/innocents abroad/page (263).png',
    'books/innocents abroad/page (264).png',
    'books/innocents abroad/page (265).png',
    'books/innocents abroad/page (266).png',
    'books/innocents abroad/page (267).png',
    'books/innocents abroad/page (268).png',
    'books/innocents abroad/page (269).png',
    'books/innocents abroad/page (270).png',
    'books/innocents abroad/page (271).png',
    'books/innocents abroad/page (272).png',
    'books/innocents abroad/page (273).png',
    'books/innocents abroad/page (274).png',
    'books/innocents abroad/page (275).png',
    'books/innocents abroad/page (276).png',
    'books/innocents abroad/page (277).png',
    'books/innocents abroad/page (278).png',
    'books/innocents abroad/page (279).png',
    'books/innocents abroad/page (280).png',
    'books/innocents abroad/page (281).png',
    'books/innocents abroad/page (282).png',
    'books/innocents abroad/page (283).png',
    'books/innocents abroad/page (284).png',
    'books/innocents abroad/page (285).png',
    'books/innocents abroad/page (286).png',
    'books/innocents abroad/page (287).png',
    'books/innocents abroad/page (288).png',
    'books/innocents abroad/page (289).png',
    'books/innocents abroad/page (290).png',
    'books/innocents abroad/page (291).png',
    'books/innocents abroad/page (292).png',
    'books/innocents abroad/page (293).png',
    'books/innocents abroad/page (294).png',
    'books/innocents abroad/page (295).png',
    'books/innocents abroad/page (296).png',
    'books/innocents abroad/page (297).png',
    'books/innocents abroad/page (298).png',
    'books/innocents abroad/page (299).png',
    'books/innocents abroad/page (300).png',
    'books/innocents abroad/page (301).png',
    'books/innocents abroad/page (302).png',
    'books/innocents abroad/page (303).png',
    'books/innocents abroad/page (304).png',
    'books/innocents abroad/page (305).png',
    'books/innocents abroad/page (306).png',
    'books/innocents abroad/page (307).png',
    'books/innocents abroad/page (308).png',
    'books/innocents abroad/page (309).png',
    'books/innocents abroad/page (310).png',
    'books/innocents abroad/page (311).png',
    'books/innocents abroad/page (312).png',
    'books/innocents abroad/page (313).png',
    'books/innocents abroad/page (314).png',
    'books/innocents abroad/page (315).png',
    'books/innocents abroad/page (316).png',
    'books/innocents abroad/page (317).png',
    'books/innocents abroad/page (318).png',
    'books/innocents abroad/page (319).png',
    'books/innocents abroad/page (320).png',
    'books/innocents abroad/page (321).png',
    'books/innocents abroad/page (322).png',
    'books/innocents abroad/page (323).png',
    'books/innocents abroad/page (324).png',
    'books/innocents abroad/page (325).png',
    'books/innocents abroad/page (326).png',
    'books/innocents abroad/page (327).png',
    'books/innocents abroad/page (328).png',
    'books/innocents abroad/page (329).png',
    'books/innocents abroad/page (330).png',
    'books/innocents abroad/page (331).png',
    'books/innocents abroad/page (332).png',
    'books/innocents abroad/page (333).png',
    'books/innocents abroad/page (334).png',
    'books/innocents abroad/page (335).png',
    'books/innocents abroad/page (336).png',
    'books/innocents abroad/page (337).png',
    'books/innocents abroad/page (338).png',
    'books/innocents abroad/page (339).png',
    'books/innocents abroad/page (340).png',
    'books/innocents abroad/page (341).png',
    'books/innocents abroad/page (342).png',
    'books/innocents abroad/page (343).png',
    'books/innocents abroad/page (344).png',
    'books/innocents abroad/page (345).png',
    'books/innocents abroad/page (346).png',
    'books/innocents abroad/page (347).png',
    'books/innocents abroad/page (348).png',
    'books/innocents abroad/page (349).png',
    'books/innocents abroad/page (350).png',
    'books/innocents abroad/page (351).png',
    'books/innocents abroad/page (352).png',
    'books/innocents abroad/page (353).png',
    'books/innocents abroad/page (354).png',
    'books/innocents abroad/page (355).png',
    'books/innocents abroad/page (356).png',
    'books/innocents abroad/page (357).png',
    'books/innocents abroad/page (358).png',
    'books/innocents abroad/page (359).png',
    'books/innocents abroad/page (360).png',
    'books/innocents abroad/page (361).png',
    'books/innocents abroad/page (362).png',
    'books/innocents abroad/page (363).png',
    'books/innocents abroad/page (364).png',
    'books/innocents abroad/page (365).png',
    'books/innocents abroad/page (366).png',
    'books/innocents abroad/page (367).png',
    'books/innocents abroad/page (368).png',
    'books/innocents abroad/page (369).png',
    'books/innocents abroad/page (370).png',
    'books/innocents abroad/page (371).png',
    'books/innocents abroad/page (372).png',
    'books/innocents abroad/page (373).png',
    'books/innocents abroad/page (374).png',
    'books/innocents abroad/page (375).png',
    'books/innocents abroad/page (376).png',
    'books/innocents abroad/page (377).png',
    'books/innocents abroad/page (378).png',
    'books/innocents abroad/page (379).png',
    'books/innocents abroad/page (380).png',
    'books/innocents abroad/page (381).png',
    'books/innocents abroad/page (382).png',
    'books/innocents abroad/page (383).png',
    'books/innocents abroad/page (384).png',
    'books/innocents abroad/page (385).png',
    'books/innocents abroad/page (386).png',
    'books/innocents abroad/page (387).png',
    'books/innocents abroad/page (388).png',
    'books/innocents abroad/page (389).png',
    'books/innocents abroad/page (390).png',
    'books/innocents abroad/page (391).png',
    'books/innocents abroad/page (392).png',
    'books/innocents abroad/page (393).png',
    'books/innocents abroad/page (394).png',
    'books/innocents abroad/page (395).png',
    'books/innocents abroad/page (396).png',
    'books/innocents abroad/page (397).png',
    'books/innocents abroad/page (398).png',
    'books/innocents abroad/page (399).png',
    'books/innocents abroad/page (400).png',
    'books/innocents abroad/page (401).png',
    'books/innocents abroad/page (402).png',
    'books/innocents abroad/page (403).png',
    'books/innocents abroad/page (404).png',
    'books/innocents abroad/page (405).png',
    'books/innocents abroad/page (406).png',
    'books/innocents abroad/page (407).png',
    'books/innocents abroad/page (408).png',
    'books/innocents abroad/page (409).png',
    'books/innocents abroad/page (410).png',
    'books/innocents abroad/page (411).png',
    'books/innocents abroad/page (412).png',
    'books/innocents abroad/page (413).png',
    'books/innocents abroad/page (414).png',
    'books/innocents abroad/page (415).png',
    'books/innocents abroad/page (416).png',
    'books/innocents abroad/page (417).png',
    'books/innocents abroad/page (418).png',
    'books/innocents abroad/page (419).png',
    'books/innocents abroad/page (420).png',
    'books/innocents abroad/page (421).png',
    'books/innocents abroad/page (422).png',
    'books/innocents abroad/page (423).png',
    'books/innocents abroad/page (424).png',
    'books/innocents abroad/page (425).png',
    'books/innocents abroad/page (426).png',
    'books/innocents abroad/page (427).png',
    'books/innocents abroad/page (428).png',
    'books/innocents abroad/page (429).png',
    'books/innocents abroad/page (430).png',
    'books/innocents abroad/page (431).png',
    'books/innocents abroad/page (432).png',
    'books/innocents abroad/page (433).png',
    'books/innocents abroad/page (434).png',
    'books/innocents abroad/page (435).png',
    'books/innocents abroad/page (436).png',
    'books/innocents abroad/page (437).png',
    'books/innocents abroad/page (438).png',
    'books/innocents abroad/page (439).png',
    'books/innocents abroad/page (440).png',
    'books/innocents abroad/page (441).png',
    'books/innocents abroad/page (442).png',
    'books/innocents abroad/page (443).png',
    'books/innocents abroad/page (444).png',
    'books/innocents abroad/page (445).png',
    'books/innocents abroad/page (446).png',
    'books/innocents abroad/page (447).png',
    'books/innocents abroad/page (448).png',
    'books/innocents abroad/page (449).png',
    'books/innocents abroad/page (450).png',
    'books/innocents abroad/page (451).png',
    'books/innocents abroad/page (452).png',
    'books/innocents abroad/page (453).png',
    'books/innocents abroad/page (454).png',
    'books/innocents abroad/page (455).png',
    'books/innocents abroad/page (456).png',
    'books/innocents abroad/page (457).png',
    'books/innocents abroad/page (458).png',
    'books/innocents abroad/page (459).png',
    'books/innocents abroad/page (460).png',
    'books/innocents abroad/page (461).png',
    'books/innocents abroad/page (462).png',
    'books/innocents abroad/page (463).png',
    'books/innocents abroad/page (464).png',
    'books/innocents abroad/page (465).png',
    'books/innocents abroad/page (466).png',
    'books/innocents abroad/page (467).png',
    'books/innocents abroad/page (468).png',
    'books/innocents abroad/page (469).png',
    'books/innocents abroad/page (470).png',
    'books/innocents abroad/page (471).png',
    'books/innocents abroad/page (472).png',
    'books/innocents abroad/page (473).png',
    'books/innocents abroad/page (474).png',
    'books/innocents abroad/page (475).png',
    'books/innocents abroad/page (476).png',
    'books/innocents abroad/page (477).png',
    'books/innocents abroad/page (478).png',
    'books/innocents abroad/page (479).png',
    'books/innocents abroad/page (480).png',
    'books/innocents abroad/page (481).png',
    'books/innocents abroad/page (482).png',
    'books/innocents abroad/page (483).png',
    'books/innocents abroad/page (484).png',
    'books/innocents abroad/page (485).png',
    'books/innocents abroad/page (486).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
