import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class littledorit extends StatefulWidget {
  const littledorit({Key? key}) : super(key: key);

  @override
  State<littledorit> createState() => _littledoritState();
}

class _littledoritState extends State<littledorit> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/little dorrit/page (1).png',
    'books/little dorrit/page (2).png',
    'books/little dorrit/page (3).png',
    'books/little dorrit/page (4).png',
    'books/little dorrit/page (5).png',
    'books/little dorrit/page (6).png',
    'books/little dorrit/page (7).png',
    'books/little dorrit/page (8).png',
    'books/little dorrit/page (9).png',
    'books/little dorrit/page (10).png',
    'books/little dorrit/page (11).png',
    'books/little dorrit/page (12).png',
    'books/little dorrit/page (13).png',
    'books/little dorrit/page (14).png',
    'books/little dorrit/page (15).png',
    'books/little dorrit/page (16).png',
    'books/little dorrit/page (17).png',
    'books/little dorrit/page (18).png',
    'books/little dorrit/page (19).png',
    'books/little dorrit/page (20).png',
    'books/little dorrit/page (21).png',
    'books/little dorrit/page (22).png',
    'books/little dorrit/page (23).png',
    'books/little dorrit/page (24).png',
    'books/little dorrit/page (25).png',
    'books/little dorrit/page (26).png',
    'books/little dorrit/page (27).png',
    'books/little dorrit/page (28).png',
    'books/little dorrit/page (29).png',
    'books/little dorrit/page (30).png',
    'books/little dorrit/page (31).png',
    'books/little dorrit/page (32).png',
    'books/little dorrit/page (33).png',
    'books/little dorrit/page (34).png',
    'books/little dorrit/page (35).png',
    'books/little dorrit/page (36).png',
    'books/little dorrit/page (37).png',
    'books/little dorrit/page (38).png',
    'books/little dorrit/page (39).png',
    'books/little dorrit/page (40).png',
    'books/little dorrit/page (41).png',
    'books/little dorrit/page (42).png',
    'books/little dorrit/page (43).png',
    'books/little dorrit/page (44).png',
    'books/little dorrit/page (45).png',
    'books/little dorrit/page (46).png',
    'books/little dorrit/page (47).png',
    'books/little dorrit/page (48).png',
    'books/little dorrit/page (49).png',
    'books/little dorrit/page (50).png',
    'books/little dorrit/page (51).png',
    'books/little dorrit/page (52).png',
    'books/little dorrit/page (53).png',
    'books/little dorrit/page (54).png',
    'books/little dorrit/page (55).png',
    'books/little dorrit/page (56).png',
    'books/little dorrit/page (57).png',
    'books/little dorrit/page (58).png',
    'books/little dorrit/page (59).png',
    'books/little dorrit/page (60).png',
    'books/little dorrit/page (61).png',
    'books/little dorrit/page (62).png',
    'books/little dorrit/page (63).png',
    'books/little dorrit/page (64).png',
    'books/little dorrit/page (65).png',
    'books/little dorrit/page (66).png',
    'books/little dorrit/page (67).png',
    'books/little dorrit/page (68).png',
    'books/little dorrit/page (69).png',
    'books/little dorrit/page (70).png',
    'books/little dorrit/page (71).png',
    'books/little dorrit/page (72).png',
    'books/little dorrit/page (73).png',
    'books/little dorrit/page (74).png',
    'books/little dorrit/page (75).png',
    'books/little dorrit/page (76).png',
    'books/little dorrit/page (77).png',
    'books/little dorrit/page (78).png',
    'books/little dorrit/page (79).png',
    'books/little dorrit/page (80).png',
    'books/little dorrit/page (81).png',
    'books/little dorrit/page (82).png',
    'books/little dorrit/page (83).png',
    'books/little dorrit/page (84).png',
    'books/little dorrit/page (85).png',
    'books/little dorrit/page (86).png',
    'books/little dorrit/page (87).png',
    'books/little dorrit/page (88).png',
    'books/little dorrit/page (89).png',
    'books/little dorrit/page (90).png',
    'books/little dorrit/page (91).png',
    'books/little dorrit/page (92).png',
    'books/little dorrit/page (93).png',
    'books/little dorrit/page (94).png',
    'books/little dorrit/page (95).png',
    'books/little dorrit/page (96).png',
    'books/little dorrit/page (97).png',
    'books/little dorrit/page (98).png',
    'books/little dorrit/page (99).png',
    'books/little dorrit/page (100).png',
    'books/little dorrit/page (101).png',
    'books/little dorrit/page (102).png',
    'books/little dorrit/page (103).png',
    'books/little dorrit/page (104).png',
    'books/little dorrit/page (105).png',
    'books/little dorrit/page (106).png',
    'books/little dorrit/page (107).png',
    'books/little dorrit/page (108).png',
    'books/little dorrit/page (109).png',
    'books/little dorrit/page (110).png',
    'books/little dorrit/page (111).png',
    'books/little dorrit/page (112).png',
    'books/little dorrit/page (113).png',
    'books/little dorrit/page (114).png',
    'books/little dorrit/page (115).png',
    'books/little dorrit/page (116).png',
    'books/little dorrit/page (117).png',
    'books/little dorrit/page (118).png',
    'books/little dorrit/page (119).png',
    'books/little dorrit/page (120).png',
    'books/little dorrit/page (121).png',
    'books/little dorrit/page (122).png',
    'books/little dorrit/page (123).png',
    'books/little dorrit/page (124).png',
    'books/little dorrit/page (125).png',
    'books/little dorrit/page (126).png',
    'books/little dorrit/page (127).png',
    'books/little dorrit/page (128).png',
    'books/little dorrit/page (129).png',
    'books/little dorrit/page (130).png',
    'books/little dorrit/page (131).png',
    'books/little dorrit/page (132).png',
    'books/little dorrit/page (133).png',
    'books/little dorrit/page (134).png',
    'books/little dorrit/page (135).png',
    'books/little dorrit/page (136).png',
    'books/little dorrit/page (137).png',
    'books/little dorrit/page (138).png',
    'books/little dorrit/page (139).png',
    'books/little dorrit/page (140).png',
    'books/little dorrit/page (141).png',
    'books/little dorrit/page (142).png',
    'books/little dorrit/page (143).png',
    'books/little dorrit/page (144).png',
    'books/little dorrit/page (145).png',
    'books/little dorrit/page (146).png',
    'books/little dorrit/page (147).png',
    'books/little dorrit/page (148).png',
    'books/little dorrit/page (149).png',
    'books/little dorrit/page (150).png',
    'books/little dorrit/page (151).png',
    'books/little dorrit/page (152).png',
    'books/little dorrit/page (153).png',
    'books/little dorrit/page (154).png',
    'books/little dorrit/page (155).png',
    'books/little dorrit/page (156).png',
    'books/little dorrit/page (157).png',
    'books/little dorrit/page (158).png',
    'books/little dorrit/page (159).png',
    'books/little dorrit/page (160).png',
    'books/little dorrit/page (161).png',
    'books/little dorrit/page (162).png',
    'books/little dorrit/page (163).png',
    'books/little dorrit/page (164).png',
    'books/little dorrit/page (165).png',
    'books/little dorrit/page (166).png',
    'books/little dorrit/page (167).png',
    'books/little dorrit/page (168).png',
    'books/little dorrit/page (169).png',
    'books/little dorrit/page (170).png',
    'books/little dorrit/page (171).png',
    'books/little dorrit/page (172).png',
    'books/little dorrit/page (173).png',
    'books/little dorrit/page (174).png',
    'books/little dorrit/page (175).png',
    'books/little dorrit/page (176).png',
    'books/little dorrit/page (177).png',
    'books/little dorrit/page (178).png',
    'books/little dorrit/page (179).png',
    'books/little dorrit/page (180).png',
    'books/little dorrit/page (181).png',
    'books/little dorrit/page (182).png',
    'books/little dorrit/page (183).png',
    'books/little dorrit/page (184).png',
    'books/little dorrit/page (185).png',
    'books/little dorrit/page (186).png',
    'books/little dorrit/page (187).png',
    'books/little dorrit/page (188).png',
    'books/little dorrit/page (189).png',
    'books/little dorrit/page (190).png',
    'books/little dorrit/page (191).png',
    'books/little dorrit/page (192).png',
    'books/little dorrit/page (193).png',
    'books/little dorrit/page (194).png',
    'books/little dorrit/page (195).png',
    'books/little dorrit/page (196).png',
    'books/little dorrit/page (197).png',
    'books/little dorrit/page (198).png',
    'books/little dorrit/page (199).png',
    'books/little dorrit/page (200).png',
    'books/little dorrit/page (201).png',
    'books/little dorrit/page (202).png',
    'books/little dorrit/page (203).png',
    'books/little dorrit/page (204).png',
    'books/little dorrit/page (205).png',
    'books/little dorrit/page (206).png',
    'books/little dorrit/page (207).png',
    'books/little dorrit/page (208).png',
    'books/little dorrit/page (209).png',
    'books/little dorrit/page (210).png',
    'books/little dorrit/page (211).png',
    'books/little dorrit/page (212).png',
    'books/little dorrit/page (213).png',
    'books/little dorrit/page (214).png',
    'books/little dorrit/page (215).png',
    'books/little dorrit/page (216).png',
    'books/little dorrit/page (217).png',
    'books/little dorrit/page (218).png',
    'books/little dorrit/page (219).png',
    'books/little dorrit/page (220).png',
    'books/little dorrit/page (221).png',
    'books/little dorrit/page (222).png',
    'books/little dorrit/page (223).png',
    'books/little dorrit/page (224).png',
    'books/little dorrit/page (225).png',
    'books/little dorrit/page (226).png',
    'books/little dorrit/page (227).png',
    'books/little dorrit/page (228).png',
    'books/little dorrit/page (229).png',
    'books/little dorrit/page (230).png',
    'books/little dorrit/page (231).png',
    'books/little dorrit/page (232).png',
    'books/little dorrit/page (233).png',
    'books/little dorrit/page (234).png',
    'books/little dorrit/page (235).png',
    'books/little dorrit/page (236).png',
    'books/little dorrit/page (237).png',
    'books/little dorrit/page (238).png',
    'books/little dorrit/page (239).png',
    'books/little dorrit/page (240).png',
    'books/little dorrit/page (241).png',
    'books/little dorrit/page (242).png',
    'books/little dorrit/page (243).png',
    'books/little dorrit/page (244).png',
    'books/little dorrit/page (245).png',
    'books/little dorrit/page (246).png',
    'books/little dorrit/page (247).png',
    'books/little dorrit/page (248).png',
    'books/little dorrit/page (249).png',
    'books/little dorrit/page (250).png',
    'books/little dorrit/page (251).png',
    'books/little dorrit/page (252).png',
    'books/little dorrit/page (253).png',
    'books/little dorrit/page (254).png',
    'books/little dorrit/page (255).png',
    'books/little dorrit/page (256).png',
    'books/little dorrit/page (257).png',
    'books/little dorrit/page (258).png',
    'books/little dorrit/page (259).png',
    'books/little dorrit/page (260).png',
    'books/little dorrit/page (261).png',
    'books/little dorrit/page (262).png',
    'books/little dorrit/page (263).png',
    'books/little dorrit/page (264).png',
    'books/little dorrit/page (265).png',
    'books/little dorrit/page (266).png',
    'books/little dorrit/page (267).png',
    'books/little dorrit/page (268).png',
    'books/little dorrit/page (269).png',
    'books/little dorrit/page (270).png',
    'books/little dorrit/page (271).png',
    'books/little dorrit/page (272).png',
    'books/little dorrit/page (273).png',
    'books/little dorrit/page (274).png',
    'books/little dorrit/page (275).png',
    'books/little dorrit/page (276).png',
    'books/little dorrit/page (277).png',
    'books/little dorrit/page (278).png',
    'books/little dorrit/page (279).png',
    'books/little dorrit/page (280).png',
    'books/little dorrit/page (281).png',
    'books/little dorrit/page (282).png',
    'books/little dorrit/page (283).png',
    'books/little dorrit/page (284).png',
    'books/little dorrit/page (285).png',
    'books/little dorrit/page (286).png',
    'books/little dorrit/page (287).png',
    'books/little dorrit/page (288).png',
    'books/little dorrit/page (289).png',
    'books/little dorrit/page (290).png',
    'books/little dorrit/page (291).png',
    'books/little dorrit/page (292).png',
    'books/little dorrit/page (293).png',
    'books/little dorrit/page (294).png',
    'books/little dorrit/page (295).png',
    'books/little dorrit/page (296).png',
    'books/little dorrit/page (297).png',
    'books/little dorrit/page (298).png',
    'books/little dorrit/page (299).png',
    'books/little dorrit/page (300).png',
    'books/little dorrit/page (301).png',
    'books/little dorrit/page (302).png',
    'books/little dorrit/page (303).png',
    'books/little dorrit/page (304).png',
    'books/little dorrit/page (305).png',
    'books/little dorrit/page (306).png',
    'books/little dorrit/page (307).png',
    'books/little dorrit/page (308).png',
    'books/little dorrit/page (309).png',
    'books/little dorrit/page (310).png',
    'books/little dorrit/page (311).png',
    'books/little dorrit/page (312).png',
    'books/little dorrit/page (313).png',
    'books/little dorrit/page (314).png',
    'books/little dorrit/page (315).png',
    'books/little dorrit/page (316).png',
    'books/little dorrit/page (317).png',
    'books/little dorrit/page (318).png',
    'books/little dorrit/page (319).png',
    'books/little dorrit/page (320).png',
    'books/little dorrit/page (321).png',
    'books/little dorrit/page (322).png',
    'books/little dorrit/page (323).png',
    'books/little dorrit/page (324).png',
    'books/little dorrit/page (325).png',
    'books/little dorrit/page (326).png',
    'books/little dorrit/page (327).png',
    'books/little dorrit/page (328).png',
    'books/little dorrit/page (329).png',
    'books/little dorrit/page (330).png',
    'books/little dorrit/page (331).png',
    'books/little dorrit/page (332).png',
    'books/little dorrit/page (333).png',
    'books/little dorrit/page (334).png',
    'books/little dorrit/page (335).png',
    'books/little dorrit/page (336).png',
    'books/little dorrit/page (337).png',
    'books/little dorrit/page (338).png',
    'books/little dorrit/page (339).png',
    'books/little dorrit/page (340).png',
    'books/little dorrit/page (341).png',
    'books/little dorrit/page (342).png',
    'books/little dorrit/page (343).png',
    'books/little dorrit/page (344).png',
    'books/little dorrit/page (345).png',
    'books/little dorrit/page (346).png',
    'books/little dorrit/page (347).png',
    'books/little dorrit/page (348).png',
    'books/little dorrit/page (349).png',
    'books/little dorrit/page (350).png',
    'books/little dorrit/page (351).png',
    'books/little dorrit/page (352).png',
    'books/little dorrit/page (353).png',
    'books/little dorrit/page (354).png',
    'books/little dorrit/page (355).png',
    'books/little dorrit/page (356).png',
    'books/little dorrit/page (357).png',
    'books/little dorrit/page (358).png',
    'books/little dorrit/page (359).png',
    'books/little dorrit/page (360).png',
    'books/little dorrit/page (361).png',
    'books/little dorrit/page (362).png',
    'books/little dorrit/page (363).png',
    'books/little dorrit/page (364).png',
    'books/little dorrit/page (365).png',
    'books/little dorrit/page (366).png',
    'books/little dorrit/page (367).png',
    'books/little dorrit/page (368).png',
    'books/little dorrit/page (369).png',
    'books/little dorrit/page (370).png',
    'books/little dorrit/page (371).png',
    'books/little dorrit/page (372).png',
    'books/little dorrit/page (373).png',
    'books/little dorrit/page (374).png',
    'books/little dorrit/page (375).png',
    'books/little dorrit/page (376).png',
    'books/little dorrit/page (377).png',
    'books/little dorrit/page (378).png',
    'books/little dorrit/page (379).png',
    'books/little dorrit/page (380).png',
    'books/little dorrit/page (381).png',
    'books/little dorrit/page (382).png',
    'books/little dorrit/page (383).png',
    'books/little dorrit/page (384).png',
    'books/little dorrit/page (385).png',
    'books/little dorrit/page (386).png',
    'books/little dorrit/page (387).png',
    'books/little dorrit/page (388).png',
    'books/little dorrit/page (389).png',
    'books/little dorrit/page (390).png',
    'books/little dorrit/page (391).png',
    'books/little dorrit/page (392).png',
    'books/little dorrit/page (393).png',
    'books/little dorrit/page (394).png',
    'books/little dorrit/page (395).png',
    'books/little dorrit/page (396).png',
    'books/little dorrit/page (397).png',
    'books/little dorrit/page (398).png',
    'books/little dorrit/page (399).png',
    'books/little dorrit/page (400).png',
    'books/little dorrit/page (401).png',
    'books/little dorrit/page (402).png',
    'books/little dorrit/page (403).png',
    'books/little dorrit/page (404).png',
    'books/little dorrit/page (405).png',
    'books/little dorrit/page (406).png',
    'books/little dorrit/page (407).png',
    'books/little dorrit/page (408).png',
    'books/little dorrit/page (409).png',
    'books/little dorrit/page (410).png',
    'books/little dorrit/page (411).png',
    'books/little dorrit/page (412).png',
    'books/little dorrit/page (413).png',
    'books/little dorrit/page (414).png',
    'books/little dorrit/page (415).png',
    'books/little dorrit/page (416).png',
    'books/little dorrit/page (417).png',
    'books/little dorrit/page (418).png',
    'books/little dorrit/page (419).png',
    'books/little dorrit/page (420).png',
    'books/little dorrit/page (421).png',
    'books/little dorrit/page (422).png',
    'books/little dorrit/page (423).png',
    'books/little dorrit/page (424).png',
    'books/little dorrit/page (425).png',
    'books/little dorrit/page (426).png',
    'books/little dorrit/page (427).png',
    'books/little dorrit/page (428).png',
    'books/little dorrit/page (429).png',
    'books/little dorrit/page (430).png',
    'books/little dorrit/page (431).png',
    'books/little dorrit/page (432).png',
    'books/little dorrit/page (433).png',
    'books/little dorrit/page (434).png',
    'books/little dorrit/page (435).png',
    'books/little dorrit/page (436).png',
    'books/little dorrit/page (437).png',
    'books/little dorrit/page (438).png',
    'books/little dorrit/page (439).png',
    'books/little dorrit/page (440).png',
    'books/little dorrit/page (441).png',
    'books/little dorrit/page (442).png',
    'books/little dorrit/page (443).png',
    'books/little dorrit/page (444).png',
    'books/little dorrit/page (445).png',
    'books/little dorrit/page (446).png',
    'books/little dorrit/page (447).png',
    'books/little dorrit/page (448).png',
    'books/little dorrit/page (449).png',
    'books/little dorrit/page (450).png',
    'books/little dorrit/page (451).png',
    'books/little dorrit/page (452).png',
    'books/little dorrit/page (453).png',
    'books/little dorrit/page (454).png',
    'books/little dorrit/page (455).png',
    'books/little dorrit/page (456).png',
    'books/little dorrit/page (457).png',
    'books/little dorrit/page (458).png',
    'books/little dorrit/page (459).png',
    'books/little dorrit/page (460).png',
    'books/little dorrit/page (461).png',
    'books/little dorrit/page (462).png',
    'books/little dorrit/page (463).png',
    'books/little dorrit/page (464).png',
    'books/little dorrit/page (465).png',
    'books/little dorrit/page (466).png',
    'books/little dorrit/page (467).png',
    'books/little dorrit/page (468).png',
    'books/little dorrit/page (469).png',
    'books/little dorrit/page (470).png',
    'books/little dorrit/page (471).png',
    'books/little dorrit/page (472).png',
    'books/little dorrit/page (473).png',
    'books/little dorrit/page (474).png',
    'books/little dorrit/page (475).png',
    'books/little dorrit/page (476).png',
    'books/little dorrit/page (477).png',
    'books/little dorrit/page (478).png',
    'books/little dorrit/page (479).png',
    'books/little dorrit/page (480).png',
    'books/little dorrit/page (481).png',
    'books/little dorrit/page (482).png',
    'books/little dorrit/page (483).png',
    'books/little dorrit/page (484).png',
    'books/little dorrit/page (485).png',
    'books/little dorrit/page (486).png',
    'books/little dorrit/page (487).png',
    'books/little dorrit/page (488).png',
    'books/little dorrit/page (489).png',
    'books/little dorrit/page (490).png',
    'books/little dorrit/page (491).png',
    'books/little dorrit/page (492).png',
    'books/little dorrit/page (493).png',
    'books/little dorrit/page (494).png',
    'books/little dorrit/page (495).png',
    'books/little dorrit/page (496).png',
    'books/little dorrit/page (497).png',
    'books/little dorrit/page (498).png',
    'books/little dorrit/page (499).png',
    'books/little dorrit/page (500).png',
    'books/little dorrit/page (501).png',
    'books/little dorrit/page (502).png',
    'books/little dorrit/page (503).png',
    'books/little dorrit/page (504).png',
    'books/little dorrit/page (505).png',
    'books/little dorrit/page (506).png',
    'books/little dorrit/page (507).png',
    'books/little dorrit/page (508).png',
    'books/little dorrit/page (509).png',
    'books/little dorrit/page (510).png',
    'books/little dorrit/page (511).png',
    'books/little dorrit/page (512).png',
    'books/little dorrit/page (513).png',
    'books/little dorrit/page (514).png',
    'books/little dorrit/page (515).png',
    'books/little dorrit/page (516).png',
    'books/little dorrit/page (517).png',
    'books/little dorrit/page (518).png',
    'books/little dorrit/page (519).png',
    'books/little dorrit/page (520).png',
    'books/little dorrit/page (521).png',
    'books/little dorrit/page (522).png',
    'books/little dorrit/page (523).png',
    'books/little dorrit/page (524).png',
    'books/little dorrit/page (525).png',
    'books/little dorrit/page (526).png',
    'books/little dorrit/page (527).png',
    'books/little dorrit/page (528).png',
    'books/little dorrit/page (529).png',
    'books/little dorrit/page (530).png',
    'books/little dorrit/page (531).png',
    'books/little dorrit/page (532).png',
    'books/little dorrit/page (533).png',
    'books/little dorrit/page (534).png',
    'books/little dorrit/page (535).png',
    'books/little dorrit/page (536).png',
    'books/little dorrit/page (537).png',
    'books/little dorrit/page (538).png',
    'books/little dorrit/page (539).png',
    'books/little dorrit/page (540).png',
    'books/little dorrit/page (541).png',
    'books/little dorrit/page (542).png',
    'books/little dorrit/page (543).png',
    'books/little dorrit/page (544).png',
    'books/little dorrit/page (545).png',
    'books/little dorrit/page (546).png',
    'books/little dorrit/page (547).png',
    'books/little dorrit/page (548).png',
    'books/little dorrit/page (549).png',
    'books/little dorrit/page (550).png',
    'books/little dorrit/page (551).png',
    'books/little dorrit/page (552).png',
    'books/little dorrit/page (553).png',
    'books/little dorrit/page (554).png',
    'books/little dorrit/page (555).png',
    'books/little dorrit/page (556).png',
    'books/little dorrit/page (557).png',
    'books/little dorrit/page (558).png',
    'books/little dorrit/page (559).png',
    'books/little dorrit/page (560).png',
    'books/little dorrit/page (561).png',
    'books/little dorrit/page (562).png',
    'books/little dorrit/page (563).png',
    'books/little dorrit/page (564).png',
    'books/little dorrit/page (565).png',
    'books/little dorrit/page (566).png',
    'books/little dorrit/page (567).png',
    'books/little dorrit/page (568).png',
    'books/little dorrit/page (569).png',
    'books/little dorrit/page (570).png',
    'books/little dorrit/page (571).png',
    'books/little dorrit/page (572).png',
    'books/little dorrit/page (573).png',
    'books/little dorrit/page (574).png',
    'books/little dorrit/page (575).png',
    'books/little dorrit/page (576).png',
    'books/little dorrit/page (577).png',
    'books/little dorrit/page (578).png',
    'books/little dorrit/page (579).png',
    'books/little dorrit/page (580).png',
    'books/little dorrit/page (581).png',
    'books/little dorrit/page (582).png',
    'books/little dorrit/page (583).png',
    'books/little dorrit/page (584).png',
    'books/little dorrit/page (585).png',
    'books/little dorrit/page (586).png',
    'books/little dorrit/page (587).png',
    'books/little dorrit/page (588).png',
    'books/little dorrit/page (589).png',
    'books/little dorrit/page (590).png',
    'books/little dorrit/page (591).png',
    'books/little dorrit/page (592).png',
    'books/little dorrit/page (593).png',
    'books/little dorrit/page (594).png',
    'books/little dorrit/page (595).png',
    'books/little dorrit/page (596).png',
    'books/little dorrit/page (597).png',
    'books/little dorrit/page (598).png',
    'books/little dorrit/page (599).png',
    'books/little dorrit/page (600).png',
    'books/little dorrit/page (601).png',
    'books/little dorrit/page (602).png',
    'books/little dorrit/page (603).png',
    'books/little dorrit/page (604).png',
    'books/little dorrit/page (605).png',
    'books/little dorrit/page (606).png',
    'books/little dorrit/page (607).png',
    'books/little dorrit/page (608).png',
    'books/little dorrit/page (609).png',
    'books/little dorrit/page (610).png',
    'books/little dorrit/page (611).png',
    'books/little dorrit/page (612).png',
    'books/little dorrit/page (613).png',
    'books/little dorrit/page (614).png',
    'books/little dorrit/page (615).png',
    'books/little dorrit/page (616).png',
    'books/little dorrit/page (617).png',
    'books/little dorrit/page (618).png',
    'books/little dorrit/page (619).png',
    'books/little dorrit/page (620).png',
    'books/little dorrit/page (621).png',
    'books/little dorrit/page (622).png',
    'books/little dorrit/page (623).png',
    'books/little dorrit/page (624).png',
    'books/little dorrit/page (625).png',
    'books/little dorrit/page (626).png',
    'books/little dorrit/page (627).png',
    'books/little dorrit/page (628).png',
    'books/little dorrit/page (629).png',
    'books/little dorrit/page (630).png',
    'books/little dorrit/page (631).png',
    'books/little dorrit/page (632).png',
    'books/little dorrit/page (633).png',
    'books/little dorrit/page (634).png',
    'books/little dorrit/page (635).png',
    'books/little dorrit/page (636).png',
    'books/little dorrit/page (637).png',
    'books/little dorrit/page (638).png',
    'books/little dorrit/page (639).png',
    'books/little dorrit/page (640).png',
    'books/little dorrit/page (641).png',
    'books/little dorrit/page (642).png',
    'books/little dorrit/page (643).png',
    'books/little dorrit/page (644).png',
    'books/little dorrit/page (645).png',
    'books/little dorrit/page (646).png',
    'books/little dorrit/page (647).png',
    'books/little dorrit/page (648).png',
    'books/little dorrit/page (649).png',
    'books/little dorrit/page (650).png',
    'books/little dorrit/page (651).png',
    'books/little dorrit/page (652).png',
    'books/little dorrit/page (653).png',
    'books/little dorrit/page (654).png',
    'books/little dorrit/page (655).png',
    'books/little dorrit/page (656).png',
    'books/little dorrit/page (657).png',
    'books/little dorrit/page (658).png',
    'books/little dorrit/page (659).png',
    'books/little dorrit/page (660).png',
    'books/little dorrit/page (661).png',
    'books/little dorrit/page (662).png',
    'books/little dorrit/page (663).png',
    'books/little dorrit/page (664).png',
    'books/little dorrit/page (665).png',
    'books/little dorrit/page (666).png',
    'books/little dorrit/page (667).png',
    'books/little dorrit/page (668).png',
    'books/little dorrit/page (669).png',
    'books/little dorrit/page (670).png',
    'books/little dorrit/page (671).png',
    'books/little dorrit/page (672).png',
    'books/little dorrit/page (673).png',
    'books/little dorrit/page (674).png',
    'books/little dorrit/page (675).png',
    'books/little dorrit/page (676).png',
    'books/little dorrit/page (677).png',
    'books/little dorrit/page (678).png',
    'books/little dorrit/page (679).png',
    'books/little dorrit/page (680).png',
    'books/little dorrit/page (681).png',
    'books/little dorrit/page (682).png',
    'books/little dorrit/page (683).png',
    'books/little dorrit/page (684).png',
    'books/little dorrit/page (685).png',
    'books/little dorrit/page (686).png',
    'books/little dorrit/page (687).png',
    'books/little dorrit/page (688).png',
    'books/little dorrit/page (689).png',
    'books/little dorrit/page (690).png',
    'books/little dorrit/page (691).png',
    'books/little dorrit/page (692).png',
    'books/little dorrit/page (693).png',
    'books/little dorrit/page (694).png',
    'books/little dorrit/page (695).png',
    'books/little dorrit/page (696).png',
    'books/little dorrit/page (697).png',
    'books/little dorrit/page (698).png',
    'books/little dorrit/page (699).png',
    'books/little dorrit/page (700).png',
    'books/little dorrit/page (701).png',
    'books/little dorrit/page (702).png',
    'books/little dorrit/page (703).png',
    'books/little dorrit/page (704).png',
    'books/little dorrit/page (705).png',
    'books/little dorrit/page (706).png',
    'books/little dorrit/page (707).png',
    'books/little dorrit/page (708).png',
    'books/little dorrit/page (709).png',
    'books/little dorrit/page (710).png',
    'books/little dorrit/page (711).png',
    'books/little dorrit/page (712).png',
    'books/little dorrit/page (713).png',
    'books/little dorrit/page (714).png',
    'books/little dorrit/page (715).png',
    'books/little dorrit/page (716).png',
    'books/little dorrit/page (717).png',
    'books/little dorrit/page (718).png',
    'books/little dorrit/page (719).png',
    'books/little dorrit/page (720).png',
    'books/little dorrit/page (721).png',
    'books/little dorrit/page (722).png',
    'books/little dorrit/page (723).png',
    'books/little dorrit/page (724).png',
    'books/little dorrit/page (725).png',
    'books/little dorrit/page (726).png',
    'books/little dorrit/page (727).png',
    'books/little dorrit/page (728).png',
    'books/little dorrit/page (729).png',
    'books/little dorrit/page (730).png',
    'books/little dorrit/page (731).png',
    'books/little dorrit/page (732).png',
    'books/little dorrit/page (733).png',
    'books/little dorrit/page (734).png',
    'books/little dorrit/page (735).png',
    'books/little dorrit/page (736).png',
    'books/little dorrit/page (737).png',
    'books/little dorrit/page (738).png',
    'books/little dorrit/page (739).png',
    'books/little dorrit/page (740).png',
    'books/little dorrit/page (741).png',
    'books/little dorrit/page (742).png',
    'books/little dorrit/page (743).png',
    'books/little dorrit/page (744).png',
    'books/little dorrit/page (745).png',
    'books/little dorrit/page (746).png',
    'books/little dorrit/page (747).png',
    'books/little dorrit/page (748).png',
    'books/little dorrit/page (749).png',
    'books/little dorrit/page (750).png',
    'books/little dorrit/page (751).png',
    'books/little dorrit/page (752).png',
    'books/little dorrit/page (753).png',
    'books/little dorrit/page (754).png',
    'books/little dorrit/page (755).png',
    'books/little dorrit/page (756).png',
    'books/little dorrit/page (757).png',
    'books/little dorrit/page (758).png',
    'books/little dorrit/page (759).png',
    'books/little dorrit/page (760).png',
    'books/little dorrit/page (761).png',
    'books/little dorrit/page (762).png',
    'books/little dorrit/page (763).png',
    'books/little dorrit/page (764).png',
    'books/little dorrit/page (765).png',
    'books/little dorrit/page (766).png',
    'books/little dorrit/page (767).png',
    'books/little dorrit/page (768).png',
    'books/little dorrit/page (769).png',
    'books/little dorrit/page (770).png',
    'books/little dorrit/page (771).png',
    'books/little dorrit/page (772).png',
    'books/little dorrit/page (773).png',
    'books/little dorrit/page (774).png',
    'books/little dorrit/page (775).png',
    'books/little dorrit/page (776).png',
    'books/little dorrit/page (777).png',
    'books/little dorrit/page (778).png',
    'books/little dorrit/page (779).png',
    'books/little dorrit/page (780).png',
    'books/little dorrit/page (781).png',
    'books/little dorrit/page (782).png',
    'books/little dorrit/page (783).png',
    'books/little dorrit/page (784).png',
    'books/little dorrit/page (785).png',
    'books/little dorrit/page (786).png',
    'books/little dorrit/page (787).png',
    'books/little dorrit/page (788).png',
    'books/little dorrit/page (789).png',
    'books/little dorrit/page (790).png',
    'books/little dorrit/page (791).png',
    'books/little dorrit/page (792).png',
    'books/little dorrit/page (793).png',
    'books/little dorrit/page (794).png',
    'books/little dorrit/page (795).png',
    'books/little dorrit/page (796).png',
    'books/little dorrit/page (797).png',
    'books/little dorrit/page (798).png',
    'books/little dorrit/page (799).png',
    'books/little dorrit/page (800).png',
    'books/little dorrit/page (801).png',
    'books/little dorrit/page (802).png',
    'books/little dorrit/page (803).png',
    'books/little dorrit/page (804).png',
    'books/little dorrit/page (805).png',
    'books/little dorrit/page (806).png',
    'books/little dorrit/page (807).png',
    'books/little dorrit/page (808).png',
    'books/little dorrit/page (809).png',
    'books/little dorrit/page (810).png',
    'books/little dorrit/page (811).png',
    'books/little dorrit/page (812).png',
    'books/little dorrit/page (813).png',
    'books/little dorrit/page (814).png',
    'books/little dorrit/page (815).png',
    'books/little dorrit/page (816).png',
    'books/little dorrit/page (817).png',
    'books/little dorrit/page (818).png',
    'books/little dorrit/page (819).png',
    'books/little dorrit/page (820).png',
    'books/little dorrit/page (821).png',
    'books/little dorrit/page (822).png',
    'books/little dorrit/page (823).png',
    'books/little dorrit/page (824).png',
    'books/little dorrit/page (825).png',
    'books/little dorrit/page (826).png',
    'books/little dorrit/page (827).png',
    'books/little dorrit/page (828).png',
    'books/little dorrit/page (829).png',
    'books/little dorrit/page (830).png',
    'books/little dorrit/page (831).png',
    'books/little dorrit/page (832).png',
    'books/little dorrit/page (833).png',
    'books/little dorrit/page (834).png',
    'books/little dorrit/page (835).png',
    'books/little dorrit/page (836).png',
    'books/little dorrit/page (837).png',
    'books/little dorrit/page (838).png',
    'books/little dorrit/page (839).png',
    'books/little dorrit/page (840).png',
    'books/little dorrit/page (841).png',
    'books/little dorrit/page (842).png',
    'books/little dorrit/page (843).png',
    'books/little dorrit/page (844).png',
    'books/little dorrit/page (845).png',
    'books/little dorrit/page (846).png',
    'books/little dorrit/page (847).png',
    'books/little dorrit/page (848).png',
    'books/little dorrit/page (849).png',
    'books/little dorrit/page (850).png',
    'books/little dorrit/page (851).png',
    'books/little dorrit/page (852).png',
    'books/little dorrit/page (853).png',
    'books/little dorrit/page (854).png',
    'books/little dorrit/page (855).png',
    'books/little dorrit/page (856).png',
    'books/little dorrit/page (857).png',
    'books/little dorrit/page (858).png',
    'books/little dorrit/page (859).png',
    'books/little dorrit/page (860).png',
    'books/little dorrit/page (861).png',
    'books/little dorrit/page (862).png',
    'books/little dorrit/page (863).png',
    'books/little dorrit/page (864).png',
    'books/little dorrit/page (865).png',
    'books/little dorrit/page (866).png',
    'books/little dorrit/page (867).png',
    'books/little dorrit/page (868).png',
    'books/little dorrit/page (869).png',
    'books/little dorrit/page (870).png',
    'books/little dorrit/page (871).png',
    'books/little dorrit/page (872).png',
    'books/little dorrit/page (873).png',
    'books/little dorrit/page (874).png',
    'books/little dorrit/page (875).png',
    'books/little dorrit/page (876).png',
    'books/little dorrit/page (877).png',
    'books/little dorrit/page (878).png',
    'books/little dorrit/page (879).png',
    'books/little dorrit/page (880).png',
    'books/little dorrit/page (881).png',
    'books/little dorrit/page (882).png',
    'books/little dorrit/page (883).png',
    'books/little dorrit/page (884).png',
    'books/little dorrit/page (885).png',
    'books/little dorrit/page (886).png',
    'books/little dorrit/page (887).png',
    'books/little dorrit/page (888).png',
    'books/little dorrit/page (889).png',
    'books/little dorrit/page (890).png',
    'books/little dorrit/page (891).png',
    'books/little dorrit/page (892).png',
    'books/little dorrit/page (893).png',
    'books/little dorrit/page (894).png',
    'books/little dorrit/page (895).png',
    'books/little dorrit/page (896).png',
    'books/little dorrit/page (897).png',
    'books/little dorrit/page (898).png',
    'books/little dorrit/page (899).png',
    'books/little dorrit/page (900).png',
    'books/little dorrit/page (901).png',
    'books/little dorrit/page (902).png',
    'books/little dorrit/page (903).png',
    'books/little dorrit/page (904).png',
    'books/little dorrit/page (905).png',
    'books/little dorrit/page (906).png',
    'books/little dorrit/page (907).png',
    'books/little dorrit/page (908).png',
    'books/little dorrit/page (909).png',
    'books/little dorrit/page (910).png',
    'books/little dorrit/page (911).png',
    'books/little dorrit/page (912).png',
    'books/little dorrit/page (913).png',
    'books/little dorrit/page (914).png',
    'books/little dorrit/page (915).png',
    'books/little dorrit/page (916).png',
    'books/little dorrit/page (917).png',
    'books/little dorrit/page (918).png',
    'books/little dorrit/page (919).png',
    'books/little dorrit/page (920).png',
    'books/little dorrit/page (921).png',
    'books/little dorrit/page (922).png',
    'books/little dorrit/page (923).png',
    'books/little dorrit/page (924).png',
    'books/little dorrit/page (925).png',
    'books/little dorrit/page (926).png',
    'books/little dorrit/page (927).png',
    'books/little dorrit/page (928).png',
    'books/little dorrit/page (929).png',
    'books/little dorrit/page (930).png',
    'books/little dorrit/page (931).png',
    'books/little dorrit/page (932).png',
    'books/little dorrit/page (933).png',
    'books/little dorrit/page (934).png',
    'books/little dorrit/page (935).png',
    'books/little dorrit/page (936).png',
    'books/little dorrit/page (937).png',
    'books/little dorrit/page (938).png',
    'books/little dorrit/page (939).png',
    'books/little dorrit/page (940).png',
    'books/little dorrit/page (941).png',
    'books/little dorrit/page (942).png',
    'books/little dorrit/page (943).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
