import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class martin extends StatefulWidget {
  const martin({Key? key}) : super(key: key);

  @override
  State<martin> createState() => _martinState();
}

class _martinState extends State<martin> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/martin/page (1).png',
    'books/martin/page (2).png',
    'books/martin/page (3).png',
    'books/martin/page (4).png',
    'books/martin/page (5).png',
    'books/martin/page (6).png',
    'books/martin/page (7).png',
    'books/martin/page (8).png',
    'books/martin/page (9).png',
    'books/martin/page (10).png',
    'books/martin/page (11).png',
    'books/martin/page (12).png',
    'books/martin/page (13).png',
    'books/martin/page (14).png',
    'books/martin/page (15).png',
    'books/martin/page (16).png',
    'books/martin/page (17).png',
    'books/martin/page (18).png',
    'books/martin/page (19).png',
    'books/martin/page (20).png',
    'books/martin/page (21).png',
    'books/martin/page (22).png',
    'books/martin/page (23).png',
    'books/martin/page (24).png',
    'books/martin/page (25).png',
    'books/martin/page (26).png',
    'books/martin/page (27).png',
    'books/martin/page (28).png',
    'books/martin/page (29).png',
    'books/martin/page (30).png',
    'books/martin/page (31).png',
    'books/martin/page (32).png',
    'books/martin/page (33).png',
    'books/martin/page (34).png',
    'books/martin/page (35).png',
    'books/martin/page (36).png',
    'books/martin/page (37).png',
    'books/martin/page (38).png',
    'books/martin/page (39).png',
    'books/martin/page (40).png',
    'books/martin/page (41).png',
    'books/martin/page (42).png',
    'books/martin/page (43).png',
    'books/martin/page (44).png',
    'books/martin/page (45).png',
    'books/martin/page (46).png',
    'books/martin/page (47).png',
    'books/martin/page (48).png',
    'books/martin/page (49).png',
    'books/martin/page (50).png',
    'books/martin/page (51).png',
    'books/martin/page (52).png',
    'books/martin/page (53).png',
    'books/martin/page (54).png',
    'books/martin/page (55).png',
    'books/martin/page (56).png',
    'books/martin/page (57).png',
    'books/martin/page (58).png',
    'books/martin/page (59).png',
    'books/martin/page (60).png',
    'books/martin/page (61).png',
    'books/martin/page (62).png',
    'books/martin/page (63).png',
    'books/martin/page (64).png',
    'books/martin/page (65).png',
    'books/martin/page (66).png',
    'books/martin/page (67).png',
    'books/martin/page (68).png',
    'books/martin/page (69).png',
    'books/martin/page (70).png',
    'books/martin/page (71).png',
    'books/martin/page (72).png',
    'books/martin/page (73).png',
    'books/martin/page (74).png',
    'books/martin/page (75).png',
    'books/martin/page (76).png',
    'books/martin/page (77).png',
    'books/martin/page (78).png',
    'books/martin/page (79).png',
    'books/martin/page (80).png',
    'books/martin/page (81).png',
    'books/martin/page (82).png',
    'books/martin/page (83).png',
    'books/martin/page (84).png',
    'books/martin/page (85).png',
    'books/martin/page (86).png',
    'books/martin/page (87).png',
    'books/martin/page (88).png',
    'books/martin/page (89).png',
    'books/martin/page (90).png',
    'books/martin/page (91).png',
    'books/martin/page (92).png',
    'books/martin/page (93).png',
    'books/martin/page (94).png',
    'books/martin/page (95).png',
    'books/martin/page (96).png',
    'books/martin/page (97).png',
    'books/martin/page (98).png',
    'books/martin/page (99).png',
    'books/martin/page (100).png',
    'books/martin/page (101).png',
    'books/martin/page (102).png',
    'books/martin/page (103).png',
    'books/martin/page (104).png',
    'books/martin/page (105).png',
    'books/martin/page (106).png',
    'books/martin/page (107).png',
    'books/martin/page (108).png',
    'books/martin/page (109).png',
    'books/martin/page (110).png',
    'books/martin/page (111).png',
    'books/martin/page (112).png',
    'books/martin/page (113).png',
    'books/martin/page (114).png',
    'books/martin/page (115).png',
    'books/martin/page (116).png',
    'books/martin/page (117).png',
    'books/martin/page (118).png',
    'books/martin/page (119).png',
    'books/martin/page (120).png',
    'books/martin/page (121).png',
    'books/martin/page (122).png',
    'books/martin/page (123).png',
    'books/martin/page (124).png',
    'books/martin/page (125).png',
    'books/martin/page (126).png',
    'books/martin/page (127).png',
    'books/martin/page (128).png',
    'books/martin/page (129).png',
    'books/martin/page (130).png',
    'books/martin/page (131).png',
    'books/martin/page (132).png',
    'books/martin/page (133).png',
    'books/martin/page (134).png',
    'books/martin/page (135).png',
    'books/martin/page (136).png',
    'books/martin/page (137).png',
    'books/martin/page (138).png',
    'books/martin/page (139).png',
    'books/martin/page (140).png',
    'books/martin/page (141).png',
    'books/martin/page (142).png',
    'books/martin/page (143).png',
    'books/martin/page (144).png',
    'books/martin/page (145).png',
    'books/martin/page (146).png',
    'books/martin/page (147).png',
    'books/martin/page (148).png',
    'books/martin/page (149).png',
    'books/martin/page (150).png',
    'books/martin/page (151).png',
    'books/martin/page (152).png',
    'books/martin/page (153).png',
    'books/martin/page (154).png',
    'books/martin/page (155).png',
    'books/martin/page (156).png',
    'books/martin/page (157).png',
    'books/martin/page (158).png',
    'books/martin/page (159).png',
    'books/martin/page (160).png',
    'books/martin/page (161).png',
    'books/martin/page (162).png',
    'books/martin/page (163).png',
    'books/martin/page (164).png',
    'books/martin/page (165).png',
    'books/martin/page (166).png',
    'books/martin/page (167).png',
    'books/martin/page (168).png',
    'books/martin/page (169).png',
    'books/martin/page (170).png',
    'books/martin/page (171).png',
    'books/martin/page (172).png',
    'books/martin/page (173).png',
    'books/martin/page (174).png',
    'books/martin/page (175).png',
    'books/martin/page (176).png',
    'books/martin/page (177).png',
    'books/martin/page (178).png',
    'books/martin/page (179).png',
    'books/martin/page (180).png',
    'books/martin/page (181).png',
    'books/martin/page (182).png',
    'books/martin/page (183).png',
    'books/martin/page (184).png',
    'books/martin/page (185).png',
    'books/martin/page (186).png',
    'books/martin/page (187).png',
    'books/martin/page (188).png',
    'books/martin/page (189).png',
    'books/martin/page (190).png',
    'books/martin/page (191).png',
    'books/martin/page (192).png',
    'books/martin/page (193).png',
    'books/martin/page (194).png',
    'books/martin/page (195).png',
    'books/martin/page (196).png',
    'books/martin/page (197).png',
    'books/martin/page (198).png',
    'books/martin/page (199).png',
    'books/martin/page (200).png',
    'books/martin/page (201).png',
    'books/martin/page (202).png',
    'books/martin/page (203).png',
    'books/martin/page (204).png',
    'books/martin/page (205).png',
    'books/martin/page (206).png',
    'books/martin/page (207).png',
    'books/martin/page (208).png',
    'books/martin/page (209).png',
    'books/martin/page (210).png',
    'books/martin/page (211).png',
    'books/martin/page (212).png',
    'books/martin/page (213).png',
    'books/martin/page (214).png',
    'books/martin/page (215).png',
    'books/martin/page (216).png',
    'books/martin/page (217).png',
    'books/martin/page (218).png',
    'books/martin/page (219).png',
    'books/martin/page (220).png',
    'books/martin/page (221).png',
    'books/martin/page (222).png',
    'books/martin/page (223).png',
    'books/martin/page (224).png',
    'books/martin/page (225).png',
    'books/martin/page (226).png',
    'books/martin/page (227).png',
    'books/martin/page (228).png',
    'books/martin/page (229).png',
    'books/martin/page (230).png',
    'books/martin/page (231).png',
    'books/martin/page (232).png',
    'books/martin/page (233).png',
    'books/martin/page (234).png',
    'books/martin/page (235).png',
    'books/martin/page (236).png',
    'books/martin/page (237).png',
    'books/martin/page (238).png',
    'books/martin/page (239).png',
    'books/martin/page (240).png',
    'books/martin/page (241).png',
    'books/martin/page (242).png',
    'books/martin/page (243).png',
    'books/martin/page (244).png',
    'books/martin/page (245).png',
    'books/martin/page (246).png',
    'books/martin/page (247).png',
    'books/martin/page (248).png',
    'books/martin/page (249).png',
    'books/martin/page (250).png',
    'books/martin/page (251).png',
    'books/martin/page (252).png',
    'books/martin/page (253).png',
    'books/martin/page (254).png',
    'books/martin/page (255).png',
    'books/martin/page (256).png',
    'books/martin/page (257).png',
    'books/martin/page (258).png',
    'books/martin/page (259).png',
    'books/martin/page (260).png',
    'books/martin/page (261).png',
    'books/martin/page (262).png',
    'books/martin/page (263).png',
    'books/martin/page (264).png',
    'books/martin/page (265).png',
    'books/martin/page (266).png',
    'books/martin/page (267).png',
    'books/martin/page (268).png',
    'books/martin/page (269).png',
    'books/martin/page (270).png',
    'books/martin/page (271).png',
    'books/martin/page (272).png',
    'books/martin/page (273).png',
    'books/martin/page (274).png',
    'books/martin/page (275).png',
    'books/martin/page (276).png',
    'books/martin/page (277).png',
    'books/martin/page (278).png',
    'books/martin/page (279).png',
    'books/martin/page (280).png',
    'books/martin/page (281).png',
    'books/martin/page (282).png',
    'books/martin/page (283).png',
    'books/martin/page (284).png',
    'books/martin/page (285).png',
    'books/martin/page (286).png',
    'books/martin/page (287).png',
    'books/martin/page (288).png',
    'books/martin/page (289).png',
    'books/martin/page (290).png',
    'books/martin/page (291).png',
    'books/martin/page (292).png',
    'books/martin/page (293).png',
    'books/martin/page (294).png',
    'books/martin/page (295).png',
    'books/martin/page (296).png',
    'books/martin/page (297).png',
    'books/martin/page (298).png',
    'books/martin/page (299).png',
    'books/martin/page (300).png',
    'books/martin/page (301).png',
    'books/martin/page (302).png',
    'books/martin/page (303).png',
    'books/martin/page (304).png',
    'books/martin/page (305).png',
    'books/martin/page (306).png',
    'books/martin/page (307).png',
    'books/martin/page (308).png',
    'books/martin/page (309).png',
    'books/martin/page (310).png',
    'books/martin/page (311).png',
    'books/martin/page (312).png',
    'books/martin/page (313).png',
    'books/martin/page (314).png',
    'books/martin/page (315).png',
    'books/martin/page (316).png',
    'books/martin/page (317).png',
    'books/martin/page (318).png',
    'books/martin/page (319).png',
    'books/martin/page (320).png',
    'books/martin/page (321).png',
    'books/martin/page (322).png',
    'books/martin/page (323).png',
    'books/martin/page (324).png',
    'books/martin/page (325).png',
    'books/martin/page (326).png',
    'books/martin/page (327).png',
    'books/martin/page (328).png',
    'books/martin/page (329).png',
    'books/martin/page (330).png',
    'books/martin/page (331).png',
    'books/martin/page (332).png',
    'books/martin/page (333).png',
    'books/martin/page (334).png',
    'books/martin/page (335).png',
    'books/martin/page (336).png',
    'books/martin/page (337).png',
    'books/martin/page (338).png',
    'books/martin/page (339).png',
    'books/martin/page (340).png',
    'books/martin/page (341).png',
    'books/martin/page (342).png',
    'books/martin/page (343).png',
    'books/martin/page (344).png',
    'books/martin/page (345).png',
    'books/martin/page (346).png',
    'books/martin/page (347).png',
    'books/martin/page (348).png',
    'books/martin/page (349).png',
    'books/martin/page (350).png',
    'books/martin/page (351).png',
    'books/martin/page (352).png',
    'books/martin/page (353).png',
    'books/martin/page (354).png',
    'books/martin/page (355).png',
    'books/martin/page (356).png',
    'books/martin/page (357).png',
    'books/martin/page (358).png',
    'books/martin/page (359).png',
    'books/martin/page (360).png',
    'books/martin/page (361).png',
    'books/martin/page (362).png',
    'books/martin/page (363).png',
    'books/martin/page (364).png',
    'books/martin/page (365).png',
    'books/martin/page (366).png',
    'books/martin/page (367).png',
    'books/martin/page (368).png',
    'books/martin/page (369).png',
    'books/martin/page (370).png',
    'books/martin/page (371).png',
    'books/martin/page (372).png',
    'books/martin/page (373).png',
    'books/martin/page (374).png',
    'books/martin/page (375).png',
    'books/martin/page (376).png',
    'books/martin/page (377).png',
    'books/martin/page (378).png',
    'books/martin/page (379).png',
    'books/martin/page (380).png',
    'books/martin/page (381).png',
    'books/martin/page (382).png',
    'books/martin/page (383).png',
    'books/martin/page (384).png',
    'books/martin/page (385).png',
    'books/martin/page (386).png',
    'books/martin/page (387).png',
    'books/martin/page (388).png',
    'books/martin/page (389).png',
    'books/martin/page (390).png',
    'books/martin/page (391).png',
    'books/martin/page (392).png',
    'books/martin/page (393).png',
    'books/martin/page (394).png',
    'books/martin/page (395).png',
    'books/martin/page (396).png',
    'books/martin/page (397).png',
    'books/martin/page (398).png',
    'books/martin/page (399).png',
    'books/martin/page (400).png',
    'books/martin/page (401).png',
    'books/martin/page (402).png',
    'books/martin/page (403).png',
    'books/martin/page (404).png',
    'books/martin/page (405).png',
    'books/martin/page (406).png',
    'books/martin/page (407).png',
    'books/martin/page (408).png',
    'books/martin/page (409).png',
    'books/martin/page (410).png',
    'books/martin/page (411).png',
    'books/martin/page (412).png',
    'books/martin/page (413).png',
    'books/martin/page (414).png',
    'books/martin/page (415).png',
    'books/martin/page (416).png',
    'books/martin/page (417).png',
    'books/martin/page (418).png',
    'books/martin/page (419).png',
    'books/martin/page (420).png',
    'books/martin/page (421).png',
    'books/martin/page (422).png',
    'books/martin/page (423).png',
    'books/martin/page (424).png',
    'books/martin/page (425).png',
    'books/martin/page (426).png',
    'books/martin/page (427).png',
    'books/martin/page (428).png',
    'books/martin/page (429).png',
    'books/martin/page (430).png',
    'books/martin/page (431).png',
    'books/martin/page (432).png',
    'books/martin/page (433).png',
    'books/martin/page (434).png',
    'books/martin/page (435).png',
    'books/martin/page (436).png',
    'books/martin/page (437).png',
    'books/martin/page (438).png',
    'books/martin/page (439).png',
    'books/martin/page (440).png',
    'books/martin/page (441).png',
    'books/martin/page (442).png',
    'books/martin/page (443).png',
    'books/martin/page (444).png',
    'books/martin/page (445).png',
    'books/martin/page (446).png',
    'books/martin/page (447).png',
    'books/martin/page (448).png',
    'books/martin/page (449).png',
    'books/martin/page (450).png',
    'books/martin/page (451).png',
    'books/martin/page (452).png',
    'books/martin/page (453).png',
    'books/martin/page (454).png',
    'books/martin/page (455).png',
    'books/martin/page (456).png',
    'books/martin/page (457).png',
    'books/martin/page (458).png',
    'books/martin/page (459).png',
    'books/martin/page (460).png',
    'books/martin/page (461).png',
    'books/martin/page (462).png',
    'books/martin/page (463).png',
    'books/martin/page (464).png',
    'books/martin/page (465).png',
    'books/martin/page (466).png',
    'books/martin/page (467).png',
    'books/martin/page (468).png',
    'books/martin/page (469).png',
    'books/martin/page (470).png',
    'books/martin/page (471).png',
    'books/martin/page (472).png',
    'books/martin/page (473).png',
    'books/martin/page (474).png',
    'books/martin/page (475).png',
    'books/martin/page (476).png',
    'books/martin/page (477).png',
    'books/martin/page (478).png',
    'books/martin/page (479).png',
    'books/martin/page (480).png',
    'books/martin/page (481).png',
    'books/martin/page (482).png',
    'books/martin/page (483).png',
    'books/martin/page (484).png',
    'books/martin/page (485).png',
    'books/martin/page (486).png',
    'books/martin/page (487).png',
    'books/martin/page (488).png',
    'books/martin/page (489).png',
    'books/martin/page (490).png',
    'books/martin/page (491).png',
    'books/martin/page (492).png',
    'books/martin/page (493).png',
    'books/martin/page (494).png',
    'books/martin/page (495).png',
    'books/martin/page (496).png',
    'books/martin/page (497).png',
    'books/martin/page (498).png',
    'books/martin/page (499).png',
    'books/martin/page (500).png',
    'books/martin/page (501).png',
    'books/martin/page (502).png',
    'books/martin/page (503).png',
    'books/martin/page (504).png',
    'books/martin/page (505).png',
    'books/martin/page (506).png',
    'books/martin/page (507).png',
    'books/martin/page (508).png',
    'books/martin/page (509).png',
    'books/martin/page (510).png',
    'books/martin/page (511).png',
    'books/martin/page (512).png',
    'books/martin/page (513).png',
    'books/martin/page (514).png',
    'books/martin/page (515).png',
    'books/martin/page (516).png',
    'books/martin/page (517).png',
    'books/martin/page (518).png',
    'books/martin/page (519).png',
    'books/martin/page (520).png',
    'books/martin/page (521).png',
    'books/martin/page (522).png',
    'books/martin/page (523).png',
    'books/martin/page (524).png',
    'books/martin/page (525).png',
    'books/martin/page (526).png',
    'books/martin/page (527).png',
    'books/martin/page (528).png',
    'books/martin/page (529).png',
    'books/martin/page (530).png',
    'books/martin/page (531).png',
    'books/martin/page (532).png',
    'books/martin/page (533).png',
    'books/martin/page (534).png',
    'books/martin/page (535).png',
    'books/martin/page (536).png',
    'books/martin/page (537).png',
    'books/martin/page (538).png',
    'books/martin/page (539).png',
    'books/martin/page (540).png',
    'books/martin/page (541).png',
    'books/martin/page (542).png',
    'books/martin/page (543).png',
    'books/martin/page (544).png',
    'books/martin/page (545).png',
    'books/martin/page (546).png',
    'books/martin/page (547).png',
    'books/martin/page (548).png',
    'books/martin/page (549).png',
    'books/martin/page (550).png',
    'books/martin/page (551).png',
    'books/martin/page (552).png',
    'books/martin/page (553).png',
    'books/martin/page (554).png',
    'books/martin/page (555).png',
    'books/martin/page (556).png',
    'books/martin/page (557).png',
    'books/martin/page (558).png',
    'books/martin/page (559).png',
    'books/martin/page (560).png',
    'books/martin/page (561).png',
    'books/martin/page (562).png',
    'books/martin/page (563).png',
    'books/martin/page (564).png',
    'books/martin/page (565).png',
    'books/martin/page (566).png',
    'books/martin/page (567).png',
    'books/martin/page (568).png',
    'books/martin/page (569).png',
    'books/martin/page (570).png',
    'books/martin/page (571).png',
    'books/martin/page (572).png',
    'books/martin/page (573).png',
    'books/martin/page (574).png',
    'books/martin/page (575).png',
    'books/martin/page (576).png',
    'books/martin/page (577).png',
    'books/martin/page (578).png',
    'books/martin/page (579).png',
    'books/martin/page (580).png',
    'books/martin/page (581).png',
    'books/martin/page (582).png',
    'books/martin/page (583).png',
    'books/martin/page (584).png',
    'books/martin/page (585).png',
    'books/martin/page (586).png',
    'books/martin/page (587).png',
    'books/martin/page (588).png',
    'books/martin/page (589).png',
    'books/martin/page (590).png',
    'books/martin/page (591).png',
    'books/martin/page (592).png',
    'books/martin/page (593).png',
    'books/martin/page (594).png',
    'books/martin/page (595).png',
    'books/martin/page (596).png',
    'books/martin/page (597).png',
    'books/martin/page (598).png',
    'books/martin/page (599).png',
    'books/martin/page (600).png',
    'books/martin/page (601).png',
    'books/martin/page (602).png',
    'books/martin/page (603).png',
    'books/martin/page (604).png',
    'books/martin/page (605).png',
    'books/martin/page (606).png',
    'books/martin/page (607).png',
    'books/martin/page (608).png',
    'books/martin/page (609).png',
    'books/martin/page (610).png',
    'books/martin/page (611).png',
    'books/martin/page (612).png',
    'books/martin/page (613).png',
    'books/martin/page (614).png',
    'books/martin/page (615).png',
    'books/martin/page (616).png',
    'books/martin/page (617).png',
    'books/martin/page (618).png',
    'books/martin/page (619).png',
    'books/martin/page (620).png',
    'books/martin/page (621).png',
    'books/martin/page (622).png',
    'books/martin/page (623).png',
    'books/martin/page (624).png',
    'books/martin/page (625).png',
    'books/martin/page (626).png',
    'books/martin/page (627).png',
    'books/martin/page (628).png',
    'books/martin/page (629).png',
    'books/martin/page (630).png',
    'books/martin/page (631).png',
    'books/martin/page (632).png',
    'books/martin/page (633).png',
    'books/martin/page (634).png',
    'books/martin/page (635).png',
    'books/martin/page (636).png',
    'books/martin/page (637).png',
    'books/martin/page (638).png',
    'books/martin/page (639).png',
    'books/martin/page (640).png',
    'books/martin/page (641).png',
    'books/martin/page (642).png',
    'books/martin/page (643).png',
    'books/martin/page (644).png',
    'books/martin/page (645).png',
    'books/martin/page (646).png',
    'books/martin/page (647).png',
    'books/martin/page (648).png',
    'books/martin/page (649).png',
    'books/martin/page (650).png',
    'books/martin/page (651).png',
    'books/martin/page (652).png',
    'books/martin/page (653).png',
    'books/martin/page (654).png',
    'books/martin/page (655).png',
    'books/martin/page (656).png',
    'books/martin/page (657).png',
    'books/martin/page (658).png',
    'books/martin/page (659).png',
    'books/martin/page (660).png',
    'books/martin/page (661).png',
    'books/martin/page (662).png',
    'books/martin/page (663).png',
    'books/martin/page (664).png',
    'books/martin/page (665).png',
    'books/martin/page (666).png',
    'books/martin/page (667).png',
    'books/martin/page (668).png',
    'books/martin/page (669).png',
    'books/martin/page (670).png',
    'books/martin/page (671).png',
    'books/martin/page (672).png',
    'books/martin/page (673).png',
    'books/martin/page (674).png',
    'books/martin/page (675).png',
    'books/martin/page (676).png',
    'books/martin/page (677).png',
    'books/martin/page (678).png',
    'books/martin/page (679).png',
    'books/martin/page (680).png',
    'books/martin/page (681).png',
    'books/martin/page (682).png',
    'books/martin/page (683).png',
    'books/martin/page (684).png',
    'books/martin/page (685).png',
    'books/martin/page (686).png',
    'books/martin/page (687).png',
    'books/martin/page (688).png',
    'books/martin/page (689).png',
    'books/martin/page (690).png',
    'books/martin/page (691).png',
    'books/martin/page (692).png',
    'books/martin/page (693).png',
    'books/martin/page (694).png',
    'books/martin/page (695).png',
    'books/martin/page (696).png',
    'books/martin/page (697).png',
    'books/martin/page (698).png',
    'books/martin/page (699).png',
    'books/martin/page (700).png',
    'books/martin/page (701).png',
    'books/martin/page (702).png',
    'books/martin/page (703).png',
    'books/martin/page (704).png',
    'books/martin/page (705).png',
    'books/martin/page (706).png',
    'books/martin/page (707).png',
    'books/martin/page (708).png',
    'books/martin/page (709).png',
    'books/martin/page (710).png',
    'books/martin/page (711).png',
    'books/martin/page (712).png',
    'books/martin/page (713).png',
    'books/martin/page (714).png',
    'books/martin/page (715).png',
    'books/martin/page (716).png',
    'books/martin/page (717).png',
    'books/martin/page (718).png',
    'books/martin/page (719).png',
    'books/martin/page (720).png',
    'books/martin/page (721).png',
    'books/martin/page (722).png',
    'books/martin/page (723).png',
    'books/martin/page (724).png',
    'books/martin/page (725).png',
    'books/martin/page (726).png',
    'books/martin/page (727).png',
    'books/martin/page (728).png',
    'books/martin/page (729).png',
    'books/martin/page (730).png',
    'books/martin/page (731).png',
    'books/martin/page (732).png',
    'books/martin/page (733).png',
    'books/martin/page (734).png',
    'books/martin/page (735).png',
    'books/martin/page (736).png',
    'books/martin/page (737).png',
    'books/martin/page (738).png',
    'books/martin/page (739).png',
    'books/martin/page (740).png',
    'books/martin/page (741).png',
    'books/martin/page (742).png',
    'books/martin/page (743).png',
    'books/martin/page (744).png',
    'books/martin/page (745).png',
    'books/martin/page (746).png',
    'books/martin/page (747).png',
    'books/martin/page (748).png',
    'books/martin/page (749).png',
    'books/martin/page (750).png',
    'books/martin/page (751).png',
    'books/martin/page (752).png',
    'books/martin/page (753).png',
    'books/martin/page (754).png',
    'books/martin/page (755).png',
    'books/martin/page (756).png',
    'books/martin/page (757).png',
    'books/martin/page (758).png',
    'books/martin/page (759).png',
    'books/martin/page (760).png',
    'books/martin/page (761).png',
    'books/martin/page (762).png',
    'books/martin/page (763).png',
    'books/martin/page (764).png',
    'books/martin/page (765).png',
    'books/martin/page (766).png',
    'books/martin/page (767).png',
    'books/martin/page (768).png',
    'books/martin/page (769).png',
    'books/martin/page (770).png',
    'books/martin/page (771).png',
    'books/martin/page (772).png',
    'books/martin/page (773).png',
    'books/martin/page (774).png',
    'books/martin/page (775).png',
    'books/martin/page (776).png',
    'books/martin/page (777).png',
    'books/martin/page (778).png',
    'books/martin/page (779).png',
    'books/martin/page (780).png',
    'books/martin/page (781).png',
    'books/martin/page (782).png',
    'books/martin/page (783).png',
    'books/martin/page (784).png',
    'books/martin/page (785).png',
    'books/martin/page (786).png',
    'books/martin/page (787).png',
    'books/martin/page (788).png',
    'books/martin/page (789).png',
    'books/martin/page (790).png',
    'books/martin/page (791).png',
    'books/martin/page (792).png',
    'books/martin/page (793).png',
    'books/martin/page (794).png',
    'books/martin/page (795).png',
    'books/martin/page (796).png',
    'books/martin/page (797).png',
    'books/martin/page (798).png',
    'books/martin/page (799).png',
    'books/martin/page (800).png',
    'books/martin/page (801).png',
    'books/martin/page (802).png',
    'books/martin/page (803).png',
    'books/martin/page (804).png',
    'books/martin/page (805).png',
    'books/martin/page (806).png',
    'books/martin/page (807).png',
    'books/martin/page (808).png',
    'books/martin/page (809).png',
    'books/martin/page (810).png',
    'books/martin/page (811).png',
    'books/martin/page (812).png',
    'books/martin/page (813).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
