import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class middlemarch extends StatefulWidget {
  const middlemarch({Key? key}) : super(key: key);

  @override
  State<middlemarch> createState() => _middlemarchState();
}

class _middlemarchState extends State<middlemarch> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/middlemarch/page (1).png',
    'books/middlemarch/page (2).png',
    'books/middlemarch/page (3).png',
    'books/middlemarch/page (4).png',
    'books/middlemarch/page (5).png',
    'books/middlemarch/page (6).png',
    'books/middlemarch/page (7).png',
    'books/middlemarch/page (8).png',
    'books/middlemarch/page (9).png',
    'books/middlemarch/page (10).png',
    'books/middlemarch/page (11).png',
    'books/middlemarch/page (12).png',
    'books/middlemarch/page (13).png',
    'books/middlemarch/page (14).png',
    'books/middlemarch/page (15).png',
    'books/middlemarch/page (16).png',
    'books/middlemarch/page (17).png',
    'books/middlemarch/page (18).png',
    'books/middlemarch/page (19).png',
    'books/middlemarch/page (20).png',
    'books/middlemarch/page (21).png',
    'books/middlemarch/page (22).png',
    'books/middlemarch/page (23).png',
    'books/middlemarch/page (24).png',
    'books/middlemarch/page (25).png',
    'books/middlemarch/page (26).png',
    'books/middlemarch/page (27).png',
    'books/middlemarch/page (28).png',
    'books/middlemarch/page (29).png',
    'books/middlemarch/page (30).png',
    'books/middlemarch/page (31).png',
    'books/middlemarch/page (32).png',
    'books/middlemarch/page (33).png',
    'books/middlemarch/page (34).png',
    'books/middlemarch/page (35).png',
    'books/middlemarch/page (36).png',
    'books/middlemarch/page (37).png',
    'books/middlemarch/page (38).png',
    'books/middlemarch/page (39).png',
    'books/middlemarch/page (40).png',
    'books/middlemarch/page (41).png',
    'books/middlemarch/page (42).png',
    'books/middlemarch/page (43).png',
    'books/middlemarch/page (44).png',
    'books/middlemarch/page (45).png',
    'books/middlemarch/page (46).png',
    'books/middlemarch/page (47).png',
    'books/middlemarch/page (48).png',
    'books/middlemarch/page (49).png',
    'books/middlemarch/page (50).png',
    'books/middlemarch/page (51).png',
    'books/middlemarch/page (52).png',
    'books/middlemarch/page (53).png',
    'books/middlemarch/page (54).png',
    'books/middlemarch/page (55).png',
    'books/middlemarch/page (56).png',
    'books/middlemarch/page (57).png',
    'books/middlemarch/page (58).png',
    'books/middlemarch/page (59).png',
    'books/middlemarch/page (60).png',
    'books/middlemarch/page (61).png',
    'books/middlemarch/page (62).png',
    'books/middlemarch/page (63).png',
    'books/middlemarch/page (64).png',
    'books/middlemarch/page (65).png',
    'books/middlemarch/page (66).png',
    'books/middlemarch/page (67).png',
    'books/middlemarch/page (68).png',
    'books/middlemarch/page (69).png',
    'books/middlemarch/page (70).png',
    'books/middlemarch/page (71).png',
    'books/middlemarch/page (72).png',
    'books/middlemarch/page (73).png',
    'books/middlemarch/page (74).png',
    'books/middlemarch/page (75).png',
    'books/middlemarch/page (76).png',
    'books/middlemarch/page (77).png',
    'books/middlemarch/page (78).png',
    'books/middlemarch/page (79).png',
    'books/middlemarch/page (80).png',
    'books/middlemarch/page (81).png',
    'books/middlemarch/page (82).png',
    'books/middlemarch/page (83).png',
    'books/middlemarch/page (84).png',
    'books/middlemarch/page (85).png',
    'books/middlemarch/page (86).png',
    'books/middlemarch/page (87).png',
    'books/middlemarch/page (88).png',
    'books/middlemarch/page (89).png',
    'books/middlemarch/page (90).png',
    'books/middlemarch/page (91).png',
    'books/middlemarch/page (92).png',
    'books/middlemarch/page (93).png',
    'books/middlemarch/page (94).png',
    'books/middlemarch/page (95).png',
    'books/middlemarch/page (96).png',
    'books/middlemarch/page (97).png',
    'books/middlemarch/page (98).png',
    'books/middlemarch/page (99).png',
    'books/middlemarch/page (100).png',
    'books/middlemarch/page (101).png',
    'books/middlemarch/page (102).png',
    'books/middlemarch/page (103).png',
    'books/middlemarch/page (104).png',
    'books/middlemarch/page (105).png',
    'books/middlemarch/page (106).png',
    'books/middlemarch/page (107).png',
    'books/middlemarch/page (108).png',
    'books/middlemarch/page (109).png',
    'books/middlemarch/page (110).png',
    'books/middlemarch/page (111).png',
    'books/middlemarch/page (112).png',
    'books/middlemarch/page (113).png',
    'books/middlemarch/page (114).png',
    'books/middlemarch/page (115).png',
    'books/middlemarch/page (116).png',
    'books/middlemarch/page (117).png',
    'books/middlemarch/page (118).png',
    'books/middlemarch/page (119).png',
    'books/middlemarch/page (120).png',
    'books/middlemarch/page (121).png',
    'books/middlemarch/page (122).png',
    'books/middlemarch/page (123).png',
    'books/middlemarch/page (124).png',
    'books/middlemarch/page (125).png',
    'books/middlemarch/page (126).png',
    'books/middlemarch/page (127).png',
    'books/middlemarch/page (128).png',
    'books/middlemarch/page (129).png',
    'books/middlemarch/page (130).png',
    'books/middlemarch/page (131).png',
    'books/middlemarch/page (132).png',
    'books/middlemarch/page (133).png',
    'books/middlemarch/page (134).png',
    'books/middlemarch/page (135).png',
    'books/middlemarch/page (136).png',
    'books/middlemarch/page (137).png',
    'books/middlemarch/page (138).png',
    'books/middlemarch/page (139).png',
    'books/middlemarch/page (140).png',
    'books/middlemarch/page (141).png',
    'books/middlemarch/page (142).png',
    'books/middlemarch/page (143).png',
    'books/middlemarch/page (144).png',
    'books/middlemarch/page (145).png',
    'books/middlemarch/page (146).png',
    'books/middlemarch/page (147).png',
    'books/middlemarch/page (148).png',
    'books/middlemarch/page (149).png',
    'books/middlemarch/page (150).png',
    'books/middlemarch/page (151).png',
    'books/middlemarch/page (152).png',
    'books/middlemarch/page (153).png',
    'books/middlemarch/page (154).png',
    'books/middlemarch/page (155).png',
    'books/middlemarch/page (156).png',
    'books/middlemarch/page (157).png',
    'books/middlemarch/page (158).png',
    'books/middlemarch/page (159).png',
    'books/middlemarch/page (160).png',
    'books/middlemarch/page (161).png',
    'books/middlemarch/page (162).png',
    'books/middlemarch/page (163).png',
    'books/middlemarch/page (164).png',
    'books/middlemarch/page (165).png',
    'books/middlemarch/page (166).png',
    'books/middlemarch/page (167).png',
    'books/middlemarch/page (168).png',
    'books/middlemarch/page (169).png',
    'books/middlemarch/page (170).png',
    'books/middlemarch/page (171).png',
    'books/middlemarch/page (172).png',
    'books/middlemarch/page (173).png',
    'books/middlemarch/page (174).png',
    'books/middlemarch/page (175).png',
    'books/middlemarch/page (176).png',
    'books/middlemarch/page (177).png',
    'books/middlemarch/page (178).png',
    'books/middlemarch/page (179).png',
    'books/middlemarch/page (180).png',
    'books/middlemarch/page (181).png',
    'books/middlemarch/page (182).png',
    'books/middlemarch/page (183).png',
    'books/middlemarch/page (184).png',
    'books/middlemarch/page (185).png',
    'books/middlemarch/page (186).png',
    'books/middlemarch/page (187).png',
    'books/middlemarch/page (188).png',
    'books/middlemarch/page (189).png',
    'books/middlemarch/page (190).png',
    'books/middlemarch/page (191).png',
    'books/middlemarch/page (192).png',
    'books/middlemarch/page (193).png',
    'books/middlemarch/page (194).png',
    'books/middlemarch/page (195).png',
    'books/middlemarch/page (196).png',
    'books/middlemarch/page (197).png',
    'books/middlemarch/page (198).png',
    'books/middlemarch/page (199).png',
    'books/middlemarch/page (200).png',
    'books/middlemarch/page (201).png',
    'books/middlemarch/page (202).png',
    'books/middlemarch/page (203).png',
    'books/middlemarch/page (204).png',
    'books/middlemarch/page (205).png',
    'books/middlemarch/page (206).png',
    'books/middlemarch/page (207).png',
    'books/middlemarch/page (208).png',
    'books/middlemarch/page (209).png',
    'books/middlemarch/page (210).png',
    'books/middlemarch/page (211).png',
    'books/middlemarch/page (212).png',
    'books/middlemarch/page (213).png',
    'books/middlemarch/page (214).png',
    'books/middlemarch/page (215).png',
    'books/middlemarch/page (216).png',
    'books/middlemarch/page (217).png',
    'books/middlemarch/page (218).png',
    'books/middlemarch/page (219).png',
    'books/middlemarch/page (220).png',
    'books/middlemarch/page (221).png',
    'books/middlemarch/page (222).png',
    'books/middlemarch/page (223).png',
    'books/middlemarch/page (224).png',
    'books/middlemarch/page (225).png',
    'books/middlemarch/page (226).png',
    'books/middlemarch/page (227).png',
    'books/middlemarch/page (228).png',
    'books/middlemarch/page (229).png',
    'books/middlemarch/page (230).png',
    'books/middlemarch/page (231).png',
    'books/middlemarch/page (232).png',
    'books/middlemarch/page (233).png',
    'books/middlemarch/page (234).png',
    'books/middlemarch/page (235).png',
    'books/middlemarch/page (236).png',
    'books/middlemarch/page (237).png',
    'books/middlemarch/page (238).png',
    'books/middlemarch/page (239).png',
    'books/middlemarch/page (240).png',
    'books/middlemarch/page (241).png',
    'books/middlemarch/page (242).png',
    'books/middlemarch/page (243).png',
    'books/middlemarch/page (244).png',
    'books/middlemarch/page (245).png',
    'books/middlemarch/page (246).png',
    'books/middlemarch/page (247).png',
    'books/middlemarch/page (248).png',
    'books/middlemarch/page (249).png',
    'books/middlemarch/page (250).png',
    'books/middlemarch/page (251).png',
    'books/middlemarch/page (252).png',
    'books/middlemarch/page (253).png',
    'books/middlemarch/page (254).png',
    'books/middlemarch/page (255).png',
    'books/middlemarch/page (256).png',
    'books/middlemarch/page (257).png',
    'books/middlemarch/page (258).png',
    'books/middlemarch/page (259).png',
    'books/middlemarch/page (260).png',
    'books/middlemarch/page (261).png',
    'books/middlemarch/page (262).png',
    'books/middlemarch/page (263).png',
    'books/middlemarch/page (264).png',
    'books/middlemarch/page (265).png',
    'books/middlemarch/page (266).png',
    'books/middlemarch/page (267).png',
    'books/middlemarch/page (268).png',
    'books/middlemarch/page (269).png',
    'books/middlemarch/page (270).png',
    'books/middlemarch/page (271).png',
    'books/middlemarch/page (272).png',
    'books/middlemarch/page (273).png',
    'books/middlemarch/page (274).png',
    'books/middlemarch/page (275).png',
    'books/middlemarch/page (276).png',
    'books/middlemarch/page (277).png',
    'books/middlemarch/page (278).png',
    'books/middlemarch/page (279).png',
    'books/middlemarch/page (280).png',
    'books/middlemarch/page (281).png',
    'books/middlemarch/page (282).png',
    'books/middlemarch/page (283).png',
    'books/middlemarch/page (284).png',
    'books/middlemarch/page (285).png',
    'books/middlemarch/page (286).png',
    'books/middlemarch/page (287).png',
    'books/middlemarch/page (288).png',
    'books/middlemarch/page (289).png',
    'books/middlemarch/page (290).png',
    'books/middlemarch/page (291).png',
    'books/middlemarch/page (292).png',
    'books/middlemarch/page (293).png',
    'books/middlemarch/page (294).png',
    'books/middlemarch/page (295).png',
    'books/middlemarch/page (296).png',
    'books/middlemarch/page (297).png',
    'books/middlemarch/page (298).png',
    'books/middlemarch/page (299).png',
    'books/middlemarch/page (300).png',
    'books/middlemarch/page (301).png',
    'books/middlemarch/page (302).png',
    'books/middlemarch/page (303).png',
    'books/middlemarch/page (304).png',
    'books/middlemarch/page (305).png',
    'books/middlemarch/page (306).png',
    'books/middlemarch/page (307).png',
    'books/middlemarch/page (308).png',
    'books/middlemarch/page (309).png',
    'books/middlemarch/page (310).png',
    'books/middlemarch/page (311).png',
    'books/middlemarch/page (312).png',
    'books/middlemarch/page (313).png',
    'books/middlemarch/page (314).png',
    'books/middlemarch/page (315).png',
    'books/middlemarch/page (316).png',
    'books/middlemarch/page (317).png',
    'books/middlemarch/page (318).png',
    'books/middlemarch/page (319).png',
    'books/middlemarch/page (320).png',
    'books/middlemarch/page (321).png',
    'books/middlemarch/page (322).png',
    'books/middlemarch/page (323).png',
    'books/middlemarch/page (324).png',
    'books/middlemarch/page (325).png',
    'books/middlemarch/page (326).png',
    'books/middlemarch/page (327).png',
    'books/middlemarch/page (328).png',
    'books/middlemarch/page (329).png',
    'books/middlemarch/page (330).png',
    'books/middlemarch/page (331).png',
    'books/middlemarch/page (332).png',
    'books/middlemarch/page (333).png',
    'books/middlemarch/page (334).png',
    'books/middlemarch/page (335).png',
    'books/middlemarch/page (336).png',
    'books/middlemarch/page (337).png',
    'books/middlemarch/page (338).png',
    'books/middlemarch/page (339).png',
    'books/middlemarch/page (340).png',
    'books/middlemarch/page (341).png',
    'books/middlemarch/page (342).png',
    'books/middlemarch/page (343).png',
    'books/middlemarch/page (344).png',
    'books/middlemarch/page (345).png',
    'books/middlemarch/page (346).png',
    'books/middlemarch/page (347).png',
    'books/middlemarch/page (348).png',
    'books/middlemarch/page (349).png',
    'books/middlemarch/page (350).png',
    'books/middlemarch/page (351).png',
    'books/middlemarch/page (352).png',
    'books/middlemarch/page (353).png',
    'books/middlemarch/page (354).png',
    'books/middlemarch/page (355).png',
    'books/middlemarch/page (356).png',
    'books/middlemarch/page (357).png',
    'books/middlemarch/page (358).png',
    'books/middlemarch/page (359).png',
    'books/middlemarch/page (360).png',
    'books/middlemarch/page (361).png',
    'books/middlemarch/page (362).png',
    'books/middlemarch/page (363).png',
    'books/middlemarch/page (364).png',
    'books/middlemarch/page (365).png',
    'books/middlemarch/page (366).png',
    'books/middlemarch/page (367).png',
    'books/middlemarch/page (368).png',
    'books/middlemarch/page (369).png',
    'books/middlemarch/page (370).png',
    'books/middlemarch/page (371).png',
    'books/middlemarch/page (372).png',
    'books/middlemarch/page (373).png',
    'books/middlemarch/page (374).png',
    'books/middlemarch/page (375).png',
    'books/middlemarch/page (376).png',
    'books/middlemarch/page (377).png',
    'books/middlemarch/page (378).png',
    'books/middlemarch/page (379).png',
    'books/middlemarch/page (380).png',
    'books/middlemarch/page (381).png',
    'books/middlemarch/page (382).png',
    'books/middlemarch/page (383).png',
    'books/middlemarch/page (384).png',
    'books/middlemarch/page (385).png',
    'books/middlemarch/page (386).png',
    'books/middlemarch/page (387).png',
    'books/middlemarch/page (388).png',
    'books/middlemarch/page (389).png',
    'books/middlemarch/page (390).png',
    'books/middlemarch/page (391).png',
    'books/middlemarch/page (392).png',
    'books/middlemarch/page (393).png',
    'books/middlemarch/page (394).png',
    'books/middlemarch/page (395).png',
    'books/middlemarch/page (396).png',
    'books/middlemarch/page (397).png',
    'books/middlemarch/page (398).png',
    'books/middlemarch/page (399).png',
    'books/middlemarch/page (400).png',
    'books/middlemarch/page (401).png',
    'books/middlemarch/page (402).png',
    'books/middlemarch/page (403).png',
    'books/middlemarch/page (404).png',
    'books/middlemarch/page (405).png',
    'books/middlemarch/page (406).png',
    'books/middlemarch/page (407).png',
    'books/middlemarch/page (408).png',
    'books/middlemarch/page (409).png',
    'books/middlemarch/page (410).png',
    'books/middlemarch/page (411).png',
    'books/middlemarch/page (412).png',
    'books/middlemarch/page (413).png',
    'books/middlemarch/page (414).png',
    'books/middlemarch/page (415).png',
    'books/middlemarch/page (416).png',
    'books/middlemarch/page (417).png',
    'books/middlemarch/page (418).png',
    'books/middlemarch/page (419).png',
    'books/middlemarch/page (420).png',
    'books/middlemarch/page (421).png',
    'books/middlemarch/page (422).png',
    'books/middlemarch/page (423).png',
    'books/middlemarch/page (424).png',
    'books/middlemarch/page (425).png',
    'books/middlemarch/page (426).png',
    'books/middlemarch/page (427).png',
    'books/middlemarch/page (428).png',
    'books/middlemarch/page (429).png',
    'books/middlemarch/page (430).png',
    'books/middlemarch/page (431).png',
    'books/middlemarch/page (432).png',
    'books/middlemarch/page (433).png',
    'books/middlemarch/page (434).png',
    'books/middlemarch/page (435).png',
    'books/middlemarch/page (436).png',
    'books/middlemarch/page (437).png',
    'books/middlemarch/page (438).png',
    'books/middlemarch/page (439).png',
    'books/middlemarch/page (440).png',
    'books/middlemarch/page (441).png',
    'books/middlemarch/page (442).png',
    'books/middlemarch/page (443).png',
    'books/middlemarch/page (444).png',
    'books/middlemarch/page (445).png',
    'books/middlemarch/page (446).png',
    'books/middlemarch/page (447).png',
    'books/middlemarch/page (448).png',
    'books/middlemarch/page (449).png',
    'books/middlemarch/page (450).png',
    'books/middlemarch/page (451).png',
    'books/middlemarch/page (452).png',
    'books/middlemarch/page (453).png',
    'books/middlemarch/page (454).png',
    'books/middlemarch/page (455).png',
    'books/middlemarch/page (456).png',
    'books/middlemarch/page (457).png',
    'books/middlemarch/page (458).png',
    'books/middlemarch/page (459).png',
    'books/middlemarch/page (460).png',
    'books/middlemarch/page (461).png',
    'books/middlemarch/page (462).png',
    'books/middlemarch/page (463).png',
    'books/middlemarch/page (464).png',
    'books/middlemarch/page (465).png',
    'books/middlemarch/page (466).png',
    'books/middlemarch/page (467).png',
    'books/middlemarch/page (468).png',
    'books/middlemarch/page (469).png',
    'books/middlemarch/page (470).png',
    'books/middlemarch/page (471).png',
    'books/middlemarch/page (472).png',
    'books/middlemarch/page (473).png',
    'books/middlemarch/page (474).png',
    'books/middlemarch/page (475).png',
    'books/middlemarch/page (476).png',
    'books/middlemarch/page (477).png',
    'books/middlemarch/page (478).png',
    'books/middlemarch/page (479).png',
    'books/middlemarch/page (480).png',
    'books/middlemarch/page (481).png',
    'books/middlemarch/page (482).png',
    'books/middlemarch/page (483).png',
    'books/middlemarch/page (484).png',
    'books/middlemarch/page (485).png',
    'books/middlemarch/page (486).png',
    'books/middlemarch/page (487).png',
    'books/middlemarch/page (488).png',
    'books/middlemarch/page (489).png',
    'books/middlemarch/page (490).png',
    'books/middlemarch/page (491).png',
    'books/middlemarch/page (492).png',
    'books/middlemarch/page (493).png',
    'books/middlemarch/page (494).png',
    'books/middlemarch/page (495).png',
    'books/middlemarch/page (496).png',
    'books/middlemarch/page (497).png',
    'books/middlemarch/page (498).png',
    'books/middlemarch/page (499).png',
    'books/middlemarch/page (500).png',
    'books/middlemarch/page (501).png',
    'books/middlemarch/page (502).png',
    'books/middlemarch/page (503).png',
    'books/middlemarch/page (504).png',
    'books/middlemarch/page (505).png',
    'books/middlemarch/page (506).png',
    'books/middlemarch/page (507).png',
    'books/middlemarch/page (508).png',
    'books/middlemarch/page (509).png',
    'books/middlemarch/page (510).png',
    'books/middlemarch/page (511).png',
    'books/middlemarch/page (512).png',
    'books/middlemarch/page (513).png',
    'books/middlemarch/page (514).png',
    'books/middlemarch/page (515).png',
    'books/middlemarch/page (516).png',
    'books/middlemarch/page (517).png',
    'books/middlemarch/page (518).png',
    'books/middlemarch/page (519).png',
    'books/middlemarch/page (520).png',
    'books/middlemarch/page (521).png',
    'books/middlemarch/page (522).png',
    'books/middlemarch/page (523).png',
    'books/middlemarch/page (524).png',
    'books/middlemarch/page (525).png',
    'books/middlemarch/page (526).png',
    'books/middlemarch/page (527).png',
    'books/middlemarch/page (528).png',
    'books/middlemarch/page (529).png',
    'books/middlemarch/page (530).png',
    'books/middlemarch/page (531).png',
    'books/middlemarch/page (532).png',
    'books/middlemarch/page (533).png',
    'books/middlemarch/page (534).png',
    'books/middlemarch/page (535).png',
    'books/middlemarch/page (536).png',
    'books/middlemarch/page (537).png',
    'books/middlemarch/page (538).png',
    'books/middlemarch/page (539).png',
    'books/middlemarch/page (540).png',
    'books/middlemarch/page (541).png',
    'books/middlemarch/page (542).png',
    'books/middlemarch/page (543).png',
    'books/middlemarch/page (544).png',
    'books/middlemarch/page (545).png',
    'books/middlemarch/page (546).png',
    'books/middlemarch/page (547).png',
    'books/middlemarch/page (548).png',
    'books/middlemarch/page (549).png',
    'books/middlemarch/page (550).png',
    'books/middlemarch/page (551).png',
    'books/middlemarch/page (552).png',
    'books/middlemarch/page (553).png',
    'books/middlemarch/page (554).png',
    'books/middlemarch/page (555).png',
    'books/middlemarch/page (556).png',
    'books/middlemarch/page (557).png',
    'books/middlemarch/page (558).png',
    'books/middlemarch/page (559).png',
    'books/middlemarch/page (560).png',
    'books/middlemarch/page (561).png',
    'books/middlemarch/page (562).png',
    'books/middlemarch/page (563).png',
    'books/middlemarch/page (564).png',
    'books/middlemarch/page (565).png',
    'books/middlemarch/page (566).png',
    'books/middlemarch/page (567).png',
    'books/middlemarch/page (568).png',
    'books/middlemarch/page (569).png',
    'books/middlemarch/page (570).png',
    'books/middlemarch/page (571).png',
    'books/middlemarch/page (572).png',
    'books/middlemarch/page (573).png',
    'books/middlemarch/page (574).png',
    'books/middlemarch/page (575).png',
    'books/middlemarch/page (576).png',
    'books/middlemarch/page (577).png',
    'books/middlemarch/page (578).png',
    'books/middlemarch/page (579).png',
    'books/middlemarch/page (580).png',
    'books/middlemarch/page (581).png',
    'books/middlemarch/page (582).png',
    'books/middlemarch/page (583).png',
    'books/middlemarch/page (584).png',
    'books/middlemarch/page (585).png',
    'books/middlemarch/page (586).png',
    'books/middlemarch/page (587).png',
    'books/middlemarch/page (588).png',
    'books/middlemarch/page (589).png',
    'books/middlemarch/page (590).png',
    'books/middlemarch/page (591).png',
    'books/middlemarch/page (592).png',
    'books/middlemarch/page (593).png',
    'books/middlemarch/page (594).png',
    'books/middlemarch/page (595).png',
    'books/middlemarch/page (596).png',
    'books/middlemarch/page (597).png',
    'books/middlemarch/page (598).png',
    'books/middlemarch/page (599).png',
    'books/middlemarch/page (600).png',
    'books/middlemarch/page (601).png',
    'books/middlemarch/page (602).png',
    'books/middlemarch/page (603).png',
    'books/middlemarch/page (604).png',
    'books/middlemarch/page (605).png',
    'books/middlemarch/page (606).png',
    'books/middlemarch/page (607).png',
    'books/middlemarch/page (608).png',
    'books/middlemarch/page (609).png',
    'books/middlemarch/page (610).png',
    'books/middlemarch/page (611).png',
    'books/middlemarch/page (612).png',
    'books/middlemarch/page (613).png',
    'books/middlemarch/page (614).png',
    'books/middlemarch/page (615).png',
    'books/middlemarch/page (616).png',
    'books/middlemarch/page (617).png',
    'books/middlemarch/page (618).png',
    'books/middlemarch/page (619).png',
    'books/middlemarch/page (620).png',
    'books/middlemarch/page (621).png',
    'books/middlemarch/page (622).png',
    'books/middlemarch/page (623).png',
    'books/middlemarch/page (624).png',
    'books/middlemarch/page (625).png',
    'books/middlemarch/page (626).png',
    'books/middlemarch/page (627).png',
    'books/middlemarch/page (628).png',
    'books/middlemarch/page (629).png',
    'books/middlemarch/page (630).png',
    'books/middlemarch/page (631).png',
    'books/middlemarch/page (632).png',
    'books/middlemarch/page (633).png',
    'books/middlemarch/page (634).png',
    'books/middlemarch/page (635).png',
    'books/middlemarch/page (636).png',
    'books/middlemarch/page (637).png',
    'books/middlemarch/page (638).png',
    'books/middlemarch/page (639).png',
    'books/middlemarch/page (640).png',
    'books/middlemarch/page (641).png',
    'books/middlemarch/page (642).png',
    'books/middlemarch/page (643).png',
    'books/middlemarch/page (644).png',
    'books/middlemarch/page (645).png',
    'books/middlemarch/page (646).png',
    'books/middlemarch/page (647).png',
    'books/middlemarch/page (648).png',
    'books/middlemarch/page (649).png',
    'books/middlemarch/page (650).png',
    'books/middlemarch/page (651).png',
    'books/middlemarch/page (652).png',
    'books/middlemarch/page (653).png',
    'books/middlemarch/page (654).png',
    'books/middlemarch/page (655).png',
    'books/middlemarch/page (656).png',
    'books/middlemarch/page (657).png',
    'books/middlemarch/page (658).png',
    'books/middlemarch/page (659).png',
    'books/middlemarch/page (660).png',
    'books/middlemarch/page (661).png',
    'books/middlemarch/page (662).png',
    'books/middlemarch/page (663).png',
    'books/middlemarch/page (664).png',
    'books/middlemarch/page (665).png',
    'books/middlemarch/page (666).png',
    'books/middlemarch/page (667).png',
    'books/middlemarch/page (668).png',
    'books/middlemarch/page (669).png',
    'books/middlemarch/page (670).png',
    'books/middlemarch/page (671).png',
    'books/middlemarch/page (672).png',
    'books/middlemarch/page (673).png',
    'books/middlemarch/page (674).png',
    'books/middlemarch/page (675).png',
    'books/middlemarch/page (676).png',
    'books/middlemarch/page (677).png',
    'books/middlemarch/page (678).png',
    'books/middlemarch/page (679).png',
    'books/middlemarch/page (680).png',
    'books/middlemarch/page (681).png',
    'books/middlemarch/page (682).png',
    'books/middlemarch/page (683).png',
    'books/middlemarch/page (684).png',
    'books/middlemarch/page (685).png',
    'books/middlemarch/page (686).png',
    'books/middlemarch/page (687).png',
    'books/middlemarch/page (688).png',
    'books/middlemarch/page (689).png',
    'books/middlemarch/page (690).png',
    'books/middlemarch/page (691).png',
    'books/middlemarch/page (692).png',
    'books/middlemarch/page (693).png',
    'books/middlemarch/page (694).png',
    'books/middlemarch/page (695).png',
    'books/middlemarch/page (696).png',
    'books/middlemarch/page (697).png',
    'books/middlemarch/page (698).png',
    'books/middlemarch/page (699).png',
    'books/middlemarch/page (700).png',
    'books/middlemarch/page (701).png',
    'books/middlemarch/page (702).png',
    'books/middlemarch/page (703).png',
    'books/middlemarch/page (704).png',
    'books/middlemarch/page (705).png',
    'books/middlemarch/page (706).png',
    'books/middlemarch/page (707).png',
    'books/middlemarch/page (708).png',
    'books/middlemarch/page (709).png',
    'books/middlemarch/page (710).png',
    'books/middlemarch/page (711).png',
    'books/middlemarch/page (712).png',
    'books/middlemarch/page (713).png',
    'books/middlemarch/page (714).png',
    'books/middlemarch/page (715).png',
    'books/middlemarch/page (716).png',
    'books/middlemarch/page (717).png',
    'books/middlemarch/page (718).png',
    'books/middlemarch/page (719).png',
    'books/middlemarch/page (720).png',
    'books/middlemarch/page (721).png',
    'books/middlemarch/page (722).png',
    'books/middlemarch/page (723).png',
    'books/middlemarch/page (724).png',
    'books/middlemarch/page (725).png',
    'books/middlemarch/page (726).png',
    'books/middlemarch/page (727).png',
    'books/middlemarch/page (728).png',
    'books/middlemarch/page (729).png',
    'books/middlemarch/page (730).png',
    'books/middlemarch/page (731).png',
    'books/middlemarch/page (732).png',
    'books/middlemarch/page (733).png',
    'books/middlemarch/page (734).png',
    'books/middlemarch/page (735).png',
    'books/middlemarch/page (736).png',
    'books/middlemarch/page (737).png',
    'books/middlemarch/page (738).png',
    'books/middlemarch/page (739).png',
    'books/middlemarch/page (740).png',
    'books/middlemarch/page (741).png',
    'books/middlemarch/page (742).png',
    'books/middlemarch/page (743).png',
    'books/middlemarch/page (744).png',
    'books/middlemarch/page (745).png',
    'books/middlemarch/page (746).png',
    'books/middlemarch/page (747).png',
    'books/middlemarch/page (748).png',
    'books/middlemarch/page (749).png',
    'books/middlemarch/page (750).png',
    'books/middlemarch/page (751).png',
    'books/middlemarch/page (752).png',
    'books/middlemarch/page (753).png',
    'books/middlemarch/page (754).png',
    'books/middlemarch/page (755).png',
    'books/middlemarch/page (756).png',
    'books/middlemarch/page (757).png',
    'books/middlemarch/page (758).png',
    'books/middlemarch/page (759).png',
    'books/middlemarch/page (760).png',
    'books/middlemarch/page (761).png',
    'books/middlemarch/page (762).png',
    'books/middlemarch/page (763).png',
    'books/middlemarch/page (764).png',
    'books/middlemarch/page (765).png',
    'books/middlemarch/page (766).png',
    'books/middlemarch/page (767).png',
    'books/middlemarch/page (768).png',
    'books/middlemarch/page (769).png',
    'books/middlemarch/page (770).png',
    'books/middlemarch/page (771).png',
    'books/middlemarch/page (772).png',
    'books/middlemarch/page (773).png',
    'books/middlemarch/page (774).png',
    'books/middlemarch/page (775).png',
    'books/middlemarch/page (776).png',
    'books/middlemarch/page (777).png',
    'books/middlemarch/page (778).png',
    'books/middlemarch/page (779).png',
    'books/middlemarch/page (780).png',
    'books/middlemarch/page (781).png',
    'books/middlemarch/page (782).png',
    'books/middlemarch/page (783).png',
    'books/middlemarch/page (784).png',
    'books/middlemarch/page (785).png',
    'books/middlemarch/page (786).png',
    'books/middlemarch/page (787).png',
    'books/middlemarch/page (788).png',
    'books/middlemarch/page (789).png',
    'books/middlemarch/page (790).png',
    'books/middlemarch/page (791).png',
    'books/middlemarch/page (792).png',
    'books/middlemarch/page (793).png',
    'books/middlemarch/page (794).png',
    'books/middlemarch/page (795).png',
    'books/middlemarch/page (796).png',
    'books/middlemarch/page (797).png',
    'books/middlemarch/page (798).png',
    'books/middlemarch/page (799).png',
    'books/middlemarch/page (800).png',
    'books/middlemarch/page (801).png',
    'books/middlemarch/page (802).png',
    'books/middlemarch/page (803).png',
    'books/middlemarch/page (804).png',
    'books/middlemarch/page (805).png',
    'books/middlemarch/page (806).png',
    'books/middlemarch/page (807).png',
    'books/middlemarch/page (808).png',
    'books/middlemarch/page (809).png',
    'books/middlemarch/page (810).png',
    'books/middlemarch/page (811).png',
    'books/middlemarch/page (812).png',
    'books/middlemarch/page (813).png',
    'books/middlemarch/page (814).png',
    'books/middlemarch/page (815).png',
    'books/middlemarch/page (816).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
