import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class ourmutual extends StatefulWidget {
  const ourmutual({Key? key}) : super(key: key);

  @override
  State<ourmutual> createState() => _ourmutualState();
}

class _ourmutualState extends State<ourmutual> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/our mutual/page (1).png',
    'books/our mutual/page (2).png',
    'books/our mutual/page (3).png',
    'books/our mutual/page (4).png',
    'books/our mutual/page (5).png',
    'books/our mutual/page (6).png',
    'books/our mutual/page (7).png',
    'books/our mutual/page (8).png',
    'books/our mutual/page (9).png',
    'books/our mutual/page (10).png',
    'books/our mutual/page (11).png',
    'books/our mutual/page (12).png',
    'books/our mutual/page (13).png',
    'books/our mutual/page (14).png',
    'books/our mutual/page (15).png',
    'books/our mutual/page (16).png',
    'books/our mutual/page (17).png',
    'books/our mutual/page (18).png',
    'books/our mutual/page (19).png',
    'books/our mutual/page (20).png',
    'books/our mutual/page (21).png',
    'books/our mutual/page (22).png',
    'books/our mutual/page (23).png',
    'books/our mutual/page (24).png',
    'books/our mutual/page (25).png',
    'books/our mutual/page (26).png',
    'books/our mutual/page (27).png',
    'books/our mutual/page (28).png',
    'books/our mutual/page (29).png',
    'books/our mutual/page (30).png',
    'books/our mutual/page (31).png',
    'books/our mutual/page (32).png',
    'books/our mutual/page (33).png',
    'books/our mutual/page (34).png',
    'books/our mutual/page (35).png',
    'books/our mutual/page (36).png',
    'books/our mutual/page (37).png',
    'books/our mutual/page (38).png',
    'books/our mutual/page (39).png',
    'books/our mutual/page (40).png',
    'books/our mutual/page (41).png',
    'books/our mutual/page (42).png',
    'books/our mutual/page (43).png',
    'books/our mutual/page (44).png',
    'books/our mutual/page (45).png',
    'books/our mutual/page (46).png',
    'books/our mutual/page (47).png',
    'books/our mutual/page (48).png',
    'books/our mutual/page (49).png',
    'books/our mutual/page (50).png',
    'books/our mutual/page (51).png',
    'books/our mutual/page (52).png',
    'books/our mutual/page (53).png',
    'books/our mutual/page (54).png',
    'books/our mutual/page (55).png',
    'books/our mutual/page (56).png',
    'books/our mutual/page (57).png',
    'books/our mutual/page (58).png',
    'books/our mutual/page (59).png',
    'books/our mutual/page (60).png',
    'books/our mutual/page (61).png',
    'books/our mutual/page (62).png',
    'books/our mutual/page (63).png',
    'books/our mutual/page (64).png',
    'books/our mutual/page (65).png',
    'books/our mutual/page (66).png',
    'books/our mutual/page (67).png',
    'books/our mutual/page (68).png',
    'books/our mutual/page (69).png',
    'books/our mutual/page (70).png',
    'books/our mutual/page (71).png',
    'books/our mutual/page (72).png',
    'books/our mutual/page (73).png',
    'books/our mutual/page (74).png',
    'books/our mutual/page (75).png',
    'books/our mutual/page (76).png',
    'books/our mutual/page (77).png',
    'books/our mutual/page (78).png',
    'books/our mutual/page (79).png',
    'books/our mutual/page (80).png',
    'books/our mutual/page (81).png',
    'books/our mutual/page (82).png',
    'books/our mutual/page (83).png',
    'books/our mutual/page (84).png',
    'books/our mutual/page (85).png',
    'books/our mutual/page (86).png',
    'books/our mutual/page (87).png',
    'books/our mutual/page (88).png',
    'books/our mutual/page (89).png',
    'books/our mutual/page (90).png',
    'books/our mutual/page (91).png',
    'books/our mutual/page (92).png',
    'books/our mutual/page (93).png',
    'books/our mutual/page (94).png',
    'books/our mutual/page (95).png',
    'books/our mutual/page (96).png',
    'books/our mutual/page (97).png',
    'books/our mutual/page (98).png',
    'books/our mutual/page (99).png',
    'books/our mutual/page (100).png',
    'books/our mutual/page (101).png',
    'books/our mutual/page (102).png',
    'books/our mutual/page (103).png',
    'books/our mutual/page (104).png',
    'books/our mutual/page (105).png',
    'books/our mutual/page (106).png',
    'books/our mutual/page (107).png',
    'books/our mutual/page (108).png',
    'books/our mutual/page (109).png',
    'books/our mutual/page (110).png',
    'books/our mutual/page (111).png',
    'books/our mutual/page (112).png',
    'books/our mutual/page (113).png',
    'books/our mutual/page (114).png',
    'books/our mutual/page (115).png',
    'books/our mutual/page (116).png',
    'books/our mutual/page (117).png',
    'books/our mutual/page (118).png',
    'books/our mutual/page (119).png',
    'books/our mutual/page (120).png',
    'books/our mutual/page (121).png',
    'books/our mutual/page (122).png',
    'books/our mutual/page (123).png',
    'books/our mutual/page (124).png',
    'books/our mutual/page (125).png',
    'books/our mutual/page (126).png',
    'books/our mutual/page (127).png',
    'books/our mutual/page (128).png',
    'books/our mutual/page (129).png',
    'books/our mutual/page (130).png',
    'books/our mutual/page (131).png',
    'books/our mutual/page (132).png',
    'books/our mutual/page (133).png',
    'books/our mutual/page (134).png',
    'books/our mutual/page (135).png',
    'books/our mutual/page (136).png',
    'books/our mutual/page (137).png',
    'books/our mutual/page (138).png',
    'books/our mutual/page (139).png',
    'books/our mutual/page (140).png',
    'books/our mutual/page (141).png',
    'books/our mutual/page (142).png',
    'books/our mutual/page (143).png',
    'books/our mutual/page (144).png',
    'books/our mutual/page (145).png',
    'books/our mutual/page (146).png',
    'books/our mutual/page (147).png',
    'books/our mutual/page (148).png',
    'books/our mutual/page (149).png',
    'books/our mutual/page (150).png',
    'books/our mutual/page (151).png',
    'books/our mutual/page (152).png',
    'books/our mutual/page (153).png',
    'books/our mutual/page (154).png',
    'books/our mutual/page (155).png',
    'books/our mutual/page (156).png',
    'books/our mutual/page (157).png',
    'books/our mutual/page (158).png',
    'books/our mutual/page (159).png',
    'books/our mutual/page (160).png',
    'books/our mutual/page (161).png',
    'books/our mutual/page (162).png',
    'books/our mutual/page (163).png',
    'books/our mutual/page (164).png',
    'books/our mutual/page (165).png',
    'books/our mutual/page (166).png',
    'books/our mutual/page (167).png',
    'books/our mutual/page (168).png',
    'books/our mutual/page (169).png',
    'books/our mutual/page (170).png',
    'books/our mutual/page (171).png',
    'books/our mutual/page (172).png',
    'books/our mutual/page (173).png',
    'books/our mutual/page (174).png',
    'books/our mutual/page (175).png',
    'books/our mutual/page (176).png',
    'books/our mutual/page (177).png',
    'books/our mutual/page (178).png',
    'books/our mutual/page (179).png',
    'books/our mutual/page (180).png',
    'books/our mutual/page (181).png',
    'books/our mutual/page (182).png',
    'books/our mutual/page (183).png',
    'books/our mutual/page (184).png',
    'books/our mutual/page (185).png',
    'books/our mutual/page (186).png',
    'books/our mutual/page (187).png',
    'books/our mutual/page (188).png',
    'books/our mutual/page (189).png',
    'books/our mutual/page (190).png',
    'books/our mutual/page (191).png',
    'books/our mutual/page (192).png',
    'books/our mutual/page (193).png',
    'books/our mutual/page (194).png',
    'books/our mutual/page (195).png',
    'books/our mutual/page (196).png',
    'books/our mutual/page (197).png',
    'books/our mutual/page (198).png',
    'books/our mutual/page (199).png',
    'books/our mutual/page (200).png',
    'books/our mutual/page (201).png',
    'books/our mutual/page (202).png',
    'books/our mutual/page (203).png',
    'books/our mutual/page (204).png',
    'books/our mutual/page (205).png',
    'books/our mutual/page (206).png',
    'books/our mutual/page (207).png',
    'books/our mutual/page (208).png',
    'books/our mutual/page (209).png',
    'books/our mutual/page (210).png',
    'books/our mutual/page (211).png',
    'books/our mutual/page (212).png',
    'books/our mutual/page (213).png',
    'books/our mutual/page (214).png',
    'books/our mutual/page (215).png',
    'books/our mutual/page (216).png',
    'books/our mutual/page (217).png',
    'books/our mutual/page (218).png',
    'books/our mutual/page (219).png',
    'books/our mutual/page (220).png',
    'books/our mutual/page (221).png',
    'books/our mutual/page (222).png',
    'books/our mutual/page (223).png',
    'books/our mutual/page (224).png',
    'books/our mutual/page (225).png',
    'books/our mutual/page (226).png',
    'books/our mutual/page (227).png',
    'books/our mutual/page (228).png',
    'books/our mutual/page (229).png',
    'books/our mutual/page (230).png',
    'books/our mutual/page (231).png',
    'books/our mutual/page (232).png',
    'books/our mutual/page (233).png',
    'books/our mutual/page (234).png',
    'books/our mutual/page (235).png',
    'books/our mutual/page (236).png',
    'books/our mutual/page (237).png',
    'books/our mutual/page (238).png',
    'books/our mutual/page (239).png',
    'books/our mutual/page (240).png',
    'books/our mutual/page (241).png',
    'books/our mutual/page (242).png',
    'books/our mutual/page (243).png',
    'books/our mutual/page (244).png',
    'books/our mutual/page (245).png',
    'books/our mutual/page (246).png',
    'books/our mutual/page (247).png',
    'books/our mutual/page (248).png',
    'books/our mutual/page (249).png',
    'books/our mutual/page (250).png',
    'books/our mutual/page (251).png',
    'books/our mutual/page (252).png',
    'books/our mutual/page (253).png',
    'books/our mutual/page (254).png',
    'books/our mutual/page (255).png',
    'books/our mutual/page (256).png',
    'books/our mutual/page (257).png',
    'books/our mutual/page (258).png',
    'books/our mutual/page (259).png',
    'books/our mutual/page (260).png',
    'books/our mutual/page (261).png',
    'books/our mutual/page (262).png',
    'books/our mutual/page (263).png',
    'books/our mutual/page (264).png',
    'books/our mutual/page (265).png',
    'books/our mutual/page (266).png',
    'books/our mutual/page (267).png',
    'books/our mutual/page (268).png',
    'books/our mutual/page (269).png',
    'books/our mutual/page (270).png',
    'books/our mutual/page (271).png',
    'books/our mutual/page (272).png',
    'books/our mutual/page (273).png',
    'books/our mutual/page (274).png',
    'books/our mutual/page (275).png',
    'books/our mutual/page (276).png',
    'books/our mutual/page (277).png',
    'books/our mutual/page (278).png',
    'books/our mutual/page (279).png',
    'books/our mutual/page (280).png',
    'books/our mutual/page (281).png',
    'books/our mutual/page (282).png',
    'books/our mutual/page (283).png',
    'books/our mutual/page (284).png',
    'books/our mutual/page (285).png',
    'books/our mutual/page (286).png',
    'books/our mutual/page (287).png',
    'books/our mutual/page (288).png',
    'books/our mutual/page (289).png',
    'books/our mutual/page (290).png',
    'books/our mutual/page (291).png',
    'books/our mutual/page (292).png',
    'books/our mutual/page (293).png',
    'books/our mutual/page (294).png',
    'books/our mutual/page (295).png',
    'books/our mutual/page (296).png',
    'books/our mutual/page (297).png',
    'books/our mutual/page (298).png',
    'books/our mutual/page (299).png',
    'books/our mutual/page (300).png',
    'books/our mutual/page (301).png',
    'books/our mutual/page (302).png',
    'books/our mutual/page (303).png',
    'books/our mutual/page (304).png',
    'books/our mutual/page (305).png',
    'books/our mutual/page (306).png',
    'books/our mutual/page (307).png',
    'books/our mutual/page (308).png',
    'books/our mutual/page (309).png',
    'books/our mutual/page (310).png',
    'books/our mutual/page (311).png',
    'books/our mutual/page (312).png',
    'books/our mutual/page (313).png',
    'books/our mutual/page (314).png',
    'books/our mutual/page (315).png',
    'books/our mutual/page (316).png',
    'books/our mutual/page (317).png',
    'books/our mutual/page (318).png',
    'books/our mutual/page (319).png',
    'books/our mutual/page (320).png',
    'books/our mutual/page (321).png',
    'books/our mutual/page (322).png',
    'books/our mutual/page (323).png',
    'books/our mutual/page (324).png',
    'books/our mutual/page (325).png',
    'books/our mutual/page (326).png',
    'books/our mutual/page (327).png',
    'books/our mutual/page (328).png',
    'books/our mutual/page (329).png',
    'books/our mutual/page (330).png',
    'books/our mutual/page (331).png',
    'books/our mutual/page (332).png',
    'books/our mutual/page (333).png',
    'books/our mutual/page (334).png',
    'books/our mutual/page (335).png',
    'books/our mutual/page (336).png',
    'books/our mutual/page (337).png',
    'books/our mutual/page (338).png',
    'books/our mutual/page (339).png',
    'books/our mutual/page (340).png',
    'books/our mutual/page (341).png',
    'books/our mutual/page (342).png',
    'books/our mutual/page (343).png',
    'books/our mutual/page (344).png',
    'books/our mutual/page (345).png',
    'books/our mutual/page (346).png',
    'books/our mutual/page (347).png',
    'books/our mutual/page (348).png',
    'books/our mutual/page (349).png',
    'books/our mutual/page (350).png',
    'books/our mutual/page (351).png',
    'books/our mutual/page (352).png',
    'books/our mutual/page (353).png',
    'books/our mutual/page (354).png',
    'books/our mutual/page (355).png',
    'books/our mutual/page (356).png',
    'books/our mutual/page (357).png',
    'books/our mutual/page (358).png',
    'books/our mutual/page (359).png',
    'books/our mutual/page (360).png',
    'books/our mutual/page (361).png',
    'books/our mutual/page (362).png',
    'books/our mutual/page (363).png',
    'books/our mutual/page (364).png',
    'books/our mutual/page (365).png',
    'books/our mutual/page (366).png',
    'books/our mutual/page (367).png',
    'books/our mutual/page (368).png',
    'books/our mutual/page (369).png',
    'books/our mutual/page (370).png',
    'books/our mutual/page (371).png',
    'books/our mutual/page (372).png',
    'books/our mutual/page (373).png',
    'books/our mutual/page (374).png',
    'books/our mutual/page (375).png',
    'books/our mutual/page (376).png',
    'books/our mutual/page (377).png',
    'books/our mutual/page (378).png',
    'books/our mutual/page (379).png',
    'books/our mutual/page (380).png',
    'books/our mutual/page (381).png',
    'books/our mutual/page (382).png',
    'books/our mutual/page (383).png',
    'books/our mutual/page (384).png',
    'books/our mutual/page (385).png',
    'books/our mutual/page (386).png',
    'books/our mutual/page (387).png',
    'books/our mutual/page (388).png',
    'books/our mutual/page (389).png',
    'books/our mutual/page (390).png',
    'books/our mutual/page (391).png',
    'books/our mutual/page (392).png',
    'books/our mutual/page (393).png',
    'books/our mutual/page (394).png',
    'books/our mutual/page (395).png',
    'books/our mutual/page (396).png',
    'books/our mutual/page (397).png',
    'books/our mutual/page (398).png',
    'books/our mutual/page (399).png',
    'books/our mutual/page (400).png',
    'books/our mutual/page (401).png',
    'books/our mutual/page (402).png',
    'books/our mutual/page (403).png',
    'books/our mutual/page (404).png',
    'books/our mutual/page (405).png',
    'books/our mutual/page (406).png',
    'books/our mutual/page (407).png',
    'books/our mutual/page (408).png',
    'books/our mutual/page (409).png',
    'books/our mutual/page (410).png',
    'books/our mutual/page (411).png',
    'books/our mutual/page (412).png',
    'books/our mutual/page (413).png',
    'books/our mutual/page (414).png',
    'books/our mutual/page (415).png',
    'books/our mutual/page (416).png',
    'books/our mutual/page (417).png',
    'books/our mutual/page (418).png',
    'books/our mutual/page (419).png',
    'books/our mutual/page (420).png',
    'books/our mutual/page (421).png',
    'books/our mutual/page (422).png',
    'books/our mutual/page (423).png',
    'books/our mutual/page (424).png',
    'books/our mutual/page (425).png',
    'books/our mutual/page (426).png',
    'books/our mutual/page (427).png',
    'books/our mutual/page (428).png',
    'books/our mutual/page (429).png',
    'books/our mutual/page (430).png',
    'books/our mutual/page (431).png',
    'books/our mutual/page (432).png',
    'books/our mutual/page (433).png',
    'books/our mutual/page (434).png',
    'books/our mutual/page (435).png',
    'books/our mutual/page (436).png',
    'books/our mutual/page (437).png',
    'books/our mutual/page (438).png',
    'books/our mutual/page (439).png',
    'books/our mutual/page (440).png',
    'books/our mutual/page (441).png',
    'books/our mutual/page (442).png',
    'books/our mutual/page (443).png',
    'books/our mutual/page (444).png',
    'books/our mutual/page (445).png',
    'books/our mutual/page (446).png',
    'books/our mutual/page (447).png',
    'books/our mutual/page (448).png',
    'books/our mutual/page (449).png',
    'books/our mutual/page (450).png',
    'books/our mutual/page (451).png',
    'books/our mutual/page (452).png',
    'books/our mutual/page (453).png',
    'books/our mutual/page (454).png',
    'books/our mutual/page (455).png',
    'books/our mutual/page (456).png',
    'books/our mutual/page (457).png',
    'books/our mutual/page (458).png',
    'books/our mutual/page (459).png',
    'books/our mutual/page (460).png',
    'books/our mutual/page (461).png',
    'books/our mutual/page (462).png',
    'books/our mutual/page (463).png',
    'books/our mutual/page (464).png',
    'books/our mutual/page (465).png',
    'books/our mutual/page (466).png',
    'books/our mutual/page (467).png',
    'books/our mutual/page (468).png',
    'books/our mutual/page (469).png',
    'books/our mutual/page (470).png',
    'books/our mutual/page (471).png',
    'books/our mutual/page (472).png',
    'books/our mutual/page (473).png',
    'books/our mutual/page (474).png',
    'books/our mutual/page (475).png',
    'books/our mutual/page (476).png',
    'books/our mutual/page (477).png',
    'books/our mutual/page (478).png',
    'books/our mutual/page (479).png',
    'books/our mutual/page (480).png',
    'books/our mutual/page (481).png',
    'books/our mutual/page (482).png',
    'books/our mutual/page (483).png',
    'books/our mutual/page (484).png',
    'books/our mutual/page (485).png',
    'books/our mutual/page (486).png',
    'books/our mutual/page (487).png',
    'books/our mutual/page (488).png',
    'books/our mutual/page (489).png',
    'books/our mutual/page (490).png',
    'books/our mutual/page (491).png',
    'books/our mutual/page (492).png',
    'books/our mutual/page (493).png',
    'books/our mutual/page (494).png',
    'books/our mutual/page (495).png',
    'books/our mutual/page (496).png',
    'books/our mutual/page (497).png',
    'books/our mutual/page (498).png',
    'books/our mutual/page (499).png',
    'books/our mutual/page (500).png',
    'books/our mutual/page (501).png',
    'books/our mutual/page (502).png',
    'books/our mutual/page (503).png',
    'books/our mutual/page (504).png',
    'books/our mutual/page (505).png',
    'books/our mutual/page (506).png',
    'books/our mutual/page (507).png',
    'books/our mutual/page (508).png',
    'books/our mutual/page (509).png',
    'books/our mutual/page (510).png',
    'books/our mutual/page (511).png',
    'books/our mutual/page (512).png',
    'books/our mutual/page (513).png',
    'books/our mutual/page (514).png',
    'books/our mutual/page (515).png',
    'books/our mutual/page (516).png',
    'books/our mutual/page (517).png',
    'books/our mutual/page (518).png',
    'books/our mutual/page (519).png',
    'books/our mutual/page (520).png',
    'books/our mutual/page (521).png',
    'books/our mutual/page (522).png',
    'books/our mutual/page (523).png',
    'books/our mutual/page (524).png',
    'books/our mutual/page (525).png',
    'books/our mutual/page (526).png',
    'books/our mutual/page (527).png',
    'books/our mutual/page (528).png',
    'books/our mutual/page (529).png',
    'books/our mutual/page (530).png',
    'books/our mutual/page (531).png',
    'books/our mutual/page (532).png',
    'books/our mutual/page (533).png',
    'books/our mutual/page (534).png',
    'books/our mutual/page (535).png',
    'books/our mutual/page (536).png',
    'books/our mutual/page (537).png',
    'books/our mutual/page (538).png',
    'books/our mutual/page (539).png',
    'books/our mutual/page (540).png',
    'books/our mutual/page (541).png',
    'books/our mutual/page (542).png',
    'books/our mutual/page (543).png',
    'books/our mutual/page (544).png',
    'books/our mutual/page (545).png',
    'books/our mutual/page (546).png',
    'books/our mutual/page (547).png',
    'books/our mutual/page (548).png',
    'books/our mutual/page (549).png',
    'books/our mutual/page (550).png',
    'books/our mutual/page (551).png',
    'books/our mutual/page (552).png',
    'books/our mutual/page (553).png',
    'books/our mutual/page (554).png',
    'books/our mutual/page (555).png',
    'books/our mutual/page (556).png',
    'books/our mutual/page (557).png',
    'books/our mutual/page (558).png',
    'books/our mutual/page (559).png',
    'books/our mutual/page (560).png',
    'books/our mutual/page (561).png',
    'books/our mutual/page (562).png',
    'books/our mutual/page (563).png',
    'books/our mutual/page (564).png',
    'books/our mutual/page (565).png',
    'books/our mutual/page (566).png',
    'books/our mutual/page (567).png',
    'books/our mutual/page (568).png',
    'books/our mutual/page (569).png',
    'books/our mutual/page (570).png',
    'books/our mutual/page (571).png',
    'books/our mutual/page (572).png',
    'books/our mutual/page (573).png',
    'books/our mutual/page (574).png',
    'books/our mutual/page (575).png',
    'books/our mutual/page (576).png',
    'books/our mutual/page (577).png',
    'books/our mutual/page (578).png',
    'books/our mutual/page (579).png',
    'books/our mutual/page (580).png',
    'books/our mutual/page (581).png',
    'books/our mutual/page (582).png',
    'books/our mutual/page (583).png',
    'books/our mutual/page (584).png',
    'books/our mutual/page (585).png',
    'books/our mutual/page (586).png',
    'books/our mutual/page (587).png',
    'books/our mutual/page (588).png',
    'books/our mutual/page (589).png',
    'books/our mutual/page (590).png',
    'books/our mutual/page (591).png',
    'books/our mutual/page (592).png',
    'books/our mutual/page (593).png',
    'books/our mutual/page (594).png',
    'books/our mutual/page (595).png',
    'books/our mutual/page (596).png',
    'books/our mutual/page (597).png',
    'books/our mutual/page (598).png',
    'books/our mutual/page (599).png',
    'books/our mutual/page (600).png',
    'books/our mutual/page (601).png',
    'books/our mutual/page (602).png',
    'books/our mutual/page (603).png',
    'books/our mutual/page (604).png',
    'books/our mutual/page (605).png',
    'books/our mutual/page (606).png',
    'books/our mutual/page (607).png',
    'books/our mutual/page (608).png',
    'books/our mutual/page (609).png',
    'books/our mutual/page (610).png',
    'books/our mutual/page (611).png',
    'books/our mutual/page (612).png',
    'books/our mutual/page (613).png',
    'books/our mutual/page (614).png',
    'books/our mutual/page (615).png',
    'books/our mutual/page (616).png',
    'books/our mutual/page (617).png',
    'books/our mutual/page (618).png',
    'books/our mutual/page (619).png',
    'books/our mutual/page (620).png',
    'books/our mutual/page (621).png',
    'books/our mutual/page (622).png',
    'books/our mutual/page (623).png',
    'books/our mutual/page (624).png',
    'books/our mutual/page (625).png',
    'books/our mutual/page (626).png',
    'books/our mutual/page (627).png',
    'books/our mutual/page (628).png',
    'books/our mutual/page (629).png',
    'books/our mutual/page (630).png',
    'books/our mutual/page (631).png',
    'books/our mutual/page (632).png',
    'books/our mutual/page (633).png',
    'books/our mutual/page (634).png',
    'books/our mutual/page (635).png',
    'books/our mutual/page (636).png',
    'books/our mutual/page (637).png',
    'books/our mutual/page (638).png',
    'books/our mutual/page (639).png',
    'books/our mutual/page (640).png',
    'books/our mutual/page (641).png',
    'books/our mutual/page (642).png',
    'books/our mutual/page (643).png',
    'books/our mutual/page (644).png',
    'books/our mutual/page (645).png',
    'books/our mutual/page (646).png',
    'books/our mutual/page (647).png',
    'books/our mutual/page (648).png',
    'books/our mutual/page (649).png',
    'books/our mutual/page (650).png',
    'books/our mutual/page (651).png',
    'books/our mutual/page (652).png',
    'books/our mutual/page (653).png',
    'books/our mutual/page (654).png',
    'books/our mutual/page (655).png',
    'books/our mutual/page (656).png',
    'books/our mutual/page (657).png',
    'books/our mutual/page (658).png',
    'books/our mutual/page (659).png',
    'books/our mutual/page (660).png',
    'books/our mutual/page (661).png',
    'books/our mutual/page (662).png',
    'books/our mutual/page (663).png',
    'books/our mutual/page (664).png',
    'books/our mutual/page (665).png',
    'books/our mutual/page (666).png',
    'books/our mutual/page (667).png',
    'books/our mutual/page (668).png',
    'books/our mutual/page (669).png',
    'books/our mutual/page (670).png',
    'books/our mutual/page (671).png',
    'books/our mutual/page (672).png',
    'books/our mutual/page (673).png',
    'books/our mutual/page (674).png',
    'books/our mutual/page (675).png',
    'books/our mutual/page (676).png',
    'books/our mutual/page (677).png',
    'books/our mutual/page (678).png',
    'books/our mutual/page (679).png',
    'books/our mutual/page (680).png',
    'books/our mutual/page (681).png',
    'books/our mutual/page (682).png',
    'books/our mutual/page (683).png',
    'books/our mutual/page (684).png',
    'books/our mutual/page (685).png',
    'books/our mutual/page (686).png',
    'books/our mutual/page (687).png',
    'books/our mutual/page (688).png',
    'books/our mutual/page (689).png',
    'books/our mutual/page (690).png',
    'books/our mutual/page (691).png',
    'books/our mutual/page (692).png',
    'books/our mutual/page (693).png',
    'books/our mutual/page (694).png',
    'books/our mutual/page (695).png',
    'books/our mutual/page (696).png',
    'books/our mutual/page (697).png',
    'books/our mutual/page (698).png',
    'books/our mutual/page (699).png',
    'books/our mutual/page (700).png',
    'books/our mutual/page (701).png',
    'books/our mutual/page (702).png',
    'books/our mutual/page (703).png',
    'books/our mutual/page (704).png',
    'books/our mutual/page (705).png',
    'books/our mutual/page (706).png',
    'books/our mutual/page (707).png',
    'books/our mutual/page (708).png',
    'books/our mutual/page (709).png',
    'books/our mutual/page (710).png',
    'books/our mutual/page (711).png',
    'books/our mutual/page (712).png',
    'books/our mutual/page (713).png',
    'books/our mutual/page (714).png',
    'books/our mutual/page (715).png',
    'books/our mutual/page (716).png',
    'books/our mutual/page (717).png',
    'books/our mutual/page (718).png',
    'books/our mutual/page (719).png',
    'books/our mutual/page (720).png',
    'books/our mutual/page (721).png',
    'books/our mutual/page (722).png',
    'books/our mutual/page (723).png',
    'books/our mutual/page (724).png',
    'books/our mutual/page (725).png',
    'books/our mutual/page (726).png',
    'books/our mutual/page (727).png',
    'books/our mutual/page (728).png',
    'books/our mutual/page (729).png',
    'books/our mutual/page (730).png',
    'books/our mutual/page (731).png',
    'books/our mutual/page (732).png',
    'books/our mutual/page (733).png',
    'books/our mutual/page (734).png',
    'books/our mutual/page (735).png',
    'books/our mutual/page (736).png',
    'books/our mutual/page (737).png',
    'books/our mutual/page (738).png',
    'books/our mutual/page (739).png',
    'books/our mutual/page (740).png',
    'books/our mutual/page (741).png',
    'books/our mutual/page (742).png',
    'books/our mutual/page (743).png',
    'books/our mutual/page (744).png',
    'books/our mutual/page (745).png',
    'books/our mutual/page (746).png',
    'books/our mutual/page (747).png',
    'books/our mutual/page (748).png',
    'books/our mutual/page (749).png',
    'books/our mutual/page (750).png',
    'books/our mutual/page (751).png',
    'books/our mutual/page (752).png',
    'books/our mutual/page (753).png',
    'books/our mutual/page (754).png',
    'books/our mutual/page (755).png',
    'books/our mutual/page (756).png',
    'books/our mutual/page (757).png',
    'books/our mutual/page (758).png',
    'books/our mutual/page (759).png',
    'books/our mutual/page (760).png',
    'books/our mutual/page (761).png',
    'books/our mutual/page (762).png',
    'books/our mutual/page (763).png',
    'books/our mutual/page (764).png',
    'books/our mutual/page (765).png',
    'books/our mutual/page (766).png',
    'books/our mutual/page (767).png',
    'books/our mutual/page (768).png',
    'books/our mutual/page (769).png',
    'books/our mutual/page (770).png',
    'books/our mutual/page (771).png',
    'books/our mutual/page (772).png',
    'books/our mutual/page (773).png',
    'books/our mutual/page (774).png',
    'books/our mutual/page (775).png',
    'books/our mutual/page (776).png',
    'books/our mutual/page (777).png',
    'books/our mutual/page (778).png',
    'books/our mutual/page (779).png',
    'books/our mutual/page (780).png',
    'books/our mutual/page (781).png',
    'books/our mutual/page (782).png',
    'books/our mutual/page (783).png',
    'books/our mutual/page (784).png',
    'books/our mutual/page (785).png',
    'books/our mutual/page (786).png',
    'books/our mutual/page (787).png',
    'books/our mutual/page (788).png',
    'books/our mutual/page (789).png',
    'books/our mutual/page (790).png',
    'books/our mutual/page (791).png',
    'books/our mutual/page (792).png',
    'books/our mutual/page (793).png',
    'books/our mutual/page (794).png',
    'books/our mutual/page (795).png',
    'books/our mutual/page (796).png',
    'books/our mutual/page (797).png',
    'books/our mutual/page (798).png',
    'books/our mutual/page (799).png',
    'books/our mutual/page (800).png',
    'books/our mutual/page (801).png',
    'books/our mutual/page (802).png',
    'books/our mutual/page (803).png',
    'books/our mutual/page (804).png',
    'books/our mutual/page (805).png',
    'books/our mutual/page (806).png',
    'books/our mutual/page (807).png',
    'books/our mutual/page (808).png',
    'books/our mutual/page (809).png',
    'books/our mutual/page (810).png',
    'books/our mutual/page (811).png',
    'books/our mutual/page (812).png',
    'books/our mutual/page (813).png',
    'books/our mutual/page (814).png',
    'books/our mutual/page (815).png',
    'books/our mutual/page (816).png',
    'books/our mutual/page (817).png',
    'books/our mutual/page (818).png',
    'books/our mutual/page (819).png',
    'books/our mutual/page (820).png',
    'books/our mutual/page (821).png',
    'books/our mutual/page (822).png',
    'books/our mutual/page (823).png',
    'books/our mutual/page (824).png',
    'books/our mutual/page (825).png',
    'books/our mutual/page (826).png',
    'books/our mutual/page (827).png',
    'books/our mutual/page (828).png',
    'books/our mutual/page (829).png',
    'books/our mutual/page (830).png',
    'books/our mutual/page (831).png',
    'books/our mutual/page (832).png',
    'books/our mutual/page (833).png',
    'books/our mutual/page (834).png',
    'books/our mutual/page (835).png',
    'books/our mutual/page (836).png',
    'books/our mutual/page (837).png',
    'books/our mutual/page (838).png',
    'books/our mutual/page (839).png',
    'books/our mutual/page (840).png',
    'books/our mutual/page (841).png',
    'books/our mutual/page (842).png',
    'books/our mutual/page (843).png',
    'books/our mutual/page (844).png',
    'books/our mutual/page (845).png',
    'books/our mutual/page (846).png',
    'books/our mutual/page (847).png',
    'books/our mutual/page (848).png',
    'books/our mutual/page (849).png',
    'books/our mutual/page (850).png',
    'books/our mutual/page (851).png',
    'books/our mutual/page (852).png',
    'books/our mutual/page (853).png',
    'books/our mutual/page (854).png',
    'books/our mutual/page (855).png',
    'books/our mutual/page (856).png',
    'books/our mutual/page (857).png',
    'books/our mutual/page (858).png',
    'books/our mutual/page (859).png',
    'books/our mutual/page (860).png',
    'books/our mutual/page (861).png',
    'books/our mutual/page (862).png',
    'books/our mutual/page (863).png',
    'books/our mutual/page (864).png',
    'books/our mutual/page (865).png',
    'books/our mutual/page (866).png',
    'books/our mutual/page (867).png',
    'books/our mutual/page (868).png',
    'books/our mutual/page (869).png',
    'books/our mutual/page (870).png',
    'books/our mutual/page (871).png',
    'books/our mutual/page (872).png',
    'books/our mutual/page (873).png',
    'books/our mutual/page (874).png',
    'books/our mutual/page (875).png',
    'books/our mutual/page (876).png',
    'books/our mutual/page (877).png',
    'books/our mutual/page (878).png',
    'books/our mutual/page (879).png',
    'books/our mutual/page (880).png',
    'books/our mutual/page (881).png',
    'books/our mutual/page (882).png',
    'books/our mutual/page (883).png',
    'books/our mutual/page (884).png',
    'books/our mutual/page (885).png',
    'books/our mutual/page (886).png',
    'books/our mutual/page (887).png',
    'books/our mutual/page (888).png',
    'books/our mutual/page (889).png',
    'books/our mutual/page (890).png',
    'books/our mutual/page (891).png',
    'books/our mutual/page (892).png',
    'books/our mutual/page (893).png',
    'books/our mutual/page (894).png',
    'books/our mutual/page (895).png',
    'books/our mutual/page (896).png',
    'books/our mutual/page (897).png',
    'books/our mutual/page (898).png',
    'books/our mutual/page (899).png',
    'books/our mutual/page (900).png',
    'books/our mutual/page (901).png',
    'books/our mutual/page (902).png',
    'books/our mutual/page (903).png',
    'books/our mutual/page (904).png',
    'books/our mutual/page (905).png',
    'books/our mutual/page (906).png',
    'books/our mutual/page (907).png',
    'books/our mutual/page (908).png',
    'books/our mutual/page (909).png',
    'books/our mutual/page (910).png',
    'books/our mutual/page (911).png',
    'books/our mutual/page (912).png',
    'books/our mutual/page (913).png',
    'books/our mutual/page (914).png',
    'books/our mutual/page (915).png',
    'books/our mutual/page (916).png',
    'books/our mutual/page (917).png',
    'books/our mutual/page (918).png',
    'books/our mutual/page (919).png',
    'books/our mutual/page (920).png',
    'books/our mutual/page (921).png',
    'books/our mutual/page (922).png',
    'books/our mutual/page (923).png',
    'books/our mutual/page (924).png',
    'books/our mutual/page (925).png',
    'books/our mutual/page (926).png',
    'books/our mutual/page (927).png',
    'books/our mutual/page (928).png',
    'books/our mutual/page (929).png',
    'books/our mutual/page (930).png',
    'books/our mutual/page (931).png',
    'books/our mutual/page (932).png',
    'books/our mutual/page (933).png',
    'books/our mutual/page (934).png',
    'books/our mutual/page (935).png',
    'books/our mutual/page (936).png',
    'books/our mutual/page (937).png',
    'books/our mutual/page (938).png',
    'books/our mutual/page (939).png',
    'books/our mutual/page (940).png',
    'books/our mutual/page (941).png',
    'books/our mutual/page (942).png',
    'books/our mutual/page (943).png',
    'books/our mutual/page (944).png',
    'books/our mutual/page (945).png',
    'books/our mutual/page (946).png',
    'books/our mutual/page (947).png',
    'books/our mutual/page (948).png',
    'books/our mutual/page (949).png',
    'books/our mutual/page (950).png',
    'books/our mutual/page (951).png',
    'books/our mutual/page (952).png',
    'books/our mutual/page (953).png',
    'books/our mutual/page (954).png',
    'books/our mutual/page (955).png',
    'books/our mutual/page (956).png',
    'books/our mutual/page (957).png',
    'books/our mutual/page (958).png',
    'books/our mutual/page (959).png',
    'books/our mutual/page (960).png',
    'books/our mutual/page (961).png',
    'books/our mutual/page (962).png',
    'books/our mutual/page (963).png',
    'books/our mutual/page (964).png',
    'books/our mutual/page (965).png',
    'books/our mutual/page (966).png',
    'books/our mutual/page (967).png',
    'books/our mutual/page (968).png',
    'books/our mutual/page (969).png',
    'books/our mutual/page (970).png',
    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
