import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class ourwithspain extends StatefulWidget {
  const ourwithspain({Key? key}) : super(key: key);

  @override
  State<ourwithspain> createState() => _ourwithspainState();
}

class _ourwithspainState extends State<ourwithspain> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/our with spain/page (1).png',
    'books/our with spain/page (2).png',
    'books/our with spain/page (3).png',
    'books/our with spain/page (4).png',
    'books/our with spain/page (5).png',
    'books/our with spain/page (6).png',
    'books/our with spain/page (7).png',
    'books/our with spain/page (8).png',
    'books/our with spain/page (9).png',
    'books/our with spain/page (10).png',
    'books/our with spain/page (11).png',
    'books/our with spain/page (12).png',
    'books/our with spain/page (13).png',
    'books/our with spain/page (14).png',
    'books/our with spain/page (15).png',
    'books/our with spain/page (16).png',
    'books/our with spain/page (17).png',
    'books/our with spain/page (18).png',
    'books/our with spain/page (19).png',
    'books/our with spain/page (20).png',
    'books/our with spain/page (21).png',
    'books/our with spain/page (22).png',
    'books/our with spain/page (23).png',
    'books/our with spain/page (24).png',
    'books/our with spain/page (25).png',
    'books/our with spain/page (26).png',
    'books/our with spain/page (27).png',
    'books/our with spain/page (28).png',
    'books/our with spain/page (29).png',
    'books/our with spain/page (30).png',
    'books/our with spain/page (31).png',
    'books/our with spain/page (32).png',
    'books/our with spain/page (33).png',
    'books/our with spain/page (34).png',
    'books/our with spain/page (35).png',
    'books/our with spain/page (36).png',
    'books/our with spain/page (37).png',
    'books/our with spain/page (38).png',
    'books/our with spain/page (39).png',
    'books/our with spain/page (40).png',
    'books/our with spain/page (41).png',
    'books/our with spain/page (42).png',
    'books/our with spain/page (43).png',
    'books/our with spain/page (44).png',
    'books/our with spain/page (45).png',
    'books/our with spain/page (46).png',
    'books/our with spain/page (47).png',
    'books/our with spain/page (48).png',
    'books/our with spain/page (49).png',
    'books/our with spain/page (50).png',
    'books/our with spain/page (51).png',
    'books/our with spain/page (52).png',
    'books/our with spain/page (53).png',
    'books/our with spain/page (54).png',
    'books/our with spain/page (55).png',
    'books/our with spain/page (56).png',
    'books/our with spain/page (57).png',
    'books/our with spain/page (58).png',
    'books/our with spain/page (59).png',
    'books/our with spain/page (60).png',
    'books/our with spain/page (61).png',
    'books/our with spain/page (62).png',
    'books/our with spain/page (63).png',
    'books/our with spain/page (64).png',
    'books/our with spain/page (65).png',
    'books/our with spain/page (66).png',
    'books/our with spain/page (67).png',
    'books/our with spain/page (68).png',
    'books/our with spain/page (69).png',
    'books/our with spain/page (70).png',
    'books/our with spain/page (71).png',
    'books/our with spain/page (72).png',
    'books/our with spain/page (73).png',
    'books/our with spain/page (74).png',
    'books/our with spain/page (75).png',
    'books/our with spain/page (76).png',
    'books/our with spain/page (77).png',
    'books/our with spain/page (78).png',
    'books/our with spain/page (79).png',
    'books/our with spain/page (80).png',
    'books/our with spain/page (81).png',
    'books/our with spain/page (82).png',
    'books/our with spain/page (83).png',
    'books/our with spain/page (84).png',
    'books/our with spain/page (85).png',
    'books/our with spain/page (86).png',
    'books/our with spain/page (87).png',
    'books/our with spain/page (88).png',
    'books/our with spain/page (89).png',
    'books/our with spain/page (90).png',
    'books/our with spain/page (91).png',
    'books/our with spain/page (92).png',
    'books/our with spain/page (93).png',
    'books/our with spain/page (94).png',
    'books/our with spain/page (95).png',
    'books/our with spain/page (96).png',
    'books/our with spain/page (97).png',
    'books/our with spain/page (98).png',
    'books/our with spain/page (99).png',
    'books/our with spain/page (100).png',
    'books/our with spain/page (101).png',
    'books/our with spain/page (102).png',
    'books/our with spain/page (103).png',
    'books/our with spain/page (104).png',
    'books/our with spain/page (105).png',
    'books/our with spain/page (106).png',
    'books/our with spain/page (107).png',
    'books/our with spain/page (108).png',
    'books/our with spain/page (109).png',
    'books/our with spain/page (110).png',
    'books/our with spain/page (111).png',
    'books/our with spain/page (112).png',
    'books/our with spain/page (113).png',
    'books/our with spain/page (114).png',
    'books/our with spain/page (115).png',
    'books/our with spain/page (116).png',
    'books/our with spain/page (117).png',
    'books/our with spain/page (118).png',
    'books/our with spain/page (119).png',
    'books/our with spain/page (120).png',
    'books/our with spain/page (121).png',
    'books/our with spain/page (122).png',
    'books/our with spain/page (123).png',
    'books/our with spain/page (124).png',
    'books/our with spain/page (125).png',
    'books/our with spain/page (126).png',
    'books/our with spain/page (127).png',
    'books/our with spain/page (128).png',
    'books/our with spain/page (129).png',
    'books/our with spain/page (130).png',
    'books/our with spain/page (131).png',
    'books/our with spain/page (132).png',
    'books/our with spain/page (133).png',
    'books/our with spain/page (134).png',
    'books/our with spain/page (135).png',
    'books/our with spain/page (136).png',
    'books/our with spain/page (137).png',
    'books/our with spain/page (138).png',
    'books/our with spain/page (139).png',
    'books/our with spain/page (140).png',
    'books/our with spain/page (141).png',
    'books/our with spain/page (142).png',
    'books/our with spain/page (143).png',
    'books/our with spain/page (144).png',
    'books/our with spain/page (145).png',
    'books/our with spain/page (146).png',
    'books/our with spain/page (147).png',
    'books/our with spain/page (148).png',
    'books/our with spain/page (149).png',
    'books/our with spain/page (150).png',
    'books/our with spain/page (151).png',
    'books/our with spain/page (152).png',
    'books/our with spain/page (153).png',
    'books/our with spain/page (154).png',
    'books/our with spain/page (155).png',
    'books/our with spain/page (156).png',
    'books/our with spain/page (157).png',
    'books/our with spain/page (158).png',
    'books/our with spain/page (159).png',
    'books/our with spain/page (160).png',
    'books/our with spain/page (161).png',
    'books/our with spain/page (162).png',
    'books/our with spain/page (163).png',
    'books/our with spain/page (164).png',
    'books/our with spain/page (165).png',
    'books/our with spain/page (166).png',
    'books/our with spain/page (167).png',
    'books/our with spain/page (168).png',
    'books/our with spain/page (169).png',
    'books/our with spain/page (170).png',
    'books/our with spain/page (171).png',
    'books/our with spain/page (172).png',
    'books/our with spain/page (173).png',
    'books/our with spain/page (174).png',
    'books/our with spain/page (175).png',
    'books/our with spain/page (176).png',
    'books/our with spain/page (177).png',
    'books/our with spain/page (178).png',
    'books/our with spain/page (179).png',
    'books/our with spain/page (180).png',
    'books/our with spain/page (181).png',
    'books/our with spain/page (182).png',
    'books/our with spain/page (183).png',
    'books/our with spain/page (184).png',
    'books/our with spain/page (185).png',
    'books/our with spain/page (186).png',
    'books/our with spain/page (187).png',
    'books/our with spain/page (188).png',
    'books/our with spain/page (189).png',
    'books/our with spain/page (190).png',
    'books/our with spain/page (191).png',
    'books/our with spain/page (192).png',
    'books/our with spain/page (193).png',
    'books/our with spain/page (194).png',
    'books/our with spain/page (195).png',
    'books/our with spain/page (196).png',
    'books/our with spain/page (197).png',
    'books/our with spain/page (198).png',
    'books/our with spain/page (199).png',
    'books/our with spain/page (200).png',
    'books/our with spain/page (201).png',
    'books/our with spain/page (202).png',
    'books/our with spain/page (203).png',
    'books/our with spain/page (204).png',
    'books/our with spain/page (205).png',
    'books/our with spain/page (206).png',
    'books/our with spain/page (207).png',
    'books/our with spain/page (208).png',
    'books/our with spain/page (209).png',
    'books/our with spain/page (210).png',
    'books/our with spain/page (211).png',
    'books/our with spain/page (212).png',
    'books/our with spain/page (213).png',
    'books/our with spain/page (214).png',
    'books/our with spain/page (215).png',
    'books/our with spain/page (216).png',
    'books/our with spain/page (217).png',
    'books/our with spain/page (218).png',
    'books/our with spain/page (219).png',
    'books/our with spain/page (220).png',
    'books/our with spain/page (221).png',
    'books/our with spain/page (222).png',
    'books/our with spain/page (223).png',
    'books/our with spain/page (224).png',
    'books/our with spain/page (225).png',
    'books/our with spain/page (226).png',
    'books/our with spain/page (227).png',
    'books/our with spain/page (228).png',
    'books/our with spain/page (229).png',
    'books/our with spain/page (230).png',
    'books/our with spain/page (231).png',
    'books/our with spain/page (232).png',
    'books/our with spain/page (233).png',
    'books/our with spain/page (234).png',
    'books/our with spain/page (235).png',
    'books/our with spain/page (236).png',
    'books/our with spain/page (237).png',
    'books/our with spain/page (238).png',
    'books/our with spain/page (239).png',
    'books/our with spain/page (240).png',
    'books/our with spain/page (241).png',
    'books/our with spain/page (242).png',
    'books/our with spain/page (243).png',
    'books/our with spain/page (244).png',
    'books/our with spain/page (245).png',
    'books/our with spain/page (246).png',
    'books/our with spain/page (247).png',
    'books/our with spain/page (248).png',
    'books/our with spain/page (249).png',
    'books/our with spain/page (250).png',
    'books/our with spain/page (251).png',
    'books/our with spain/page (252).png',
    'books/our with spain/page (253).png',
    'books/our with spain/page (254).png',
    'books/our with spain/page (255).png',
    'books/our with spain/page (256).png',
    'books/our with spain/page (257).png',
    'books/our with spain/page (258).png',
    'books/our with spain/page (259).png',
    'books/our with spain/page (260).png',
    'books/our with spain/page (261).png',
    'books/our with spain/page (262).png',
    'books/our with spain/page (263).png',
    'books/our with spain/page (264).png',
    'books/our with spain/page (265).png',
    'books/our with spain/page (266).png',
    'books/our with spain/page (267).png',
    'books/our with spain/page (268).png',
    'books/our with spain/page (269).png',
    'books/our with spain/page (270).png',
    'books/our with spain/page (271).png',
    'books/our with spain/page (272).png',
    'books/our with spain/page (273).png',
    'books/our with spain/page (274).png',
    'books/our with spain/page (275).png',
    'books/our with spain/page (276).png',
    'books/our with spain/page (277).png',
    'books/our with spain/page (278).png',
    'books/our with spain/page (279).png',
    'books/our with spain/page (280).png',
    'books/our with spain/page (281).png',
    'books/our with spain/page (282).png',
    'books/our with spain/page (283).png',
    'books/our with spain/page (284).png',
    'books/our with spain/page (285).png',
    'books/our with spain/page (286).png',
    'books/our with spain/page (287).png',
    'books/our with spain/page (288).png',
    'books/our with spain/page (289).png',
    'books/our with spain/page (290).png',
    'books/our with spain/page (291).png',
    'books/our with spain/page (292).png',
    'books/our with spain/page (293).png',
    'books/our with spain/page (294).png',
    'books/our with spain/page (295).png',
    'books/our with spain/page (296).png',
    'books/our with spain/page (297).png',
    'books/our with spain/page (298).png',
    'books/our with spain/page (299).png',
    'books/our with spain/page (300).png',
    'books/our with spain/page (301).png',
    'books/our with spain/page (302).png',
    'books/our with spain/page (303).png',
    'books/our with spain/page (304).png',
    'books/our with spain/page (305).png',
    'books/our with spain/page (306).png',
    'books/our with spain/page (307).png',
    'books/our with spain/page (308).png',
    'books/our with spain/page (309).png',
    'books/our with spain/page (310).png',
    'books/our with spain/page (311).png',
    'books/our with spain/page (312).png',
    'books/our with spain/page (313).png',
    'books/our with spain/page (314).png',
    'books/our with spain/page (315).png',
    'books/our with spain/page (316).png',
    'books/our with spain/page (317).png',
    'books/our with spain/page (318).png',
    'books/our with spain/page (319).png',
    'books/our with spain/page (320).png',
    'books/our with spain/page (321).png',
    'books/our with spain/page (322).png',
    'books/our with spain/page (323).png',
    'books/our with spain/page (324).png',
    'books/our with spain/page (325).png',
    'books/our with spain/page (326).png',
    'books/our with spain/page (327).png',
    'books/our with spain/page (328).png',
    'books/our with spain/page (329).png',
    'books/our with spain/page (330).png',
    'books/our with spain/page (331).png',
    'books/our with spain/page (332).png',
    'books/our with spain/page (333).png',
    'books/our with spain/page (334).png',
    'books/our with spain/page (335).png',
    'books/our with spain/page (336).png',
    'books/our with spain/page (337).png',
    'books/our with spain/page (338).png',
    'books/our with spain/page (339).png',
    'books/our with spain/page (340).png',
    'books/our with spain/page (341).png',
    'books/our with spain/page (342).png',
    'books/our with spain/page (343).png',
    'books/our with spain/page (344).png',
    'books/our with spain/page (345).png',
    'books/our with spain/page (346).png',
    'books/our with spain/page (347).png',
    'books/our with spain/page (348).png',
    'books/our with spain/page (349).png',
    'books/our with spain/page (350).png',
    'books/our with spain/page (351).png',
    'books/our with spain/page (352).png',
    'books/our with spain/page (353).png',
    'books/our with spain/page (354).png',
    'books/our with spain/page (355).png',
    'books/our with spain/page (356).png',
    'books/our with spain/page (357).png',
    'books/our with spain/page (358).png',
    'books/our with spain/page (359).png',
    'books/our with spain/page (360).png',
    'books/our with spain/page (361).png',
    'books/our with spain/page (362).png',
    'books/our with spain/page (363).png',
    'books/our with spain/page (364).png',
    'books/our with spain/page (365).png',
    'books/our with spain/page (366).png',
    'books/our with spain/page (367).png',
    'books/our with spain/page (368).png',
    'books/our with spain/page (369).png',
    'books/our with spain/page (370).png',
    'books/our with spain/page (371).png',
    'books/our with spain/page (372).png',
    'books/our with spain/page (373).png',
    'books/our with spain/page (374).png',
    'books/our with spain/page (375).png',
    'books/our with spain/page (376).png',
    'books/our with spain/page (377).png',
    'books/our with spain/page (378).png',
    'books/our with spain/page (379).png',
    'books/our with spain/page (380).png',
    'books/our with spain/page (381).png',
    'books/our with spain/page (382).png',
    'books/our with spain/page (383).png',
    'books/our with spain/page (384).png',
    'books/our with spain/page (385).png',
    'books/our with spain/page (386).png',
    'books/our with spain/page (387).png',
    'books/our with spain/page (388).png',
    'books/our with spain/page (389).png',
    'books/our with spain/page (390).png',
    'books/our with spain/page (391).png',
    'books/our with spain/page (392).png',
    'books/our with spain/page (393).png',
    'books/our with spain/page (394).png',
    'books/our with spain/page (395).png',
    'books/our with spain/page (396).png',
    'books/our with spain/page (397).png',
    'books/our with spain/page (398).png',
    'books/our with spain/page (399).png',
    'books/our with spain/page (400).png',
    'books/our with spain/page (401).png',
    'books/our with spain/page (402).png',
    'books/our with spain/page (403).png',
    'books/our with spain/page (404).png',
    'books/our with spain/page (405).png',
    'books/our with spain/page (406).png',
    'books/our with spain/page (407).png',
    'books/our with spain/page (408).png',
    'books/our with spain/page (409).png',
    'books/our with spain/page (410).png',
    'books/our with spain/page (411).png',
    'books/our with spain/page (412).png',
    'books/our with spain/page (413).png',
    'books/our with spain/page (414).png',
    'books/our with spain/page (415).png',
    'books/our with spain/page (416).png',
    'books/our with spain/page (417).png',
    'books/our with spain/page (418).png',
    'books/our with spain/page (419).png',
    'books/our with spain/page (420).png',
    'books/our with spain/page (421).png',
    'books/our with spain/page (422).png',
    'books/our with spain/page (423).png',
    'books/our with spain/page (424).png',
    'books/our with spain/page (425).png',
    'books/our with spain/page (426).png',
    'books/our with spain/page (427).png',
    'books/our with spain/page (428).png',
    'books/our with spain/page (429).png',
    'books/our with spain/page (430).png',
    'books/our with spain/page (431).png',
    'books/our with spain/page (432).png',
    'books/our with spain/page (433).png',
    'books/our with spain/page (434).png',
    'books/our with spain/page (435).png',
    'books/our with spain/page (436).png',
    'books/our with spain/page (437).png',
    'books/our with spain/page (438).png',
    'books/our with spain/page (439).png',
    'books/our with spain/page (440).png',
    'books/our with spain/page (441).png',
    'books/our with spain/page (442).png',
    'books/our with spain/page (443).png',
    'books/our with spain/page (444).png',
    'books/our with spain/page (445).png',
    'books/our with spain/page (446).png',
    'books/our with spain/page (447).png',
    'books/our with spain/page (448).png',
    'books/our with spain/page (449).png',
    'books/our with spain/page (450).png',
    'books/our with spain/page (451).png',
    'books/our with spain/page (452).png',
    'books/our with spain/page (453).png',
    'books/our with spain/page (454).png',
    'books/our with spain/page (455).png',
    'books/our with spain/page (456).png',
    'books/our with spain/page (457).png',
    'books/our with spain/page (458).png',
    'books/our with spain/page (459).png',
    'books/our with spain/page (460).png',
    'books/our with spain/page (461).png',
    'books/our with spain/page (462).png',
    'books/our with spain/page (463).png',
    'books/our with spain/page (464).png',
    'books/our with spain/page (465).png',
    'books/our with spain/page (466).png',
    'books/our with spain/page (467).png',
    'books/our with spain/page (468).png',
    'books/our with spain/page (469).png',
    'books/our with spain/page (470).png',
    'books/our with spain/page (471).png',
    'books/our with spain/page (472).png',
    'books/our with spain/page (473).png',
    'books/our with spain/page (474).png',
    'books/our with spain/page (475).png',
    'books/our with spain/page (476).png',
    'books/our with spain/page (477).png',
    'books/our with spain/page (478).png',
    'books/our with spain/page (479).png',
    'books/our with spain/page (480).png',
    'books/our with spain/page (481).png',
    'books/our with spain/page (482).png',
    'books/our with spain/page (483).png',
    'books/our with spain/page (484).png',
    'books/our with spain/page (485).png',
    'books/our with spain/page (486).png',
    'books/our with spain/page (487).png',
    'books/our with spain/page (488).png',
    'books/our with spain/page (489).png',
    'books/our with spain/page (490).png',
    'books/our with spain/page (491).png',
    'books/our with spain/page (492).png',
    'books/our with spain/page (493).png',
    'books/our with spain/page (494).png',
    'books/our with spain/page (495).png',
    'books/our with spain/page (496).png',
    'books/our with spain/page (497).png',
    'books/our with spain/page (498).png',
    'books/our with spain/page (499).png',
    'books/our with spain/page (500).png',
    'books/our with spain/page (501).png',
    'books/our with spain/page (502).png',
    'books/our with spain/page (503).png',
    'books/our with spain/page (504).png',
    'books/our with spain/page (505).png',
    'books/our with spain/page (506).png',
    'books/our with spain/page (507).png',
    'books/our with spain/page (508).png',
    'books/our with spain/page (509).png',
    'books/our with spain/page (510).png',
    'books/our with spain/page (511).png',
    'books/our with spain/page (512).png',
    'books/our with spain/page (513).png',
    'books/our with spain/page (514).png',
    'books/our with spain/page (515).png',
    'books/our with spain/page (516).png',
    'books/our with spain/page (517).png',
    'books/our with spain/page (518).png',
    'books/our with spain/page (519).png',
    'books/our with spain/page (520).png',
    'books/our with spain/page (521).png',
    'books/our with spain/page (522).png',
    'books/our with spain/page (523).png',
    'books/our with spain/page (524).png',
    'books/our with spain/page (525).png',
    'books/our with spain/page (526).png',
    'books/our with spain/page (527).png',
    'books/our with spain/page (528).png',
    'books/our with spain/page (529).png',
    'books/our with spain/page (530).png',
    'books/our with spain/page (531).png',
    'books/our with spain/page (532).png',
    'books/our with spain/page (533).png',
    'books/our with spain/page (534).png',
    'books/our with spain/page (535).png',
    'books/our with spain/page (536).png',
    'books/our with spain/page (537).png',
    'books/our with spain/page (538).png',
    'books/our with spain/page (539).png',
    'books/our with spain/page (540).png',
    'books/our with spain/page (541).png',
    'books/our with spain/page (542).png',
    'books/our with spain/page (543).png',
    'books/our with spain/page (544).png',
    'books/our with spain/page (545).png',
    'books/our with spain/page (546).png',
    'books/our with spain/page (547).png',
    'books/our with spain/page (548).png',
    'books/our with spain/page (549).png',
    'books/our with spain/page (550).png',
    'books/our with spain/page (551).png',
    'books/our with spain/page (552).png',
    'books/our with spain/page (553).png',
    'books/our with spain/page (554).png',
    'books/our with spain/page (555).png',
    'books/our with spain/page (556).png',
    'books/our with spain/page (557).png',
    'books/our with spain/page (558).png',
    'books/our with spain/page (559).png',
    'books/our with spain/page (560).png',
    'books/our with spain/page (561).png',
    'books/our with spain/page (562).png',
    'books/our with spain/page (563).png',
    'books/our with spain/page (564).png',
    'books/our with spain/page (565).png',
    'books/our with spain/page (566).png',
    'books/our with spain/page (567).png',
    'books/our with spain/page (568).png',
    'books/our with spain/page (569).png',
    'books/our with spain/page (570).png',
    'books/our with spain/page (571).png',
    'books/our with spain/page (572).png',
    'books/our with spain/page (573).png',
    'books/our with spain/page (574).png',
    'books/our with spain/page (575).png',
    'books/our with spain/page (576).png',
    'books/our with spain/page (577).png',
    'books/our with spain/page (578).png',
    'books/our with spain/page (579).png',
    'books/our with spain/page (580).png',
    'books/our with spain/page (581).png',
    'books/our with spain/page (582).png',
    'books/our with spain/page (583).png',
    'books/our with spain/page (584).png',
    'books/our with spain/page (585).png',
    'books/our with spain/page (586).png',
    'books/our with spain/page (587).png',
    'books/our with spain/page (588).png',
    'books/our with spain/page (589).png',
    'books/our with spain/page (590).png',
    'books/our with spain/page (591).png',
    'books/our with spain/page (592).png',
    'books/our with spain/page (593).png',
    'books/our with spain/page (594).png',
    'books/our with spain/page (595).png',
    'books/our with spain/page (596).png',
    'books/our with spain/page (597).png',
    'books/our with spain/page (598).png',
    'books/our with spain/page (599).png',
    'books/our with spain/page (600).png',
    'books/our with spain/page (601).png',
    'books/our with spain/page (602).png',
    'books/our with spain/page (603).png',
    'books/our with spain/page (604).png',
    'books/our with spain/page (605).png',
    'books/our with spain/page (606).png',
    'books/our with spain/page (607).png',
    'books/our with spain/page (608).png',
    'books/our with spain/page (609).png',
    'books/our with spain/page (610).png',
    'books/our with spain/page (611).png',
    'books/our with spain/page (612).png',
    'books/our with spain/page (613).png',
    'books/our with spain/page (614).png',
    'books/our with spain/page (615).png',
    'books/our with spain/page (616).png',
    'books/our with spain/page (617).png',
    'books/our with spain/page (618).png',
    'books/our with spain/page (619).png',
    'books/our with spain/page (620).png',
    'books/our with spain/page (621).png',
    'books/our with spain/page (622).png',
    'books/our with spain/page (623).png',
    'books/our with spain/page (624).png',
    'books/our with spain/page (625).png',
    'books/our with spain/page (626).png',
    'books/our with spain/page (627).png',
    'books/our with spain/page (628).png',
    'books/our with spain/page (629).png',
    'books/our with spain/page (630).png',
    'books/our with spain/page (631).png',
    'books/our with spain/page (632).png',
    'books/our with spain/page (633).png',
    'books/our with spain/page (634).png',
    'books/our with spain/page (635).png',
    'books/our with spain/page (636).png',
    'books/our with spain/page (637).png',
    'books/our with spain/page (638).png',
    'books/our with spain/page (639).png',
    'books/our with spain/page (640).png',
    'books/our with spain/page (641).png',
    'books/our with spain/page (642).png',
    'books/our with spain/page (643).png',
    'books/our with spain/page (644).png',
    'books/our with spain/page (645).png',
    'books/our with spain/page (646).png',
    'books/our with spain/page (647).png',
    'books/our with spain/page (648).png',
    'books/our with spain/page (649).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
