import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class oylehikaye extends StatefulWidget {
  const oylehikaye({Key? key}) : super(key: key);

  @override
  State<oylehikaye> createState() => _oylehikayeState();
}

class _oylehikayeState extends State<oylehikaye> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/oyle hikaye/page (1).png',
    'books/oyle hikaye/page (2).png',
    'books/oyle hikaye/page (3).png',
    'books/oyle hikaye/page (4).png',
    'books/oyle hikaye/page (5).png',
    'books/oyle hikaye/page (6).png',
    'books/oyle hikaye/page (7).png',
    'books/oyle hikaye/page (8).png',
    'books/oyle hikaye/page (9).png',
    'books/oyle hikaye/page (10).png',
    'books/oyle hikaye/page (11).png',
    'books/oyle hikaye/page (12).png',
    'books/oyle hikaye/page (13).png',
    'books/oyle hikaye/page (14).png',
    'books/oyle hikaye/page (15).png',
    'books/oyle hikaye/page (16).png',
    'books/oyle hikaye/page (17).png',
    'books/oyle hikaye/page (18).png',
    'books/oyle hikaye/page (19).png',
    'books/oyle hikaye/page (20).png',
    'books/oyle hikaye/page (21).png',
    'books/oyle hikaye/page (22).png',
    'books/oyle hikaye/page (23).png',
    'books/oyle hikaye/page (24).png',
    'books/oyle hikaye/page (25).png',
    'books/oyle hikaye/page (26).png',
    'books/oyle hikaye/page (27).png',
    'books/oyle hikaye/page (28).png',
    'books/oyle hikaye/page (29).png',
    'books/oyle hikaye/page (30).png',
    'books/oyle hikaye/page (31).png',
    'books/oyle hikaye/page (32).png',
    'books/oyle hikaye/page (33).png',
    'books/oyle hikaye/page (34).png',
    'books/oyle hikaye/page (35).png',
    'books/oyle hikaye/page (36).png',
    'books/oyle hikaye/page (37).png',
    'books/oyle hikaye/page (38).png',
    'books/oyle hikaye/page (39).png',
    'books/oyle hikaye/page (40).png',
    'books/oyle hikaye/page (41).png',
    'books/oyle hikaye/page (42).png',
    'books/oyle hikaye/page (43).png',
    'books/oyle hikaye/page (44).png',
    'books/oyle hikaye/page (45).png',
    'books/oyle hikaye/page (46).png',
    'books/oyle hikaye/page (47).png',
    'books/oyle hikaye/page (48).png',
    'books/oyle hikaye/page (49).png',
    'books/oyle hikaye/page (50).png',
    'books/oyle hikaye/page (51).png',
    'books/oyle hikaye/page (52).png',
    'books/oyle hikaye/page (53).png',
    'books/oyle hikaye/page (54).png',
    'books/oyle hikaye/page (55).png',
    'books/oyle hikaye/page (56).png',
    'books/oyle hikaye/page (57).png',
    'books/oyle hikaye/page (58).png',
    'books/oyle hikaye/page (59).png',
    'books/oyle hikaye/page (60).png',
    'books/oyle hikaye/page (61).png',
    'books/oyle hikaye/page (62).png',
    'books/oyle hikaye/page (63).png',
    'books/oyle hikaye/page (64).png',
    'books/oyle hikaye/page (65).png',
    'books/oyle hikaye/page (66).png',
    'books/oyle hikaye/page (67).png',
    'books/oyle hikaye/page (68).png',
    'books/oyle hikaye/page (69).png',
    'books/oyle hikaye/page (70).png',
    'books/oyle hikaye/page (71).png',
    'books/oyle hikaye/page (72).png',
    'books/oyle hikaye/page (73).png',
    'books/oyle hikaye/page (74).png',
    'books/oyle hikaye/page (75).png',
    'books/oyle hikaye/page (76).png',
    'books/oyle hikaye/page (77).png',
    'books/oyle hikaye/page (78).png',
    'books/oyle hikaye/page (79).png',
    'books/oyle hikaye/page (80).png',
    'books/oyle hikaye/page (81).png',
    'books/oyle hikaye/page (82).png',
    'books/oyle hikaye/page (83).png',
    'books/oyle hikaye/page (84).png',
    'books/oyle hikaye/page (85).png',
    'books/oyle hikaye/page (86).png',
    'books/oyle hikaye/page (87).png',
    'books/oyle hikaye/page (88).png',
    'books/oyle hikaye/page (89).png',
    'books/oyle hikaye/page (90).png',
    'books/oyle hikaye/page (91).png',
    'books/oyle hikaye/page (92).png',
    'books/oyle hikaye/page (93).png',
    'books/oyle hikaye/page (94).png',
    'books/oyle hikaye/page (95).png',
    'books/oyle hikaye/page (96).png',
    'books/oyle hikaye/page (97).png',
    'books/oyle hikaye/page (98).png',
    'books/oyle hikaye/page (99).png',
    'books/oyle hikaye/page (100).png',
    'books/oyle hikaye/page (101).png',
    'books/oyle hikaye/page (102).png',
    'books/oyle hikaye/page (103).png',
    'books/oyle hikaye/page (104).png',
    'books/oyle hikaye/page (105).png',
    'books/oyle hikaye/page (106).png',
    'books/oyle hikaye/page (107).png',
    'books/oyle hikaye/page (108).png',
    'books/oyle hikaye/page (109).png',
    'books/oyle hikaye/page (110).png',
    'books/oyle hikaye/page (111).png',
    'books/oyle hikaye/page (112).png',
    'books/oyle hikaye/page (113).png',
    'books/oyle hikaye/page (114).png',
    'books/oyle hikaye/page (115).png',
    'books/oyle hikaye/page (116).png',
    'books/oyle hikaye/page (117).png',
    'books/oyle hikaye/page (118).png',
    'books/oyle hikaye/page (119).png',
    'books/oyle hikaye/page (120).png',
    'books/oyle hikaye/page (121).png',
    'books/oyle hikaye/page (122).png',
    'books/oyle hikaye/page (123).png',
    'books/oyle hikaye/page (124).png',
    'books/oyle hikaye/page (125).png',
    'books/oyle hikaye/page (126).png',
    'books/oyle hikaye/page (127).png',
    'books/oyle hikaye/page (128).png',
    'books/oyle hikaye/page (129).png',
    'books/oyle hikaye/page (130).png',
    'books/oyle hikaye/page (131).png',
    'books/oyle hikaye/page (132).png',
    'books/oyle hikaye/page (133).png',
    'books/oyle hikaye/page (134).png',
    'books/oyle hikaye/page (135).png',
    'books/oyle hikaye/page (136).png',
    'books/oyle hikaye/page (137).png',
    'books/oyle hikaye/page (138).png',
    'books/oyle hikaye/page (139).png',
    'books/oyle hikaye/page (140).png',
    'books/oyle hikaye/page (141).png',
    'books/oyle hikaye/page (142).png',
    'books/oyle hikaye/page (143).png',
    'books/oyle hikaye/page (144).png',
    'books/oyle hikaye/page (145).png',
    'books/oyle hikaye/page (146).png',
    'books/oyle hikaye/page (147).png',
    'books/oyle hikaye/page (148).png',
    'books/oyle hikaye/page (149).png',
    'books/oyle hikaye/page (150).png',
    'books/oyle hikaye/page (151).png',
    'books/oyle hikaye/page (152).png',
    'books/oyle hikaye/page (153).png',
    'books/oyle hikaye/page (154).png',
    'books/oyle hikaye/page (155).png',
    'books/oyle hikaye/page (156).png',
    'books/oyle hikaye/page (157).png',
    'books/oyle hikaye/page (158).png',
    'books/oyle hikaye/page (159).png',
    'books/oyle hikaye/page (160).png',
    'books/oyle hikaye/page (161).png',
    'books/oyle hikaye/page (162).png',
    'books/oyle hikaye/page (163).png',
    'books/oyle hikaye/page (164).png',
    'books/oyle hikaye/page (165).png',
    'books/oyle hikaye/page (166).png',
    'books/oyle hikaye/page (167).png',
    'books/oyle hikaye/page (168).png',
    'books/oyle hikaye/page (169).png',
    'books/oyle hikaye/page (170).png',
    'books/oyle hikaye/page (171).png',
    'books/oyle hikaye/page (172).png',
    'books/oyle hikaye/page (173).png',
    'books/oyle hikaye/page (174).png',
    'books/oyle hikaye/page (175).png',
    'books/oyle hikaye/page (176).png',
    'books/oyle hikaye/page (177).png',
    'books/oyle hikaye/page (178).png',
    'books/oyle hikaye/page (179).png',
    'books/oyle hikaye/page (180).png',
    'books/oyle hikaye/page (181).png',
    'books/oyle hikaye/page (182).png',
    'books/oyle hikaye/page (183).png',
    'books/oyle hikaye/page (184).png',
    'books/oyle hikaye/page (185).png',
    'books/oyle hikaye/page (186).png',
    'books/oyle hikaye/page (187).png',
    'books/oyle hikaye/page (188).png',
    'books/oyle hikaye/page (189).png',
    'books/oyle hikaye/page (190).png',
    'books/oyle hikaye/page (191).png',
    'books/oyle hikaye/page (192).png',
    'books/oyle hikaye/page (193).png',
    'books/oyle hikaye/page (194).png',
    'books/oyle hikaye/page (195).png',
    'books/oyle hikaye/page (196).png',
    'books/oyle hikaye/page (197).png',
    'books/oyle hikaye/page (198).png',
    'books/oyle hikaye/page (199).png',
    'books/oyle hikaye/page (200).png',
    'books/oyle hikaye/page (201).png',
    'books/oyle hikaye/page (202).png',
    'books/oyle hikaye/page (203).png',
    'books/oyle hikaye/page (204).png',
    'books/oyle hikaye/page (205).png',
    'books/oyle hikaye/page (206).png',
    'books/oyle hikaye/page (207).png',
    'books/oyle hikaye/page (208).png',
    'books/oyle hikaye/page (209).png',
    'books/oyle hikaye/page (210).png',
    'books/oyle hikaye/page (211).png',
    'books/oyle hikaye/page (212).png',
    'books/oyle hikaye/page (213).png',
    'books/oyle hikaye/page (214).png',
    'books/oyle hikaye/page (215).png',
    'books/oyle hikaye/page (216).png',
    'books/oyle hikaye/page (217).png',
    'books/oyle hikaye/page (218).png',
    'books/oyle hikaye/page (219).png',
    'books/oyle hikaye/page (220).png',
    'books/oyle hikaye/page (221).png',
    'books/oyle hikaye/page (222).png',
    'books/oyle hikaye/page (223).png',
    'books/oyle hikaye/page (224).png',
    'books/oyle hikaye/page (225).png',
    'books/oyle hikaye/page (226).png',
    'books/oyle hikaye/page (227).png',
    'books/oyle hikaye/page (228).png',
    'books/oyle hikaye/page (229).png',
    'books/oyle hikaye/page (230).png',
    'books/oyle hikaye/page (231).png',
    'books/oyle hikaye/page (232).png',
    'books/oyle hikaye/page (233).png',
    'books/oyle hikaye/page (234).png',
    'books/oyle hikaye/page (235).png',
    'books/oyle hikaye/page (236).png',
    'books/oyle hikaye/page (237).png',
    'books/oyle hikaye/page (238).png',
    'books/oyle hikaye/page (239).png',
    'books/oyle hikaye/page (240).png',
    'books/oyle hikaye/page (241).png',
    'books/oyle hikaye/page (242).png',
    'books/oyle hikaye/page (243).png',
    'books/oyle hikaye/page (244).png',
    'books/oyle hikaye/page (245).png',
    'books/oyle hikaye/page (246).png',
    'books/oyle hikaye/page (247).png',
    'books/oyle hikaye/page (248).png',
    'books/oyle hikaye/page (249).png',
    'books/oyle hikaye/page (250).png',
    'books/oyle hikaye/page (251).png',
    'books/oyle hikaye/page (252).png',
    'books/oyle hikaye/page (253).png',
    'books/oyle hikaye/page (254).png',
    'books/oyle hikaye/page (255).png',
    'books/oyle hikaye/page (256).png',
    'books/oyle hikaye/page (257).png',
    'books/oyle hikaye/page (258).png',
    'books/oyle hikaye/page (259).png',
    'books/oyle hikaye/page (260).png',
    'books/oyle hikaye/page (261).png',
    'books/oyle hikaye/page (262).png',
    'books/oyle hikaye/page (263).png',
    'books/oyle hikaye/page (264).png',
    'books/oyle hikaye/page (265).png',
    'books/oyle hikaye/page (266).png',
    'books/oyle hikaye/page (267).png',
    'books/oyle hikaye/page (268).png',
    'books/oyle hikaye/page (269).png',
    'books/oyle hikaye/page (270).png',
    'books/oyle hikaye/page (271).png',
    'books/oyle hikaye/page (272).png',
    'books/oyle hikaye/page (273).png',
    'books/oyle hikaye/page (274).png',
    'books/oyle hikaye/page (275).png',
    'books/oyle hikaye/page (276).png',
    'books/oyle hikaye/page (277).png',
    'books/oyle hikaye/page (278).png',
    'books/oyle hikaye/page (279).png',
    'books/oyle hikaye/page (280).png',
    'books/oyle hikaye/page (281).png',
    'books/oyle hikaye/page (282).png',
    'books/oyle hikaye/page (283).png',
    'books/oyle hikaye/page (284).png',
    'books/oyle hikaye/page (285).png',
    'books/oyle hikaye/page (286).png',
    'books/oyle hikaye/page (287).png',
    'books/oyle hikaye/page (288).png',
    'books/oyle hikaye/page (289).png',
    'books/oyle hikaye/page (290).png',
    'books/oyle hikaye/page (291).png',
    'books/oyle hikaye/page (292).png',
    'books/oyle hikaye/page (293).png',
    'books/oyle hikaye/page (294).png',
    'books/oyle hikaye/page (295).png',
    'books/oyle hikaye/page (296).png',
    'books/oyle hikaye/page (297).png',
    'books/oyle hikaye/page (298).png',
    'books/oyle hikaye/page (299).png',
    'books/oyle hikaye/page (300).png',
    'books/oyle hikaye/page (301).png',
    'books/oyle hikaye/page (302).png',
    'books/oyle hikaye/page (303).png',
    'books/oyle hikaye/page (304).png',
    'books/oyle hikaye/page (305).png',
    'books/oyle hikaye/page (306).png',
    'books/oyle hikaye/page (307).png',
    'books/oyle hikaye/page (308).png',
    'books/oyle hikaye/page (309).png',
    'books/oyle hikaye/page (310).png',
    'books/oyle hikaye/page (311).png',
    'books/oyle hikaye/page (312).png',
    'books/oyle hikaye/page (313).png',
    'books/oyle hikaye/page (314).png',
    'books/oyle hikaye/page (315).png',
    'books/oyle hikaye/page (316).png',
    'books/oyle hikaye/page (317).png',
    'books/oyle hikaye/page (318).png',
    'books/oyle hikaye/page (319).png',
    'books/oyle hikaye/page (320).png',
    'books/oyle hikaye/page (321).png',
    'books/oyle hikaye/page (322).png',
    'books/oyle hikaye/page (323).png',
    'books/oyle hikaye/page (324).png',
    'books/oyle hikaye/page (325).png',
    'books/oyle hikaye/page (326).png',
    'books/oyle hikaye/page (327).png',
    'books/oyle hikaye/page (328).png',
    'books/oyle hikaye/page (329).png',
    'books/oyle hikaye/page (330).png',
    'books/oyle hikaye/page (331).png',
    'books/oyle hikaye/page (332).png',
    'books/oyle hikaye/page (333).png',
    'books/oyle hikaye/page (334).png',
    'books/oyle hikaye/page (335).png',
    'books/oyle hikaye/page (336).png',
    'books/oyle hikaye/page (337).png',
    'books/oyle hikaye/page (338).png',
    'books/oyle hikaye/page (339).png',
    'books/oyle hikaye/page (340).png',
    'books/oyle hikaye/page (341).png',
    'books/oyle hikaye/page (342).png',
    'books/oyle hikaye/page (343).png',
    'books/oyle hikaye/page (344).png',
    'books/oyle hikaye/page (345).png',
    'books/oyle hikaye/page (346).png',
    'books/oyle hikaye/page (347).png',
    'books/oyle hikaye/page (348).png',
    'books/oyle hikaye/page (349).png',
    'books/oyle hikaye/page (350).png',
    'books/oyle hikaye/page (351).png',
    'books/oyle hikaye/page (352).png',
    'books/oyle hikaye/page (353).png',
    'books/oyle hikaye/page (354).png',
    'books/oyle hikaye/page (355).png',
    'books/oyle hikaye/page (356).png',
    'books/oyle hikaye/page (357).png',
    'books/oyle hikaye/page (358).png',
    'books/oyle hikaye/page (359).png',
    'books/oyle hikaye/page (360).png',
    'books/oyle hikaye/page (361).png',
    'books/oyle hikaye/page (362).png',
    'books/oyle hikaye/page (363).png',
    'books/oyle hikaye/page (364).png',
    'books/oyle hikaye/page (365).png',
    'books/oyle hikaye/page (366).png',
    'books/oyle hikaye/page (367).png',
    'books/oyle hikaye/page (368).png',
    'books/oyle hikaye/page (369).png',
    'books/oyle hikaye/page (370).png',
    'books/oyle hikaye/page (371).png',
    'books/oyle hikaye/page (372).png',
    'books/oyle hikaye/page (373).png',
    'books/oyle hikaye/page (374).png',
    'books/oyle hikaye/page (375).png',
    'books/oyle hikaye/page (376).png',
    'books/oyle hikaye/page (377).png',
    'books/oyle hikaye/page (378).png',
    'books/oyle hikaye/page (379).png',
    'books/oyle hikaye/page (380).png',
    'books/oyle hikaye/page (381).png',
    'books/oyle hikaye/page (382).png',
    'books/oyle hikaye/page (383).png',
    'books/oyle hikaye/page (384).png',
    'books/oyle hikaye/page (385).png',
    'books/oyle hikaye/page (386).png',
    'books/oyle hikaye/page (387).png',
    'books/oyle hikaye/page (388).png',
    'books/oyle hikaye/page (389).png',
    'books/oyle hikaye/page (390).png',
    'books/oyle hikaye/page (391).png',
    'books/oyle hikaye/page (392).png',
    'books/oyle hikaye/page (393).png',
    'books/oyle hikaye/page (394).png',
    'books/oyle hikaye/page (395).png',
    'books/oyle hikaye/page (396).png',
    'books/oyle hikaye/page (397).png',
    'books/oyle hikaye/page (398).png',
    'books/oyle hikaye/page (399).png',
    'books/oyle hikaye/page (400).png',
    'books/oyle hikaye/page (401).png',
    'books/oyle hikaye/page (402).png',
    'books/oyle hikaye/page (403).png',
    'books/oyle hikaye/page (404).png',
    'books/oyle hikaye/page (405).png',
    'books/oyle hikaye/page (406).png',
    'books/oyle hikaye/page (407).png',
    'books/oyle hikaye/page (408).png',
    'books/oyle hikaye/page (409).png',
    'books/oyle hikaye/page (410).png',
    'books/oyle hikaye/page (411).png',
    'books/oyle hikaye/page (412).png',
    'books/oyle hikaye/page (413).png',
    'books/oyle hikaye/page (414).png',
    'books/oyle hikaye/page (415).png',
    'books/oyle hikaye/page (416).png',
    'books/oyle hikaye/page (417).png',
    'books/oyle hikaye/page (418).png',
    'books/oyle hikaye/page (419).png',
    'books/oyle hikaye/page (420).png',
    'books/oyle hikaye/page (421).png',
    'books/oyle hikaye/page (422).png',
    'books/oyle hikaye/page (423).png',
    'books/oyle hikaye/page (424).png',
    'books/oyle hikaye/page (425).png',
    'books/oyle hikaye/page (426).png',
    'books/oyle hikaye/page (427).png',
    'books/oyle hikaye/page (428).png',
    'books/oyle hikaye/page (429).png',
    'books/oyle hikaye/page (430).png',
    'books/oyle hikaye/page (431).png',
    'books/oyle hikaye/page (432).png',
    'books/oyle hikaye/page (433).png',
    'books/oyle hikaye/page (434).png',
    'books/oyle hikaye/page (435).png',
    'books/oyle hikaye/page (436).png',
    'books/oyle hikaye/page (437).png',
    'books/oyle hikaye/page (438).png',
    'books/oyle hikaye/page (439).png',
    'books/oyle hikaye/page (440).png',
    'books/oyle hikaye/page (441).png',
    'books/oyle hikaye/page (442).png',
    'books/oyle hikaye/page (443).png',
    'books/oyle hikaye/page (444).png',
    'books/oyle hikaye/page (445).png',
    'books/oyle hikaye/page (446).png',
    'books/oyle hikaye/page (447).png',
    'books/oyle hikaye/page (448).png',
    'books/oyle hikaye/page (449).png',
    'books/oyle hikaye/page (450).png',
    'books/oyle hikaye/page (451).png',
    'books/oyle hikaye/page (452).png',
    'books/oyle hikaye/page (453).png',
    'books/oyle hikaye/page (454).png',
    'books/oyle hikaye/page (455).png',
    'books/oyle hikaye/page (456).png',
    'books/oyle hikaye/page (457).png',
    'books/oyle hikaye/page (458).png',
    'books/oyle hikaye/page (459).png',
    'books/oyle hikaye/page (460).png',
    'books/oyle hikaye/page (461).png',
    'books/oyle hikaye/page (462).png',
    'books/oyle hikaye/page (463).png',
    'books/oyle hikaye/page (464).png',
    'books/oyle hikaye/page (465).png',
    'books/oyle hikaye/page (466).png',
    'books/oyle hikaye/page (467).png',
    'books/oyle hikaye/page (468).png',
    'books/oyle hikaye/page (469).png',
    'books/oyle hikaye/page (470).png',
    'books/oyle hikaye/page (471).png',
    'books/oyle hikaye/page (472).png',
    'books/oyle hikaye/page (473).png',
    'books/oyle hikaye/page (474).png',
    'books/oyle hikaye/page (475).png',
    'books/oyle hikaye/page (476).png',
    'books/oyle hikaye/page (477).png',
    'books/oyle hikaye/page (478).png',
    'books/oyle hikaye/page (479).png',
    'books/oyle hikaye/page (480).png',
    'books/oyle hikaye/page (481).png',
    'books/oyle hikaye/page (482).png',
    'books/oyle hikaye/page (483).png',
    'books/oyle hikaye/page (484).png',
    'books/oyle hikaye/page (485).png',
    'books/oyle hikaye/page (486).png',
    'books/oyle hikaye/page (487).png',
    'books/oyle hikaye/page (488).png',
    'books/oyle hikaye/page (489).png',
    'books/oyle hikaye/page (490).png',
    'books/oyle hikaye/page (491).png',
    'books/oyle hikaye/page (492).png',
    'books/oyle hikaye/page (493).png',
    'books/oyle hikaye/page (494).png',
    'books/oyle hikaye/page (495).png',
    'books/oyle hikaye/page (496).png',
    'books/oyle hikaye/page (497).png',
    'books/oyle hikaye/page (498).png',
    'books/oyle hikaye/page (499).png',
    'books/oyle hikaye/page (500).png',
    'books/oyle hikaye/page (501).png',
    'books/oyle hikaye/page (502).png',
    'books/oyle hikaye/page (503).png',
    'books/oyle hikaye/page (504).png',
    'books/oyle hikaye/page (505).png',
    'books/oyle hikaye/page (506).png',
    'books/oyle hikaye/page (507).png',
    'books/oyle hikaye/page (508).png',
    'books/oyle hikaye/page (509).png',
    'books/oyle hikaye/page (510).png',
    'books/oyle hikaye/page (511).png',
    'books/oyle hikaye/page (512).png',
    'books/oyle hikaye/page (513).png',
    'books/oyle hikaye/page (514).png',
    'books/oyle hikaye/page (515).png',
    'books/oyle hikaye/page (516).png',
    'books/oyle hikaye/page (517).png',
    'books/oyle hikaye/page (518).png',
    'books/oyle hikaye/page (519).png',
    'books/oyle hikaye/page (520).png',
    'books/oyle hikaye/page (521).png',
    'books/oyle hikaye/page (522).png',
    'books/oyle hikaye/page (523).png',
    'books/oyle hikaye/page (524).png',
    'books/oyle hikaye/page (525).png',
    'books/oyle hikaye/page (526).png',
    'books/oyle hikaye/page (527).png',
    'books/oyle hikaye/page (528).png',
    'books/oyle hikaye/page (529).png',
    'books/oyle hikaye/page (530).png',
    'books/oyle hikaye/page (531).png',
    'books/oyle hikaye/page (532).png',
    'books/oyle hikaye/page (533).png',
    'books/oyle hikaye/page (534).png',
    'books/oyle hikaye/page (535).png',
    'books/oyle hikaye/page (536).png',
    'books/oyle hikaye/page (537).png',
    'books/oyle hikaye/page (538).png',
    'books/oyle hikaye/page (539).png',
    'books/oyle hikaye/page (540).png',
    'books/oyle hikaye/page (541).png',
    'books/oyle hikaye/page (542).png',
    'books/oyle hikaye/page (543).png',
    'books/oyle hikaye/page (544).png',
    'books/oyle hikaye/page (545).png',
    'books/oyle hikaye/page (546).png',
    'books/oyle hikaye/page (547).png',
    'books/oyle hikaye/page (548).png',
    'books/oyle hikaye/page (549).png',
    'books/oyle hikaye/page (550).png',
    'books/oyle hikaye/page (551).png',
    'books/oyle hikaye/page (552).png',
    'books/oyle hikaye/page (553).png',
    'books/oyle hikaye/page (554).png',
    'books/oyle hikaye/page (555).png',
    'books/oyle hikaye/page (556).png',
    'books/oyle hikaye/page (557).png',
    'books/oyle hikaye/page (558).png',
    'books/oyle hikaye/page (559).png',
    'books/oyle hikaye/page (560).png',
    'books/oyle hikaye/page (561).png',
    'books/oyle hikaye/page (562).png',
    'books/oyle hikaye/page (563).png',
    'books/oyle hikaye/page (564).png',
    'books/oyle hikaye/page (565).png',
    'books/oyle hikaye/page (566).png',
    'books/oyle hikaye/page (567).png',
    'books/oyle hikaye/page (568).png',
    'books/oyle hikaye/page (569).png',
    'books/oyle hikaye/page (570).png',
    'books/oyle hikaye/page (571).png',
    'books/oyle hikaye/page (572).png',
    'books/oyle hikaye/page (573).png',
    'books/oyle hikaye/page (574).png',
    'books/oyle hikaye/page (575).png',
    'books/oyle hikaye/page (576).png',
    'books/oyle hikaye/page (577).png',
    'books/oyle hikaye/page (578).png',
    'books/oyle hikaye/page (579).png',
    'books/oyle hikaye/page (580).png',
    'books/oyle hikaye/page (581).png',
    'books/oyle hikaye/page (582).png',
    'books/oyle hikaye/page (583).png',
    'books/oyle hikaye/page (584).png',
    'books/oyle hikaye/page (585).png',
    'books/oyle hikaye/page (586).png',
    'books/oyle hikaye/page (587).png',
    'books/oyle hikaye/page (588).png',
    'books/oyle hikaye/page (589).png',
    'books/oyle hikaye/page (590).png',
    'books/oyle hikaye/page (591).png',
    'books/oyle hikaye/page (592).png',
    'books/oyle hikaye/page (593).png',
    'books/oyle hikaye/page (594).png',
    'books/oyle hikaye/page (595).png',
    'books/oyle hikaye/page (596).png',
    'books/oyle hikaye/page (597).png',
    'books/oyle hikaye/page (598).png',
    'books/oyle hikaye/page (599).png',
    'books/oyle hikaye/page (600).png',
    'books/oyle hikaye/page (601).png',
    'books/oyle hikaye/page (602).png',
    'books/oyle hikaye/page (603).png',
    'books/oyle hikaye/page (604).png',
    'books/oyle hikaye/page (605).png',
    'books/oyle hikaye/page (606).png',
    'books/oyle hikaye/page (607).png',
    'books/oyle hikaye/page (608).png',
    'books/oyle hikaye/page (609).png',
    'books/oyle hikaye/page (610).png',
    'books/oyle hikaye/page (611).png',
    'books/oyle hikaye/page (612).png',
    'books/oyle hikaye/page (613).png',
    'books/oyle hikaye/page (614).png',
    'books/oyle hikaye/page (615).png',
    'books/oyle hikaye/page (616).png',
    'books/oyle hikaye/page (617).png',
    'books/oyle hikaye/page (618).png',
    'books/oyle hikaye/page (619).png',
    'books/oyle hikaye/page (620).png',
    'books/oyle hikaye/page (621).png',
    'books/oyle hikaye/page (622).png',
    'books/oyle hikaye/page (623).png',
    'books/oyle hikaye/page (624).png',
    'books/oyle hikaye/page (625).png',
    'books/oyle hikaye/page (626).png',
    'books/oyle hikaye/page (627).png',
    'books/oyle hikaye/page (628).png',
    'books/oyle hikaye/page (629).png',
    'books/oyle hikaye/page (630).png',
    'books/oyle hikaye/page (631).png',
    'books/oyle hikaye/page (632).png',
    'books/oyle hikaye/page (633).png',
    'books/oyle hikaye/page (634).png',
    'books/oyle hikaye/page (635).png',
    'books/oyle hikaye/page (636).png',
    'books/oyle hikaye/page (637).png',
    'books/oyle hikaye/page (638).png',
    'books/oyle hikaye/page (639).png',
    'books/oyle hikaye/page (640).png',
    'books/oyle hikaye/page (641).png',
    'books/oyle hikaye/page (642).png',
    'books/oyle hikaye/page (643).png',
    'books/oyle hikaye/page (644).png',
    'books/oyle hikaye/page (645).png',
    'books/oyle hikaye/page (646).png',
    'books/oyle hikaye/page (647).png',
    'books/oyle hikaye/page (648).png',
    'books/oyle hikaye/page (649).png',
    'books/oyle hikaye/page (650).png',
    'books/oyle hikaye/page (651).png',
    'books/oyle hikaye/page (652).png',
    'books/oyle hikaye/page (653).png',
    'books/oyle hikaye/page (654).png',
    'books/oyle hikaye/page (655).png',
    'books/oyle hikaye/page (656).png',
    'books/oyle hikaye/page (657).png',
    'books/oyle hikaye/page (658).png',
    'books/oyle hikaye/page (659).png',
    'books/oyle hikaye/page (660).png',
    'books/oyle hikaye/page (661).png',
    'books/oyle hikaye/page (662).png',
    'books/oyle hikaye/page (663).png',
    'books/oyle hikaye/page (664).png',
    'books/oyle hikaye/page (665).png',
    'books/oyle hikaye/page (666).png',
    'books/oyle hikaye/page (667).png',
    'books/oyle hikaye/page (668).png',
    'books/oyle hikaye/page (669).png',
    'books/oyle hikaye/page (670).png',
    'books/oyle hikaye/page (671).png',
    'books/oyle hikaye/page (672).png',
    'books/oyle hikaye/page (673).png',
    'books/oyle hikaye/page (674).png',
    'books/oyle hikaye/page (675).png',
    'books/oyle hikaye/page (676).png',
    'books/oyle hikaye/page (677).png',
    'books/oyle hikaye/page (678).png',
    'books/oyle hikaye/page (679).png',
    'books/oyle hikaye/page (680).png',
    'books/oyle hikaye/page (681).png',
    'books/oyle hikaye/page (682).png',
    'books/oyle hikaye/page (683).png',
    'books/oyle hikaye/page (684).png',
    'books/oyle hikaye/page (685).png',
    'books/oyle hikaye/page (686).png',
    'books/oyle hikaye/page (687).png',
    'books/oyle hikaye/page (688).png',
    'books/oyle hikaye/page (689).png',
    'books/oyle hikaye/page (690).png',
    'books/oyle hikaye/page (691).png',
    'books/oyle hikaye/page (692).png',
    'books/oyle hikaye/page (693).png',
    'books/oyle hikaye/page (694).png',
    'books/oyle hikaye/page (695).png',
    'books/oyle hikaye/page (696).png',
    'books/oyle hikaye/page (697).png',
    'books/oyle hikaye/page (698).png',
    'books/oyle hikaye/page (699).png',
    'books/oyle hikaye/page (700).png',
    'books/oyle hikaye/page (701).png',
    'books/oyle hikaye/page (702).png',
    'books/oyle hikaye/page (703).png',
    'books/oyle hikaye/page (704).png',
    'books/oyle hikaye/page (705).png',
    'books/oyle hikaye/page (706).png',
    'books/oyle hikaye/page (707).png',
    'books/oyle hikaye/page (708).png',
    'books/oyle hikaye/page (709).png',
    'books/oyle hikaye/page (710).png',
    'books/oyle hikaye/page (711).png',
    'books/oyle hikaye/page (712).png',
    'books/oyle hikaye/page (713).png',
    'books/oyle hikaye/page (714).png',
    'books/oyle hikaye/page (715).png',
    'books/oyle hikaye/page (716).png',
    'books/oyle hikaye/page (717).png',
    'books/oyle hikaye/page (718).png',
    'books/oyle hikaye/page (719).png',
    'books/oyle hikaye/page (720).png',
    'books/oyle hikaye/page (721).png',
    'books/oyle hikaye/page (722).png',
    'books/oyle hikaye/page (723).png',
    'books/oyle hikaye/page (724).png',
    'books/oyle hikaye/page (725).png',
    'books/oyle hikaye/page (726).png',
    'books/oyle hikaye/page (727).png',
    'books/oyle hikaye/page (728).png',
    'books/oyle hikaye/page (729).png',
    'books/oyle hikaye/page (730).png',
    'books/oyle hikaye/page (731).png',
    'books/oyle hikaye/page (732).png',
    'books/oyle hikaye/page (733).png',
    'books/oyle hikaye/page (734).png',
    'books/oyle hikaye/page (735).png',
    'books/oyle hikaye/page (736).png',
    'books/oyle hikaye/page (737).png',
    'books/oyle hikaye/page (738).png',
    'books/oyle hikaye/page (739).png',
    'books/oyle hikaye/page (740).png',
    'books/oyle hikaye/page (741).png',
    'books/oyle hikaye/page (742).png',
    'books/oyle hikaye/page (743).png',
    'books/oyle hikaye/page (744).png',
    'books/oyle hikaye/page (745).png',
    'books/oyle hikaye/page (746).png',
    'books/oyle hikaye/page (747).png',
    'books/oyle hikaye/page (748).png',
    'books/oyle hikaye/page (749).png',
    'books/oyle hikaye/page (750).png',
    'books/oyle hikaye/page (751).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
