import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class romola extends StatefulWidget {
  const romola({Key? key}) : super(key: key);

  @override
  State<romola> createState() => _romolaState();
}

class _romolaState extends State<romola> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/romola/page (1).png',
    'books/romola/page (2).png',
    'books/romola/page (3).png',
    'books/romola/page (4).png',
    'books/romola/page (5).png',
    'books/romola/page (6).png',
    'books/romola/page (7).png',
    'books/romola/page (8).png',
    'books/romola/page (9).png',
    'books/romola/page (10).png',
    'books/romola/page (11).png',
    'books/romola/page (12).png',
    'books/romola/page (13).png',
    'books/romola/page (14).png',
    'books/romola/page (15).png',
    'books/romola/page (16).png',
    'books/romola/page (17).png',
    'books/romola/page (18).png',
    'books/romola/page (19).png',
    'books/romola/page (20).png',
    'books/romola/page (21).png',
    'books/romola/page (22).png',
    'books/romola/page (23).png',
    'books/romola/page (24).png',
    'books/romola/page (25).png',
    'books/romola/page (26).png',
    'books/romola/page (27).png',
    'books/romola/page (28).png',
    'books/romola/page (29).png',
    'books/romola/page (30).png',
    'books/romola/page (31).png',
    'books/romola/page (32).png',
    'books/romola/page (33).png',
    'books/romola/page (34).png',
    'books/romola/page (35).png',
    'books/romola/page (36).png',
    'books/romola/page (37).png',
    'books/romola/page (38).png',
    'books/romola/page (39).png',
    'books/romola/page (40).png',
    'books/romola/page (41).png',
    'books/romola/page (42).png',
    'books/romola/page (43).png',
    'books/romola/page (44).png',
    'books/romola/page (45).png',
    'books/romola/page (46).png',
    'books/romola/page (47).png',
    'books/romola/page (48).png',
    'books/romola/page (49).png',
    'books/romola/page (50).png',
    'books/romola/page (51).png',
    'books/romola/page (52).png',
    'books/romola/page (53).png',
    'books/romola/page (54).png',
    'books/romola/page (55).png',
    'books/romola/page (56).png',
    'books/romola/page (57).png',
    'books/romola/page (58).png',
    'books/romola/page (59).png',
    'books/romola/page (60).png',
    'books/romola/page (61).png',
    'books/romola/page (62).png',
    'books/romola/page (63).png',
    'books/romola/page (64).png',
    'books/romola/page (65).png',
    'books/romola/page (66).png',
    'books/romola/page (67).png',
    'books/romola/page (68).png',
    'books/romola/page (69).png',
    'books/romola/page (70).png',
    'books/romola/page (71).png',
    'books/romola/page (72).png',
    'books/romola/page (73).png',
    'books/romola/page (74).png',
    'books/romola/page (75).png',
    'books/romola/page (76).png',
    'books/romola/page (77).png',
    'books/romola/page (78).png',
    'books/romola/page (79).png',
    'books/romola/page (80).png',
    'books/romola/page (81).png',
    'books/romola/page (82).png',
    'books/romola/page (83).png',
    'books/romola/page (84).png',
    'books/romola/page (85).png',
    'books/romola/page (86).png',
    'books/romola/page (87).png',
    'books/romola/page (88).png',
    'books/romola/page (89).png',
    'books/romola/page (90).png',
    'books/romola/page (91).png',
    'books/romola/page (92).png',
    'books/romola/page (93).png',
    'books/romola/page (94).png',
    'books/romola/page (95).png',
    'books/romola/page (96).png',
    'books/romola/page (97).png',
    'books/romola/page (98).png',
    'books/romola/page (99).png',
    'books/romola/page (100).png',
    'books/romola/page (101).png',
    'books/romola/page (102).png',
    'books/romola/page (103).png',
    'books/romola/page (104).png',
    'books/romola/page (105).png',
    'books/romola/page (106).png',
    'books/romola/page (107).png',
    'books/romola/page (108).png',
    'books/romola/page (109).png',
    'books/romola/page (110).png',
    'books/romola/page (111).png',
    'books/romola/page (112).png',
    'books/romola/page (113).png',
    'books/romola/page (114).png',
    'books/romola/page (115).png',
    'books/romola/page (116).png',
    'books/romola/page (117).png',
    'books/romola/page (118).png',
    'books/romola/page (119).png',
    'books/romola/page (120).png',
    'books/romola/page (121).png',
    'books/romola/page (122).png',
    'books/romola/page (123).png',
    'books/romola/page (124).png',
    'books/romola/page (125).png',
    'books/romola/page (126).png',
    'books/romola/page (127).png',
    'books/romola/page (128).png',
    'books/romola/page (129).png',
    'books/romola/page (130).png',
    'books/romola/page (131).png',
    'books/romola/page (132).png',
    'books/romola/page (133).png',
    'books/romola/page (134).png',
    'books/romola/page (135).png',
    'books/romola/page (136).png',
    'books/romola/page (137).png',
    'books/romola/page (138).png',
    'books/romola/page (139).png',
    'books/romola/page (140).png',
    'books/romola/page (141).png',
    'books/romola/page (142).png',
    'books/romola/page (143).png',
    'books/romola/page (144).png',
    'books/romola/page (145).png',
    'books/romola/page (146).png',
    'books/romola/page (147).png',
    'books/romola/page (148).png',
    'books/romola/page (149).png',
    'books/romola/page (150).png',
    'books/romola/page (151).png',
    'books/romola/page (152).png',
    'books/romola/page (153).png',
    'books/romola/page (154).png',
    'books/romola/page (155).png',
    'books/romola/page (156).png',
    'books/romola/page (157).png',
    'books/romola/page (158).png',
    'books/romola/page (159).png',
    'books/romola/page (160).png',
    'books/romola/page (161).png',
    'books/romola/page (162).png',
    'books/romola/page (163).png',
    'books/romola/page (164).png',
    'books/romola/page (165).png',
    'books/romola/page (166).png',
    'books/romola/page (167).png',
    'books/romola/page (168).png',
    'books/romola/page (169).png',
    'books/romola/page (170).png',
    'books/romola/page (171).png',
    'books/romola/page (172).png',
    'books/romola/page (173).png',
    'books/romola/page (174).png',
    'books/romola/page (175).png',
    'books/romola/page (176).png',
    'books/romola/page (177).png',
    'books/romola/page (178).png',
    'books/romola/page (179).png',
    'books/romola/page (180).png',
    'books/romola/page (181).png',
    'books/romola/page (182).png',
    'books/romola/page (183).png',
    'books/romola/page (184).png',
    'books/romola/page (185).png',
    'books/romola/page (186).png',
    'books/romola/page (187).png',
    'books/romola/page (188).png',
    'books/romola/page (189).png',
    'books/romola/page (190).png',
    'books/romola/page (191).png',
    'books/romola/page (192).png',
    'books/romola/page (193).png',
    'books/romola/page (194).png',
    'books/romola/page (195).png',
    'books/romola/page (196).png',
    'books/romola/page (197).png',
    'books/romola/page (198).png',
    'books/romola/page (199).png',
    'books/romola/page (200).png',
    'books/romola/page (201).png',
    'books/romola/page (202).png',
    'books/romola/page (203).png',
    'books/romola/page (204).png',
    'books/romola/page (205).png',
    'books/romola/page (206).png',
    'books/romola/page (207).png',
    'books/romola/page (208).png',
    'books/romola/page (209).png',
    'books/romola/page (210).png',
    'books/romola/page (211).png',
    'books/romola/page (212).png',
    'books/romola/page (213).png',
    'books/romola/page (214).png',
    'books/romola/page (215).png',
    'books/romola/page (216).png',
    'books/romola/page (217).png',
    'books/romola/page (218).png',
    'books/romola/page (219).png',
    'books/romola/page (220).png',
    'books/romola/page (221).png',
    'books/romola/page (222).png',
    'books/romola/page (223).png',
    'books/romola/page (224).png',
    'books/romola/page (225).png',
    'books/romola/page (226).png',
    'books/romola/page (227).png',
    'books/romola/page (228).png',
    'books/romola/page (229).png',
    'books/romola/page (230).png',
    'books/romola/page (231).png',
    'books/romola/page (232).png',
    'books/romola/page (233).png',
    'books/romola/page (234).png',
    'books/romola/page (235).png',
    'books/romola/page (236).png',
    'books/romola/page (237).png',
    'books/romola/page (238).png',
    'books/romola/page (239).png',
    'books/romola/page (240).png',
    'books/romola/page (241).png',
    'books/romola/page (242).png',
    'books/romola/page (243).png',
    'books/romola/page (244).png',
    'books/romola/page (245).png',
    'books/romola/page (246).png',
    'books/romola/page (247).png',
    'books/romola/page (248).png',
    'books/romola/page (249).png',
    'books/romola/page (250).png',
    'books/romola/page (251).png',
    'books/romola/page (252).png',
    'books/romola/page (253).png',
    'books/romola/page (254).png',
    'books/romola/page (255).png',
    'books/romola/page (256).png',
    'books/romola/page (257).png',
    'books/romola/page (258).png',
    'books/romola/page (259).png',
    'books/romola/page (260).png',
    'books/romola/page (261).png',
    'books/romola/page (262).png',
    'books/romola/page (263).png',
    'books/romola/page (264).png',
    'books/romola/page (265).png',
    'books/romola/page (266).png',
    'books/romola/page (267).png',
    'books/romola/page (268).png',
    'books/romola/page (269).png',
    'books/romola/page (270).png',
    'books/romola/page (271).png',
    'books/romola/page (272).png',
    'books/romola/page (273).png',
    'books/romola/page (274).png',
    'books/romola/page (275).png',
    'books/romola/page (276).png',
    'books/romola/page (277).png',
    'books/romola/page (278).png',
    'books/romola/page (279).png',
    'books/romola/page (280).png',
    'books/romola/page (281).png',
    'books/romola/page (282).png',
    'books/romola/page (283).png',
    'books/romola/page (284).png',
    'books/romola/page (285).png',
    'books/romola/page (286).png',
    'books/romola/page (287).png',
    'books/romola/page (288).png',
    'books/romola/page (289).png',
    'books/romola/page (290).png',
    'books/romola/page (291).png',
    'books/romola/page (292).png',
    'books/romola/page (293).png',
    'books/romola/page (294).png',
    'books/romola/page (295).png',
    'books/romola/page (296).png',
    'books/romola/page (297).png',
    'books/romola/page (298).png',
    'books/romola/page (299).png',
    'books/romola/page (300).png',
    'books/romola/page (301).png',
    'books/romola/page (302).png',
    'books/romola/page (303).png',
    'books/romola/page (304).png',
    'books/romola/page (305).png',
    'books/romola/page (306).png',
    'books/romola/page (307).png',
    'books/romola/page (308).png',
    'books/romola/page (309).png',
    'books/romola/page (310).png',
    'books/romola/page (311).png',
    'books/romola/page (312).png',
    'books/romola/page (313).png',
    'books/romola/page (314).png',
    'books/romola/page (315).png',
    'books/romola/page (316).png',
    'books/romola/page (317).png',
    'books/romola/page (318).png',
    'books/romola/page (319).png',
    'books/romola/page (320).png',
    'books/romola/page (321).png',
    'books/romola/page (322).png',
    'books/romola/page (323).png',
    'books/romola/page (324).png',
    'books/romola/page (325).png',
    'books/romola/page (326).png',
    'books/romola/page (327).png',
    'books/romola/page (328).png',
    'books/romola/page (329).png',
    'books/romola/page (330).png',
    'books/romola/page (331).png',
    'books/romola/page (332).png',
    'books/romola/page (333).png',
    'books/romola/page (334).png',
    'books/romola/page (335).png',
    'books/romola/page (336).png',
    'books/romola/page (337).png',
    'books/romola/page (338).png',
    'books/romola/page (339).png',
    'books/romola/page (340).png',
    'books/romola/page (341).png',
    'books/romola/page (342).png',
    'books/romola/page (343).png',
    'books/romola/page (344).png',
    'books/romola/page (345).png',
    'books/romola/page (346).png',
    'books/romola/page (347).png',
    'books/romola/page (348).png',
    'books/romola/page (349).png',
    'books/romola/page (350).png',
    'books/romola/page (351).png',
    'books/romola/page (352).png',
    'books/romola/page (353).png',
    'books/romola/page (354).png',
    'books/romola/page (355).png',
    'books/romola/page (356).png',
    'books/romola/page (357).png',
    'books/romola/page (358).png',
    'books/romola/page (359).png',
    'books/romola/page (360).png',
    'books/romola/page (361).png',
    'books/romola/page (362).png',
    'books/romola/page (363).png',
    'books/romola/page (364).png',
    'books/romola/page (365).png',
    'books/romola/page (366).png',
    'books/romola/page (367).png',
    'books/romola/page (368).png',
    'books/romola/page (369).png',
    'books/romola/page (370).png',
    'books/romola/page (371).png',
    'books/romola/page (372).png',
    'books/romola/page (373).png',
    'books/romola/page (374).png',
    'books/romola/page (375).png',
    'books/romola/page (376).png',
    'books/romola/page (377).png',
    'books/romola/page (378).png',
    'books/romola/page (379).png',
    'books/romola/page (380).png',
    'books/romola/page (381).png',
    'books/romola/page (382).png',
    'books/romola/page (383).png',
    'books/romola/page (384).png',
    'books/romola/page (385).png',
    'books/romola/page (386).png',
    'books/romola/page (387).png',
    'books/romola/page (388).png',
    'books/romola/page (389).png',
    'books/romola/page (390).png',
    'books/romola/page (391).png',
    'books/romola/page (392).png',
    'books/romola/page (393).png',
    'books/romola/page (394).png',
    'books/romola/page (395).png',
    'books/romola/page (396).png',
    'books/romola/page (397).png',
    'books/romola/page (398).png',
    'books/romola/page (399).png',
    'books/romola/page (400).png',
    'books/romola/page (401).png',
    'books/romola/page (402).png',
    'books/romola/page (403).png',
    'books/romola/page (404).png',
    'books/romola/page (405).png',
    'books/romola/page (406).png',
    'books/romola/page (407).png',
    'books/romola/page (408).png',
    'books/romola/page (409).png',
    'books/romola/page (410).png',
    'books/romola/page (411).png',
    'books/romola/page (412).png',
    'books/romola/page (413).png',
    'books/romola/page (414).png',
    'books/romola/page (415).png',
    'books/romola/page (416).png',
    'books/romola/page (417).png',
    'books/romola/page (418).png',
    'books/romola/page (419).png',
    'books/romola/page (420).png',
    'books/romola/page (421).png',
    'books/romola/page (422).png',
    'books/romola/page (423).png',
    'books/romola/page (424).png',
    'books/romola/page (425).png',
    'books/romola/page (426).png',
    'books/romola/page (427).png',
    'books/romola/page (428).png',
    'books/romola/page (429).png',
    'books/romola/page (430).png',
    'books/romola/page (431).png',
    'books/romola/page (432).png',
    'books/romola/page (433).png',
    'books/romola/page (434).png',
    'books/romola/page (435).png',
    'books/romola/page (436).png',
    'books/romola/page (437).png',
    'books/romola/page (438).png',
    'books/romola/page (439).png',
    'books/romola/page (440).png',
    'books/romola/page (441).png',
    'books/romola/page (442).png',
    'books/romola/page (443).png',
    'books/romola/page (444).png',
    'books/romola/page (445).png',
    'books/romola/page (446).png',
    'books/romola/page (447).png',
    'books/romola/page (448).png',
    'books/romola/page (449).png',
    'books/romola/page (450).png',
    'books/romola/page (451).png',
    'books/romola/page (452).png',
    'books/romola/page (453).png',
    'books/romola/page (454).png',
    'books/romola/page (455).png',
    'books/romola/page (456).png',
    'books/romola/page (457).png',
    'books/romola/page (458).png',
    'books/romola/page (459).png',
    'books/romola/page (460).png',
    'books/romola/page (461).png',
    'books/romola/page (462).png',
    'books/romola/page (463).png',
    'books/romola/page (464).png',
    'books/romola/page (465).png',
    'books/romola/page (466).png',
    'books/romola/page (467).png',
    'books/romola/page (468).png',
    'books/romola/page (469).png',
    'books/romola/page (470).png',
    'books/romola/page (471).png',
    'books/romola/page (472).png',
    'books/romola/page (473).png',
    'books/romola/page (474).png',
    'books/romola/page (475).png',
    'books/romola/page (476).png',
    'books/romola/page (477).png',
    'books/romola/page (478).png',
    'books/romola/page (479).png',
    'books/romola/page (480).png',
    'books/romola/page (481).png',
    'books/romola/page (482).png',
    'books/romola/page (483).png',
    'books/romola/page (484).png',
    'books/romola/page (485).png',
    'books/romola/page (486).png',
    'books/romola/page (487).png',
    'books/romola/page (488).png',
    'books/romola/page (489).png',
    'books/romola/page (490).png',
    'books/romola/page (491).png',
    'books/romola/page (492).png',
    'books/romola/page (493).png',
    'books/romola/page (494).png',
    'books/romola/page (495).png',
    'books/romola/page (496).png',
    'books/romola/page (497).png',
    'books/romola/page (498).png',
    'books/romola/page (499).png',
    'books/romola/page (500).png',
    'books/romola/page (501).png',
    'books/romola/page (502).png',
    'books/romola/page (503).png',
    'books/romola/page (504).png',
    'books/romola/page (505).png',
    'books/romola/page (506).png',
    'books/romola/page (507).png',
    'books/romola/page (508).png',
    'books/romola/page (509).png',
    'books/romola/page (510).png',
    'books/romola/page (511).png',
    'books/romola/page (512).png',
    'books/romola/page (513).png',
    'books/romola/page (514).png',
    'books/romola/page (515).png',
    'books/romola/page (516).png',
    'books/romola/page (517).png',
    'books/romola/page (518).png',
    'books/romola/page (519).png',
    'books/romola/page (520).png',
    'books/romola/page (521).png',
    'books/romola/page (522).png',
    'books/romola/page (523).png',
    'books/romola/page (524).png',
    'books/romola/page (525).png',
    'books/romola/page (526).png',
    'books/romola/page (527).png',
    'books/romola/page (528).png',
    'books/romola/page (529).png',
    'books/romola/page (530).png',
    'books/romola/page (531).png',
    'books/romola/page (532).png',
    'books/romola/page (533).png',
    'books/romola/page (534).png',
    'books/romola/page (535).png',
    'books/romola/page (536).png',
    'books/romola/page (537).png',
    'books/romola/page (538).png',
    'books/romola/page (539).png',
    'books/romola/page (540).png',
    'books/romola/page (541).png',
    'books/romola/page (542).png',
    'books/romola/page (543).png',
    'books/romola/page (544).png',
    'books/romola/page (545).png',
    'books/romola/page (546).png',
    'books/romola/page (547).png',
    'books/romola/page (548).png',
    'books/romola/page (549).png',
    'books/romola/page (550).png',
    'books/romola/page (551).png',
    'books/romola/page (552).png',
    'books/romola/page (553).png',
    'books/romola/page (554).png',
    'books/romola/page (555).png',
    'books/romola/page (556).png',
    'books/romola/page (557).png',
    'books/romola/page (558).png',
    'books/romola/page (559).png',
    'books/romola/page (560).png',
    'books/romola/page (561).png',
    'books/romola/page (562).png',
    'books/romola/page (563).png',
    'books/romola/page (564).png',
    'books/romola/page (565).png',
    'books/romola/page (566).png',
    'books/romola/page (567).png',
    'books/romola/page (568).png',
    'books/romola/page (569).png',
    'books/romola/page (570).png',
    'books/romola/page (571).png',
    'books/romola/page (572).png',
    'books/romola/page (573).png',
    'books/romola/page (574).png',
    'books/romola/page (575).png',
    'books/romola/page (576).png',
    'books/romola/page (577).png',
    'books/romola/page (578).png',
    'books/romola/page (579).png',
    'books/romola/page (580).png',
    'books/romola/page (581).png',
    'books/romola/page (582).png',
    'books/romola/page (583).png',
    'books/romola/page (584).png',
    'books/romola/page (585).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
