import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:page_flip/page_flip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

final _controller = GlobalKey<PageFlipWidgetState>();

class wilheimmeister extends StatefulWidget {
  const wilheimmeister({Key? key}) : super(key: key);

  @override
  State<wilheimmeister> createState() => _wilheimmeisterState();
}

class _wilheimmeisterState extends State<wilheimmeister> {
  final _controller = GlobalKey<PageFlipWidgetState>();

  // sharedPreferences to store lastLeftOverPage Index
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();

  // last left over page index
  int lastLeftOverPageIndex = 0;

  // SharedPreference key to retrieve the  value of lastLeftOverPageIndex
  String lastLeftOverPageNoPrefKey = "_lastLeftOverPageNoPrefKey";

  final List<String> imagesPath = [
    'books/wilheim meister/page (1).png',
    'books/wilheim meister/page (2).png',
    'books/wilheim meister/page (3).png',
    'books/wilheim meister/page (4).png',
    'books/wilheim meister/page (5).png',
    'books/wilheim meister/page (6).png',
    'books/wilheim meister/page (7).png',
    'books/wilheim meister/page (8).png',
    'books/wilheim meister/page (9).png',
    'books/wilheim meister/page (10).png',
    'books/wilheim meister/page (11).png',
    'books/wilheim meister/page (12).png',
    'books/wilheim meister/page (13).png',
    'books/wilheim meister/page (14).png',
    'books/wilheim meister/page (15).png',
    'books/wilheim meister/page (16).png',
    'books/wilheim meister/page (17).png',
    'books/wilheim meister/page (18).png',
    'books/wilheim meister/page (19).png',
    'books/wilheim meister/page (20).png',
    'books/wilheim meister/page (21).png',
    'books/wilheim meister/page (22).png',
    'books/wilheim meister/page (23).png',
    'books/wilheim meister/page (24).png',
    'books/wilheim meister/page (25).png',
    'books/wilheim meister/page (26).png',
    'books/wilheim meister/page (27).png',
    'books/wilheim meister/page (28).png',
    'books/wilheim meister/page (29).png',
    'books/wilheim meister/page (30).png',
    'books/wilheim meister/page (31).png',
    'books/wilheim meister/page (32).png',
    'books/wilheim meister/page (33).png',
    'books/wilheim meister/page (34).png',
    'books/wilheim meister/page (35).png',
    'books/wilheim meister/page (36).png',
    'books/wilheim meister/page (37).png',
    'books/wilheim meister/page (38).png',
    'books/wilheim meister/page (39).png',
    'books/wilheim meister/page (40).png',
    'books/wilheim meister/page (41).png',
    'books/wilheim meister/page (42).png',
    'books/wilheim meister/page (43).png',
    'books/wilheim meister/page (44).png',
    'books/wilheim meister/page (45).png',
    'books/wilheim meister/page (46).png',
    'books/wilheim meister/page (47).png',
    'books/wilheim meister/page (48).png',
    'books/wilheim meister/page (49).png',
    'books/wilheim meister/page (50).png',
    'books/wilheim meister/page (51).png',
    'books/wilheim meister/page (52).png',
    'books/wilheim meister/page (53).png',
    'books/wilheim meister/page (54).png',
    'books/wilheim meister/page (55).png',
    'books/wilheim meister/page (56).png',
    'books/wilheim meister/page (57).png',
    'books/wilheim meister/page (58).png',
    'books/wilheim meister/page (59).png',
    'books/wilheim meister/page (60).png',
    'books/wilheim meister/page (61).png',
    'books/wilheim meister/page (62).png',
    'books/wilheim meister/page (63).png',
    'books/wilheim meister/page (64).png',
    'books/wilheim meister/page (65).png',
    'books/wilheim meister/page (66).png',
    'books/wilheim meister/page (67).png',
    'books/wilheim meister/page (68).png',
    'books/wilheim meister/page (69).png',
    'books/wilheim meister/page (70).png',
    'books/wilheim meister/page (71).png',
    'books/wilheim meister/page (72).png',
    'books/wilheim meister/page (73).png',
    'books/wilheim meister/page (74).png',
    'books/wilheim meister/page (75).png',
    'books/wilheim meister/page (76).png',
    'books/wilheim meister/page (77).png',
    'books/wilheim meister/page (78).png',
    'books/wilheim meister/page (79).png',
    'books/wilheim meister/page (80).png',
    'books/wilheim meister/page (81).png',
    'books/wilheim meister/page (82).png',
    'books/wilheim meister/page (83).png',
    'books/wilheim meister/page (84).png',
    'books/wilheim meister/page (85).png',
    'books/wilheim meister/page (86).png',
    'books/wilheim meister/page (87).png',
    'books/wilheim meister/page (88).png',
    'books/wilheim meister/page (89).png',
    'books/wilheim meister/page (90).png',
    'books/wilheim meister/page (91).png',
    'books/wilheim meister/page (92).png',
    'books/wilheim meister/page (93).png',
    'books/wilheim meister/page (94).png',
    'books/wilheim meister/page (95).png',
    'books/wilheim meister/page (96).png',
    'books/wilheim meister/page (97).png',
    'books/wilheim meister/page (98).png',
    'books/wilheim meister/page (99).png',
    'books/wilheim meister/page (100).png',
    'books/wilheim meister/page (101).png',
    'books/wilheim meister/page (102).png',
    'books/wilheim meister/page (103).png',
    'books/wilheim meister/page (104).png',
    'books/wilheim meister/page (105).png',
    'books/wilheim meister/page (106).png',
    'books/wilheim meister/page (107).png',
    'books/wilheim meister/page (108).png',
    'books/wilheim meister/page (109).png',
    'books/wilheim meister/page (110).png',
    'books/wilheim meister/page (111).png',
    'books/wilheim meister/page (112).png',
    'books/wilheim meister/page (113).png',
    'books/wilheim meister/page (114).png',
    'books/wilheim meister/page (115).png',
    'books/wilheim meister/page (116).png',
    'books/wilheim meister/page (117).png',
    'books/wilheim meister/page (118).png',
    'books/wilheim meister/page (119).png',
    'books/wilheim meister/page (120).png',
    'books/wilheim meister/page (121).png',
    'books/wilheim meister/page (122).png',
    'books/wilheim meister/page (123).png',
    'books/wilheim meister/page (124).png',
    'books/wilheim meister/page (125).png',
    'books/wilheim meister/page (126).png',
    'books/wilheim meister/page (127).png',
    'books/wilheim meister/page (128).png',
    'books/wilheim meister/page (129).png',
    'books/wilheim meister/page (130).png',
    'books/wilheim meister/page (131).png',
    'books/wilheim meister/page (132).png',
    'books/wilheim meister/page (133).png',
    'books/wilheim meister/page (134).png',
    'books/wilheim meister/page (135).png',
    'books/wilheim meister/page (136).png',
    'books/wilheim meister/page (137).png',
    'books/wilheim meister/page (138).png',
    'books/wilheim meister/page (139).png',
    'books/wilheim meister/page (140).png',
    'books/wilheim meister/page (141).png',
    'books/wilheim meister/page (142).png',
    'books/wilheim meister/page (143).png',
    'books/wilheim meister/page (144).png',
    'books/wilheim meister/page (145).png',
    'books/wilheim meister/page (146).png',
    'books/wilheim meister/page (147).png',
    'books/wilheim meister/page (148).png',
    'books/wilheim meister/page (149).png',
    'books/wilheim meister/page (150).png',
    'books/wilheim meister/page (151).png',
    'books/wilheim meister/page (152).png',
    'books/wilheim meister/page (153).png',
    'books/wilheim meister/page (154).png',
    'books/wilheim meister/page (155).png',
    'books/wilheim meister/page (156).png',
    'books/wilheim meister/page (157).png',
    'books/wilheim meister/page (158).png',
    'books/wilheim meister/page (159).png',
    'books/wilheim meister/page (160).png',
    'books/wilheim meister/page (161).png',
    'books/wilheim meister/page (162).png',
    'books/wilheim meister/page (163).png',
    'books/wilheim meister/page (164).png',
    'books/wilheim meister/page (165).png',
    'books/wilheim meister/page (166).png',
    'books/wilheim meister/page (167).png',
    'books/wilheim meister/page (168).png',
    'books/wilheim meister/page (169).png',
    'books/wilheim meister/page (170).png',
    'books/wilheim meister/page (171).png',
    'books/wilheim meister/page (172).png',
    'books/wilheim meister/page (173).png',
    'books/wilheim meister/page (174).png',
    'books/wilheim meister/page (175).png',
    'books/wilheim meister/page (176).png',
    'books/wilheim meister/page (177).png',
    'books/wilheim meister/page (178).png',
    'books/wilheim meister/page (179).png',
    'books/wilheim meister/page (180).png',
    'books/wilheim meister/page (181).png',
    'books/wilheim meister/page (182).png',
    'books/wilheim meister/page (183).png',
    'books/wilheim meister/page (184).png',
    'books/wilheim meister/page (185).png',
    'books/wilheim meister/page (186).png',
    'books/wilheim meister/page (187).png',
    'books/wilheim meister/page (188).png',
    'books/wilheim meister/page (189).png',
    'books/wilheim meister/page (190).png',
    'books/wilheim meister/page (191).png',
    'books/wilheim meister/page (192).png',
    'books/wilheim meister/page (193).png',
    'books/wilheim meister/page (194).png',
    'books/wilheim meister/page (195).png',
    'books/wilheim meister/page (196).png',
    'books/wilheim meister/page (197).png',
    'books/wilheim meister/page (198).png',
    'books/wilheim meister/page (199).png',
    'books/wilheim meister/page (200).png',
    'books/wilheim meister/page (201).png',
    'books/wilheim meister/page (202).png',
    'books/wilheim meister/page (203).png',
    'books/wilheim meister/page (204).png',
    'books/wilheim meister/page (205).png',
    'books/wilheim meister/page (206).png',
    'books/wilheim meister/page (207).png',
    'books/wilheim meister/page (208).png',
    'books/wilheim meister/page (209).png',
    'books/wilheim meister/page (210).png',
    'books/wilheim meister/page (211).png',
    'books/wilheim meister/page (212).png',
    'books/wilheim meister/page (213).png',
    'books/wilheim meister/page (214).png',
    'books/wilheim meister/page (215).png',
    'books/wilheim meister/page (216).png',
    'books/wilheim meister/page (217).png',
    'books/wilheim meister/page (218).png',
    'books/wilheim meister/page (219).png',
    'books/wilheim meister/page (220).png',
    'books/wilheim meister/page (221).png',
    'books/wilheim meister/page (222).png',
    'books/wilheim meister/page (223).png',
    'books/wilheim meister/page (224).png',
    'books/wilheim meister/page (225).png',
    'books/wilheim meister/page (226).png',
    'books/wilheim meister/page (227).png',
    'books/wilheim meister/page (228).png',
    'books/wilheim meister/page (229).png',
    'books/wilheim meister/page (230).png',
    'books/wilheim meister/page (231).png',
    'books/wilheim meister/page (232).png',
    'books/wilheim meister/page (233).png',
    'books/wilheim meister/page (234).png',
    'books/wilheim meister/page (235).png',
    'books/wilheim meister/page (236).png',
    'books/wilheim meister/page (237).png',
    'books/wilheim meister/page (238).png',
    'books/wilheim meister/page (239).png',
    'books/wilheim meister/page (240).png',
    'books/wilheim meister/page (241).png',
    'books/wilheim meister/page (242).png',
    'books/wilheim meister/page (243).png',
    'books/wilheim meister/page (244).png',
    'books/wilheim meister/page (245).png',
    'books/wilheim meister/page (246).png',
    'books/wilheim meister/page (247).png',
    'books/wilheim meister/page (248).png',
    'books/wilheim meister/page (249).png',
    'books/wilheim meister/page (250).png',
    'books/wilheim meister/page (251).png',
    'books/wilheim meister/page (252).png',
    'books/wilheim meister/page (253).png',
    'books/wilheim meister/page (254).png',
    'books/wilheim meister/page (255).png',
    'books/wilheim meister/page (256).png',
    'books/wilheim meister/page (257).png',
    'books/wilheim meister/page (258).png',
    'books/wilheim meister/page (259).png',
    'books/wilheim meister/page (260).png',
    'books/wilheim meister/page (261).png',
    'books/wilheim meister/page (262).png',
    'books/wilheim meister/page (263).png',
    'books/wilheim meister/page (264).png',
    'books/wilheim meister/page (265).png',
    'books/wilheim meister/page (266).png',
    'books/wilheim meister/page (267).png',
    'books/wilheim meister/page (268).png',
    'books/wilheim meister/page (269).png',
    'books/wilheim meister/page (270).png',
    'books/wilheim meister/page (271).png',
    'books/wilheim meister/page (272).png',
    'books/wilheim meister/page (273).png',
    'books/wilheim meister/page (274).png',
    'books/wilheim meister/page (275).png',
    'books/wilheim meister/page (276).png',
    'books/wilheim meister/page (277).png',
    'books/wilheim meister/page (278).png',
    'books/wilheim meister/page (279).png',
    'books/wilheim meister/page (280).png',
    'books/wilheim meister/page (281).png',
    'books/wilheim meister/page (282).png',
    'books/wilheim meister/page (283).png',
    'books/wilheim meister/page (284).png',
    'books/wilheim meister/page (285).png',
    'books/wilheim meister/page (286).png',
    'books/wilheim meister/page (287).png',
    'books/wilheim meister/page (288).png',
    'books/wilheim meister/page (289).png',
    'books/wilheim meister/page (290).png',
    'books/wilheim meister/page (291).png',
    'books/wilheim meister/page (292).png',
    'books/wilheim meister/page (293).png',
    'books/wilheim meister/page (294).png',
    'books/wilheim meister/page (295).png',
    'books/wilheim meister/page (296).png',
    'books/wilheim meister/page (297).png',
    'books/wilheim meister/page (298).png',
    'books/wilheim meister/page (299).png',
    'books/wilheim meister/page (300).png',
    'books/wilheim meister/page (301).png',
    'books/wilheim meister/page (302).png',
    'books/wilheim meister/page (303).png',
    'books/wilheim meister/page (304).png',
    'books/wilheim meister/page (305).png',
    'books/wilheim meister/page (306).png',
    'books/wilheim meister/page (307).png',
    'books/wilheim meister/page (308).png',
    'books/wilheim meister/page (309).png',
    'books/wilheim meister/page (310).png',
    'books/wilheim meister/page (311).png',
    'books/wilheim meister/page (312).png',
    'books/wilheim meister/page (313).png',
    'books/wilheim meister/page (314).png',
    'books/wilheim meister/page (315).png',
    'books/wilheim meister/page (316).png',
    'books/wilheim meister/page (317).png',
    'books/wilheim meister/page (318).png',
    'books/wilheim meister/page (319).png',
    'books/wilheim meister/page (320).png',
    'books/wilheim meister/page (321).png',
    'books/wilheim meister/page (322).png',
    'books/wilheim meister/page (323).png',
    'books/wilheim meister/page (324).png',
    'books/wilheim meister/page (325).png',
    'books/wilheim meister/page (326).png',
    'books/wilheim meister/page (327).png',
    'books/wilheim meister/page (328).png',
    'books/wilheim meister/page (329).png',
    'books/wilheim meister/page (330).png',
    'books/wilheim meister/page (331).png',
    'books/wilheim meister/page (332).png',
    'books/wilheim meister/page (333).png',
    'books/wilheim meister/page (334).png',
    'books/wilheim meister/page (335).png',
    'books/wilheim meister/page (336).png',
    'books/wilheim meister/page (337).png',
    'books/wilheim meister/page (338).png',
    'books/wilheim meister/page (339).png',
    'books/wilheim meister/page (340).png',
    'books/wilheim meister/page (341).png',
    'books/wilheim meister/page (342).png',
    'books/wilheim meister/page (343).png',
    'books/wilheim meister/page (344).png',
    'books/wilheim meister/page (345).png',
    'books/wilheim meister/page (346).png',
    'books/wilheim meister/page (347).png',
    'books/wilheim meister/page (348).png',
    'books/wilheim meister/page (349).png',
    'books/wilheim meister/page (350).png',
    'books/wilheim meister/page (351).png',
    'books/wilheim meister/page (352).png',
    'books/wilheim meister/page (353).png',
    'books/wilheim meister/page (354).png',
    'books/wilheim meister/page (355).png',
    'books/wilheim meister/page (356).png',
    'books/wilheim meister/page (357).png',
    'books/wilheim meister/page (358).png',
    'books/wilheim meister/page (359).png',
    'books/wilheim meister/page (360).png',
    'books/wilheim meister/page (361).png',
    'books/wilheim meister/page (362).png',
    'books/wilheim meister/page (363).png',
    'books/wilheim meister/page (364).png',
    'books/wilheim meister/page (365).png',
    'books/wilheim meister/page (366).png',
    'books/wilheim meister/page (367).png',
    'books/wilheim meister/page (368).png',
    'books/wilheim meister/page (369).png',
    'books/wilheim meister/page (370).png',
    'books/wilheim meister/page (371).png',
    'books/wilheim meister/page (372).png',
    'books/wilheim meister/page (373).png',
    'books/wilheim meister/page (374).png',
    'books/wilheim meister/page (375).png',
    'books/wilheim meister/page (376).png',
    'books/wilheim meister/page (377).png',
    'books/wilheim meister/page (378).png',
    'books/wilheim meister/page (379).png',
    'books/wilheim meister/page (380).png',
    'books/wilheim meister/page (381).png',
    'books/wilheim meister/page (382).png',
    'books/wilheim meister/page (383).png',
    'books/wilheim meister/page (384).png',
    'books/wilheim meister/page (385).png',
    'books/wilheim meister/page (386).png',
    'books/wilheim meister/page (387).png',
    'books/wilheim meister/page (388).png',
    'books/wilheim meister/page (389).png',
    'books/wilheim meister/page (390).png',
    'books/wilheim meister/page (391).png',
    'books/wilheim meister/page (392).png',
    'books/wilheim meister/page (393).png',
    'books/wilheim meister/page (394).png',
    'books/wilheim meister/page (395).png',
    'books/wilheim meister/page (396).png',
    'books/wilheim meister/page (397).png',
    'books/wilheim meister/page (398).png',
    'books/wilheim meister/page (399).png',
    'books/wilheim meister/page (400).png',
    'books/wilheim meister/page (401).png',
    'books/wilheim meister/page (402).png',
    'books/wilheim meister/page (403).png',
    'books/wilheim meister/page (404).png',
    'books/wilheim meister/page (405).png',
    'books/wilheim meister/page (406).png',
    'books/wilheim meister/page (407).png',
    'books/wilheim meister/page (408).png',
    'books/wilheim meister/page (409).png',
    'books/wilheim meister/page (410).png',
    'books/wilheim meister/page (411).png',
    'books/wilheim meister/page (412).png',
    'books/wilheim meister/page (413).png',
    'books/wilheim meister/page (414).png',
    'books/wilheim meister/page (415).png',
    'books/wilheim meister/page (416).png',
    'books/wilheim meister/page (417).png',
    'books/wilheim meister/page (418).png',
    'books/wilheim meister/page (419).png',
    'books/wilheim meister/page (420).png',
    'books/wilheim meister/page (421).png',
    'books/wilheim meister/page (422).png',
    'books/wilheim meister/page (423).png',
    'books/wilheim meister/page (424).png',
    'books/wilheim meister/page (425).png',
    'books/wilheim meister/page (426).png',
    'books/wilheim meister/page (427).png',
    'books/wilheim meister/page (428).png',
    'books/wilheim meister/page (429).png',
    'books/wilheim meister/page (430).png',
    'books/wilheim meister/page (431).png',
    'books/wilheim meister/page (432).png',
    'books/wilheim meister/page (433).png',
    'books/wilheim meister/page (434).png',

    // Diğer sayfaları ekleyin
  ];

  late List<String> downloadUrls;

  @override
  void initState() {
    // Firebase'i başlat
    Firebase.initializeApp();

    // restore the previous lastLeftOverPageIndex;
    _restoreLeftOverPage();
    super.initState();
  }

  Future<void> _restoreLeftOverPage() async {
    SharedPreferences pref = await _prefs;
    lastLeftOverPageIndex =
        pref.getInt(lastLeftOverPageNoPrefKey)?.toInt() ?? 0;
    // navigate the book page index to lastLeftOverPageIndex
    _controller.currentState?.goToPage(lastLeftOverPageIndex);
  }

  Widget _buildDemoPage(String imagePath) {
    return FutureBuilder(
      future: _getImageUrl(imagePath),
      builder: (BuildContext context, AsyncSnapshot<String?> snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError || snapshot.data == null) {
          return Center(child: Text('Error fetching image'));
        }
        return Scaffold(
          body: Center(
            child: Image.network(
              snapshot.data!,
              fit: BoxFit.cover,
            ),
          ),
        );
      },
    );
  }

  Future<String?> _getImageUrl(String imagePath) async {
    try {
      final ref = firebase_storage.FirebaseStorage.instance.ref(imagePath);
      final url = await ref.getDownloadURL();
      return url;
    } catch (e) {
      print('Error getting image URL for $imagePath: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageFlipWidget(
        key: _controller,
        backgroundColor: Colors.white,
        initialIndex: lastLeftOverPageIndex,
        lastPage: Container(
            color: Colors.white, child: const Center(child: Text('The End!'))),
        children: [
          for (var imagePath in imagesPath) _buildDemoPage(imagePath),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.looks_one_outlined),
        onPressed: () {
          _controller.currentState?.goToPage(1);
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    // before disposing the widget save the current page no
    var currentPageNo = _controller.currentState?.pageNumber.toInt() ?? 0;
    saveLastLeftOverPagePref(currentPageNo);
  }

  Future<void> saveLastLeftOverPagePref(int lastPage) async {
    SharedPreferences pref = await _prefs;
    pref.setInt(lastLeftOverPageNoPrefKey, lastPage);
  }
}
