// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqAb1wOrYys5Vdg2BOnmU4KEYaEEaCLuY',
    appId: '1:708047736437:web:a7777a5b82100821d4323c',
    messagingSenderId: '708047736437',
    projectId: 'libsyapp',
    authDomain: 'libsyapp.firebaseapp.com',
    storageBucket: 'libsyapp.appspot.com',
    measurementId: 'G-8YCBJC46RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Q6oQZzJQK00RFh14Hmv-HCR_Rcb7KeM',
    appId: '1:708047736437:android:87b8be8f4e5ac760d4323c',
    messagingSenderId: '708047736437',
    projectId: 'libsyapp',
    storageBucket: 'libsyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkJg6lEGjdOVubXWidwS2hIOr5dCvYQq0',
    appId: '1:708047736437:ios:d5cc8c7f31cad533d4323c',
    messagingSenderId: '708047736437',
    projectId: 'libsyapp',
    storageBucket: 'libsyapp.appspot.com',
    iosBundleId: 'com.example.libsyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkJg6lEGjdOVubXWidwS2hIOr5dCvYQq0',
    appId: '1:708047736437:ios:af2387b01c487dc3d4323c',
    messagingSenderId: '708047736437',
    projectId: 'libsyapp',
    storageBucket: 'libsyapp.appspot.com',
    iosBundleId: 'com.example.libsyApp.RunnerTests',
  );
}
